mozilla/activity-stream

- content-src/components/PocketStories/PocketStories.scss
`+` some minor CSS improvements
> fix(content): #2677 Pocket card overlaps with history card

- test/lib/utils.js
- test/test-TabTracker.js
> fix (travis): fix tests. return promise from mock asyncFetchLinks()

- content-src/components/PreferencesPane/PreferencesPane.js
- content-src/components/PreferencesPane/PreferencesPane.scss
> fix (sidebar): #2618 fix Done button on bottom and make contents scrollable

- content-src/components/PreferencesPane/PreferencesPane.scss
tiny r? @ncloudioj 
Fixes #2690
> fix (style): #2690 only show sidebar scrollbar when needed

- content-src/components/TopSites/TopSites.js
- content-test/components/EditTopSites.test.js
> fix (content) #2713 fix url validator to allow / in fragment locator

- content-src/components/CollapsibleSection/CollapsibleSection.js
- content-src/components/CollapsibleSection/CollapsibleSection.scss
Fixes #2709 
Fixes #2712 
Two small ones. r? @piatra
> #2709/#2712: section header issues

- system-addon/lib/ActivityStreamMessageChannel.jsm
Fix #2745. r?@k88hudson Just extending the ignoring to cases where target happens to be around but not quite.
> fix(mc): Ignore send failures to non-existent or unloading target pages

- system-addon/lib/ActivityStream.jsm
- system-addon/lib/ActivityStreamPrefs.jsm
- system-addon/test/unit/lib/ActivityStreamPrefs.test.js
- system-addon/test/unit/unit-entry.js
Fix #2694 @Mardak has approved this via in person review
> feat(mc) #2694 Switch telemetry endpoint and add value_local_dev for prefs

- system-addon/test/functional/mochitest/.eslintrc.js
Fix #2808. r?@sarracini See https://hg.mozilla.org/mozilla-central/rev/37651b6bd99c#l6.1
> chore(mc): Backport removal of thisTestLeaksUncaughtRejectionsAndShouldBeFixed

- addon/MetadataStore.js
This patch was made based on this [comment on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1376874#c12)
> fix(db): 2817 - Add shutdown blocker for metadata store

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #2821. let's try this again, but this time, with passing tests
> feat(systemaddon): Closes #2821 Implement clear history

- system-addon/lib/ActivityStream.jsm
> chore(mc): Switch over to the telemetry endpoint in prod

- system-addon/test/functional/mochitest/browser.ini
Fix #2851. r?@sarracini  Skip with issue reference
> fix(mc): Temporarily disable getScreenshots test

- system-addon/content-src/activity-stream.jsx
This is a backport of https://bugzilla.mozilla.org/show_bug.cgi?id=1381929
> fix(mc): Turn on indexedDB for snippets

- system-addon/content-src/styles/_icons.scss
Oops! Check all the CSS. Fixes: https://treeherder.mozilla.org/#/jobs?repo=pine&selectedJob=115412302
> fix(systemaddon): Delete reference to unused svg

- system-addon/content-src/components/Card/Card.jsx
@AdamHillier what do you think of this change?
> nit(highlights): Simplify background image for card UI

- locales/en-US/strings.properties
- system-addon/content-src/components/Card/Card.jsx
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/components/Topics/Topics.jsx
- system-addon/content-src/components/Topics/_Topics.scss
- system-addon/content-src/styles/_variables.scss
- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
Initial version that brings it all together:
Feed is still off by default until (likely tomorrow) we wire up the context menu options and bring in the final empty state.
> feat(systemaddon): Integration of all available #2512 related work.

- system-addon/content-src/components/Search/Search.jsx
- system-addon/test/unit/content-src/components/Search.test.jsx
> fix(mc): #2917 Only initialize search on focus

- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
> fix(systemaddon): #2930 Restore context menu order

- system-addon/content-src/lib/short-url.js
- system-addon/test/unit/content-src/lib/short-url.test.js
> fix (systemaddon): #2938 add fallback to shortUrl() for missing title

- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
This makes the provider name and provider description configurable and resolves #2957.
> fix(systemaddon): Section labels do not match. Closes #2957.

- system-addon/lib/SnippetsFeed.jsm
- system-addon/test/unit/lib/SnippetsFeed.test.js
At the moment we server the same content as with startpage_version 4.
@k88hudson please r?
> Bump Snippets STARTPAGE_VERSION to 5.

- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/Topics/_Topics.scss
This will make the Cards UI (Top Stories) consistent (tested on windows/ubuntu/mac).
> fix(systemaddon): CSS tweaks for Top Stories UI

- system-addon/common/PerfService.jsm
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/content-src/lib/detect-user-session-start.js
- system-addon/test/unit/content-src/components/TopSites.test.jsx
- system-addon/test/unit/content-src/lib/detect-user-session-start.test.js
> fix(telemetry): fix telemetry privacy.resistFingerprinting test failures (#2981)

- system-addon/data/content/activity-stream.html
> Remove obsolete #topSection from snippets-container.

- system-addon/content-src/components/Base/_Base.scss
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/ManualMigration/ManualMigration.scss
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/content-src/components/Topics/_Topics.scss
- system-addon/content-src/styles/_variables.scss
> fix(layout): #2951 Responsive UI improvements for top sites/stories

- system-addon/content-src/components/Card/Card.jsx
add a source so the telemetry ping can pick up the actions from the link menu
> fix(systemaddon): Closes #3016 Add SOURCE to LinkMenu telemetry pings

- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
- system-addon/test/unit/unit-entry.js
Fix #3029. @dmose, can you also review this approach?
> fix(topstories): Closes #3029 Add ETLDs for top stories

- system-addon/common/Reducers.jsm
> fix(topsites): Actually export TOP_SITES_SHOWMORE_LENGTH from Reducers

- docs/v2-system-addon/data_dictionary.md
- docs/v2-system-addon/data_events.md
- system-addon/lib/TelemetryFeed.jsm
- system-addon/test/schemas/pings.js
- system-addon/test/unit/lib/TelemetryFeed.test.js
> fix(telemetry): Add user_prefs to all the telemetry pings

- locales/en-US/strings.properties
> chore(l10n): Add about:home's document title to l10n

- system-addon/content-src/components/Base/_Base.scss
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/styles/_variables.scss
> chore(cards): Closes #3076 Update Cards spacing to match designs

- system-addon/content-src/components/Base/Base.jsx
Fix #3160. preloading gets me every time
> fix(favicon): Closes #3160 Favicon doesn't show on preloaded about:newtab

- system-addon/content-src/components/Card/Card.jsx
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/styles/_variables.scss
> fix(sections): Make context labels optional and adjust card text height.

- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TelemetryFeed.jsm
- system-addon/test/unit/lib/TelemetryFeed.test.js
> feat(mc): Only send one user interaction ping for each top stories article

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/styles/_icons.scss
- system-addon/data/content/assets/glyph-webextension-16.svg
- system-addon/test/unit/content-src/components/Sections.test.jsx
To be default icon for custom sections
> assets(system-addon): Add webextension icon

- system-addon/content-src/components/Card/Card.jsx
- system-addon/content-src/components/LinkMenu/LinkMenu.jsx
- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/lib/link-menu-options.js
- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TelemetryFeed.jsm
- system-addon/test/schemas/pings.js
- system-addon/test/unit/content-src/components/Card.test.jsx
- system-addon/test/unit/content-src/components/LinkMenu.test.jsx
- system-addon/test/unit/content-src/components/Sections.test.jsx
- system-addon/test/unit/lib/TelemetryFeed.test.js
I had to include 83c17c9 as well to get a clean rebase and passing tests
> Telemetry uplift (Don't merge)

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/test/unit/content-src/components/Sections.test.jsx
This reverts commit 9ea0f8fc52f7cdf87bd25ee0d310ded439a8d77e.
> Revert fix(a11y): Add basic a11y support to section-info-option (#3069)

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/test/unit/content-src/components/Sections.test.jsx
> fix(system-addon): Allow strings to be passed to sections instead of

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/test/unit/content-src/components/Sections.test.jsx
The first commit restores 9ea0f8;
The second commit fixes the issue for which 9ea0f8 was originally reverted
> Restore 9ea0f8 and fix #3180 

- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/test/unit/content-src/components/TopSites.test.jsx
Followup to pull #3191 
r? @sarracini
> fix (systemaddon): allow dismiss of default sites in edit modal

- system-addon/test/functional/mochitest/browser_getScreenshots.js
> fix(tests): Wait for pref to set before testing thumbnails

- system-addon/lib/ShortURL.jsm
- system-addon/lib/TopSitesFeed.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/ShortUrl.test.js
- system-addon/test/unit/lib/TopSitesFeed.test.js
- system-addon/test/unit/lib/TopStoriesFeed.test.js
Just made this as a new PR since it was significantly different from the previous.
> fix(systemaddon): Handle internationalized domain names. Closes #3200.

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #2739 and fix #2993. r?@sarracini
> feat(topsites): Only show top sites that have been visited more than once

- system-addon/lib/ActivityStreamMessageChannel.jsm
> chore(systemaddon): Backport bug 1392324 enable AS behind pref

- addon/main.js
> fix(testpilot): #3112 - Self destruct

- system-addon/content-src/components/Search/Search.jsx
- system-addon/test/unit/content-src/components/Search.test.jsx
> fix(search): Avoid default form submit behavior by not using <form>

- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
> fix (systemaddon): followup fix for 22d9a7999738e7c149e70eb26e64cc50938d37b2

- system-addon/jar.mn
> chore(build): Backport bug 863246 set contentaccessible=yes

- system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
> fix (systemaddon): remove no longer used ref="string" attrs

- system-addon/lib/SectionsManager.jsm
- system-addon/test/unit/lib/SectionsManager.test.js
> fix(pocket): Remove Save to Pocket option if Pocket is disabled

- system-addon/content-src/components/Sections/Sections.jsx
> fix: Options prop in Sections is optional

- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
> fix (systemaddon): Fix #3308 clicking outside prefs sidebar

- system-addon/lib/ShortURL.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/ShortUrl.test.js
- system-addon/test/unit/lib/TopStoriesFeed.test.js
> fix(systemaddon): Use tippytop title as hostname for default sites.

- system-addon/content-src/activity-stream.scss
- system-addon/content-src/components/ManualMigration/_ManualMigration.scss
- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
- system-addon/content-src/styles/_variables.scss
Fix #3256 and fix #3273. r?@rlr 
short:
tall:
> fix(styles): Update preferences to be scrollable with new styling

- system-addon/lib/HighlightsFeed.jsm
- system-addon/test/unit/lib/HighlightsFeed.test.js
> fix (systemaddon): #3379 use dedupe and update highlights on TOP_SITES_UPDATED

- system-addon/common/Reducers.jsm
- system-addon/lib/HighlightsFeed.jsm
- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/common/Reducers.test.js
- system-addon/test/unit/lib/HighlightsFeed.test.js
- system-addon/test/unit/lib/PlacesFeed.test.js
@Mardak this mostly fixes it for me. But I am still seeing weird behavior sometimes, or it's just getting late.
Fixes #3378
> fix (systemaddon): #3378 update contextmenu on unbookmark/bookmark

- system-addon/lib/SectionsManager.jsm
> fix(contextmenu): Fixes #3392 Highlights context menu should have a 'Delete from history' option

- docs/v2-system-addon/snippets.md
- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/content-src/lib/snippets.js
- system-addon/lib/SnippetsFeed.jsm
- system-addon/test/unit/content-src/lib/snippets.test.js
- system-addon/test/unit/lib/SnippetsFeed.test.js
> feat(pref-panel): Add control to disable snippets. Closes #3146.

- system-addon/common/PerfService.jsm
> chore(perf): #3437 Prevent checking Component from warning in the console

- system-addon/content-src/lib/snippets.js
- system-addon/test/unit/content-src/lib/snippets.test.js
> fix(snippets): #3453 Guard against non-string snippet payloads

- system-addon/content-src/components/Card/_Card.scss
> chore(styles): Remove card placeholder hover state. Closes #3457.

- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/test/unit/content-src/components/TopSites.test.jsx
Fixes #3384 Always show the edit button.... ALWAYS
> Top Sites Edit button disappears after removing all Top Sites

- system-addon/lib/TelemetryFeed.jsm
Fix #3441. r?@dmose Probably spent more collective mental space on triaging and tracking this than it took to fix.
> chore(telemetry): Remove unnecessary code

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
> fix(topsites): Ensure that editing or adding a top site fetches an icon.

- system-addon/content-src/components/Base/Base.jsx
- system-addon/content-src/components/Card/Card.jsx
- system-addon/content-src/components/ContextMenu/ContextMenu.jsx
- system-addon/content-src/components/LinkMenu/LinkMenu.jsx
- system-addon/content-src/components/ManualMigration/ManualMigration.jsx
- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/content-src/components/Search/Search.jsx
- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/TopSiteForm.jsx
- system-addon/content-src/components/TopSites/TopSitesEdit.jsx
- system-addon/content-src/components/TopSites/TopSitesPerfTimer.jsx
- system-addon/content-src/components/Topics/Topics.jsx
> chore(react): #3473 Use PureComponent for all components

- system-addon/lib/HighlightsFeed.jsm
- system-addon/test/unit/lib/HighlightsFeed.test.js
> fix(highlights): Reduce card renders by only fetching new images.

- system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
- system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
> fix(pref-pane): Disable secondary options when parent option disabled.

- bin/render-activity-stream-html.js
Fix #3502. r?@k88hudson Without this, I'm getting 12 frames from first paint to hero element. With this, I get 8 frames.
`-prerendered.html` diff:
```diff
<div id="snippets-container">
<div id="snippets"></div>
</div>
-<script src="resource://activity-stream/data/content/activity-stream-initial-state.js"></script>
-    <script src="chrome://browser/content/contentSearchUI.js"></script>
-    <script src="resource://activity-stream/vendor/react.js"></script>
-    <script src="resource://activity-stream/vendor/react-dom.js"></script>
-    <script src="resource://activity-stream/vendor/react-intl.js"></script>
-    <script src="resource://activity-stream/vendor/redux.js"></script>
-    <script src="resource://activity-stream/vendor/react-redux.js"></script>
-    <script …
```
> feat(prerender): Load scripts from a script tag instead of from html

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/lib/SectionsManager.jsm
- system-addon/test/unit/content-src/components/Sections.test.jsx
> fix(telemetry): Highlights section is sending impression pings (#3520)

- system-addon/lib/NewTabInit.jsm
- system-addon/test/unit/lib/NewTabInit.test.js
> fix(search): Only attempt to autofocus if there would be a search box

- system-addon/lib/SectionsManager.jsm
- system-addon/test/unit/lib/SectionsManager.test.js
@csadilek is this what you were thinking? f? Still need to write tests.
> feat (sections): #3423 implement deduping for sections

- system-addon/content-src/activity-stream.scss
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/content-src/styles/_variables.scss
> fix(style): #3504 Show snippets above other UI elements

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #3493. r?@sarracini 
Before / after
> feat(topsites): Fetch favicons for pinned sites instead of only relying on frecency data

- system-addon/ping-centre/PingCentre.jsm
- system-addon/test/unit/ping-centre/PingCentre.test.js
> chore(ping-centre): Make adjustments to default Ping Centre fields. Closes #3557.

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/content-src/components/Sections.test.jsx
- system-addon/test/unit/lib/TopStoriesFeed.test.js
Closes #3574 
This also addressed the duplicated telemetry described in the issue when dismissing....
> fix(topstories): #3574 Dismissing top stories stopped working

- system-addon/content-src/components/TopSites/TopSitesEdit.jsx
Fix #3595. r?@rlr Missed this from #3563. Doh #3189.
> fix(styles): Also use same 12px margin for editing top sites

- system-addon/lib/PrefsFeed.jsm
Followup from #3542. @k88hudson Landing for bustage fix.
> chore(prefs): Restore default onboarding pref when UNINITing

- system-addon/content-src/activity-stream.scss
> fix(styles): Always keep vertical scroll visible to avoid horizontal jank

- system-addon/common/Reducers.jsm
- system-addon/lib/HighlightsFeed.jsm
- system-addon/lib/SectionsManager.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/common/Reducers.test.js
- system-addon/test/unit/lib/HighlightsFeed.test.js
- system-addon/test/unit/lib/SectionsManager.test.js
- system-addon/test/unit/lib/TopStoriesFeed.test.js
closes Bug #3131 and fix #3573 and fix #3629
> Bookmarking topstories

- docs/v2-system-addon/data_dictionary.md
- system-addon/lib/TelemetryFeed.jsm
> fix(reporting): Add showHighlights and showSnippets to user_prefs

- system-addon/content-src/activity-stream-prerender.jsx
- system-addon/test/unit/activity-stream-prerender.test.jsx
Fix #3655 Ok so this is the fix (the exported code will have more lines) but we still need to deal with the situation with the test regressing –
@Mardak any ideas about what we should do there? Maybe change the test? maybe just let some people know?
> fix(l10n): #3655 Fix flash of untranslated content

- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
- system-addon/content-src/components/Topics/_Topics.scss
- system-addon/content-src/styles/_icons.scss
don't ask. because i don't know really know why. lolcss
Fixes #3665
> fix (systemaddon): #3665 fix alignment of collapsible header

- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
- system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
Followup to #3700. r?@rlr I guess I looked through https://developer.mozilla.org/en-US/docs/Web/CSS/background-position too quickly. Too many possible values! ;)
> chore(styles): Switch background-position calc to 2-value syntax

- system-addon/content-src/components/Base/_Base.scss
Fix #3692 and fix #3640. r?@k88hudson Just backporting https://hg.mozilla.org/integration/autoland/rev/310eff6bb091 and updating comments.
> feat(styles): Show placeholders for better perceived performance

- system-addon/content-src/components/Topics/_Topics.scss
Fixes #3712. It would still move if the topics get wide due to quantity or l10n.
> fix (styles): #3712 fix sizing of topics read more link

- system-addon/common/Actions.jsm
- system-addon/content-src/activity-stream.jsx
- system-addon/content-src/lib/detect-user-session-start.js
- system-addon/content-src/lib/init-store.js
- system-addon/test/unit/common/Actions.test.js
- system-addon/test/unit/content-src/lib/detect-user-session-start.test.js
- system-addon/test/unit/lib/init-store.test.js
> fix(reporting): Send visibility_event when ActivityStream is ready

- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/lib/PlacesFeed.test.js
> Ignore first run bookmark added events.

- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
- system-addon/content-src/components/TopSites/_TopSites.scss
> fix (styles): #3671 dont show hover state on collapsed sections

- system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
- system-addon/content-src/components/ConfirmDialog/_ConfirmDialog.scss
- system-addon/content-src/lib/link-menu-options.js
- system-addon/content-src/styles/_icons.scss
- system-addon/content-src/styles/_variables.scss
- system-addon/data/content/assets/glyph-modal-delete-32.svg
- system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
specs: https://mozilla.invisionapp.com/share/59E45AXDJ#/screens/238928525_Photon_-_Confirm_Dialog
> feat(modal): Closes #3615 Provide an icon for the confirm dialog

- system-addon/content-src/components/Card/Card.jsx
- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/test/functional/mochitest/browser.ini
- system-addon/test/functional/mochitest/browser_highlights_section.js
- system-addon/test/functional/mochitest/browser_topsites_section.js
- system-addon/test/functional/mochitest/head.js
WIP. Closes #3768 
Try run https://treeherder.mozilla.org/#/jobs?repo=try&revision=22305f3b8c03d5af8fd332629b2a64fe74044c19&selectedJob=142050925
> Add more mochitests

- system-addon/lib/FaviconFeed.jsm
- system-addon/test/unit/lib/FaviconFeed.test.js
@Mardak exponential backoff?
Fixes #3834
> fix (faviconfeed): #3834 exponential backoff for tippytop manifest fetch

- system-addon/content-src/components/ManualMigration/_ManualMigration.scss
> fix(systemaddon): Use nowrap to display migration buttons on the same line

- mozilla-central-patches/add-favicon-ref.diff
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/content-src/components/TopSites.test.jsx
@Mardak kind of hoping that this change is as simple as this? But I'm guessing more needs to be done for the m-c change?
Fixes #3837
> fix (telemetry): #3837 detect remote tippytop

- system-addon/lib/ActivityStream.jsm
> fix (tippytop): URL for remote tippytop

- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/test/unit/content-src/components/TopSites.test.jsx
> chore(systemaddon): Use a single method to dispatch TopSites icon stats.

- .sass-lint.yml
- package-lock.json
- package.json
- system-addon/content-src/components/Base/_Base.scss
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
- system-addon/content-src/components/ConfirmDialog/_ConfirmDialog.scss
- system-addon/content-src/components/ContextMenu/_ContextMenu.scss
- system-addon/content-src/components/ManualMigration/_ManualMigration.scss
- system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
- system-addon/content-src/components/Search/_Search.scss
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/content-src/components/Topics/_Topics.scss
- system-addon/content-src/styles/_activity-stream.scss
- system-addon/content-src/styles/_icons.scss
- system-addon/content-src/styles/_normalize.scss
- system-addon/content-src/styles/_variables.scss
- system-addon/content-src/styles/activity-stream-linux.scss
- system-addon/content-src/styles/activity-stream-mac.scss
- system-addon/content-src/styles/activity-stream-windows.scss
- yamscripts.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1421444
Supersedes #3871.
r?@sarracini
I rebased @SeanPrashad's PR to latest master, which required some additional fixups. Updating sass-lint also required some additional fixup. I also added a commit to re-enable temporarily disabled rules.
> Bug 1421444 - Fix sass linting

- package-lock.json
- package.json
- system-addon/test/unit/lib/TelemetryFeed.test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1421847 r?@dmose Easy enough ;)
https://github.com/chaijs/chai/releases
> Fix Bug 1421847 - Update chai by fixing assert.propertyNotVal is not a function

- bin/test-merges.js
Tested by-hand in place, it should fix the problem (and can't possibly make it worse :-).
> Fix Bug 1421857 - fix test-merges regression to un-bust pine

- bin/render-activity-stream-html.js
- system-addon/content-src/components/Base/Base.jsx
> Fix Bug 1422074 - Remove icon <link> as it's specially shown for about:home/about:newtab

- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/TopSitesEdit.jsx
- system-addon/test/unit/content-src/components/TopSites.test.jsx
> chore (cleanup): infer TopSite editMode from onEdit prop

- system-addon/lib/FaviconFeed.jsm
- system-addon/test/unit/lib/FaviconFeed.test.js
r?@rlr Check prefs before trying to fetch. Also removes `ActivitySteramPrefs` usage to `getState` instead. Also fixed up not quite right test that was still checking state.TippyTop.
> Fix Bug 1423506 - Tippytop does not honor preference browser.chrome.site_icons

- docs/v2-system-addon/data_dictionary.md
- docs/v2-system-addon/data_events.md
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/test/schemas/pings.js
- system-addon/test/unit/content-src/components/TopSites.test.jsx
- system-addon/test/unit/lib/TelemetryFeed.test.js
> Fix Bug 1425319 - Add count of pinned Top Sites to session telemetry ping

- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/TopSitesEdit.jsx
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/test/unit/content-src/components/TopSites.test.jsx
> Fix Bug 1426464 - edit button for Top Site placeholders

- system-addon/common/PrerenderData.jsm
> Fix Bug 1426777 - Flash of 2 rows of top sites when only 1 should be shown

- system-addon/common/Reducers.jsm
- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/TopSitesEdit.jsx
- system-addon/content-src/lib/link-menu-options.js
- system-addon/test/unit/common/Reducers.test.js
- system-addon/test/unit/content-src/components/LinkMenu.test.jsx
- system-addon/test/unit/content-src/components/TopSites.test.jsx
> Followup fixes for Bug 1426464

- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/_TopSites.scss
Fixes an issue where the placeholder edit button was too small and
off-centre in windows.
> Fix Bug 1428035 - Make placeholder edit button use same styles as context  e h

- system-addon/content-src/components/TopSites/TopSite.jsx
@Mardak r? does that make sense?
> Followup for c2427c0 - added a comment for future us

- system-addon/common/Reducers.jsm
- system-addon/test/unit/common/Reducers.test.js
I removed the optimistic optimization that doesn't work right when there are pinned sites.
r? @Mardak
> Fix Bug 1428356 - dismissing/deleting Top Sites when some are pinned

- system-addon/lib/ActivityStreamMessageChannel.jsm
- system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js
Add all preloaded browser ports across windows and send a message to each + a new test and updated comments
> Fix Bug 1430218 - Update each preloaded browser in every window with new content

- system-addon/ping-centre/PingCentre.jsm
- system-addon/test/unit/ping-centre/PingCentre.test.js
This closes Bugzilla bug 1421422
> Fix Bug 1421422 - Add a region whitelist for PingCentre

- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/_TopSites.scss
> Fix Bug 1430132 - dont show hover/active/focus state during DnD

- locales/en-US/strings.properties
r?@rlr Address review comments from https://github.com/mozilla/activity-stream-l10n/pull/10
> chore(l10n): Update localization comments based on reviews

- docs/v2-system-addon/data_events.md
- system-addon/common/Reducers.jsm
- system-addon/content-src/components/TopSites/TopSiteForm.jsx
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/content-src/components/TopSites.test.jsx
- system-addon/test/unit/lib/TopSitesFeed.test.js
> Fix Bug 1434937 topsites refactor

- system-addon/lib/HighlightsFeed.jsm
Just backporting this change since it landed in nightly while i work on  Bug 1425496
> chore(mc): Backport changes from Bug 1425496

- system-addon/lib/TelemetryFeed.jsm
- system-addon/lib/UTEventReporting.jsm
- system-addon/test/schemas/pings.js
Followup to #3926. r?@emtwo 
All fixed automatically with `eslint --fix`
> chore(lint): Fix eslint issues from bug 1429489 changes

- system-addon/content-src/activity-stream-prerender.jsx
- system-addon/content-src/components/Base/Base.jsx
- system-addon/test/unit/activity-stream-prerender.test.jsx
- system-addon/test/unit/content-src/components/Base.test.jsx
To test: 
1. `npm run cleanmc && npm run buildmc`
2. note that line 12 of `system-addon/prerendered/locales/en-US/activity-stream-prerendered.html` (the line with `div id="root"`) once again has lots of stuff in it.
> fix(React 16): fix prerendering (bug 1435920)

- system-addon/common/Reducers.jsm
- system-addon/content-src/components/Base/Base.jsx
- system-addon/content-src/components/Base/_Base.scss
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/content-src/styles/_variables.scss
- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/content-src/components/TopSites.test.jsx
- system-addon/test/unit/lib/TopSitesFeed.test.js
@Mardak turns out we don't dedupe from Top Sites anymore 😅 
before:
after:
> Fix Bug 1385944 - support wider layout

- webpack.system-addon.config.js
https://webpack.js.org/configuration/devtool/
> (nobug) Fix webpack sourcemap config to say 'source-map'

- system-addon/content-src/components/TopSites/TopSite.jsx
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/test/unit/content-src/components/TopSites.test.jsx
@aaronrbenson requested and approved these changes.
Before:
After:
> chore (polish): change drag and drop target to a grey box

- system-addon/common/PrerenderData.jsm
- system-addon/content-src/components/Sections/_Sections.scss
The "wireframe" term threw me off but I eventually figured it out.
> Fix Bug 1438523 - add enableWideLayout to prerender prefs

- system-addon/test/functional/mochitest/browser.ini
- system-addon/test/functional/mochitest/browser_topsites_contextMenu_options.js
- system-addon/test/functional/mochitest/browser_topsites_section.js
- system-addon/test/functional/mochitest/head.js
r?@sarracini https://hg.mozilla.org/mozilla-central/rev/bebe83ac3b64
Needed to fix some lint issues.
> chore(mc): Port Bug 1410818 - Add a test to verify the menu options for a default top site. r=Mardak

- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1440419
>  Fix Bug 1440419 - Use probabilistic approach instead of counter for spoc frequency

- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
> Fix Bug 1440792 - Context menus for sites and cards are opened too far from the button

- system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
- system-addon/content-src/styles/_icons.scss
- system-addon/data/content/assets/glyph-arrowhead-up-16.svg
r?@sarracini kept the downs and rotated them. cc @rlr
> chore(styles): Use a down-16 arrow for down/up and a smaller down-12 for down/forward.

- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TelemetryFeed.jsm
- system-addon/test/unit/lib/TelemetryFeed.test.js
> Fix Bug 1440378: Events Telemetry should be off by default in release

- system-addon/common/Reducers.jsm
- system-addon/content-src/components/Card/Card.jsx
- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/content-src/components/Card.test.jsx
- system-addon/test/unit/lib/PlacesFeed.test.js
> Fix Bug 1441931 - Use open_url provided by Pocket for 'saved to pocket' items in highlights

- CODEOWNERS
- locales/en-US/strings.properties
r?@k88hudson cc@piatra 
Landing final strings for #4015 and #3891 sooner than those PRs.
> chore(strings): Add strings for about:preferences and top site custom images

- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
> Fix Bug 1442193 - show section context menu button on :focus

- system-addon/content-src/components/Card/_Card.scss
> Fix Bug 1443347 - Adjust styles for larger cards on wide layout

- system-addon/test/functional/mochitest/browser.ini
- system-addon/test/functional/mochitest/browser_topsites_contextMenu_edit.js
Bug 1441570 - Add a test to verify that a topsite can be edited from the context menu.
> Bug 1441570 - Add a test to verify that a topsite can be edited from the context menu.

- package-lock.json
Update to commit https://github.com/mozilla/activity-stream/commit/d8e8a193141a04d867776fc1057282e35fe0f037
> Fix Bug 1441278 - Update package-lock.json

- locales/en-US/strings.properties
- system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
- system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
Document tracking unused strings https://docs.google.com/document/d/1o7cZ2xmNOJNmyzGxbLzYq-w-AYp8TQyLhU9u-z3XOzs/edit
More deletions to go with [the previous PR that landed](https://github.com/mozilla/activity-stream/commit/1d0e3079ce17b23ac77bd0ec2513205fa9c11dd0).
> Fix Bug 1433209 - Remove unused strings

- system-addon/lib/HighlightsFeed.jsm
- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/lib/HighlightsFeed.test.js
- system-addon/test/unit/lib/PlacesFeed.test.js
I think I did this right, but please let me know if there's anything that needs changing! 😄
> Fix Bug 1444518 - Ignore bookmarks added and removed during an import or restore

- system-addon/lib/UTEventReporting.jsm
- system-addon/test/unit/lib/TelemetryFeed.test.js
> Fix Bug 1442820 - Fix the unbound this in UTEventReporting

- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/lib/PlacesFeed.test.js
[Bug 1199077](https://bugzilla.mozilla.org/show_bug.cgi?id=1199077) is now in Nightly. 🌔 🔜 🏞
> Backport new bookmark change sources

- system-addon/test/unit/lib/SystemTickFeed.test.js
> chore (codequality) #nobug Remove unnecessary usage of injector

- system-addon/lib/UserDomainAffinityProvider.jsm
- system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
> chore (perf): lazy load NavHistoryService in UserDomainAffinityProvider

- system-addon/content-src/components/Base/Base.jsx
- system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
ref:
https://github.com/mozilla/activity-stream/pull/4044#discussion_r178161891
https://github.com/mozilla/activity-stream/pull/4044#discussion_r178194126
r? @Mardak
> chore(cleanup): fix some missed r? comments from 997f422

- system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.jsx
- system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.scss
> Fix Bug 1450964 - Add scoped CSS variables to MessageCenterAdmin

- system-addon/content-src/components/ContextMenu/_ContextMenu.scss
- system-addon/content-src/styles/_theme.scss
> Fix Bug 1451089 - make context menu styles consistent with doorhangers

- system-addon/content-src/components/Search/_Search.scss
- system-addon/content-src/styles/_theme.scss
> Fix Bug 1451474 - color updates for search drop down

- system-addon/lib/AboutPreferences.jsm
design r=abenson
see also https://reviewboard.mozilla.org/r/236154/
> Bug 1453761 - Make font size of option descriptions larger

- system-addon/test/functional/mochitest/browser_topsites_contextMenu_options.js
Bug 1410828 - Add a test to verify that the next top site in queue replaces a dismissed top site
> Fix Bug 1410828 - Add a test to verify that the next top site in queue replaces a dismissed top site

- system-addon/lib/ThemeFeed.jsm
- system-addon/test/unit/lib/ThemeFeed.test.js
r? @Mardak 
This bug hadn't been exported to m-c yet?
> Fix Bug 1454501 - followup to ee47675 to handle default theme being undefined

- system-addon/content-src/components/ConfirmDialog/_ConfirmDialog.scss
- system-addon/content-src/styles/_theme.scss
- system-addon/content-src/styles/_variables.scss
tiny little refactor to make onboarding theming easier.
> chore (styles): modal overlay color refactor

- system-addon/lib/TopStoriesFeed.jsm
- system-addon/test/unit/lib/TopStoriesFeed.test.js
@csadilek how do I test this locally? r?
> Fix Bug 1454743 - fix section fetching in spocs experiment

- system-addon/lib/ActivityStream.jsm
Also update feed_variant to be either "default_spocs_on" or "default_spocs_off".
en-US / US
en-US / CA
de / DE
zh-TW (stories section not even shown)
> Followup Bug 1454807 - Enable for US region only (for en-* locales)

- system-addon/content-src/asrouter/components/SnippetBase/_SnippetBase.scss
- system-addon/content-src/styles/_theme.scss
- system-addon/content-src/styles/_variables.scss
Related PRs that depend on this:
https://github.com/mozmeao/snippets-service/pull/385
https://github.com/mozmeao/snippets/pull/144
r? @k88hudson
> Fix Bug 1449653 - Implement a dark theme for snippets

- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/unit-entry.js
r? @sarracini Just stubbing ChromeUtils https://hg.mozilla.org/mozilla-central/rev/c58f0b4dd849
> Port Bug 1456035: Part 4 - Convert callers of XPCOMUtils.generateQI to ChromeUtils.generateQI. r=mccr8

- system-addon/common/PrerenderData.jsm
- system-addon/content-src/components/Base/Base.jsx
- system-addon/content-src/components/Base/_Base.scss
- system-addon/content-src/components/Card/_Card.scss
- system-addon/content-src/components/Sections/_Sections.scss
- system-addon/content-src/components/TopSites/_TopSites.scss
- system-addon/lib/ActivityStream.jsm
This was put in the backlog but it was bothering me every time I saw it. r? @Mardak
> Fix Bug 1456554 - remove wide layout experiment

- system-addon/lib/TelemetryFeed.jsm
- system-addon/test/unit/lib/TelemetryFeed.test.js
This adds the client side ping handling for AS router.
Three more items on the TODO list after merging this.
* Finalize the schema of event & impression pings for Snippets
* Complete data review accordingly
* Enable data collection for AS Router both on the client side and in the data pipeline
> Fix Bug 1456127 - Handle telemetry pings for AS Router in TelemetryFeed

- system-addon/lib/ActivityStream.jsm
r?@k88hudson I put CA first! (and alphabetized)
> Fix Bug 1458701 - Enable pocket stories for en-CA

- locales/en-US/strings.properties
Removes unused strings, as documented in Bug 1445090.
> Fix Bug 1445090-chore(l10n): remove unused strings to ease l10n work

- system-addon/content-src/lib/snippets.js
- system-addon/lib/SnippetsFeed.jsm
- system-addon/test/unit/lib/SnippetsFeed.test.js
> Fix Bug 1460119 - gSnippetsMap.getTotalBookmarksCount() never resolves

- system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
- system-addon/content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
> Fix unreferenced onboarding illustrations

- system-addon/test/functional/mochitest/browser_highlights_section.js
r?@k88hudson Followup to #4159
> chore(highlights): Update mochitest to check for 2 rows of placeholders

- docs/v2-system-addon/data_dictionary.md
- docs/v2-system-addon/data_events.md
This documents the ping added in [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1458617)
> chore(doc): Update doc for Activity Stream heartbeat ping

- bin/strings-import.js
- package-lock.json
- package.json
- yamscripts.yml
Waiting for Pike's feedback before review.
> Fix Bug 1457580 - Update strings-import to get strings from l10n-central

- system-addon/content-src/asrouter/asrouter-content.jsx
- system-addon/content-src/lib/snippets.js
- system-addon/test/unit/content-src/lib/snippets.test.js
This is the commit for uplifting Bug 1464019
> Bug 1464019 - Turn off asrouter snippets when snippets.feed is is false

- system-addon/content-src/components/Sections/Sections.jsx
- system-addon/lib/ActivityStream.jsm
- system-addon/lib/HighlightsFeed.jsm
- system-addon/lib/SectionsManager.jsm
- system-addon/test/unit/content-src/components/Sections.test.jsx
- system-addon/test/unit/lib/HighlightsFeed.test.js
Whoa, I was super excited to open about:preferences and see this without touching any of that code (🎩 tip @Mardak):
> Fix Bug 1400536 - add pref for number of rows in sections

- system-addon/lib/AboutPreferences.jsm
- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
I think this is all we have to do? @Mardak r?
> Fix Bug 1465398 - change max rows for top sites to 4

- system-addon/content-src/styles/_theme.scss
> (nobug) remove unused var(--newtab-text-tertiary-color)

- content-src/components/StartupOverlay/StartupOverlay.jsx
- content-src/components/StartupOverlay/_StartupOverlay.scss
- locales/en-US/strings.properties
r?@sarracini
Some visual things went unnoticed in the first round.
Done:
Bug 1467811
Bug 1467816
Bug 1467812
Bug 1467815
Bug 1467817 
To discuss:
https://bugzilla.mozilla.org/show_bug.cgi?id=1467814 - I'm not sure this red highlight and custom message are necessary.
https://bugzilla.mozilla.org/show_bug.cgi?id=1467813 - various font differences. If I recall correctly, there were some issues that we couldn't use the same font in product.
> Various Visual Edits

- content-src/components/StartupOverlay/_StartupOverlay.scss
@sarracini 
One more missed thing. The fonts should be bolder, looks a bit better this way.
> Bug 1467813 - Make fonts bolder.

- content-src/components/StartupOverlay/_StartupOverlay.scss
> chore(fix): Fix media query to use px

- content-src/components/StartupOverlay/_StartupOverlay.scss
r? @sarracini More #4200 followup to #4206
> chore(styles): More followup max-width media query fix with px

- test/functional/mochitest/browser_asrouter_targeting.js
> chore(tests): Follow up to bug 1465553 fix failing mochitests

- lib/TopSitesFeed.jsm
- test/unit/lib/TopSitesFeed.test.js
Quick fix + a test for this bug. Easy win and makes unblocking a lower priority
> Bug 1458658 - Unblock sites that are added

- bin/render-activity-stream-html.js
This patch renders Activity Stream HTML files without the script tag. This should not modify the existing behavior of Activity Stream because the noscripts HTML files will only be used when the "browser.tabs.remote.separatePrivilegedContentProcess" preference is turned on. When that happens, we render the noscripts version of Activity Stream and inject scripts into the page using mozJSSubScriptLoader when DOMContentLoaded is fired. (Ref: https://reviewboard.mozilla.org/r/252462/diff/3#index_header)
We will need to do an export before landing https://bugzilla.mozilla.org/show_bug.cgi?id=1416066.
> Bug 1416066 - Render Activity Stream HTML files without scripts

- content-src/asrouter/components/Button/_Button.scss
- content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
- content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
- content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
- content-src/components/StartupOverlay/_StartupOverlay.scss
- content-src/styles/_variables.scss
a variety of things that were annoying me showing up as warnings
63 problems down to 35
exciting times
> chore(css): Fix various css warnings and adjust margins for about:welcome

- content-src/asrouter/components/SnippetBase/_SnippetBase.scss
- content-src/components/Base/_Base.scss
- content-src/components/Card/_Card.scss
- content-src/components/CollapsibleSection/_CollapsibleSection.scss
- content-src/components/ContextMenu/_ContextMenu.scss
- content-src/components/Search/_Search.scss
- content-src/components/StartupOverlay/_StartupOverlay.scss
- content-src/components/TopSites/_TopSites.scss
- content-src/styles/_variables.scss
Property names can change who knew!
Used:
```
find . -type f -exec sed -i 's/offset-\(inline\|block\)/inset-\1/g' {} \;;
```
> Backport changes from bug 1464782

- content-src/asrouter/schemas/message-format.md
Just some documentation updates. I also changed targeting to not required, since it is not required.
> (nobug): Add trigger to message spec

- content-src/components/Base/Base.jsx
- content-src/styles/_activity-stream.scss
> Fix Bug 1472297 - Hide the existing onboarding button for users in the new simplified onboarding experience cohort

- content-src/asrouter/asrouter-content.jsx
- content-src/asrouter/schemas/provider-response.schema.json
- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/asrouter-content.test.jsx
> Fix Bug 1470170 - Implement priority system for AS Router messages

- content-src/components/Base/Base.jsx
- content-src/components/StartupOverlay/StartupOverlay.jsx
- test/unit/content-src/components/StartupOverlay.test.jsx
issue described in https://github.com/piatra/activity-stream/blob/1cb7444a7bd1c653e87512d5b9e4ce83e454c9b2/content-src/components/StartupOverlay/StartupOverlay.jsx#L62-L63
> Fix Bug 1472209 - Remove StartupOverlay if the tour is skipped

- lib/AboutPreferences.jsm
- test/unit/lib/AboutPreferences.test.js
r?@sarracini Moved the code a little bit higher and `s/detailVbox/sectionVbox/` and `s/label/checkbox/`
> Fix Bug 1465548 - Pocket about:preferences "Learn more" is in the wrong place

- lib/PlacesFeed.jsm
- test/unit/lib/PlacesFeed.test.js
backport from https://hg.mozilla.org/mozilla-central/rev/31115ed412b5
> Backport changes from Bug 1472472

- content-src/components/StartupOverlay/_StartupOverlay.scss
Fix test failures from #4233
r?@sarracini Use longhand background to avoid replacing themed background-color
> Followup Bug 1471243 to fix browser_ext_themes_ntp_colors.js mochitest failure.

- content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
- content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
- content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
- content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
Adds focus & active to the buttons in the onboarding overlay
> Fix Bug 1475212 - Onboarding overlay's buttons are not visibly focused using keyboard navigation

- lib/TopStoriesFeed.jsm
- test/unit/lib/TopStoriesFeed.test.js
> Fixing spocs so they have the chance to load on first tab.

- content-src/components/StartupOverlay/StartupOverlay.jsx
- lib/PrefsFeed.jsm
Uplift pr for bug 1471514
Note: when this gets exported to beta there will be another patch that will be part of the uplift patch: https://hg.mozilla.org/mozilla-central/rev/c8b52817d7f9
> Fix Bug 1471514 - Add top-of-funnel metrics for fxa

- bootstrap.js
- lib/ActivityStream.jsm
- test/unit/lib/ActivityStream.test.js
- test/unit/unit-entry.js
Removes pref migration stuff and moves it to ActivityStream.jsm
> Fix Bug 1474411 - Port remaining desired functionality from bootstrap.js to ActivityStream.jsm

- content-src/asrouter/README.md
- lib/ASRouter.jsm
- test/unit/asrouter/ASRouter.test.js
And add documentation about how preview works.
> Fix Bug 1479413 - Remove preview provider and message after it has been displayed

- .sass-lint.yml
- content-src/components/Card/_Card.scss
- content-src/components/TopSites/_TopSites.scss
> Fix Bug 1476450 - disallow text-transform in sass-lint

- aboutNewTabService.js
r?@sarracini https://hg.mozilla.org/mozilla-central/rev/6499bc583b57#l2.12
> Port Bug 1478404 - remove _xpcom_categories annotations as they're dead code, r=florian

- lib/ActivityStream.jsm
- lib/TopSitesFeed.jsm
- test/browser/head.js
- test/unit/lib/TopSitesFeed.test.js
WIP, based off Andrei's PR. Will need to rebase when his lands and add more tests.
> Fix Bug 1480508: Add search shortcuts for new and existing users

- content-src/components/Base/Base.jsx
- content-src/components/ContextMenu/_ContextMenu.scss
- content-src/components/Search/Search.jsx
- content-src/components/Search/_Search.scss
- content-src/styles/_theme.scss
- content-src/styles/_variables.scss
Be sure to test scrolling at different window heights.
* At <= 700px it shouldn't become fixed and it has less padding.
* At > 700px it should turn into the persistent header search bar.
Verify dark theme too.
before:
after:
> Fix Bug 1481677 - persistent/stable search (aka fixed position search bar)

- lib/PlacesFeed.jsm
- test/unit/lib/PlacesFeed.test.js
This should wait for https://phabricator.services.mozilla.com/D2895 to land.
> Fix Bug 1481597 - Use the correct awesomebar API

- content-src/components/Base/Base.jsx
> Fix Bug 1482184 - only apply fixed-search if search section is visible

- content-src/components/TopSites/TopSite.jsx
- content-src/components/TopSites/_TopSites.scss
- data/content/assets/glyph-search-16.svg
- test/unit/content-src/components/TopSites.test.jsx
Just squashing the commits in https://github.com/mozilla/activity-stream/pull/4302
> Fix Bug 1481605 - Update designs for Top Site Search Shortcut tiles

- lib/TopSitesFeed.jsm
- test/unit/lib/TopSitesFeed.test.js
to test this, toggle the pref `browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts` to false and observe that the pref `browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned` was cleared, and check newtab that the pinned search shortcuts are gone. toggle again and see that they are there!
if you want to check even MORE! pin some other stuff and then toggle and see that the pinned stuff is intact
> Fix Bug 1482209 - Handle disabling of the search shortcuts experiment

- content-src/components/TopSites/TopSite.jsx
- content-src/components/TopSites/_TopSites.scss
- test/unit/content-src/components/TopSites.test.jsx
it's a button but it's also like a link. but its mostly a button. so now it's a button
> Fix Bug 1482473 - Top search should be more like a button not a link

- content-src/components/TopSites/TopSite.jsx
> Fix Bug 1482532 - make search shorcuts draggable again

- mochitest.sh
r?@k88hudson @piatra untested.. but.. should.. fix ?
> fix(tests): Skip taskcluster eslint as we have coverage with travis

- content-src/components/TopSites/SearchShortcutsForm.jsx
- content-src/components/TopSites/TopSite.jsx
- content-src/components/TopSites/_TopSites.scss
is this the solution you had in mind @k88hudson ?
> Fix Bug 1482853 - white background for all searchys

- lib/SearchShortcuts.jsm
> chore(mc): Port Bug 1482565 - Support and show @Яндекс and @百度 searches for yandex and baidu r=mkaply

- content-src/components/Search/_Search.scss
not sure why that was there in the first place?
> Fix Bug 1482871 - remove blue flash when clicking on div.search-wrapper

- lib/TopSitesFeed.jsm
- test/unit/lib/TopSitesFeed.test.js
> Fix Bug 1483257 - update search shortcuts when enabling experiment

- lib/AboutPreferences.jsm
- test/unit/lib/AboutPreferences.test.js
https://hg.mozilla.org/mozilla-central/rev/7c59c72f3c8c
> chore(mc): Port Bug 1479538 - Rewrite non-test callers of document.createElementNS(XUL_NS, ...) to use document.createXULElement(...);r=paolo

- content-src/asrouter/schemas/message-format.md
- lib/ASRouterTargeting.jsm
- test/browser/browser_asrouter_targeting.js
1483037	Add snippets targeting for attribution/source
1483046	Add snippets targeting for number of devices synced
1483050	Add snippets targeting for type of devices synced
1483056	Add snippets targeting for updates enabled
1483057	Add snippets targeting for update auto-downloads enabled
> (multiple): Add ASR telem

- content-src/components/StartupOverlay/StartupOverlay.jsx
This fixes the extra spaces added to the `entrypoint` param.
Fixes for the Bug 1478649 - https://github.com/ericawright/activity-stream/commit/39bff0e346b5134f341d977ef6105d1d05992048
@k88hudson @ericawright r?
> fix(fxa): remove extra spacing in the FxA funnel cake flow url

- content-src/activity-stream.jsx
- content-src/components/Base/Base.jsx
- content-src/lib/asroutercontent.js
- content-src/lib/snippets.js
- lib/ASRouter.jsm
- lib/ASRouterFeed.jsm
- lib/ASRouterTargeting.jsm
- lib/ActivityStream.jsm
- test/browser/browser_asrouter_targeting.js
- test/unit/activity-stream.test.jsx
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/ASRouterTargeting.test.js
- test/unit/asrouter/constants.js
- test/unit/content-src/lib/snippets.test.js
feedback needed before i fix all the tests... @k88hudson is this the right approach for this?
> Fix Bug 1476684 - Onboarding shouldn't be affected by snippets experiment prefs

- content-src/components/TopSites/_TopSites.scss
> Fix Bug 1484292 - remove hover state in Add Search Engine modal

- karma.mc.config.js
- lib/ASRouter.jsm
- lib/CFRMessageProvider.jsm
- lib/CFRPageActions.jsm
- test/unit/asrouter/ASRouter.test.js
To test this, open `about:config#asrouter` and click "show" on a CFR message. You should see a recommended chiclet show up, which should be clickable.
Please make sure your MC is up to date (you will need the latest patches that landed for CFR)
> Bug 1486529 - Add doorhanger testing via asrouter admin panel

- content-src/components/TopSites/_TopSites.scss
- content-src/styles/_variables.scss
@bryanbell and Amy said ship it:
> Fix Bug 1484289 - Update hover state style for Search Shortcuts

- lib/ASRouter.jsm
- lib/CFRPageActions.jsm
- test/unit/asrouter/ASRouter.test.js
> Fix Admin page CFR

- lib/ActivityStream.jsm
Turn onboarding off by default
> (nobug) Turn onboarding off by default

- lib/TelemetryFeed.jsm
- test/unit/lib/TelemetryFeed.test.js
This implements the telemetry policy for CFR described in https://docs.google.com/document/d/1iIBKyouzofpf3O3luEutqKc6J3F6SGMLGtFcvQydQv8/edit
> Fix Bug 1486648 - Implement telemetry policy for CFR

- lib/ASRouterTargeting.jsm
- lib/CFRMessageProvider.jsm
> Fix Bug 1487241 - Make sure top frecent query targeting meets requirements for CFR

- content-src/styles/_variables.scss
> Fix Bug 1487771 - add a delay for showing the context menu button when hovering links/sites

- lib/CFRMessageProvider.jsm
- lib/CFRPageActions.jsm
r?@piatra https://hg.mozilla.org/mozilla-central/rev/c14b6edd8863
Fixed various merge conflicts and updated messages to have string_id. Schema test fails.
> Port Bug 1485418 - Land CFR UI Strings r=flod,k88hudson

- content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
- test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
~Blocked on backporting 1485418~ now part of this bug
> Fix Bug 1487406 - Update ExtensionDoorhanger schema and tests

- content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
- docs/v2-system-addon/data_events.md
- lib/ASRouter.jsm
- lib/CFRMessageProvider.jsm
- lib/CFRPageActions.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx
Will request for data & legal review based on this document.
> Fix Bug 1484035, 1480099 - Implement CFR telemetry

- test/browser/browser.ini
- test/browser/browser_topsites_contextMenu_options.js
- test/browser/browser_topsites_section.js
- test/browser/head.js
f? @Mardak still working on this.
> Fix Bug 1481680 - Add mochitests for search shortcuts and fix existing mochitests

- test/browser/browser_asrouter_targeting.js
I was not able to reproduce this locally but since it's intermittent this is the only explanation I could come up with.
> Fix Bug 1486950 - Increase date range to avoid intermittent

- content-src/styles/activity-stream-mac.scss
This reverts commit 9cfd41c0fa592b014b135e381423327af34352fd.
> Revert "Fix Bug 1482534 - fix font smoothing in OSX (#4410)"

- lib/ASRouterTargeting.jsm
- test/unit/asrouter/ASRouterTargeting.test.js
Fixes an issue with the first PR that landed for this bug in https://github.com/mozilla/activity-stream/commit/3a65ec06d0633ad28ec80d6563c65a304e480abc
> Fix Bug 1484206 - Fix merge of custom context and targetting getters

- .eslintrc.js
https://hg.mozilla.org/mozilla-central/rev/05e07c98cc36
> Port Bug 1487246: Enable the eslint no-sequences rule. r=Standard8

- content-src/components/StartupOverlay/StartupOverlay.jsx
i know this is a p3 but it took me all of 3 seconds to do so
> Fix Bug 1491841 - Incorrect payload for undesired event FXA_METRICS_ERROR

- .eslintrc.js
- ping-centre/PingCentre.jsm
Note that this is specifically for changes that landed in 63.
> Port Bug 1486739 - Enable ESLint rule comma-dangle

- lib/ActivityStream.jsm
- lib/CFRMessageProvider.jsm
Note: when this is uplifted, we will need to change `UpdateUtils.getUpdateChannel` back to `AppConstants`
> Bug 1492174 - Update CFR Message to reflect planned cohorts

- test/browser/browser.ini
* https://treeherder.mozilla.org/logviewer.html#?job_id=200295332&repo=mozilla-central
* https://bugzilla.mozilla.org/show_bug.cgi?id=1489962#c7
Bug to revert this change https://bugzilla.mozilla.org/show_bug.cgi?id=1492777
> (nobug): Skip failing CFR mochitest

- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
Derived from Algorithm A [here](http://utopia.duth.gr/~pefraimi/research/data/2007EncOfAlg.pdf)
The paper doesn't give proofs of the right mathematical properties; I have provided some justification [here in the Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1484996#c2).
> Fix Bug 1484996: add weights for ASRouter messages

- lib/CFRMessageProvider.jsm
- test/unit/asrouter/CFRMessageProvider.test.js
> Bug 1492174 - Part 2. Add variants for lifetime caps

- content-src/components/TopSites/_TopSites.scss
- content-src/styles/_icons.scss
This shouldn't be merged until [the patch](https://bugzilla.mozilla.org/show_bug.cgi?id=1491609) makes it to Nightly.
> Backport Bug 1491609 - Updates to radio and checkbox common.css styling

- aboutNewTabService.js
- lib/ASRouter.jsm
- lib/ActivityStream.jsm
- lib/TelemetryFeed.jsm
- ping-centre/PingCentre.jsm
- test/browser/browser_packaged_as_locales.js
- test/unit/lib/ActivityStream.test.js
- test/unit/ping-centre/PingCentre.test.js
- test/unit/unit-entry.js
Backport of bug https://bugzilla.mozilla.org/show_bug.cgi?id=1491394 landed
> Backport Bug 1491394 - Update callsites to use new mozILocaleService API. r=jfkthame

- content-src/components/StartupOverlay/StartupOverlay.jsx
- docs/v2-system-addon/data_dictionary.md
- docs/v2-system-addon/data_events.md
- test/schemas/pings.js
- test/unit/content-src/components/StartupOverlay.test.jsx
cc @ncloudioj 
Context: https://bugzilla.mozilla.org/show_bug.cgi?id=1490826#c9
> Bug 1490826 - Add form info to FxA form submits

- content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
- test/browser/browser_asrouter_targeting.js
- test/browser/head.js
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/ASRouterTargeting.test.js
Test this by running mochi tests and confirming no failures happen on repeat=5, also try pressing the clear cache button on about:newtab#asrouter
> Bug 1494973 - Add clear cache method for ASRouter

- lib/HighlightsFeed.jsm
- test/unit/lib/HighlightsFeed.test.js
r?@sarracini Just process locally by grabbing the first result and adding type.
> Fix Bug 1488462 - Big slowdown happening every x minutes

- lib/HighlightsFeed.jsm
- test/unit/lib/HighlightsFeed.test.js
Merge after https://bugzilla.mozilla.org/show_bug.cgi?id=1488462 has landed on beta.
> [Uplift backport] Bug 1488462 - Big slowdown happening every x minutes

- content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
- docs/v2-system-addon/data_events.md
- lib/TelemetryFeed.jsm
- test/unit/lib/TelemetryFeed.test.js
Merge after https://bugzilla.mozilla.org/show_bug.cgi?id=1485069 has landed on beta.
> [Uplift backport] Bug 1485069 - Add client_id for Snippets reporting

- lib/ActivityStream.jsm
THE FINAL PIECE OF THE PUZZLE
this needs to wait for bug 1462415 to land in central
well, it doesn't *need* to... it just... should
> Fix Bug 1496721 - Flip the pref to turn simplified onboarding on

- content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
> Fix Bug 1499078 - Add RTL margins to onboarding modal

- content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
> Fix Bug 1499083 - Fix 'Dismiss' button colour in Newsletter snippet dark theme

- content-src/components/Card/Card.jsx
- content-src/components/CollapsibleSection/CollapsibleSection.jsx
- content-src/components/TopSites/TopSite.jsx
- locales/en-US/strings.properties
- test/unit/content-src/components/Card.test.jsx
- test/unit/content-src/components/TopSites.test.jsx
Add title to TopSite, Card, CollabsibleSection, 3 dotted menu.
Add `Menu` in `strings.properties` for localization
Fixes [Bugzilla#1483027](https://bugzilla.mozilla.org/show_bug.cgi?id=1483027)
> Fix Bug 1483027 - Add title to three doted menu in home

- .eslintrc.js
- lib/ASRouterPreferences.jsm
> Bug 1499823 - Change object-curly-newline to consistent instead of minProperties in eslint

- content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
- content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
I know this is not the ideal solution, but for the sake of fixing this and getting it in 64, I'm just making the modal a bit bigger, long enough to accommodate more lines. I'm thinking of making this more responsive with more grids and grid rows and stuff but it would be a bit of a rewrite.... so I'm not sure it's worth it
> Fix Bug 1499071 - Make onboarding just a bit longer for l10n

- lib/TelemetryFeed.jsm
- test/schemas/pings.js
- test/unit/lib/TelemetryFeed.test.js
> Fix Bug 1500431 - Add missing required fields to PAGE_TAKEOVER_DATA ping

- content-src/asrouter/docs/targeting-attributes.md
- lib/ASRouterTargeting.jsm
- test/browser/browser_asrouter_targeting.js
See documentation for description; covered by mochitests, no manual testing needed.
> Bug 1483055 - Add targeting for pinned sites

- mochitest.sh
Try doesn't complain https://treeherder.mozilla.org/#/jobs?repo=try&revision=5cfa3e4007e1fcab55dc9ee1859dd07829406616&selectedJob=206662390
> TC trigger listeners failure

- common/Actions.jsm
- lib/ASRouter.jsm
- lib/CFRMessageProvider.jsm
- lib/CFRPageActions.jsm
- test/browser/browser_asrouter_cfr.js
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/CFRPageActions.test.js
- test/unit/asrouter/constants.js
> Fix Bug 1497967 - Add Opt-out flow for users to stop seeing CFR recommendations

- .mcignore
> chore(nobug): Do not build about:library in buildmc

- lib/AboutPreferences.jsm
https://hg.mozilla.org/mozilla-central/rev/e6a310eb8e42
Currently on master, about:preferences just doesn't show "Firefox Home Content" !
> Port Bug 1493844 - Part 2 - Remove the "caption" and "groupbox" bindings. r=bgrins,dao,jaws,johannh,surkov

- content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
- content-src/components/ASRouterAdmin/ASRouterAdmin.scss
- lib/ASRouter.jsm
- test/unit/asrouter/ASRouter.test.js
Wanted to land this part first and then work on adding more features on top: 
* message filtering based on expression
* copy targeting parameters environment
The feature is on by default, @k88hudson do you still think it should be toggled on?
> Targeting devtools

- content-src/components/Base/_Base.scss
- content-src/components/Search/_Search.scss
- content-src/components/TopSites/_TopSites.scss
- content-src/styles/_variables.scss
> Fix Bug 1497683 - remove small breakpoint with 3 top sites across

- content-src/components/MoreRecommendations/_MoreRecommendations.scss
- content-src/components/PocketLoggedInCta/_PocketLoggedInCta.scss
- content-src/components/Sections/_Sections.scss
I can't assign a reviewer, so @k88hudson or @ScottDowne R?
> Bug 1497507 - aligning cta w. value proposition

- content-src/asrouter/components/RichText/RichText.jsx
- content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
- lib/ASRouter.jsm
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/RichText.test.jsx
I kept privacy and learn more links as `target=_blank` since it isn't the main action of the message.
> Fix Bug 1506594 - Open snippet links in same window

- mochitest.sh
This is the check that is failing. Do we want to have this as part of TC?
https://searchfox.org/mozilla-central/rev/7f7c353e969e61a6a85201cc8ad3c3de12ac30d8/toolkit/mozapps/installer/packager.mk#38
> Fix Bug 1506229 - Run check for duplicate files in TC

- lib/CFRMessageProvider.jsm
- test/unit/asrouter/CFRMessageProvider.test.js
Changes CFR to only include:
- Facebook Container
- Youtube 
- Google Translate
> Bug 1510678 - Change recommended addons for Firefox 64 CFR release

- locales-src/ca/strings.properties
- locales-src/he/strings.properties
- locales-src/hy-AM/strings.properties
- locales-src/ia/strings.properties
- locales-src/it/strings.properties
- locales-src/ja-JP-mac/strings.properties
- locales-src/ja/strings.properties
- locales-src/nl/strings.properties
- locales-src/oc/strings.properties
- locales-src/pt-BR/strings.properties
- locales-src/pt-PT/strings.properties
- locales-src/ro/strings.properties
maybe again robot?
chore(l10n): Update from l10n-central Thu Dec 13 2018 13:32:49 GMT-0800 (PST)
> Fix Bug 1514056 - Update strings 2018-12-13

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/components/DiscoveryStreamComponents/HorizontalRule/HorizontalRule.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/components/DiscoveryStreamComponents/SectionTitle/SectionTitle.jsx
- content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
- content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
- content-src/styles/_activity-stream.scss
- lib/ActivityStream.jsm
Updated the gist with a better set of data, closer matching the current API.
I also started to stub out the components we probably need. (without proper design, this is all I was willing to get into)
~~TopSites is a whole thing that I copied in, I left a githube comment in the pr explaining some of my reasoning, but it's not intended to be a proper solution, I might just rip it out and go with a placeholder instead.~~ Removed this, and went with a simple stub.
> no bug - Stubbing out Discovery Stream components.

- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
- lib/ActivityStream.jsm
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouterTargeting.test.js
- test/unit/asrouter/MessageLoaderUtils.test.js
- test/unit/content-src/components/ReturnToAMO.test.jsx
- test/unit/content-src/components/StartupOverlay.test.jsx
- test/unit/unit-entry.js
This landed in beta https://bugzilla.mozilla.org/show_bug.cgi?id=1515411#c14
> Bug 1515411 - Disable Return to AMO for 65 Beta and Release

- content-src/components/Search/Search.jsx
- docs/v2-system-addon/data_events.md
- test/schemas/pings.js
- test/unit/content-src/components/Search.test.jsx
> Bug 1514732 - Create a telemetry ping for search hand-off

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/lib/selectLayoutRender.js
- package-lock.json
- package.json
- test/unit/content-src/lib/selectLayoutRender.test.js
Testing plan:
1. Enable Discovery Stream, check that the `Hero` element still loads as expected with data from the feed.
> Bug 1520514 - Add memoized selector to add feed data and spocs to layout

- common/Reducers.jsm
- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/lib/selectLayoutRender.js
To test, ensure the page doesn't crash on multiple refreshes.
> Bug 1520662: Ensure undeterministic load order is not causing crashes

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- test/browser/browser.ini
- test/browser/browser_discovery_styles.js
r?@ScottDowne or @k88hudson Fix regression from #4692 and adds a variety of mochitests
Pushed try to see if there's cross platform issues with the normalization… https://treeherder.mozilla.org/#/jobs?repo=try&revision=64ad4c83e051c35083072f9d30a6f8936a8f63fc
> (no bug) - Fix css style regression from grid column alignment and add tests

- content-src/components/DiscoveryStreamComponents/List/_List.scss
Normal
Hover
Active
Hover
Active
And same for List without image.
> Bug 1519772 - Implement pressed and hover states for list items

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/components/DiscoveryStreamComponents/List/_List.scss
r?@piatra or @dmose Removed the explicit hr to just add a top border to the ul conditionally. Scoped the other border to the class.
> Bug 1519871 - implement borderless ds lists

- content-src/components/Search/Search.jsx
- content-src/components/Search/_Search.scss
r? @piatra 
Basically the same as https://phabricator.services.mozilla.com/D17304 with less style overrides.
(Make sure your m-c is up to date)
> Bug 1521568 - Can't drag downloaded PDF into new tab

- content-src/styles/_mixins.scss
Wolasi wants the previous behavior back...
> (nobug) – Reverting clamping mixin behavior

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/components/DiscoveryStreamComponents/List/_List.scss
r?@dmose or @piatra Slightly refactoring of using :not to avoid applying a style then overriding with more specificity.
> Bug 1519878 - implement full width ds-list items

- content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
- content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
- content-src/components/DiscoveryStreamComponents/List/_List.scss
- content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
- content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
- content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
- content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
- content-src/styles/_mixins.scss
> Design Jam Stuff!

- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
r? @punamdahiya @k88hudson or @gvn ? Turns out we *were* showing more than what the server was specifying 😛 !
> Bug 1523031 - Hero with lists show 1 too many items

- test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx
r?@punamdahiya or @gvn Adds tests to cover the regressions fixed in #4739 and #4740.
> chore(tests): Add basic hero and list tests to ensure correct item offset rendering

- content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
I just updated a few descriptions to make the schema a little more comprehensive.
> Bug 1524386 - Update descriptions in CFR template schema

- lib/ASRouter.jsm
- test/unit/asrouter/MessageLoaderUtils.test.js
Against master as there's merge conflicts for the "amo" source change #4597
> Port Bug 1504056 Part 1: Refactor AddonManager.getInstallForURL() arguments r=kmag

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
> (nobug) - Refactor loadLayout so that _timestamp is now lastUpdated

- bin/render-activity-stream-html.js
- content-src/lib/snippets.js
Note that the rest of snippets will be removed in a future patch.
> Bug 1500061 - Tighen CSP for new tab

- content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
- content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
- content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
- content-src/components/DiscoveryStreamComponents/DSMessage/DSMessage.jsx
- content-src/components/DiscoveryStreamComponents/DSMessage/_DSMessage.scss
- content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
- content-src/components/DiscoveryStreamComponents/List/_List.scss
- content-src/styles/_variables.scss
- Set `browser.newtabpage.activity-stream.discoverystream.config` to `{"enabled":true,"show_spocs":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}`
- See [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1527370) for requested design tweaks
> Bug 1527370 – Design Tweaks 2: Electric Boogaloo

- lib/AboutPreferences.jsm
https://hg.mozilla.org/mozilla-central/rev/5b7bdfe0b357
r?@punamdahiya Just straight copy and tests are passing locally.
> Port Bug 1527495 - migrate text-link binding to CE, r=bgrins

- test/unit/lib/DiscoveryStreamFeed.test.js
r? @k88hudson Renamed the action and structure.
> Bug 1527702 - Followup: Fix test to check for new DISCOVERY_STREAM_IMPRESSION_STATS action

- docs/v2-system-addon/data_events.md
- lib/TelemetryFeed.jsm
- test/unit/lib/TelemetryFeed.test.js
- test/unit/unit-entry.js
A little different from our other events this is triggered from the parent process and is not associated with a `session_id` is that an issue?
>  Bug 1508744 - Instrument pin tab event 

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
To test:
1. Use pref dev-test-all
2. Load a new tab
3. Start scrolling down the page
Expected: spocs should be diverse and re ordered a bit.
> Bug 1522899 - Limit spocs per domain

- lib/ASRouter.jsm
- lib/ASRouterPreferences.jsm
- lib/ActivityStream.jsm
- lib/CFRMessageProvider.jsm
- lib/CFRPageActions.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/ASRouterPreferences.test.js
- test/unit/asrouter/CFRMessageProvider.test.js
https://phabricator.services.mozilla.com/D21408
> Bug 1528953 - Add pref to opt out of recommended features

- content-src/components/Base/Base.jsx
- content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
- content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
- content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
- content-src/components/DiscoveryStreamComponents/DSMessage/_DSMessage.scss
- content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
- content-src/components/DiscoveryStreamComponents/HorizontalRule/_HorizontalRule.scss
- content-src/components/DiscoveryStreamComponents/List/_List.scss
- content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
- content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
- content-src/styles/_mixins.scss
- content-src/styles/_theme.scss
- content-src/styles/_variables.scss
*Has had a design review from Wolasi.
Repro:
- Turn on Dark theme in preferences
> Bug 1525442 – Enable Dark Mode

- lib/DownloadsManager.jsm
- test/unit/unit-entry.js
Changes include lint fixes and a test stub. (Don't merge this PR, just for review)
> Backport Bug 827976 (with fixes)

- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
- content-src/lib/selectLayoutRender.js
- lib/TelemetryFeed.jsm
- test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
- test/unit/content-src/lib/selectLayoutRender.test.js
- test/unit/lib/TelemetryFeed.test.js
* Bug 1531604 - Fixing impression pos
* Fix unit tests
* tests and wteaks
> Bug 1531604 - Fixing impression pos (#4823)

- test/browser/browser_asrouter_targeting.js
@k88hudson r? was this what you had in mind or was there more? These tests assume that the trigger is setting up the context properly.
> Bug 1517303 - Add tests to verify CFR & targeting

- common/Reducers.jsm
- lib/DiscoveryStreamFeed.jsm
- test/unit/common/Reducers.test.js
- test/unit/lib/DiscoveryStreamFeed.test.js
> Bug 1529035 - State and pref reset

- .eslintrc.js
- lib/ASRouter.jsm
- test/browser/.eslintrc.js
- test/unit/asrouter/ASRouter.test.js
- test/xpcshell/.eslintrc.js
Making sure backports are fixed.
> [checking tests]

- docs/v2-system-addon/remote_cfr.md
- docs/v2-system-addon/tippytop.md
> Bug 1538811 - Document how to setup the dev environment for remote CFR messages

- lib/ActivityStream.jsm
@gvn just a small refactor I noticed.
The bug itself is related, kinda. I noticed when doing the bug that nothing needs to happen, but I also noticed we can do it in a better way.
To test, just make sure using a new profile you see spocs.
> bug 1522301 - Move to non hard coded geo check.

- lib/ASRouter.jsm
- lib/AboutPreferences.jsm
- test/unit/asrouter/ASRouter.test.js
r?@piatra https://hg.mozilla.org/mozilla-central/rev/28416f5a55b5
> Port 1494948: Removed FX_PREFERENCES_OPENED_VIA probe and origin parameter for openPreferences r=jaws,chutten

- lib/ActivityStream.jsm
- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
To test:
1. reset `browser.newtabpage.activity-stream.discoverystream.config`
2. Load a new tab, and ensure it is displaying basiclayout.
3. Updates `browser.newtabpage.activity-stream.discoverystream.config` so hardcoded_layout is true
4. Load a new tab, and ensure it is displaying the hardcoded layout.
> bug 1543800 - local layout

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
You can test this by looking at the as devtools with ds turned on and look at feeds returned, should have a last updated value and not "no data"
> bug 1545448 - Fixing bug around feed data last updated.

- lib/AboutPreferences.jsm
r?@rlr https://hg.mozilla.org/mozilla-central/rev/5320b47ea99b
> Port 1544887 - Fix some in-content page icon colors in dark mode. r=dao

- bin/render-activity-stream-html.js
- content-src/asrouter/asrouter-content.jsx
- content-src/asrouter/components/SnippetBase/SnippetBase.jsx
- content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
- content-src/components/Base/Base.jsx
- content-src/components/Search/_Search.scss
- content-src/styles/_activity-stream.scss
- test/unit/asrouter/asrouter-content.test.jsx
- test/unit/asrouter/constants.js
@k88hudson thoughts on the portal approach?
> Bug 1543686 - Add ability to place a snippet below the Activity Stream search box

- content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
- content-src/components/ASRouterAdmin/ASRouterAdmin.scss
r?@k88hudson or @rlr Not so yellow all the time 😉 There's a delay to avoid accidentally flashing yellow if the pointer runs over
> (nobug) - Make devtools button hidden but clickable

- content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
- content-src/components/Search/_Search.scss
After a live hacking session with Wolasi over slack, here is the final screenshot that he approved to :ship:
> Bug 1546768 - Design fixes for Special FXA snippet

- bin/render-activity-stream-html.js
r?@k88hudson or @rlr Looks happier
> (nobug) - Properly close snippets div tag

- content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- content-src/asrouter/templates/Trailhead/Trailhead.scss
- content-src/styles/_activity-stream.scss
Had to refactor a little bit to get it working without the bottom bar;
Also removed the card rendering.
cc @Mardak
> Bug 1547744 - Add modal overlay to trailhead

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- content-src/asrouter/templates/Trailhead/Trailhead.scss
- content-src/styles/_variables.scss
- data/trailhead.ftl
- lib/OnboardingMessageProvider.jsm
r?@rlr Lots of temporary stuff that I made up (colors, sizing, etc.) but basic layout is there. I also ended up copying over the strings from mozilla-central side and concatenating them together for now.
> (nobug) - Partial quick visual changes for trailhead first run

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- lib/ASRouter.jsm
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouter.test.js
> Bug 1547748 - add includeBundle stuff to trailhead

- content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
- content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
- content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- content-src/asrouter/templates/Trailhead/Trailhead.scss
Still needs work on responsive sizing, but here's a start
> (nobug) Trailhead basic card styles

- lib/ASRouter.jsm
- mochitest.sh
Just testing for now… https://github.com/mozilla/activity-stream/pull/4944/files#r280008798
> Followup Bug 1547748 - Run browser_newtab_userTypedValue.js and fix sendAsyncMessage exception

- lib/OnboardingMessageProvider.jsm
This is for us to land in nightly, we will follow-up with proper targeting when we are ready to uplift.
> (nobug) remove locale targeting for nightly testing

- lib/OnboardingMessageProvider.jsm
r?@k88hudson Just a first pass until actions get more finalized.
> Bug 1547065 - Add some finalized actions for trailhead cards

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- content-src/asrouter/templates/Trailhead/_Trailhead.scss
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouterTargeting.test.js
> Bug 1548065 - "Take Firefox with you" sync CTA first run variant

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/asrouter-content.test.jsx
- test/unit/asrouter/templates/Trailhead.test.jsx
> Bug 1548504 - Support localized "Sync" first run variant

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- content-src/asrouter/templates/Trailhead/_Trailhead.scss
- content-src/components/ASRouterAdmin/ASRouterAdmin.scss
- content-src/styles/_activity-stream.scss
- content-src/styles/_theme.scss
- content-src/styles/_variables.scss
* animation to reveal the cards after closing modal
* (subtle) animation to reveal modal content
* fix devtools toggle button position
* responsive tweaks to the modal content
* dismiss cards feature
> Bug 1548743 - Improve styling of trailhead flow (scrollable page, animations, dismiss)

- content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
- content-src/components/DiscoveryStreamComponents/DSImage/DSImage.scss
To test:
- Turn off internet connection
- Open FF
- See that missing images are grey boxes
(Note: This may take a few refreshes if there are cached images.)
> Bug 1547211 - Better fallback states for DS for offline mode

- content-src/asrouter/docs/targeting-attributes.md
- content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
- content-src/components/ASRouterAdmin/ASRouterAdmin.scss
- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/TargetingDocs.test.js
- test/unit/content-src/components/ASRouterAdmin.test.jsx
- test/unit/unit-entry.js
Still need to write some tests/comments for this, but this has most of what we need
> Bug 1547062 - Experiment branch generation for trailhead

- content-src/lib/selectLayoutRender.js
- lib/DiscoveryStreamFeed.jsm
STR https://bugzilla.mozilla.org/show_bug.cgi?id=1548929#c0
> Bug 1548929 - Fix broken state after spoc endpoint fetch failure

- lib/DiscoveryStreamFeed.jsm
To test, just reset the pref `browser.newtabpage.activity-stream.discoverystream.config` and ensure you see a layout with three stories in the first row, and a bunch of rows with 4 stories after it.
> Bug 1548915 - Change DS default layout

- content-src/styles/_theme.scss
> Bug 1549722 - The hover effect of the buttons from the first run card s is barely noticeable on Dark Theme

- content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- lib/OnboardingMessageProvider.jsm
- test/unit/asrouter/templates/Trailhead.test.jsx
OK, wasn't as simple as I first thought....
> Bug 1548503 - Update card button actions with finalized urls or actions

- content-src/asrouter/templates/Trailhead/_Trailhead.scss
I think it's a good sign that these are the kinds of bugs coming in 😃
> Bug 1549714 - The new onboarding modal is not scrollable if the browser window is horizontally resized to less than 25%

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- jar.mn
- lib/OnboardingMessageProvider.jsm
This can't land until mozilla-central gets the actual string changes.
> Bug 1547016 - Use regular packaged finalized onboarding strings

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
snuck in the `required="required"` fix
> Bug 1550062 - First run modal should open all links in a new tab.

- lib/OnboardingMessageProvider.jsm
odds on needing to file a "final final finalized urls" bug?
> Bug 1549802 - Update card button actions with final finalized urls or actions

- docs/v2-system-addon/remote_cfr.md
docs only change https://hg.mozilla.org/mozilla-central/rev/e677f0ef8e59
> Port 1547994 - Remove preference that can disable Remote Settings signature verification r=glasserc

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
- test/unit/asrouter/templates/Trailhead.test.jsx
r?@rlr Fixes both required and windows dialog focus bug. For the latter, I'm getting a windows try build for asa to test, so we shouldn't merge until we confirm it actually fixes the problem…
https://treeherder.mozilla.org/#/jobs?repo=try&revision=5533578d7712c703e3ff785526db6d577c37c91c
> Bug 1551677 - Improve accessibility of trailhead dialog

- content-src/asrouter/components/RichText/RichText.jsx
- content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
- content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
- content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
- content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
- content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
- package.json
- test/unit/content-src/components/ASRouterAdmin.test.jsx
- yamscripts.yml
Fixed accessibility linting errors for asrouter and ASRouterAdmin components.
> Bug 1551566 - Enable jsx-a11y eslint for ASRouterAdmin/asrouter directory and fix errors

- test/browser/browser.ini
- test/browser/browser_asrouter_snippets.js
Well, that looks pretty trivial once I figured out the proper way to send the snippet over to the page 😄
> Bug 1546429 - Add mochitest coverage of Special FXA (Below Search) Snippet

- content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
- content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
- content-src/styles/_mixins.scss
- content-src/styles/_variables.scss
QA:
- Set focus to a card
- Compare to [design spec](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A1)
> Bug 1548917 - [Accessibility] Focus state refinements

- lib/OnboardingMessageProvider.jsm
r?@rlr or @k88hudson I suppose I could have used asrouter targeting `localeLanguageCode` but wasn't sure about duplicating `id` or having a whole separate action and other interactions…
> Bug 1550858 - Update final final final final final actions or urls

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
r?@rlr or @k88hudson Hacky refactoring to fetch on both mount and update.
> Bug 1553205 - FxA metrics values sometimes don't get set

- content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Testing:
Compare `dev-test-all` between Nightly and this version to ensure layout hasn't regressed.
> Bug 1550160 - Clean up unused card CSS

- test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
r?@gvn Some reason this was needed for an unrelated change in a different PR but might as well land this on its own.
> (nobug) - Increase DSImage to 100% coverage

- docs/v2-system-addon/telemetry.md
@piatra Hope this could clarify the telemetry HOWTO for AS.
> chore(Doc) - Update the telemetry checklist

- AboutNewTabService.jsm
https://hg.mozilla.org/mozilla-central/rev/7f30c1db8835cf11237b51835ca26522f8d0c06d
> Port 1539595 - Rename Priveleged Content Process to PrivlegedAbout Content Process r=mconley,flod

- content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
- content-src/components/TopSites/_TopSites.scss
Testing: Compare build & changes requested to [spec](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A1)
> Bug 1552932 - [Top Sites] Focus and Hover UX updates

- .eslintrc.js
It didn't turn out to complicated. This PR is based on the work for bug 1553917. Waiting on that to land first before attempting this change.
> Bug 1553926 - Re-enable fetch-options eslint plugin

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
To test:
1. Fresh profile
2. Open about:config
3. search for impressionId
expected: You should only see "browser.newtabpage.activity-stream.impressionId"
actual: You may see "impressionId" too, which is broken.
> no bug - Fixing impression issue

- content-src/components/ContextMenu/ContextMenu.jsx
Added support for closing context menus with the escape key
>  Bug 1559380 - The ESC key should dismiss the context menu if accessed via keyboard navigation

- lib/PlacesFeed.jsm
- test/unit/lib/PlacesFeed.test.js
- test/unit/unit-entry.js
Waiting on https://bugzilla.mozilla.org/show_bug.cgi?id=1558917 to land in m-c
https://hg.mozilla.org/integration/autoland/rev/9dac8ade6630
> Port 1558917 - Referrer no longer sent for new tab links r=thecount

- content-src/asrouter/templates/Trailhead/Trailhead.jsx
(cherry picked from commit b572c6d72628a9815713a72c71d57e331ff51b31)
> Bug 1553205 - FxA metrics values sometimes don't get set (#5053)

- lib/OnboardingMessageProvider.jsm
(cherry picked from commit a63ed2b443679280cd8f9d0ef7a1126b59d13809)
> Bug 1550858 - Update final final final final final actions or urls (#5046)

- content-src/components/CollapsibleSection/CollapsibleSection.jsx
- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/FluentOrText/FluentOrText.jsx
- content-src/components/Sections/Sections.jsx
- lib/SectionsManager.jsm
- test/unit/content-src/components/FluentOrText.test.jsx
r?@JeaneC This is on top of #5125, so I'll rebase when that gets merged. So look at the last commit for the changes for the refactoring.
>  Bug 1561091 - Refactor getFormattedMessage to set fluent attributes or use plain text

- content-src/components/ContextMenu/ContextMenu.jsx
The second commit solves some test issues with a refactor, but maintains the same behavior.
> Bug 1559383 - The arrow keys do not go through the available context menu option unless you press TAB first

- mochitest.sh
Just testing against fluent branch as it should have a failure. But we can merge into master as we already have fluent files there.
> (nobug) - Run codespell lint for fluent files

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
Testing:
- Open FF and confirm that default layout matches [winning layout](https://www.figma.com/file/o1Ep3tU1pCsCgM0gWNe7Iu/2-Branch-Study-Firefox-v67)
> Bug 1561694 - Switching hardcoded layout to `3-col-7-row-octr`

- lib/ActivityStream.jsm
~ON HOLD: Pending final decision on regions.~
> Bug 1551273 - Turning on DS for non-nightly users

- lib/ASRouter.jsm
- lib/ToolbarPanelHub.jsm
- locales-src/asrouter.ftl
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/ASRouterFeed.test.js
- test/unit/lib/ToolbarPanelHub.test.js
This depends on https://phabricator.services.mozilla.com/D36548
> Bug 1563319 - Enable the What's New UI when pref is enabled

- content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
- lib/ASRouter.jsm
- lib/ASRouterTargeting.jsm
- lib/OnboardingMessageProvider.jsm
- lib/ToolbarPanelHub.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/templates/OnboardingMessage.test.jsx
- test/unit/lib/ToolbarPanelHub.test.js
This requires come changes to panelUI in m-c: https://phabricator.services.mozilla.com/D37320
The styling is bare bones, I'll be working with Aaron on styling tomorrow (Tuesday).
I think there is more that needs to be done to get messages with the right targeting, but thinking that should be a followup as this is getting big enough.
> Bug 1561349 - Implement message templates for What's New panel

- lib/ToolbarPanelHub.jsm
Oops. I keep forgetting to return the elements from the helpers.
> (nobug) Fix _createDateElement() helper

- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
> Bug 1562928 - Image source changes properly refresh card.

- content-src/components/ContextMenu/ContextMenuButton.jsx
> (nobug) - Add license header to ContextMenuButton.jsx

- content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx
Some steps to test in the bug, but also probably want to ensure images are still rendering at the correct sizes.
> Bug 1570192 - Potential perf fixes in DS image onSeen

- content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
- content-src/components/Base/_Base.scss
Later we should hide the snippets past the smallest width.
> Bug 1571441 - Fixed snippet width and block button position on smaller screens

- content-src/asrouter/templates/FirstRun/FirstRun.jsx
- test/unit/asrouter/templates/FirstRun.test.jsx
r?@k88hudson Looks like Triplets had it but not Interrupt !
> Bug 1572378 - Unable to install extension from RTAMO overlay

- content-src/asrouter/asrouter-content.jsx
- content-src/asrouter/templates/FirstRun/FirstRun.jsx
- lib/ASRouter.jsm
- test/unit/asrouter/ASRouter.test.js
- test/unit/asrouter/templates/FirstRun.test.jsx
I don't love this solution but I couldn't really think of anything else that works better at the moment. What do you think?
> Bug 1573209 - Installing addon from ReturntoAMO shouldnt hide triplets

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
Adding steps to test to bugzilla
> Bug 1572556 - Mitigation strategy for 69 DS and Adzerk

- content-src/asrouter/components/Button/_Button.scss
- content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
Let me know if a different highlight color would be better :)
> Bug 1571450 - Added a focus highlight to Snippet CTA and dismiss buttons

- content-src/asrouter/docs/user-actions.md
I added some documentation for all the button actions / user actions that are available.
> (nobug) Docs for Messaging System user actions

- content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
- content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
- content-src/components/DiscoveryStreamComponents/DSImage/_DSImage.scss
To test:
You should see roughly the same experience before and after the patch as these videos:
https://drive.google.com/file/d/1V8R167fe2grm3vIiYdERCqIEE8QtCdBo/view?usp=sharing
https://drive.google.com/file/d/1fw2kCaJUxrGyhZQZ8FH2cAuRb1qnOFVZ/view?usp=sharing
> Bug 1576223 - Testing a better image and card load

- lib/OnboardingMessageProvider.jsm
- lib/PanelTestProvider.jsm
- test/unit/asrouter/PanelTestProvider.test.js
- test/unit/lib/ToolbarBadgeHub.test.js
r?@k88hudson Relanding #5273 without the version checks
> Bug 1575888 - Enable the What's New toolbar badge (#5273)

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/DSDismiss/DSDismiss.jsx
- content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
To test:
2. Update `browser.newtabpage.activity-stream.discoverystream.config` with `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://5ad1b408-b40a-4a49-b6ec-27473d192df0.mock.pstmn.io/layout-1577654"} `
> Bug 1577654 - Design tweaks for TextPromo

- content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
To test:
1. Run `npm run tddmc`
2. Click debug on the resulting page.
3. Make a change to a file, like a comment or whitespace.
Expected: tests should pass.
Actual: some tests timeout.
> no bug - Fixing test timeout

- content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
- content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
- content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
- content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
- content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
- content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
- content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
- content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
- lib/SnippetsTestMessageProvider.jsm
- test/unit/asrouter/templates/FXASignupSnippet.test.jsx
- test/unit/asrouter/templates/NewsletterSnippet.test.jsx
- test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
- test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
Fixes mozmeao/snippets-service#862
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1510331
> [fix snippets-service #862] Add SubmitForm error button label.

- .taskcluster.yml
Preparation for move to the new community deployment -- see https://bugzilla.mozilla.org/show_bug.cgi?id=1574657
> Upgrade .taskcluster.yml to v1

- common/Reducers.jsm
- test/unit/common/Reducers.test.js
> Bug 1581570 - Spocs placement bug impacting non placements fixed

- common/Reducers.jsm
- test/unit/common/Reducers.test.js
* Bug 1581570 - Spocs placement bug impacting non placements fixed
> Bug 1581570 - Spocs placement bug impacting non placements fixed (#5310)

- content-src/asrouter/docs/debugging-docs.md
> (nobug) - Fixing a few items in telemetry debugging docs

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
- content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
- lib/ActivityStream.jsm
- test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx
> Bug 1584642 - Control engagement label visibility with a pref (#5331)

- test/browser/browser_onboarding_rtamo.js
Updated to detect OSX. And here is a try run:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=6143cc3837cde919722f6a8645440722ba122cd1
> Bug 1584625 - browser_aboutwelcome.js mochitest fails when run twice

- content-src/asrouter/docs/targeting-attributes.md
- lib/ASRouterTargeting.jsm
- test/browser/browser_asrouter_targeting.js
Fixes https://github.com/mozmeao/snippets-service/issues/996
> Bug 1376637 - Export platform name to targeting attributes

- content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
Testing: See https://bugzilla.mozilla.org/show_bug.cgi?id=1577655#c5
> Bug 1577655 - Removing unused margin override

- content-src/asrouter/components/FxASignupForm/FxASignupForm.jsx
- content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
- content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
- content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
Requires https://github.com/mozilla/fxa/pull/2534 in production
This is for 71 at some point
> Fix Bug 1582002 - make sync optional in the about:welcome signin flow

- lib/DiscoveryStreamFeed.jsm
To test:
1.    Ensure you can see sponsored content.
2.    Set browser.newtabpage.activity-stream.discoverystream.enabled to true.
3.    Set browser.newtabpage.activity-stream.discoverystream.spocs-endpoint to "https://getpocket.cdn.mozilla.net/v3/firefox/unique-spocs"
4.    Set browser.newtabpage.activity-stream.discoverystream.spocs-endpoint to "" or clear it.
5.    Go to "about:home#devtools-ds" and scroll down until you see "spocs_endpoint https://spocs.getpocket.com/spocs" and ensure you see sponsored content.
> Bug 1574549 - Small bug with pref change, not critical

- content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
Steps to test.
1. Just ensure you see spocs.
2. Open the context menu for a spoc, ensure the last menu item is the privacy item.
3. Open the context menu for a non spoc, ensure the last menu items is not th privacy item.
> Bug 1589117 - Privacy info link menu changes

- content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
Test steps: https://bugzilla.mozilla.org/show_bug.cgi?id=1583839#c0
> Bug 1583839 - Putting active state back on cards

- content-src/components/DiscoveryStreamComponents/DSPrivacyModal/DSPrivacyModal.jsx
- content-src/components/DiscoveryStreamComponents/DSPrivacyModal/_DSPrivacyModal.scss
Test steps: https://bugzilla.mozilla.org/show_bug.cgi?id=1589659#c0
> Bug 1589659 - Enabling hover state for privacy modal

- lib/DiscoveryStreamFeed.jsm
- test/unit/lib/DiscoveryStreamFeed.test.js
> Bug 1593018 - Placements bug after layout update

- lib/ActivityStream.jsm
To test, I think we can try using these steps again, should work: https://github.com/mozilla/activity-stream/pull/4864#issuecomment-479962039
And also, ensure basic spoc functionality works.
> Bug 1593290 - Personalization switch for Discovery Stream

- content-src/components/CollapsibleSection/_CollapsibleSection.scss
- lib/DiscoveryStreamFeed.jsm
- lib/SectionsManager.jsm
- locales-src/newtab.ftl
- locales-src/onboarding.ftl
- test/browser/browser_discovery_render.js
Test Steps:
- Open browser & look for "What's Pocket?" (See pic)
> Bug 1574297 - "How it works" -> "What's Pocket?"

- content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
- content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
- content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
- content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
- content-src/components/DiscoveryStreamComponents/DSTextPromo/DSTextPromo.jsx
- content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
- content-src/components/DiscoveryStreamComponents/List/List.jsx
- content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
- content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
- content-src/components/TopSites/TopSite.jsx
- content-src/lib/link-menu-options.js
- docs/v2-system-addon/data_dictionary.md
- docs/v2-system-addon/preferences.md
- lib/ActivityStream.jsm
- lib/DiscoveryStreamFeed.jsm
- test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
- test/unit/content-src/components/DiscoveryStreamComponents/TopSites.test.jsx
- test/unit/lib/DiscoveryStreamFeed.test.js
To test:
1. You need to enable DS and spocs.
2. Ensure you see spocs.
3. Ensure spocs frequency cap out.
4. Ensure spocs can be blocked.
5. Change `browser.newtabpage.activity-stream.discoverystream.spocs-endpoint` to `https://getpocket.cdn.mozilla.net/v3/firefox/unique-spocs`
6. Ensure steps 2-4 work still.
> Bug 1592724 - campaign to flight value change
