system-addon/lib/ActivityStream.jsm
system-addon/lib/TopStoriesFeed.jsm
system-addon/test/unit/lib/TopStoriesFeed.test.js

Introduces a new client-side rotation mechanism for personalization mode:
Similar to frequency capping, we record impressions in a pref. Main difference is that for recs (stories) we only record the first impression. After fetching and sorting stories we check that stories don't have an impression older than 90 mins (configurable server-side). If they do we'll sort them to the end. The impression tracking pref is cleaned up after every fetch to remove impressions for stories no longer in the feed.
Other minor fixes included here are:
- Adding a check so domain affinity calculation is never calculated more than twice a day in case of idle-daily firing too often. Really just a safe-guard to avoid unneeded computation in case of a problem.
- Changing the View More Topics link to not use the …

New client-side rotation for personalization mode, and minor fixes for Pocket

---

system-addon/lib/ActivityStreamPrefs.jsm
system-addon/test/unit/lib/ActivityStreamPrefs.test.js
system-addon/test/unit/unit-entry.js

Fix #3769. r?@k88hudson Also adds test that we don't use `value_local_dev` when not dev.

fix(prefs): Use MOZILLA_OFFICIAL instead of checking channel for dev-ness

---

system-addon/lib/ActivityStream.jsm

This is turning on personalization by default as requested for 59 and 58 (by Nate, Maria). 
I will double-check today and mark this as blocked in the meantime.

feat(topstories): Turn on personalized recommendations by default

---

system-addon/lib/FaviconFeed.jsm
system-addon/test/unit/lib/FaviconFeed.test.js

Fixes #3855 
@Mardak r?
Can set the pref to https://raw.githubusercontent.com/rlr/tippy-top-playground/master/data/tippy-top-domains.json for testing with airbnb.com and go.twitch.tv.

fix (faviconfeed): domains instead of url/urls in remote tippy top manifest

---

system-addon/ping-centre/PingCentre.jsm
system-addon/test/unit/ping-centre/PingCentre.test.js

This closes ping-centre [#117](https://github.com/mozilla/ping-centre/issues/117) and [#111](https://github.com/mozilla/ping-centre/issues/111)

Fix(pingcentre): Collect region and profile creation date

---

system-addon/content-src/components/Search/Search.jsx
system-addon/lib/ActivityStream.jsm
system-addon/lib/NewTabInit.jsm
system-addon/test/unit/lib/NewTabInit.test.js

Also fix Bug 1400585 - With activity-stream.aboutHome.autoFocus set, initil focus is in the address bar then moves to content search
Also fix Bug 1421417 - Focus moves to about:home search box when turning on the search preference
r?@sarracini Basically reverts #3452

fix(search): Close Bug 1417943 - in-page search box gets focus after entering input in location bar (only on initial tab at browser startup)

---

package-lock.json
package.json

Supersede #3870 by splitting each change into its own commit. r?@dmose 
As noted on IRC, these are `devDependency` changes that are passing `npm test` where the `buildmc` generated output shows no changes.

Fix Bug 1421823 - Green up our JS dependencies

---

system-addon/lib/TippyTopProvider.jsm
system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/lib/TippyTopProvider.test.js
system-addon/test/unit/lib/TopSitesFeed.test.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1421903 r?@rlr 
Before (2nd row), after (4th row):

Fix Bug 1421903 - Allow default packaged top site rich icons to be used for non-root pages

---

karma.mc.config.js

To test: 
* edit a test so that it will always fail
* npm run tddmc
* notice whether the error message contains the name of the test file where the error came from

Fix Bug 1422918 - make sourcemaps for unit tests work again

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/content-src/components/TopSites/TopSites.jsx
system-addon/content-src/components/TopSites/TopSitesEdit.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx

I separated this out from my drag and drop changes. I wasn't sure if this is a bug or a feature, but I think we need to "honor" holes for drag and drop to work properly (so the user can pin a site over any placeholder past their frecent+default top sites).
r? @Mardak

fix (topsites): dont collapse holes in Top Sites

---

system-addon/lib/ActivityStream.jsm

Basically, lots of German publishers don't use HTTPS. The current referrer isn't sent along for these publishers, so switching the referrer to plain HTTP. This will make sure it's sent for both HTTP and HTTPS stories.
Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1424292

Fix Bug 1424292 - Pocket referrer only sent when story has HTTPS URL

---

.eslintrc.js
package-lock.json
package.json
system-addon/common/PerfService.jsm

In [bug 1369722](https://bugzilla.mozilla.org/show_bug.cgi?id=1369722) I'm working on updating the environment for .jsm files so that it is more accurate (currently we assume 'browser' which is too much).
This patch adds a simple ignore for something that is already checked.
Whilst here, I'm also upgrading e-p-m to 0.4.10 and as it now specifies mozilla/use-services by default, removing that from the activity stream definition.

Prepare for Bug 1369722 - Use non-browser environment for jsms

---

system-addon/common/PrerenderData.jsm
system-addon/lib/ActivityStream.jsm

tiny r? @Mardak 
My only concern is the first run experience will now have a row of placeholders. Is that OK @aaronrbenson @bryanbell ? Or do we need to add 6 more default sites?

Fix Bug 1425489 - Default to two rows of Top Sites

---

system-addon/content-src/components/LinkMenu/LinkMenu.jsx
system-addon/test/unit/content-src/components/LinkMenu.test.jsx

Was bothering me that you could drag a default top site but then not edit it… Also that a placeholder had more edit-ability than a default site. But you could still do so via edit mode. r?@rlr

Fix Bug 1402864 - Default Top Sites do not have the "Edit" option

---

system-addon/lib/TelemetryFeed.jsm
system-addon/test/unit/lib/TelemetryFeed.test.js

Fixes #3916 
Backports changes from bug 1420285 found here: https://hg.mozilla.org/mozilla-central/rev/b30d693096e3 for TelemetryFeed.jsm
browser attribute name and possible values changed

chore(telemetry): Backport Bug 1420285 - Changes to TelemetryFeed for preloaded sessions

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx

With these changes, linux behavior seems to match os-x. The big difference is that I removed the handling for `dragleave`, which means the last preview sticks until a `drop`, `dragend` or new `dragenter` happens. On the plus side, this also solves some of the flickering that happened when dragging around over multiple sites. Thoughts @Mardak ?

Fix Bug 1427361 - linux drag and drop

---

karma.mc.config.js

You've seen it at the lightning talks, now in our repo!
This makes it so that `testmc:unit` runs in headless mode but `tddmc` still starts up regular firefox.
I like it because it doesn't steal the focus to start firefox, I don't know of any negative. 
Lmk if you think it's a good idea and I'll go ahead and make a bug for it too.

Use headless mode for unit tests

---

system-addon/lib/TopSitesFeed.jsm

Only add ```isDefault``` attribute to pinned sites that are not frecent, meaning we don't care if it is a default if it's a frecent. Prioritize frecent sites. This puts the 'remove from history' item back in the context menu of sites that are pinned + frecent + coincidentally also in the list of default sites

Fix Bug 1426787 - Top sites that match defaults lose 'Remove from History' option when they are pinned

---

bin/render-activity-stream-html.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1423256
This PR adds title and link elements back.
* This fixes cases like session restore where title is completely missing. Related to the icon it looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1422074 was not needed.
* Adding it back fixes the case for "Duplicate Tab" when the icon would not show up.
* It also fixes the case where navigating New Tab -> Website -> (Back Button) would display the favicon of `website`
There was also an event listener ([see PR](https://github.com/mozilla/activity-stream/commit/20b392dd7e35d2a369ced71971f7fdbde782a5ef#diff-92b55e4a266df72d234dd8551ab6ca10)) that was removed when the link element was removed. I did not add it back in this PR because I'm not sure of the use case it covered (I'm not seeing …

Fix Bug 1423256 - Add title and link elements back.

---

system-addon/lib/TopSitesFeed.jsm
system-addon/test/functional/mochitest/browser.ini
system-addon/test/functional/mochitest/browser_highlights_section.js
system-addon/test/functional/mochitest/browser_topsites_section.js
system-addon/test/functional/mochitest/head.js

I removed the failing assert and tests seem fine.
https://treeherder.mozilla.org/#/jobs?repo=try&revision=f56ac6ac3f2f94a7a75308f10fb1cd86df6d4b2e&selectedJob=143776229
I did a re-trigger on bc4 previously failing.
Test still checks for the correct number of highlights bookmarks.
Closes #3820

Fix Bug 1421844 - Add implementation to Activity Stream mochitests/head.js

---

bin/render-activity-stream-html.js
mozilla-central-patches/b1423703-applocale.diff
system-addon/lib/ActivityStream.jsm
system-addon/lib/TelemetryFeed.jsm
system-addon/test/unit/lib/ActivityStream.test.js
system-addon/test/unit/lib/TopStoriesFeed.test.js
system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
system-addon/test/unit/unit-entry.js

Switch from `getRequestedLocale` to `getAppLocaleAsLangTag` (and `getAppLocalesAsLangTags` for negotiate in aboutNewTabService). Skips the mochitest for now as per bug as fixing it would depend on some other changes for 60. r?@k88hudson

Fix Bug 1423703 - Use negotiated locales, rather than requested in Activity Stream

---

package-lock.json
package.json
webpack.system-addon.config.js
yamscripts.yml

This patch will result in some changes to the compiled JS since it allows for all our jsms imported via webpack to be ES modules rather than commonjs – I made this change after noticing in the `--display-optimization-bailout` was skipping those files.

Add --display-optimization-bailout, use jsm-to-esmodules 

---

docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md

Fix Bug 1421422 - Collect "region" and "profile_creation_date" for AS

---

package-lock.json
package.json
system-addon/test/unit/lib/PlacesFeed.test.js

I accidentally broke a bunch of tests in the patch that converted to using jsm-to-esmodules (since our injector requires common-js, not esmodules). There was also a small error that wasn't caught in https://github.com/mozilla/activity-stream/commit/e51ee0272e93f4821f76ddb05f7d77d661aebb66 because tests weren't running properly. 
This must not have been caught due to the jsm-to-commonjs package being in travis's cache

Fix (nobug): Add babel-plugin-jsm-to-commonjs back in, fix PlacesFeed test

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx

I had to move `activeTile` tracking from the `TopSite` up to the `TopSiteList`.
r? @Mardak

Fix Bug 1430132 - close context menu on drag start

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/content-src/components/TopSites.test.jsx
system-addon/test/unit/lib/TopSitesFeed.test.js

@Mardak this is what I was thinking. And no recursion! I haven't made the corresponding changes to the feed yet. Thoughts?
I'll show UX tomorrow. But I am pretty sure this is closer to what tiles was doing.
Before:
After:

Fix Bug 1428727 - better shifting of pinned sites during drag n drop

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx

r?@rlr When dumping out various mouse events and barely dragging a top site, sometimes I see:
```
mousedown
dragstart
dragenter
drop
dragend
mouseup
click
```
And other times I get:
```
mousedown
dragstart
dragenter
drop
dragend
```
So I just made it cancel any `click`s after a `dragstart`.

Bug 1429825 - Dragging and Dropping a Top Site in the same position with the trackpad wrongly opens the site

---

system-addon/content-src/components/TopSites/TopSite.jsx

I already had all this code here https://github.com/rlr/activity-streams/blob/47951e8dae81183d7e7e968844b616d69ef0e36e/system-addon/content-src/components/TopSites/TopSite.jsx#L272-L283 to handle this. But I didn't realize dragend was called when dropping. Is this too hacky? Any better ideas?
@Mardak @k88hudson r?

Fix Bug 1430130 - fix top site flickering on drop

---

system-addon/content-src/components/ConfirmDialog/_ConfirmDialog.scss

Verified with Aaron that this is the desirable look for long strings

Fix Bug 1430640 - Button labels are cut in 'Delete from history' dialog on localized build

---

system-addon/lib/LinksCache.jsm
system-addon/test/unit/lib/TopSitesFeed.test.js

https://bugzilla.mozilla.org/show_bug.cgi?id=1433227

Fix Bug 1433227 - Different sharedCache reference between migrated LinksCache objects

---

system-addon/lib/ActivityStream.jsm
system-addon/lib/PlacesFeed.jsm
system-addon/test/unit/lib/PlacesFeed.test.js
system-addon/test/unit/unit-entry.js

r?@csadilek Cleaned up `openNewWindow` to be `openLink` to avoid duplicate referrer processing.

Fix Bug 1433353 - Use referrerpolicy to send Pocket referrer when story has HTTP URL

---

system-addon/lib/Screenshots.jsm
system-addon/test/unit/lib/HighlightsFeed.test.js
system-addon/test/unit/lib/Screenshots.test.js
system-addon/test/unit/lib/TopSitesFeed.test.js

Bails out of getting a screenshot of highlights and top sites if the most recent window is a private window. I think doing it here rather than in ```BackgroundPageThumbs.jsm``` has 3 advantages that I can think of...
1. If there are other components of ffx that depend on BackgroundPageThumbs to get a screenshot (even in the future) and maybe don't  care about private browsing, we shouldn't change the implementation for them
2. If we do it earlier can avoid some unnecessary code execution by doing it as soon as we know we don't need to fetch them
3. We have finer control over when to get or not get screenshots
Disadvantages:
1. More code, in more places. We have to remember to explicitly tell any feeds that need a screenshot to check for private browsing in the future. 
So here's the …

Fix Bug 1428583 - Disable thumbnails if all open windows are in Private Browsing mode

---

system-addon/lib/ActivityStream.jsm

Refinement to #3943. Not urgent.

Removed '.php' extension from disclaimer_link

---

locales/en-US/strings.properties
system-addon/content-src/components/TopSites/TopSites.jsx

r?@rlr One more comment from https://github.com/mozilla/activity-stream-l10n/pull/10

chore(l10n): Switch string id from _label to _tooltip

---

system-addon/common/Actions.jsm
system-addon/content-src/components/Card/Card.jsx
system-addon/content-src/components/LinkMenu/LinkMenu.jsx
system-addon/content-src/components/Sections/Sections.jsx
system-addon/content-src/lib/link-menu-options.js
system-addon/lib/SectionsManager.jsm
system-addon/test/unit/common/Actions.test.js
system-addon/test/unit/content-src/components/Card.test.jsx
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/lib/SectionsManager.test.js

This adds some new `CLICK` and `DISMISS` actions for web extension sections and allows the `SectionManager` to notify those web extensions when they happen. This is so that web extension authors can choose to respond to clicks/dismisses as they see fit.

Bug 1431506 - Support AS actions for Web Extension click / dismiss

---

.sass-lint.yml

As discussed at the most recent retrospective.

fix(lint): disable forced CSS prop sorting; fixes bug 1434655

---

system-addon/bootstrap.js
system-addon/common/PrerenderData.jsm
system-addon/common/Reducers.jsm
system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx
system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/content-src/components/TopSites/TopSites.jsx
system-addon/lib/ActivityStream.jsm
system-addon/lib/HighlightsFeed.jsm
system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx
system-addon/test/unit/lib/TopSitesFeed.test.js

@Mardak, this was more tedious then I thought but it *should* help make it easier to implement the wider top sites with 8 across. And it's a better match to how we are allowing users to change # of rows. Thoughts? Did I do the migration right? r?

chore (prefs): migrate topSitesCount to topSitesRows

---

package-lock.json
package.json
system-addon/common/Reducers.jsm

Relevant commits are here:
https://github.com/k88hudson/babel-plugin-jsm-to-commonjs/commit/c4227a3fb7d75e71637abab6ff9635f08d54d75a
https://github.com/k88hudson/babel-plugin-jsm-to-esmodules/commit/24032c428074e8950e38bd3487aa6f5153af4b28
I converted one file (Actions.jsm) to ensure tests are passing.

Upgrade babel to support ChromeUtils (for Bug 1431533)

---

package-lock.json
package.json
system-addon/bootstrap.js
system-addon/common/PerfService.jsm
system-addon/lib/ActivityStream.jsm
system-addon/lib/ActivityStreamMessageChannel.jsm
system-addon/lib/ActivityStreamPrefs.jsm
system-addon/lib/FaviconFeed.jsm
system-addon/lib/FilterAdult.jsm
system-addon/lib/HighlightsFeed.jsm
system-addon/lib/ManualMigration.jsm
system-addon/lib/NewTabInit.jsm
system-addon/lib/PersistentCache.jsm
system-addon/lib/PlacesFeed.jsm
system-addon/lib/PrefsFeed.jsm
system-addon/lib/Screenshots.jsm
system-addon/lib/SectionsManager.jsm
system-addon/lib/ShortURL.jsm
system-addon/lib/SnippetsFeed.jsm
system-addon/lib/Store.jsm
system-addon/lib/SystemTickFeed.jsm
system-addon/lib/TelemetryFeed.jsm
system-addon/lib/TopSitesFeed.jsm
system-addon/lib/TopStoriesFeed.jsm
system-addon/lib/UserDomainAffinityProvider.jsm
system-addon/ping-centre/PingCentre.jsm
system-addon/test/functional/mochitest/browser_getScreenshots.js
system-addon/test/functional/mochitest/head.js
system-addon/test/unit/unit-entry.js

Checked out the last exported activity-stream revision and applied the mozilla-central changes from https://hg.mozilla.org/mozilla-central/rev/e6a7b5e11ba8 scoped to our browser directory. Amazingly it applied just fine.
```
$ git co 7b6573a1
activity-stream/system-addon$ git -C ../../mozilla-central sh 5e0d08c727b1 browser/extensions/activity-stream/ | patch -p4
```
It's failing a bunch of eslint, e.g.,
```
activity-stream/system-addon/lib/ActivityStream.jsm (6/0)
✖  271:7   'Services' is not defined  no-undef
```
And some stuff needs to be fixed more correctly, e.g., `PerfService.jsm` should check for `ChromeUtils` instead of `Components.utils`:
https://hg.mozilla.org/mozilla-central/diff/e6a7b5e11ba8/browser/extensions/activity-stream/common/PerfService.jsm

Port Bug 1431533 - Add ChromeUtils helpers for lazy module import

---

.gitignore
package.json
system-addon/jar.mn
webpack.system-addon.config.js
yamscripts.yml

I've added source maps such that they will be included in all builds for Firefox (they are external, so won't be loaded until devtools are opened, but they do add ~`360kb` of additional files to be downloaded). What do you think @sarracini @Mardak? Or should we perhaps only include them for non-release channels?

Fix Bug 1435863 - Add source map support for css, js in Activity Stream

---

system-addon/lib/SnippetsFeed.jsm
system-addon/test/unit/lib/SnippetsFeed.test.js

We are going to move `FxAccounts.promiseAccountsSignUpURI` to `FxAccounts.config.promiseSignUpURI` in [bug 1427674](https://bugzilla.mozilla.org/show_bug.cgi?id=1427674).
Please do not merge this PR until the upstream patch is merged.

fix(snippets): Use the correct FxAccounts#promiseSignUpURI method

---

system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss

Reported by Nate in Slack.
Before:
After:

fix (styles): fix pocket disclaimer text for wide layout

---

system-addon/lib/TopStoriesFeed.jsm
system-addon/test/unit/lib/TopStoriesFeed.test.js

This allows Pocket to specify the host name displayed on story cards. Until now we've used `shortURL` to generate it, which works fine, but there are cases where we need to specify a different domain than in the story URL (e.g for spocs).

Bug 1438200 - Use domain name as provided in Pocket feed response

---

system-addon/vendor/react-dev.js

This landed as part of the export to avoid devtools conflict.

chore(mc): Port Bug 1426705 - Add responsive layout, React 16 and bug fixes to Activity Stream. r=ursula

---

system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
system-addon/content-src/lib/link-menu-options.js
system-addon/test/schemas/pings.js
system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
system-addon/test/unit/content-src/components/LinkMenu.test.jsx

I initially thought this was a lot worse but it looks like we "didn't lose" all the clicks.
`DeleteUrl` has a userEvent of [`DIALOG_OPEN`](https://github.com/mozilla/activity-stream/blob/a050adee0eebcc47c310ed9d9fb9973f1a07e1bd/system-addon/content-src/lib/link-menu-options.js#L89) defined which is [handled by the `LinkMenu`](https://github.com/mozilla/activity-stream/blob/a050adee0eebcc47c310ed9d9fb9973f1a07e1bd/system-addon/content-src/components/LinkMenu/LinkMenu.jsx#L23-L28).
If you sum up the DIALOG_OPEN events from Highlights and from Topsites they roughly add up to the DELETE count with n/a source (+/- some CANCEL events I suppose).
update: The bug mentioned the DELETE event but looks like DIALOG_CANCEL also has no source

Fix Bug 1438565 - Send source and action_position with DELETE ping

---

locales/en-US/strings.properties
system-addon/common/Actions.jsm
system-addon/common/Reducers.jsm
system-addon/content-src/components/Card/types.js
system-addon/content-src/components/ContextMenu/ContextMenu.jsx
system-addon/content-src/lib/link-menu-options.js
system-addon/content-src/styles/_icons.scss
system-addon/lib/ActivityStream.jsm
system-addon/lib/HighlightsFeed.jsm
system-addon/lib/PlacesFeed.jsm
system-addon/lib/SectionsManager.jsm
system-addon/test/schemas/pings.js
system-addon/test/unit/common/Reducers.test.js
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/lib/HighlightsFeed.test.js
system-addon/test/unit/lib/PlacesFeed.test.js

1. Allows Pocket items to be shown in highlights
2. Adds a "remove from pocket list" option in context menu (includes string + icon)
3. Adds functionality to actually remove the item from the pocket list via context menu
4. Adds a "saved to pocket" highlight  context  type (includes string + small version of regular pocket icon)
5. Preemptively updates UI when removing a pocket item via the reducer 
Has the same behaviour as when you bookmark a trending story - update the card itself then next time you refresh it shows it in the highlights section

Fix Bug 1432657 - Add pocket card type to highlight types

---

system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss

Followup fix for e939451 that caused link menus to always open to the left.

Fix Bug 1440970 - Fix top sites context menu position

---

system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
system-addon/content-src/styles/_variables.scss

I asked @aaronrbenson to look over the colors that we landed on nightly since they looked lighter than the mockups. He requested these changes.
Don't need to track this in bugzilla do I? 😉

Fix Bug 1441301 - Adjust section context menu related styling

---

system-addon/common/Reducers.jsm
system-addon/lib/TopStoriesFeed.jsm
system-addon/test/unit/common/Reducers.test.js
system-addon/test/unit/lib/TopStoriesFeed.test.js

Fixes a regression, introduced in 59, but plan is to fix for 60 only.
This PR introduces a way to mark cards as pinned, so they don't get refreshed as part of a SECTION_UPDATEs.
This is useful to avoid losing spoc cards when preloaded tabs refresh based on the latest feed data. A preloaded tab with a spoc will still refresh and all its cards will update except the spoc (pinned card) which will remain in place. This is to make sure we keep the spoc frequency as configured in the feed.

 Fix Bug 1440781 - Refreshing preloaded tabs interferes with spoc placement

---

docs/v2-system-addon/snippets.md
system-addon/lib/SnippetsFeed.jsm
system-addon/test/unit/lib/SnippetsFeed.test.js
system-addon/test/unit/unit-entry.js

This adds a property to snippets data indicating whether or not devtools have been used.
To test this, add the following to your console on a page in which snippets are turned enabled:
```js
gSnippetsMap.get("appData.isDevtoolsUser")
```
It should be `true` (since you have used devtools)
cc @glogiotatidis

fix Bug 1431464 - Expose devtools usage to snippets

---

docs/v2-system-addon/snippets.md
system-addon/lib/SnippetsFeed.jsm
system-addon/test/unit/lib/SnippetsFeed.test.js
system-addon/test/unit/unit-entry.js

To test this, add the following to your console on a page in which snippets are enabled:
```js
gSnippetsMap.get("appData.addonInfo")
```

fix Bug 1431525 - Add addonInfo to snippets data

---

system-addon/common/Reducers.jsm
system-addon/test/unit/common/Reducers.test.js

This refines the earlier fix to *not* retain pinned cards when the section is disabled and enabled again i.e. by an .options change or when the user toggles the checkbox in the pref pane.
I think in these cases we do want the cards to update. Disabling the section causes a SECTION_UPDATE event with an empty rows array.

fix(topstories): Pinned cards should be cleared when section is re-initialized

---

system-addon/content-src/components/LinkMenu/LinkMenu.jsx
system-addon/content-src/lib/link-menu-options.js
system-addon/lib/PrefsFeed.jsm
system-addon/test/unit/content-src/components/Card.test.jsx
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/lib/PrefsFeed.test.js

This should fix the issue of only showing OpenInPrivateBrowsing when private browsing is enabled, I decided to add the value into `Prefs` since `SnippetsFeed` could be turned off. Alternatively, I could add it to a completely new file/reducer, but i don't think overhead is worth it
cc @Mardak 
@rlr what do you think about connecting the `LinkComponent` again? I had to refactor tests to get it work

Bug 1441984 - Only show OpenInPrivateBrowsing option if private browsing enabled

---

system-addon/lib/PlacesFeed.jsm

Adds a ```skipTags: true``` property to the observer so it knows that it should not notify observers when adding/removing tags during a sync.
Also removes unused code for ```onItemChanged()```
This doesn't actually work yet with ```onItemChanged```.... posted my findings on https://bugzilla.mozilla.org/show_bug.cgi?id=1440276
_Update: Since this bug now involves some changes in ```nsNavBookmarks.cpp```, I'm going to make the changes to ```PlacesFeed.jsm``` also in m-c and this will become a backport PR of those changes_

chore(mc): Backport of Bug 1440276 - Activity Stream spikes after Bookmark activity, triggering lots of main thread work

---

system-addon/lib/FaviconFeed.jsm
system-addon/test/unit/lib/FaviconFeed.test.js
system-addon/test/unit/unit-entry.js

r?@k88hudson https://hg.mozilla.org/mozilla-central/rev/d39e5d03e446
So many nested objects for unit-entry ;)
I needed to do sinon.match to ignore the `mutate` method.

chore(mc): Port Bug 1433958 - Change code that sets nsIURI.ref to use nsIURIMutator r=mayhemer

---

system-addon/lib/SectionsManager.jsm

Relevant context https://bugzilla.mozilla.org/show_bug.cgi?id=1442992#c10

Fix Bug 1442992 - Remove second argument from Cu.reportError call

---

package.json

WFM now
>  @webpack:///system-addon/test/unit/content-src/components/PreferencesPane.test.jsx:101:4 <- system-addon/test/unit/unit-entry.js:89146:5

Fix Bug 1441278 - Missing line numbers in failing unit tests

---

system-addon/content-src/components/Sections/Sections.jsx
system-addon/test/unit/content-src/components/Sections.test.jsx

Fixed this by removing the visibility change listener when the section is removed. A new one will be attached anyway when a section is (re-)created. The listener was firing for sections that no longer exist.

 Fix Bug 1443243 - Preloaded tab is sending impression ping after section was disabled

---

system-addon/content-src/components/TopSites/_TopSites.scss

r? @piatra 
Note that it now stays at the "standard width" even on the wider layout. This change was nodded by @aaronrbenson on slack.

Fix Bug 1443908 - position: fixed; for Add Top Site modal

---

system-addon/lib/HighlightsFeed.jsm
system-addon/lib/PlacesFeed.jsm
system-addon/test/unit/lib/HighlightsFeed.test.js
system-addon/test/unit/lib/PlacesFeed.test.js

This patch does 2 things as per the conversation in [bug 1442383](https://bugzilla.mozilla.org/show_bug.cgi?id=1442383):
1. it ignores all bookmark added/removed notifications that came from sync by checking `SOURCES.SYNC`
2. when sync is finished and we receive the notification `weave:engine:sync:applied`, it refreshes highlights to check if there were some important bookmarks either added or removed that should show up in activity stream
In addition, there were some tests for `onItemChanged` that were being skipped that are now removed as per [this comment from bug 1440276](https://github.com/mozilla/activity-stream/pull/4005#pullrequestreview-100580633)

Fix Bug 1442383 - Activity stream spends a lot time fetching highlights after bookmark sync

---

system-addon/content-src/components/Card/types.js
system-addon/content-src/styles/_icons.scss

fix(nobug): Use regular size pocket icon

---

system-addon/lib/AboutPreferences.jsm
system-addon/lib/ActivityStream.jsm
system-addon/lib/SectionsManager.jsm
system-addon/test/unit/lib/AboutPreferences.test.js
system-addon/test/unit/lib/ActivityStream.test.js
system-addon/test/unit/unit-entry.js

r?@k88hudson Added a new feed (only so it can access `Sections` state -- originally I had it as part of `PrefsFeed`, but turns out `Preferences` https://searchfox.org/mozilla-central/source/toolkit/content/preferencesBindings.js manages all the updating just fine.)
There is an unused string ` +prefs_restore_defaults_button=Restore Defaults ` which would be needed for bug 1434751. Pretty sure there aren't others to add to activity stream, although there are others that would be needed as part of mozilla-central: https://docs.google.com/document/d/1uI7xtTuI9pw9rbOzN7q1kjUeIOEH3wfJtFr-4-degzQ
Design: https://mozilla.invisionapp.com/share/EGFI16P8Y36#/screens
Screenshot (with testing a locked search pref):
There are no tests for the new jsm right now, but I'll try adding some to at least make …

Fix Bug 1404890 - Move new tab settings for sections to about:preferences

---

system-addon/lib/AboutPreferences.jsm
system-addon/test/unit/lib/AboutPreferences.test.js

r? @sarracini. Followup to #4015 for various failures everywhere. Basically inlines `appendItem` from https://searchfox.org/mozilla-central/rev/8976abf9cab8eb4661665cc86bd355cd08238011/toolkit/content/widgets/menulist.xml#322-341
TEST-UNEXPECTED-FAIL | browser/extensions/formautofill/test/browser/browser_privacyPreferences.js | A promise chain failed to handle a rejection: menulist.appendItem is not a function - stack: renderPreferences/<@resource://activity-stream/lib/AboutPreferences.jsm:206:13

fix(preferences): Use plain DOM instead of XBL appendItem

---

system-addon/content-src/lib/link-menu-options.js
system-addon/lib/SectionsManager.jsm
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/lib/SectionsManager.test.js

Instead of assigning context menus to each card for an entire section type, this allows you to specify context menu options for each card type *only* for highlights.

Fix Bug 1446395 - Assign context menus in Highlights on a per card type basis

---

system-addon/lib/ActivityStreamMessageChannel.jsm
system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js

This is still WIP, because I'd like to know if:
1. This is the right place to handle this action, and
2. Whether or not there's a way I can only do this for preloaded tabs
@sarracini, if you have a second, can you help me with those questions?

Fix Bug 1408026 - Render layers for the preloaded newtab after hydration

---

system-addon/test/functional/mochitest/browser_as_load_location.js
system-addon/test/functional/mochitest/head.js

r?@sarracini 
https://hg.mozilla.org/mozilla-central/rev/ba58e9052ab9

Port Bug 1442465 - Part 4.2: Stop unnecessarily awaiting on BrowserTestUtils.removeTab (simple part). r=dao

---

system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx
system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
system-addon/content-src/components/Sections/Sections.jsx
system-addon/content-src/components/TopSites/TopSites.jsx
system-addon/content-src/styles/_variables.scss

Fix Bug 1444616 - fix context menu button alignment

---

system-addon/lib/SnippetsFeed.jsm
system-addon/test/unit/lib/ActivityStreamStorage.test.js
system-addon/test/unit/lib/SnippetsFeed.test.js

I was wondering if we really need to pass the current session start? Snippets could just use Date.now() and that should be good enough?
r? @k88hudson 
cc: @piatra

Fix Bug 1431469 - expose previous session end (UNINIT) to snippets

---

system-addon/lib/Screenshots.jsm

r? @sarracini try looks better
before https://treeherder.mozilla.org/#/jobs?repo=try&revision=bb65bbbae92907a67a5210562142f8e15cd67e1f
after https://treeherder.mozilla.org/#/jobs?repo=try&revision=0f2f3337a6a431153107f65d24195c11c17a4889

fix(screenshots): Ignore failures when trying to write empty file

---

system-addon/content-src/components/Base/_Base.scss
system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
system-addon/content-src/styles/_variables.scss

I guess it was still off by half a pixel. r? @piatra 
Before:
After:

Fix Bug 1444616 - push section menu button half a pixel up

---

system-addon/content-src/components/Card/_Card.scss

r? @piatra 
I added some extra breathing room. It looks like this was only broken on wide layouts with the bigger font size that comes with that.
Before:
After:

Fix Bug 1448394 - fix cut off g in Trending

---

system-addon/test/unit/lib/PlacesFeed.test.js
system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
system-addon/test/unit/unit-entry.js
system-addon/test/unit/utils.js

r? @rlr Followup for #4064. Make unit-entry have a TEST_GLOBAL for the various Cc and alias PlacesUtils to get those Cc. Also fixes PlacesFeed test to not change global directly, which wasn't getting restored.
Basically adding dummy methods/properties on unit-entry to later sandbox.stub/spy.

chore(tests): Clean up unnecessary injector and wrong global setting

---

system-addon/content-src/components/Base/Base.jsx
system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.jsx
system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.scss
system-addon/content-src/lib/snippets.js
system-addon/content-src/message-center/components/Button.jsx
system-addon/content-src/message-center/components/SnippetBase.jsx
system-addon/content-src/message-center/message-center-content.jsx
system-addon/content-src/message-center/templates/SimpleSnippet.jsx
system-addon/content-src/styles/_activity-stream.scss
system-addon/content-src/styles/_variables.scss
system-addon/lib/ActivityStream.jsm
system-addon/lib/MessageCenterFeed.jsm
system-addon/lib/MessageCenterRouter.jsm
system-addon/test/unit/content-src/lib/snippets.test.js
system-addon/test/unit/lib/ActivityStream.test.js
system-addon/test/unit/message-center/MessageCenterRouter.test.js
system-addon/test/unit/message-center/constants.js
system-addon/test/unit/unit-entry.js

This patch creates an experiment that demonstrates:
- React/JS based templates
- A template router in the main process
- An admin panel to block/unblock/view messages
You can test it by setting the `messageCenterExperimentEnabled` pref to true. When you do that, you should see:
- a snippet pop up at the bottom of every new tab page
- an admin panel when you visit `about:newtab#message-center-admin`

Bug 1432675 - Add Message Center experiment

---

locales/en-US/strings.properties
system-addon/lib/AboutPreferences.jsm
system-addon/lib/ActivityStream.jsm
system-addon/lib/SectionsManager.jsm
system-addon/test/unit/lib/AboutPreferences.test.js

r?@sarracini Moved the link to always be shown for stories instead of conditionally for sponsored. The old string can be replaced/removed because it wasn't actually used in 60. Also removed the option fallback stuff as it was confusingly out of sync for the disclaimer link href and the other options weren't being set (originally fixing #3796 in #3797)
Before sponsored off:
Before sponsored on:
After sponsored off:
After sponsored on:

Fix Bug 1446195 - Update story preferences description and link

---

system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/lib/TopSitesFeed.test.js

This scenario didn't really show up in development because it required some amount of history.
You can have frecent topsites which are low quality (have a screenshot not a hi-res icon). If you were to set a screenshot for these, we would not do a lookup in the frecent cache to clear the old screenshot and because of 
https://github.com/mozilla/activity-stream/blob/e8ef6e23b38c4eed36c6d0bf3f04516290b86ad9/system-addon/lib/TopSitesFeed.jsm#L203-L205
We would not fetch the new screenshot.

Fix Bug 1449292 - TopSites don't update their custom screenshot

---

system-addon/content-src/components/Search/_Search.scss

Fix #1447752 - set search input background to $white

---

system-addon/content-src/components/Card/_Card.scss
system-addon/content-src/styles/_theme.scss

Fix Bug 1451001 - add black fill and hairline for cards in dark theme

---

system-addon/content-src/components/TopSites/_TopSites.scss

I am confirming with Amy that this should also apply to the default theme.
Before:
After:

Fix Bug 1451419 - set background of Top Site icons to $white

---

system-addon/lib/HighlightsFeed.jsm
system-addon/test/unit/lib/HighlightsFeed.test.js

Takes all highlights, splits them into things that should be chronologically sorted, and things to be just appended at the end, then sorts them and returns them.
Via: https://mozilla.invisionapp.com/share/C4GL6VF2KRY#/screens 
Blocks: #4076

Fix Bug 1451091 - Chronologically order highlights

---

system-addon/content-src/components/Base/Base.jsx
system-addon/content-src/components/Base/_Base.scss
system-addon/content-src/styles/_activity-stream.scss
system-addon/content-src/styles/_theme.scss
system-addon/test/unit/content-src/components/Base.test.jsx

The theme variables need to be promoted up higher in the DOM tree so they can be used for onboarding and snippets.
This would also fix https://bugzilla.mozilla.org/show_bug.cgi?id=1451778
What do you think about this approach? @Mardak @k88hudson f?

Fix #1451778 - Set <body/> bg color. Move --theme-vars up to body. 

---

system-addon/bootstrap.js
system-addon/common/PrerenderData.jsm
system-addon/content-src/components/Sections/Sections.jsx
system-addon/content-src/components/TopSites/TopSites.jsx
system-addon/lib/AboutPreferences.jsm
system-addon/lib/ActivityStream.jsm
system-addon/lib/HighlightsFeed.jsm
system-addon/lib/SectionsManager.jsm
system-addon/lib/TelemetryFeed.jsm
system-addon/lib/TopSitesFeed.jsm
system-addon/test/functional/mochitest/browser_as_render.js
system-addon/test/unit/content-src/components/Sections.test.jsx
system-addon/test/unit/lib/HighlightsFeed.test.js
system-addon/test/unit/lib/SectionsManager.test.js

Only two small issues found when migrating the pref because our code never expected Topsites to be "really turned off".
* `HighlightsFeed.fetchHighlights` waiting on topsites to be initialised
* The `TopSitesFeed` not having `DEFAULT_SITES` if you open the browser and the section was previously disabled

Fix Bug 1445769 - Top Sites runs `refresh` at startup even when disabled

---

system-addon/content-src/styles/_theme.scss

What do we think about using `moz-osx-font-smoothing: grayscale` when the dark theme is enabled? it makes some of the type look a lot sharper, especially with the reversed text. Is there any reason we might not want to do this?

Use moz-osx-font-smoothing: grayscale for dark theme

---

system-addon/content-src/styles/_theme.scss

Followup to https://github.com/mozilla/activity-stream/pull/4087#discussion_r181510445
r?@rlr It works with no .css differences when exported. The .map files change though.

chore(styles): Refactor textbox shadow from color rule

---

system-addon/content-src/styles/_theme.scss
system-addon/content-src/styles/activity-stream-mac.scss

Followup to #4089 to avoid test failures:
TEST-UNEXPECTED-FAIL | browser/base/content/test/static/browser_parsable_css.js | Got error message for resource://activity-stream/css/activity-stream.css: Unknown property ‘-moz-osx-font-smoothing’. Declaration dropped. -
r? @rlr or @k88hudson ?

fix(styles): Only use osx property for mac css

---

system-addon/content-src/components/Search/_Search.scss
system-addon/content-src/styles/_theme.scss
system-addon/content-src/styles/_variables.scss

r? @Mardak 
Before:
(hovering the change search settings button)
(hovering ebay search engine)
After:
(hovering the change search settings button)
(hovering ebay search engine)

Fix Bug 1454263 - fix search drop down dividers and hover colors

---

system-addon/content-src/components/Card/_Card.scss
system-addon/content-src/styles/_theme.scss

* also add a tertiary text color (only currently used for card context text)
* secondary and tertiary text color are the same in default theme for now
Before:
After:

Fix Bug 1454423 - update secondary text color to pass contrast test

---

system-addon/lib/ActivityStream.jsm

Diff of originally provided pref change:
```diff
{
"api_key_pref": "extensions.pocket.oAuthConsumerKey",
"hidden": false,
"provider_icon": "pocket",
"provider_name": "Pocket",
"read_more_endpoint": "https://getpocket.com/explore/trending?src=fx_new_tab",
-  "stories_endpoint": "https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=3&consumer_key=$apiKey&locale_lang=en-US",
+  "stories_endpoint": "https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=3&consumer_key=$apiKey&locale_lang=en-US&feed_variant=default",
"stories_referrer": "https://getpocket.com/recommendations",
"topics_endpoint": "https://getpocket.cdn.mozilla.net/v3/firefox/trending-topics?version=2&consumer_key=$apiKey&locale_lang=en-US",
-  "show_spocs": false,
+  "show_spocs": true,
"personalized": …
```

feat(stories): Turn on sponsored content with new feed variant

---

system-addon/lib/HighlightsFeed.jsm
system-addon/test/unit/lib/HighlightsFeed.test.js

It looks like the `SectionsManager` does not initialise/add the sections until `PREFS_INITIAL_VALUES` because prefs are required for sections. `PREFS_INITIAL_VALUES` is triggered after `INIT`, but `INIT` also triggers Topsites to update and afterwards the HighlightsFeed. If the SectionsManager hasn't finished before the `HighlightsFeed.fetchHighlights` call, then we run into this issue. 
I wasn't able to reproduce, what I did was add an `await` call for a promise resolved in a `setTimeout` in `addBuiltInSection`.
I propose that we just return early if we don't have the sections available yet because when they finally become available [the feed will trigger the postInit fetch](https://github.com/mozilla/activity-stream/blob/7c6b298462b4d4a7aa685901adce3a0ba59d779a/system-addon/lib/Highlight …

Fix Bug 1450875 - Wait for Sections to be added before broadcasting content

---

system-addon/content-src/components/TopSites/_TopSites.scss
system-addon/content-src/styles/_theme.scss

This is a followup to 1d07b6188509323a80b500e2ee1f370fb1219723
r? @piatra 
Before:
After:

Fix Bug 1454730 - change Top Site icon background to grey-70 on dark theme

---

system-addon/content-src/components/Search/_Search.scss

And... this is LTR friendly now 😄 
Before:
After:

Fix Bug 1454985 - use ::after for search provider dividers

---

system-addon/content-src/styles/_theme.scss

Only variable value tweaking now. I see the light at the end of the tunnel 😅 
Before:
After:

Fix Bug 1455081 - update icon and text tertiary colors in dark theme

---

system-addon/content-src/components/Search/_Search.scss

This updates the CSS to handle the change in https://reviewboard.mozilla.org/r/237204/diff/#index_header

Fix Bug 1449338 - Show currently selected engine in newtabs search input

---

system-addon/content-src/components/Search/_Search.scss

Followup as suggested in https://github.com/mozilla/activity-stream/pull/4107#issuecomment-383393619
r? @rlr Turns out the icons weren't actually centered with `::after` but now they're exactly 32px from the line on each side!
before:
after:
(Open up both images in tabs and switch between the two tabs to check! ;))

fix(styles): Switch to border-image instead of ::after for search engine separator

---

system-addon/content-src/components/MessageCenterAdmin/MessageCenterAdmin.scss
system-addon/content-src/message-center/components/Button.jsx
system-addon/content-src/message-center/components/SnippetBase.jsx

These are some style changes so that the AS router templates respect dark theme. Mostly I'm looking for feedback on whether I used the right variables and if everything looks ok in dark/light themes
**To Test**:
- set `browser.newtabpage.activity-stream.messageCenterExperimentEnabled` pref to `true` in `about:config`
- check the bottom bar snippet looks right in both dark / light themes

AS router Snippet template should respect theme variables

---

system-addon/content-src/styles/_icons.scss

Fix modal icon width

---

system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
system-addon/lib/ASRouter.jsm
system-addon/lib/ASRouterFeed.jsm
system-addon/test/unit/asrouter/ASRouter.test.js

This uses the same object storage as snippets since both block based on string ids. Modified the Message Center blocklist to be an array.

Fix Bug 1433215 - Add blockList persistance to Message Center

---

system-addon/content-src/components/TopSites/TopSite.jsx
system-addon/content-src/lib/link-menu-options.js
system-addon/lib/PlacesFeed.jsm
system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx
system-addon/test/unit/lib/PlacesFeed.test.js
system-addon/test/unit/lib/TopSitesFeed.test.js
system-addon/test/unit/unit-entry.js

r?@piatra Handles regular clicks, modified clicks, and actions from the context menu.
Initially I only modified `TopSite.onLinkClick` to set a typed flag, but that wasn't enough for the context menu stuff, so I ended up setting the flag in the feed.
Oh, and this doesn't fix the OS-level context menu…

Fix Bug 1447891 - Top Sites keep changing dramatically

---

system-addon/test/unit/content-src/components/Card.test.jsx
system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
system-addon/test/unit/content-src/components/LinkMenu.test.jsx
system-addon/test/unit/content-src/components/SectionMenu.test.jsx
system-addon/test/unit/content-src/components/TopSites.test.jsx

When writing tests recently I noticed a few that are written to never fail. The `wrapper`, even when empty has a truthy value and will pass an `assert.ok`, this is also the case for `wrapper.find('foo')`.
In `test/unit/content-src/components/Card.test.jsx`, line 67, this was passing because of the `wrapper` having a value, when in fact the link menu has never existed. This is directly contradicted by line 71, which ensures it does not exist. This is why I removed it.
`test/unit/content-src/components/ConfirmDialog.test.jsx` line 26, it fails to find ConfirmDialog, but will succeed in finding '.confirmation-dialog` - I'm assuming those are intended as the same thing.

Fix tests that would never fail

---

system-addon/lib/TopSitesFeed.jsm
system-addon/test/unit/lib/TopSitesFeed.test.js

10x try run seems ok https://treeherder.mozilla.org/#/jobs?repo=try&revision=2f365be13e9300da2d1323e3f024b040639c8b8a&selectedJob=175553460
While previously (without the patch) it failed on the second attempt.

Fix Bug 1455931 - TopSites refresh should wait for tippytop provider to initialize

---

system-addon/lib/ActivityStreamStorage.jsm
system-addon/test/unit/lib/ActivityStreamStorage.test.js

Telemetry is no longer required and updated unit test that checks for that.

Fix Bug 1456082 - Storage should not have telemetry be a required argument

---

system-addon/lib/DownloadsManager.jsm
system-addon/test/unit/lib/HighlightsFeed.test.js

I accidentally removed the `date_added` field in DownloadsManager.jsm when this patch landed, which is what highlights looks to sort on. This fixes the issues, I tested it with the same case as Bug 1457927

Bug 1457927 - The most recent download is wrongly displayed in the last position

---

bin/render-activity-stream-html.js

r?@k88hudson Just short circuit the rest of the top level script

fix(prerender): Check top before loading more scripts

---

bin/render-activity-stream-html.js

r?@k88hudson We could try to be smarter in detecting and reusing, but this might just be a temporarily collision where they happen to match up:
```
0:07.81 ERROR: The following duplicated files are not allowed:
0:07.81 Nightly.app/Contents/Resources/browser/features/activity-stream@mozilla.org/chrome/content/prerendered/en-CA/activity-stream-strings.js
0:07.81 Nightly.app/Contents/Resources/browser/features/activity-stream@mozilla.org/chrome/content/prerendered/en-GB/activity-stream-strings.js
```

fix(prerender): Make localized files different to avoid duplicate checks

---

package-lock.json
package.json

r?@k88hudson Most upgrades are dev dependencies except prop-types, which didn't actually change any code as it was fixing up its license header for some files. I kept the changes to the single package.json with a final package-lock update if someone wants to bisect later.
These are not updated:
```
react                         16.2.0  →  16.3.2 
react-dom                     16.2.0  →  16.3.2 
react-redux                    5.0.6  →   5.0.7 
redux                          3.6.0  →   4.0.0 
istanbul-instrumenter-loader   0.2.0  →   3.0.1 
karma-sinon                    1.0.5  →   1.8.0 
loader-utils                  0.2.16  →   1.1.0 
node-sass                      4.7.2  →   4.9.0 
sinon                          4.5.0  →   5.0.3 
webpack                       3.10.0  →   4.6.0 
``` …

Fix Bug 1436228 - Green up our JS dependencies for Firefox 61

---

system-addon/content-src/asrouter/asrouter-content.jsx
system-addon/content-src/asrouter/components/ImpressionsWrapper/ImpressionsWrapper.jsx
system-addon/content-src/asrouter/components/SnippetBase/SnippetBase.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
system-addon/lib/ASRouter.jsm
system-addon/test/unit/asrouter/asrouter-content.test.jsx

This patch includes work done by Andrei in https://github.com/mozilla/activity-stream/pull/4127, as well as some additional follow-up work, in order to fix up a few things.
It adds a new impression ping to all messages. To test this, make sure you have the `asrouterExperiment` pref on and open your browser console to see if the correct ping is being logged. Please try opening about: newtab#asrouter and switching the message to ensure the right pings are correctly logged

AS Router Impression Stats

---

system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx

This is to support tests that will be added in Bug 1401194 in order for web extension tests to identify the correct section more easily (see https://reviewboard.mozilla.org/r/213240/#comment299514)

Bug 1401194 - Add data-section-id to sections for web extension tests

---

system-addon/content-src/asrouter/components/Button/Button.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
system-addon/lib/ASRouter.jsm
system-addon/lib/ActivityStream.jsm

These are some final changes for the 61 experiment, including making the as endpoint changeable via a pref, as well as adding "button_type" option for messages that allows them to be anchor-style buttons.
You can test this by:
- setting `browser.newtabpage.activity-stream.asrouter.snippetsUrl` to `https://gist.github.com/k88hudson/2d627d17ebd3e622e5b05e060d98b182/raw` and **restarting** the browser
- make sure the correct url shows up on about:newtab#asrouter
- make sure both types of snippets show up correctly
The two types of buttons look like this:
anchor
default/button

Bug 1461787 - Add endpoint pref, button_type to ASRouter experiment

---

system-addon/content-src/components/StartupOverlay/StartupOverlay.jsx

r?@sarracini 
Bugzilla Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1462569
Adds `utm_campaign`, `entrypoint`, and `utm_source` params to fxa url.

Bug 1462569 - Add entrypoint query params when sending users to FxA

---

docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
system-addon/content-src/asrouter/components/Button/Button.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
system-addon/lib/ASRouter.jsm
system-addon/lib/ActivityStream.jsm
system-addon/lib/TelemetryFeed.jsm
system-addon/test/schemas/pings.js
system-addon/test/unit/lib/TelemetryFeed.test.js

This patch turns on telemetry and adds a few final changes to match the spec for our intended snippets/AS Router experiment in Firefox 61. It will need to be uplifted.

Turn on telemetry, endpoint pref, and button_type option for AS Router experiment

---

system-addon/content-src/asrouter/asrouter-content.jsx
system-addon/content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
system-addon/lib/ASRouter.jsm
system-addon/test/unit/asrouter/ASRouter.test.js

This pull request fixes an issue where if a AS router message is blocked, other preloaded browsers with the message don't also get blocked.

Bug 1457227 - convert currentId to lastMessageId

---

system-addon/bootstrap.js
system-addon/lib/TelemetryFeed.jsm

The problem described in [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1460782#c4) seems very likely. The feed is instantiated but the `initAction` is dispatched later because it waits for indexeddb. We could move the `addObserver` call in the constructor but I'm not sure if it has any other consequences cc @dmose ?
Guarding against exceptions than could be thrown by removeObserver seems like a common pattern.

Fix Bug 1460782 - Exception in TelemetryFeed uninit

---

locales/en-US/strings.properties

Was preparing to export with #4149 and ran into
```
browser/locales/en-US/chrome/browser/activity-stream/newtab.properties
187  warning  sentance  ==> sentence  (codespell)
✖ 1 problem (0 errors, 1 warning)
abort: Lint run failed (if you really need to you can --skip-lint)
```

chore(lint): Fix sentance/sentence codespell warning

---

system-addon/lib/ASRouter.jsm
system-addon/test/unit/asrouter/MessageLoaderUtils.test.js

I added some tests here to make sure AS Router handles different error codes correctly.
Does the behaviour in these tests look reasonable to you @glogiotatidis?

Bug 1428274 - AS Router should handle 204, 302, 500 codes approrpiately

---

system-addon/lib/AboutPreferences.jsm

r?@k88hudson Simple! ? https://searchfox.org/mozilla-central/search?q=crop%3D"none
Before:
After:

Fix Bug 1457239 - Setting for number of rows is truncated making the label not readable unless you click on it

---

system-addon/content-src/components/Card/_Card.scss

Fix Bug 1464467 - fix type icon in RTL

---

system-addon/content-src/components/Card/_Card.scss

r?@rlr I don't think I've used so many characters to generate "4px" for `clip-path: inset(0 0 4px);`
Before:
After:
(gold background added to see the clipping)

Fix Bug 1464536 - Compact icon type circle can overlap host name

---

system-addon/content-src/asrouter/asrouter-content.jsx
system-addon/content-src/lib/snippets.js
system-addon/test/unit/content-src/lib/snippets.test.js

This patch turns off asrouter snippets when the snippets user-facing pref is set to false
To test:
1. turn on asrouter snippets by setting `browser.newtabpage.activity-stream.asrouterExperimentEnabled` to `true`, verify asrouter snippets are showing up
2. go to about:config#home and turning snippets off
3. verify no snippets are showing on the new tab page

Bug 1464019 - Turn off asrouter snippets when snippets.feed is false

---

system-addon/lib/ASRouter.jsm
system-addon/test/unit/asrouter/ASRouter.test.js
system-addon/test/unit/asrouter/constants.js

I just need to make sure `OpenBrowserWindow` works on windows/linux too I think it should be fine tho

Fix Bug 1463426 - Open 'about:privatebrowsing' on onboarding 'Try Now' action

---

system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx

This should match the same button click event that the other snippets has, is that ok @ncloudioj? Changed it based on the convo we had yesterday

chore(telemetry): Change telemetry for onboarding from 'TRY_NOW' to regular button click

---

system-addon/content-src/asrouter/asrouter-content.jsx
system-addon/content-src/asrouter/components/ImpressionsWrapper/ImpressionsWrapper.jsx
system-addon/content-src/asrouter/components/SnippetBase/SnippetBase.jsx
system-addon/content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
system-addon/test/unit/asrouter/asrouter-content.test.jsx
system-addon/test/unit/asrouter/templates/SimpleSnippet.test.jsx

The events I tested for:
* snippet impressions
* snippet dismiss
* snippet click event (link)
* onboarding "Try it Now" button
"Start Browsing" the button that closes the tour doesn't have telemetry attached, not sure if that is intended or not.

Fix Bug 1465178 - Telemetry source in AS Router is null

---

system-addon/content-src/components/Card/_Card.scss

tiny r? @Mardak 
Before:
After:

Fix Bug 1463381 - change color of context text and icon on Pocket cards

---

system-addon/lib/ASRouter.jsm
system-addon/test/unit/asrouter/ASRouter.test.js

Return a null bundle if we don't have enough items to fill the bundle. This is so we don't encounter the case where you get the onboarding overlay with only 1 or 2 messages

Fix Bug 1465902 - Do not send a bundle of messages if we do not have enough messages to fill the bundle

---

system-addon/content-src/components/Card/Card.jsx
system-addon/lib/Screenshots.jsm
system-addon/test/functional/mochitest/browser_getScreenshots.js
system-addon/test/unit/content-src/components/Card.test.jsx
system-addon/test/unit/lib/Screenshots.test.js

This patch fixes bug 1436615 in which lots of memory is used for activity stream PNGs encoded as data URIs when sending data URIs from the parent process to the child process through IPC.
We will use blobs instead of data URIs. Screenshots will be sent as blob objects from the parent process to the child process. The Card component will receive those blob objects and generate blob object URLs. Images in the same tab which reference to the same blob object will share the same blob URL and this is achieved by keeping a global `Map` of blob paths to blob metadata (URL, reference count, and path). Blob object URLs will be revoked when they are no longer in use.
treeherder: https://treeherder.mozilla.org/#/jobs?repo=try&revision=87a4335396d684a3294ec983fc7ad06bcf6181c3

Bug 1436615 - Lots of memory used for activity stream PNGs encoded as data URIs

---

karma.mc.config.js
system-addon/content-src/asrouter/schemas/provider-response.schema.json
system-addon/lib/ASRouter.jsm
system-addon/lib/ASRouterTargeting.jsm
system-addon/test/functional/mochitest/browser.ini
system-addon/test/functional/mochitest/browser_asrouter_targeting.js
system-addon/test/unit/unit-entry.js

This patch adds basic support for targeting via JEXL, and a few basic targeting values. 
To test this, set `browser.newtabpage.activity-stream.asrouter.snippetsUrl` to https://gist.github.com/k88hudson/2d627d17ebd3e622e5b05e060d98b182 and try logging in / logging out of firefox accounts.

Bug 1433216	- Add AS Router targeting

---

system-addon/content-src/components/Card/_Card.scss

Did I get that math right?
Before:
After:

Fix Bug 1465623 - fix position of type icon border on highlight cards

---

system-addon/content-src/asrouter/schemas/message-format.md
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json

Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1457233#c8 mentioning the allowed tags in the documentation.

Fix Bug 1465818 - Add semver-based version and information about allowed tags

---

system-addon/content-src/components/Card/_Card.scss

Fix Bug 1466608 - increase highlight title font size to 12px

---

system-addon/content-src/asrouter/components/Button/Button.jsx
system-addon/content-src/asrouter/components/Button/_Button.scss
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
system-addon/content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
system-addon/content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss

This adds some new variables and therefore bumps the SimpleSnippet template version to 0.2.0
To test:
1. Set `browser.newtabpage.activity-stream.asrouter.snippetsUrl` to `https://gist.github.com/k88hudson/f56034f9b2c7ff30ff79859d9af47372/raw` in about:config
2. Restart the browser
3. Check that the small title icon appears, the button is blue with red text, and the snippet looks taller

Bug 1464126 - Implement the rest of simple template vars in AS Router

---

docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
system-addon/test/schemas/pings.js

r= @sarracini 
r=@ncloudioj
I edited some telemetry documents to include about:welcome, since these events will also send on this page, and will include "about:welcome" as a string for the `page` key.
questions: 
- in `data_events` around line 32 - how should I reword that to include about:welcome, or should I? 
- should I have changed the line about`Joi`, in `test/schemas/pings.js`

fix: Update docs to include about:welcome

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

[Bugzilla description](https://bugzilla.mozilla.org/show_bug.cgi?id=1467449) shows how to reproduce.
The issue here is that `setMessageById` and `sendNextMessage` have very similar flows (get the message to the target) but `sendNextMessage` has more safeguards against `null` messages so I just refactored that code into a common method that both can use.
https://github.com/mozilla/activity-stream/blob/7e544945fbe0cba46eba9387e4c593e98d8f9f55/lib/ASRouter.jsm#L256-L289

Fix Bug 1467449 - ASRouter sets bundle to null

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
karma.mc.config.js
package-lock.json
package.json
webpack.prerender.config.js
webpack.system-addon.config.js

I've tried including fluent as external modules that resulted in some issues where the build step would complain about the syntax and fail. Alternatively using the [`compat version`](https://github.com/projectfluent/fluent.js/tree/master/fluent-react#compatibility) requires the `regenerator-runtime` and in order to build you would have to include this module before fluent, this would result in too many external modules.
Similar problems occur when bundling fluent with AS:
* syntax errors force to use `compat` which also implies a dependency on `regenerator-runtime`
* maybe a different preprocessing step?
* [the spread syntax](https://github.com/projectfluent/fluent.js/blob/75f57aa43a95f7e2072c1066e44524af9a07e7a1/fluent-react/vendor/voidElementTags.js#L15) results in an error for me even …

Fix Bug 1457233 - Allow AS router message content to include subset of HTML

---

content-src/components/Card/_Card.scss
content-src/styles/_variables.scss

@bryanbell says the history icon color should match the trending icon color from pocket. So we just remove the color override.
Before:
After:

Followup to Bug 1463381 - fix history icon fill color (compact cards)

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
test/unit/asrouter/asrouter-content.test.jsx

This is based on the work in #4162 so only the very last commit should be reviewed https://github.com/mozilla/activity-stream/pull/4196/commits/c2f696b6df5e6a7b44fcf8d77c9f4db9b1d82080
Follow up work for https://bugzilla.mozilla.org/show_bug.cgi?id=1457233

Fix Bug 1457233 - Use custom metric attributes for links

---

.eslintrc.js
package-lock.json
package.json

r?@sarracini Makes the warnings go away!

Followup Bug 1464548 - Restore eslint no-undef by upgrading to eslint-plugin-mozilla 0.14.0

---

lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

Looking back at the [discussion in the PR](https://github.com/mozilla/activity-stream/pull/4184#discussion_r191934937) the original change so that we don't fetch `4 * TOP_SITES_MAX_SITES_PER_ROW` unnecessarily, but I didn't see this usecase (when the user removes a topsites) being discussed. 
This would fetch an extra 4 items to be used in case a hole needs to be filled in.
It also seems like Highlights deduping uses all the `TopSites.rows` in the store (not just the ones being displayed) so this would also need to be fixed. 
f? @Mardak

Fix Bug 1469823 - Listen for PLACES_LINK_DELETED actions and update Topsites

---

bin/render-activity-stream-html.js

Alright, I think this should cover what we want. I changed a few things:
* images no longer allow `http` (I think that's OK? I don't think we use any external images right now anyway)
*  I added `default-src none` which should cover frames, object-src, etc.
* `connect-src` is `https` only (i.e. fetching). This is only used for snippets as far as I can think of right now.
The only thing I am a bit worried about is if the (legacy) snippets url is OK as `https` only – @glogiotatidis @pmac do you see this as being an issue possibly?

Bug 1448359 - Enable CSP for Activity Stream

---

content-src/asrouter/asrouter-content.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

Endpoint: https://gist.githubusercontent.com/piatra/70234f08696c0a0509d7ba5568cd830f/raw/68370f34abc134142c64b6f0a9b9258a06de7aa3/messages.json
Example url: `about:newtab?endpoint=https://gist.githubusercontent.com/piatra/70234f08696c0a0509d7ba5568cd830f/raw/68370f34abc134142c64b6f0a9b9258a06de7aa3/messages.json&snippetId=42`
When navigating to this URL it should automatically load the correct snippet. 
On every refresh we want to fetch data from the endpoint again. The workflow would be:
* snippet creator makes v0 of snippet
* copy-paste the url and open it in a new tab
* make changes to snippet -> refresh the same page, get the latest/updated content
ASRouterAdmin will add the endpoint (if found in the URL) only for debugging purposes, snippet creators are interested in landing on …

Fix Bug 1463836 - AS Router Remote Provider Message Previewing

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/schemas/provider-response.schema.json
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/asrouter-content.test.jsx

This PR allows for a notion of "triggers" which act as a way to have priority in AS Router. This means that messages can be both targeted, for things that are long lasting (e.g locale, list of addons, prefs etc) but they can also be shown when a trigger happens - a one time event (e.g first new tab on a fresh profile, new addon installed, etc). Basically the content requests that a trigger message be shown under some condition (in this case we check the url to be about:welcome, indicating we are in a first run case) and then AS Router searches for messages that should be shown on a 'firstRun' trigger. Picks those, and shows them.
New method  `findMatchingMessageWithTrigger` called when content sends data 'trigger', and then fall back to the original `findMatchingMessage` if no messages …

Fix Bug 1470170 - Implement priority system for AS Router messages

---

content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json

Documentation https://spacetelescope.github.io/understanding-json-schema/reference/string.html#format
@k88hudson do you know if there's a better way to do this?
@glogiotatidis will this update to the schema help you format things on the server side?

Fix Bug 1468978 - Update schema to use format: uri for links

---

lib/Store.jsm
test/unit/lib/Store.test.js

This is the only "small" change I could think of to prevent a lot of `TRANSACTION_FAILED` events.
This solution will still log the `INDEXEDDB_OPEN_FAILED` event.

Fix Bug 1471375 - Catch IndexedDB permafail

---

lib/PlacesFeed.jsm
test/unit/lib/PlacesFeed.test.js

Backport bug 1340498 which landed today: https://hg.mozilla.org/mozilla-central/diff/b6f047709e8e/browser/extensions/activity-stream/lib/PlacesFeed.jsm
and fix the test along with it

Backport Bug 1340498 - Remove onVisits from PlacesFeed

---

content-src/components/CollapsibleSection/_CollapsibleSection.scss

(styles) Fix Bug 1472819: adjust position of Pocket disclaimer button

---

bin/render-activity-stream-html.js

r?@k88hudson Skips the extra and makes the message yellow instead of red.

Fix Bug 1473848 - Stop exporting locales not explicitly in CENTRAL_LOCALES, e.g., "mix"

---

content-src/components/StartupOverlay/StartupOverlay.jsx
lib/PrefsFeed.jsm

@sarracini @vladikoff
~To Test: change line 32 from "https://accounts.firefox.com/metrics-flow" to "https://latest.dev.lcip.org/metrics-flow"
Currently there is a CORs issue with accounts.firefox.com and the changes required will hopefully be live in a few days.~
re: https://github.com/mozilla/fxa-content-server/issues/6267
re: https://github.com/mozilla/fxa-content-server/issues/5882

Fix Bug 1471514 - Add top-of-funnel metrics for fxa

---

bootstrap.js
common/Reducers.jsm
docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
lib/ActivityStream.jsm
lib/TelemetryFeed.jsm
test/unit/common/Reducers.test.js
test/unit/lib/ActivityStream.test.js
test/unit/lib/TelemetryFeed.test.js
test/unit/unit-entry.js

This fixes bug 1472038.
It also simplifies the ActivityStream by
* Getting rid of the `option` argument of constructor
* Getting rid of the `reason` argument of `init()`

Fix Bug 1472038: Use app build ID for telemetry addon_version

---

content-src/components/Base/Base.jsx
content-src/components/Base/_Base.scss
content-src/components/StartupOverlay/StartupOverlay.jsx
content-src/components/StartupOverlay/_StartupOverlay.scss
content-src/styles/_activity-stream.scss

These CSS changes will stop AS flashing before the startup overlay renders, but only if prerendering is disabled for the about:welcome load. With prerendering you'll still see the prerendered page flash before the overlay.
I have a patch to AboutRedirector and aboutNewTabService to disable prerendering on about:welcome; I'm not sure if there's a way to do that within AS that would be easier?
Kate and I talked about the possibility of having separate prerendered about:welcome files; [timing measurements](https://gist.github.com/AdamHillier/c32db37b66570f0e0d7f08a31b1849f6) suggest that these CSS changes should be sufficient by themselves.

Fix Bug 1471243: stop AS showing before first run overlay

---

content-src/components/StartupOverlay/StartupOverlay.jsx
lib/PrefsFeed.jsm

This is almost identical to #4218, except it now uses `identity.fxaccounts.remote.firstrun`  instead of `identity.fxaccounts.remote.root` as a pref. This new pref was created so that we can turn it off during tests without disrupting anything else that may depend on `identity.fxaccounts.remote.root`.

Fix Bug 1471514 - Add top-of-funnel metrics for fxa.

---

bootstrap.js
lib/ActivityStream.jsm
test/unit/lib/ActivityStream.test.js

Backport changes which move activity stream init/uninit from boostrap.js to AboutNewTab.jsm in m-c. Also while here, deleting the now unused `uninstall` function in ActivityStream.jsm.
This needs to wait until changes in bug 1474410 land in mozilla central before landing

Backport chanages from Bug 1474410

---

content-src/asrouter/schemas/message-format.md
lib/ASRouterTargeting.jsm
test/functional/mochitest/browser_asrouter_targeting.js

Adds additional targeting properties to achieve parity with existing snippets targeting fields.
To test:
- Please ensure mochi tests pass by running `./mach test browser/extensions/activity-stream/test/functional/mochitest/browser_asrouter_targeting.js`. See tests and docs for examples and JEXL

gSnippetsMap parity in ASRouter

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/schemas/message-format.md
content-src/asrouter/schemas/provider-response.schema.json
content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
test/functional/mochitest/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterTargeting.test.js

This patch allows messages to define lifetime and custom period frequency caps for impressions. 
For example, this message allows 50 impressions in total, 5 within a day and only 1 within a minute.
```json
{
"id": "MSG123",
"caps": {
"lifetime": 50,
"custom": [{"period": "daily", "cap": 5}, {"period": 60000, "cap": 1}]
}
}
```
The current behaviour for cleaning up the impression list is that impressions for messages that are not found in the currently loaded list of messages get removed. Perhaps this is too aggressive?
Testing setup:
1. ensure `browser.newtabpage.activity-stream.asrouterExperimentEnabled` is `true`
2. set `browser.newtabpage.activity-stream.asrouter.snippetsUrl` to `https://gist.githubusercontent.com/k88hudson/bab3cf6e9035d5d0392311ca928480fd/raw` (this will give you some …

Bug 1432674	- Add support for frequency caps for AS Router

---

.sass-lint.yml
content-src/components/Base/_Base.scss
content-src/components/StartupOverlay/_StartupOverlay.scss
content-src/styles/_activity-stream.scss
content-src/styles/_theme.scss
content-src/styles/_variables.scss

Woohoo, no more warnings!
To test:
- run `npm run lint:sasslint` and ensure no warnings are produced.
- please check `about:welcome` and dark theme since almost all changes involve those files.
Notes:
- I don't think there's actually a way to allow for more than 1 `class-name-format` convention, so I just removed the rule. Personally I don't particularly think it matters if people use camel case or hyphens anyway
- these changes should not result in any significant changes in the output and definitely not in the design

Bug 1476381 - Fix outstanding sass lint warnings

---

lib/ActivityStream.jsm
lib/FaviconFeed.jsm
test/unit/lib/FaviconFeed.test.js
test/unit/unit-entry.js

@ncloudioj to test it out, you need to change the prefs for RS. I just run the following in the browser console:
```
const SERVER_STAGE = "https://settings.stage.mozaws.net/v1";
const HASH_STAGE = "DB:74:CE:58:E4:F9:D0:9E:E0:42:36:BE:6C:C5:C4:F6:6A:E7:74:7D:C0:21:42:7A:03:BC:2F:57:0C:8B:9B:90";
Services.prefs.setCharPref("services.settings.server", SERVER_STAGE);
Services.prefs.setCharPref("security.content.signature.root_hash", HASH_STAGE);
```

Bug 1476309 - use RemoteSettings for Tippy Top

---

lib/ASRouterTargeting.jsm
test/functional/mochitest/browser_asrouter_targeting.js
test/unit/unit-entry.js

Relies on some minor changes to FilterExpressions.jsm in order to work effectively (and in order for the added mochitests to pass).

Fix Bug 1471350: add topFrecentSites to ASRouterTargeting

---

.taskcluster.yml
README.md
mochitest.sh
package.json
yamscripts.yml

Not sure where that request actually goes. It's needed so that taskcluster actually registers our repository.
Here are the logs of the mochitests running on my fork of AS https://tools.taskcluster.net/groups/FZ0dHWLVTq6q0sbQj2JEig/tasks/FZ0dHWLVTq6q0sbQj2JEig/runs/0/logs/public%2Flogs%2Flive.log#L1753
Some more info about the task steps include:
* pulling the image
* updating m-c 
* pulling the PR we want to test
* building AS and m-c (artifact)
* running the tests
Took 17 minutes. To achieve this the docker image `piatra/asmochitests` (specified in .taskcluster.yml) is built to include m-c repo + an artifact built before publishing in an attempt to speed things up.
As a follow up I am planning to set up a cron job on my machine that will rebuild + publish a new version of the image …

Fix Bug 1474372: Run mochitests on taskcluster

---

content-src/components/Card/_Card.scss

I was actually able to reproduce this on Mac. I gave it a whole extra 4 pixels to be safe.
r? @ncloudioj 
Before:
After:

Fix Bug 1476959 - Cut off tail letters in New Tab page (Highlights section)

---

content-src/asrouter/schemas/message-format.md
content-src/asrouter/schemas/provider-response.schema.json
lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/constants.js

Adds an order property to the message, and sorts on that order. Defaults to 0 if no order provided - meaning this bundle doesn't care about this order

Fix Bug 1477766 - Display Simplified Onboarding Tour Cards in specific order

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

With this PR you can add additional whitelist hosts via the pref `browser.newtab.activity-stream.asrouter.whitelistHosts`. They are added in addition to the already existing list.
Because this is used for development only the pref **does not come with a default value** (does not exist in about:config), it will have to be added manually. Example value `["gist.github.com", "gist.githubusercontent.com"]`
You also need to restart the Router by flipping `browser.newtabpage.activity-stream.asrouterExperimentEnabled` which I think is acceptable since it's used for development.
Every host added will be of type preview: when adding an endpoint its`updateCycle` will be 0 so that it refreshes on every page load.
If you are trying to add an endpoint that is not in the list you will get an error …

Fix Bug 1477631: Allow setting whitelist hosts via prefs

---

lib/ActivityStreamMessageChannel.jsm

r?@piatra  Manually add RemotePages global until eslint-plugin-mozilla is updated.
Simple port of https://hg.mozilla.org/mozilla-central/rev/6aa03eee1597 but needs some fixes until eslint-plugin-mozilla gets the changes from https://hg.mozilla.org/mozilla-central/rev/df67254b8e79 (for modules.json)

Port Bug 1369466 - Change consumers to the new location of RemotePageManager. r=mossop

---

aboutNewTabService.js
bin/render-activity-stream-html.js
test/browser/browser_packaged_as_locales.js

r?@sarracini Use BCP47 instead of lang tags for negotiation and switch back to lang tags for paths. As suggested in https://bugzilla.mozilla.org/show_bug.cgi?id=1478930#c7
(Not "Fix"-ing as looks like the bug will be kept open for fixing the underlying negotiate issue.)

Bug 1478930 - ja-JP-mac builds incorrectly use ja strings

---

content-src/components/CollapsibleSection/_CollapsibleSection.scss
content-src/components/TopSites/_TopSites.scss

There are two more instances of `text-transform: uppercase;` but they are on strings that aren't localized (domain letter fallback and domain names). We can take care of those with `/* eslint-disable */` or possibly `.toUpperCase()` when we add the eslint rule in https://bugzilla.mozilla.org/show_bug.cgi?id=1476450
r? @k88hudson

Fix Bug 1475921 - remove text-transform usage on localized strings (section headers)

---

content-src/lib/link-menu-options.js

This needs part 1 to land in order to actually work. See attachment on bug 1470211 for part 1
https://reviewboard.mozilla.org/r/260524/diff/1#index_header
STR:
1. go to a page and  pocket it, then bookmark it
2. open a new tab, see that there is both a pocket card and a bookmark card for that page (lets call this site 1)
3. go to a different page and pocket it, then bookmark it
4. open a new tab, see that there is both a pocket card and a bookmark card for that page (lets call this site 2)
_Note: At this point you should have 4 highlights from 2 different sites - 2 bookmarks and 2 pocket items_
5. dismiss **pocket** card from site 1 - see that the corresponding bookmark card of site 1 is still there
6. dismiss the **bookmark** card from site 2 - see that the corresponding pocket card of …

Fix Bug 1470211 - Dismissing a Bookmarked highlight also dismissed a Saved To Pocket highlight of the same content - Part 2

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/schemas/provider-response.schema.json
karma.mc.config.js
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/ASRouterTriggerListeners.jsm
lib/OnboardingMessageProvider.jsm
test/browser/browser.ini
test/browser/browser_asrouter_trigger_listeners.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterTriggerListeners.test.js
test/unit/unit-entry.js

In order to support an `openURL` trigger, triggers become (instead of being just strings) objects with an `id` and an optional `param` (in this case the url host name).
`ASRouterTriggerListeners.jsm` has a map of singleton listeners which are initialised or not depending on whether ASRouter has messages that have that particular trigger. Every time ASRouter updates its messages, it checks their triggers to do this un/initialisation of the trigger listeners.
At the moment the only listener is for `openURL`, which listens for webpages being opened with specific host names, but it's set up in a way that allows listeners for new triggers to be added very easily.
You can manually test that the patch works by adding a test message to `OnboardingMessageProvider` such as:
```js
{
id: "TEST", …
```

Fix Bug 1471351: Add openURL trigger to ASRouter

---

lib/ActivityStream.jsm
lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

This patch removes `google.*` and `amazon.*` from top sites if google or amazon are set to the default search engine respectively.
To manually test this, please do the following: 
1. On a new profile with this patch applied, do a few google searches such that you organically have google in your top sites as well as the default amazon top site tile. 
2. With google as your default search, set `browser.newtabpage.activity-stream.improvesearch.noDefaultSearchTile` to true in about:config. Confirm that the google no longer appears in your top sites.
3. Restart the browser to ensure that on a first load, google is still not in your top sites.
4. Set your default search to amazon in `about:preferences#search`. Confirm that google is now visible in your top sites and the default amazon tile is …

Bug 1479478 - Exclude default search URLs from topsites

---

docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/ASRouterFeed.jsm
lib/ASRouterTargeting.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterFeed.test.js

This patch adds telemetry for errors that occur in JEXL string or elsewhere in the targeting environment.
If an error is thrown when a jexl string is being parsed/evaluated, a ping in the following format will be sent:
```json
{
"client_id": "n/a",
"action": "asrouter_undesired_event",
"addon_version": "20180710100040",
"impression_id": "{005deed0-e3e4-4c02-a041-17405fd703f6}",
"locale": "en-US",
"message_id": "some_message_id",
"event": ["MALFORMED_EXPRESSION" | "OTHER_TARGETING_ERROR"],
}
```
To test this, you can:
1. Set the following prefs in about:config
- `browser.newtabpage.activity-stream.asrouter.snippetsUrl` to `https://gist.githubusercontent.com/k88hudson/bab3cf6e9035d5d0392311ca928480fd/raw`
- `browser.newtabpage.activity-stream.asrouterExperimentEnabled` to `true`
- …

Bug 1476055 - Add telemetry for JEXL and other targeting errors

---

lib/ActivityStream.jsm

Adds pref for top sites search shortcuts experiment

Fix Bug 1480814 - Add a pref to enable/disable top site search shortcuts on the newtab page

---

content-src/lib/link-menu-options.js
content-src/styles/_icons.scss
data/content/assets/glyph-pocket-save-16.svg

r?@AdamHillier   Ports https://hg.mozilla.org/mozilla-central/rev/d2dfd67e6fc8 by adding the outline as a separate icon.
Before bug 1462790:
After bug 1462790:
After this fix:

Fix Bug 1481503 - Use pocket outline for save action and solid pocket for saved

---

content-src/components/Search/_Search.scss

In addition to the height change, I (under the supervision of @aaronrbenson) adjusted the padding around the icons to give them some extra horizontal breathing room and make it look better.
Before:
After:

Fix Bug 1480535 - Make in-content search box more prominent

---

content-src/components/LinkMenu/LinkMenu.jsx
content-src/components/TopSites/TopSite.jsx
content-src/components/TopSites/TopSitesConstants.js

Adds a context menu for 'pin/unpin' and 'block' if a site is a search shortcut top site
a lil baby context menu 👶

Fix Bug 1480506 - Top Search Shortcuts should allow user to unpin

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

The previous snippets implementation calls `Services.urlFormatter.formatURL`, passing in the snippets endpoint URL, to replace params such as %OS_VERSION%, %LOCALE%, etc. with correct values to help target snippets. It also manually supports an additional param %STARTPAGE_VERSION%. You can see the existing url param support [here](https://github.com/mozilla/activity-stream/blob/7e544945fbe0cba46eba9387e4c593e98d8f9f55/lib/SnippetsFeed.jsm#L43).
This patch extends the same behaviour to ASRouter, applying the same replacement to all remote endpoint URLs. For the %STARTPAGE_VERSION% Kate and I agreed to use the `version` property of the provider-response.schema.json. There is an included test case to ensure that the two values agree.
I don't know whether or not you want to restrict the param …

Bug 1479021: support url params in provider endpoints

---

lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

Check that if we've blocked a search shortcut, then we should also filter out the matching default site. See https://phabricator.services.mozilla.com/D2970 for Part 2

Bug 1480888 - Implement blocking system for special search shortcut top sites - Part 1

---

content-src/components/Base/Base.jsx
lib/SectionsManager.jsm
lib/TopStoriesFeed.jsm
test/unit/content-src/components/Base.test.jsx
test/unit/lib/SectionsManager.test.js
test/unit/lib/TopStoriesFeed.test.js

To test:
1. Set the pref "browser.newtabpage.activity-stream.feeds.section.topstories.options" to default.
2. load about:home take not of the third rec. This ensures that we have a preloaded tab generated with default recs. You can keep this tab open, or close it, both are viable and shouldn't matter.
3. Update "browser.newtabpage.activity-stream.feeds.section.topstories.options" pref to:
```
{"api_key_pref":"extensions.pocket.oAuthConsumerKey","hidden":false,"provider_icon":"pocket","provider_name":"Pocket","read_more_endpoint":"https://getpocket.com/explore/trending?src=fx_new_tab","stories_endpoint":"file:///home/scott/spoc.json","stories_referrer":"https://getpocket.com/recommendations","topics_endpoint":"https://getpocket.cdn.mozilla.net/v3/firefox/trending-topics?version=2&consumer_k …
```

Fix Bug 1479458 - Spocs updating when pref changes from a shield study

---

content-src/components/StartupOverlay/StartupOverlay.jsx

utm params are added to the initial fetch call to give more information to FxA
as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1478649#c5
fixes: Bug 1478649

Add utm params to initial fetch call.

---

lib/TopSitesFeed.jsm

Oops was caused by my patch. Solution is straightforward.

Fix Bug 1482190: don't convert manually pinned sites to search shortcuts

---

lib/ActivityStream.jsm
lib/SearchShortcuts.jsm
lib/TopSitesFeed.jsm
test/unit/lib/ActivityStream.test.js
test/unit/lib/TopSitesFeed.test.js

Uses Romanised names for the @... search labels for now, can be corrected if needed in a follow-up. Also moves some of the search shortcut tests so that they're all in the same place.

Fix Bug 1481901: include additional search shortcut providers

---

content-src/components/TopSites/TopSite.jsx
docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
test/schemas/pings.js
test/unit/content-src/components/TopSites.test.jsx

This documents the telemetry part for [search shortcuts](https://bugzilla.mozilla.org/show_bug.cgi?id=1479806) in Top Sites of Activity Stream.
@fmarier Could you take a look at this please? The data review request was attached at [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1480513#c2)

Bug 1480513: Add telemetry for search shortcut

---

lib/TopSitesFeed.jsm

Refresh and broadcast the top sites when we get the geo-dependent list of search shortcuts to pin.

Fix Bug 1482255: fix search shortcut pinning race condition

---

lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

When we add existing information from frecent sites we accidentaly copy over the `searchTopSite` label to existing pinned sites.

Fix Bug 1482412 - Don't change the status of existing pinned sites

---

lib/TopSitesFeed.jsm

As you say, this should stop that particular error.

Fix Bug 1482464: check for e.identifier before trying to match

---

content-src/components/TopSites/SearchShortcutsForm.jsx
lib/SearchShortcuts.jsm
lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

Also fixed a small bug where null top sites were crashing the add search
shortcuts editor.

Bug 1482519 - Separate custom search shortcut options from organic ones

---

lib/TopStoriesFeed.jsm
test/unit/lib/TopStoriesFeed.test.js

To test.
1. Checkout aab3771a50215d97ed4f34c7056f46a0f943a822 which is the pr before the patch that caused the bug.
2. Open about:home enough to generate some spocs and a preload and a cache.
3. Checkout my branch.
4. Go to about:home
5. Should see rec.
If you want to see the initial bug reproduced, instead of checking out my branch on step 3, checkout  be0ccddd3e6f7d7adffa55b0440f8a1104286ca5 and do everything else the same, and then on 5 should see no recs.

Bug 1479458 - Fixing broadcast of updated data from cache.

---

content-src/components/TopSites/_TopSites.scss

Fix Bug 1482865 - fix searchy overlap when resizing window

---

content-src/components/TopSites/TopSite.jsx

No more middle clicks for search top sites

Fix Bug 1482854 - Middle clicking an @search Top Site wrongly triggers autoscroll

---

content-src/components/TopSites/SearchShortcutsForm.jsx
docs/v2-system-addon/data_events.md

Ended up splitting up the composite edit ping into individual add & delete pings, since the deeply nested JSON query is not well supported in our database.

Fix Bug 1482568 - Add telemetry for adding/deleting search shortcut

---

mochitest.sh

I'm not sure if this is a bug or not but running `./mach test` or `./mach mochitest` seems to return 0 regardless of the success/failure of the actual test.
The only workaround I've found is outputing the logs in a file and grepping for the `TEST-UNEXPECTED` string, funny enough this method is also mentioned in a bug [about returning the correct status code from mochitests](https://bugzilla.mozilla.org/show_bug.cgi?id=875382#c3)
f? @Mardak

Fix Bug 1482246 - Correctly report mochitest failures

---

content-src/components/TopSites/TopSite.jsx

Calls the onClick function for the link if it is a search shortcut and we pressed enter. To test, tab to a search shortcut top site and click enter. Observe that the normal search shortcut behaviour works

Fix Bug 1483135 - Search shortcuts are not tabbable

---

lib/TopSitesFeed.jsm

If you'd like to test this, you can paste this in [NewTabUtils at line 1159](https://searchfox.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#1159) to override your top sites query:
https://gist.github.com/k88hudson/e69eea7e89342e5fcb294ad45d8d403a
Prefs:
- 1 row of top sites
- `improvesearch.noDefaultSearchTiles` set to `true`
The incorrect behavior on master is that with you should see the last two positions be filled with default tiles (youtube, facebook) rather than organic tiles.
With my patch applied, you should see organic tiles (slack, github).

Bug 1483653 - Sites filtered out by improvesearch.noDefaultSearchTiles are replaced by default sites

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js

To test this, just open the onboarding panels via `about:newtab#asrouter` and make sure the buttons still work.
Changes `button_action` and `button_params` to be a single `button_action`

Bug 1483562 - Use object for button_action in ASR

---

common/Actions.jsm
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/components/Button/Button.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/SimpleSnippet.test.jsx

Some steps in order to test this.
1. Whitelist gist.githubusercontent.com
1. set `browser.newtab.activity-stream.asrouter.whitelistHosts` to `browser.newtab.activity-stream.asrouter.whitelistHosts`
2. Navigate to about:newtab?endpoint=https://gist.githubusercontent.com/piatra/70234f08696c0a0509d7ba5568cd830f/raw/41338334ba7e523020b0ea9a875f872ccb050633/messages.json
The snippet should have a Learn more button that opens the browser menu.
Exposed `sendMessage` method to snippet messages. It can only be triggered if the messages contains a `button_action`. Need to confirm that regular snippet links don't trigger actions but it didn't seem like the case from the examples.
The snippet example served by our endpoint `https://activity-stream-icons.services.mozilla.com/v1/messages.json.br` need …

Fix Bug 1478569 - New Action: Show AppMenu

---

lib/TopSitesFeed.jsm
test/unit/unit-entry.js

Ideally I would like to refactor all the accesses to search services into one (maybe move all to init) because the pattern to await for `search.init` seems to repeat itself several time in the feed.
I can follow up with another PR but for now this will fix the sync access and [Mike's comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1482579#c7) seemed pretty serious I wanted to have a fix ready.

Fix Bug 1482579 - Wait on Search services to intialize before using it

---

content-src/components/TopSites/_TopSites.scss

Before:
After:
(It's even more noticeable in dark theme).

Fix Bug 1484290 - remove hairline/border from searchy icon

---

content-src/asrouter/README.md
content-src/asrouter/schemas/message-format.md
lib/ASRouterTargeting.jsm
lib/ActivityStream.jsm
test/browser/browser_asrouter_targeting.js

This adds a `currentTimestamp` attribute for targeting. Allows ASRouter messages to filter by time, also allows for more complicated JEXL expressions like "profile age".
I also updated some of the docs `publish_start|end` is not something we support.
And I've moved our remote snippet endpoint to fetch from the snippets cdn. We can now validate the integration of the two services. Also the previous endpoint was using a schema we no longer support (link are now only rendered as part of Fluent).

Bug 1485345 - Add timestamp targeting

---

lib/ASRouter.jsm
test/unit/unit-entry.js

This might be the smallest easiest win but ASRouter was showing up in the profiler for no good reason:
Even though the experiment is disabled we include ASRouter.jsm which includes UITour.jsm which automatically calls `init()` [when the file is loaded](https://searchfox.org/mozilla-central/rev/55da592d85c2baf8d8818010c41d9738c97013d2/browser/components/uitour/UITour.jsm#1732).

(nobug): Switch to lazy loading the modules

---

lib/CFRPageActions.jsm

"No Thanks" should hide both the panel and the chiclet, without collapsing, or shrinking the chiclet, without blocking the addon itself
"Install" hide both the panel and the chiclet, without collapsing, or shrinking the chiclet. Additionally it should block the addon, regardless of a successful install 
Best way to test this is in about:newtab#asrouter

Fix Bug 1486867 - Install and No thanks actions should block and hide CFR message

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/CFRPageActions.jsm

Adds frequency capping for when the chiclet is shown via `shouldExpand` only 
To test this, either see the impressions go up in about:newtab#asrouter, or in real life, see that the recommendation only appears once.

Fix Bug 1487156 - Track impressions for frequency capping in CFR

---

lib/CFRPageActions.jsm

Remove the popupnotification so that a "removed" event isn't triggered for a subsequent popupnotification in the same tab, causing the chiclet to collapse.

(nobug) Remove the popupnotification to stop undesired chiclet collapse

---

lib/CFRPageActions.jsm

Doh this was me being dumb, in fact it does matter if the currentNotification is undefined, the remove method throws if `.hide()` is called and the chiclet hasn't been clicked on. Thanks Andrei for catching this.

(nobug) Check for presence of currentNotification before removal

---

content-src/asrouter/schemas/message-format.md
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js

This PR has unit tests instead of our usual mochitests for targeting because targeting parameter was added to `ASRouter` and that's more complicated to set up for mochitesting than our (stateless) `ASRouterTargeting.jsm`
Fetches and updates the timestamp in the router, passes it down to targeting through the context parameter. Targeting will merge the provided context and default one. `ASRouterFeed` calls `Router.uninit` on shutdown and that's when we update the timestamp.

Fix Bug 1484206 - Add previousSessionEnd to targeting context

---

content-src/styles/activity-stream-mac.scss

@AdamHillier what do you think of this fix?
Before:
After:

Fix Bug 1482534 - fix font smoothing in OSX

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/SimpleSnippet.test.jsx

This fixes the issue for `SimpleSnippet` but I would keep the bug open until we land all templates (video, newsletter etc) because they all require this feature.

Fix Bug 1482859 - Block snippet messages after CTA was clicked

---

lib/CFRPageActions.jsm
test/unit/asrouter/CFRPageActions.test.js

The `useClientID` flag is redundant for CFR telemetry, since using `client_id` or `impression_id` is fully controlled by `TelemetryFeed.applyCFRPolicy()`.

chore(telemetry): Remove the redundant flag in CFR telemetry

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/MessageLoaderUtils.test.js

I also added the ETag header so the CDN can return 304 (Not Modified) if the file hasn't changed since the last fetch. I manually tested by adding a bunch of console statements and it all seems to be working for me locally.

Fix Bug 1433243 - Implement ASR persistent caching for remote endpoints

---

common/Reducers.jsm
content-src/components/Base/_Base.scss
content-src/components/Sections/Sections.jsx
content-src/components/Sections/_Sections.scss
test/unit/common/Reducers.test.js
test/unit/content-src/components/Sections.test.jsx

@k88hudson 
Two small design related issues noticed in https://bugzilla.mozilla.org/show_bug.cgi?id=1483655, which this fixes.
1. Flicker of logged in/out state while the page loads. Adding a gif below.
2. The height of the cta was actually a few pixels larger than the topics, which potentially causes a slight shift in content as it loads. I made sure on max screen sizes the content doesn't move.

Fix Bug 1488846 - Pocket cta for logged out users flickers a bit before displaying the logged in version (topics) and shifting

---

content-src/asrouter/schemas/message-format.md
content-src/asrouter/schemas/provider-response.schema.json
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/ActivityStream.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterTargeting.test.js
test/unit/unit-entry.js

Some more insights: This is needed because previously Snippets could execute code in the browser and it was done to get [user country](https://github.com/mozmeao/snippets-service/blob/2f84e39574bd496921a3defc496888c8ff8c66d0/snippets/base/templates/base/includes/snippet_as.js#L484) and [useragent](https://github.com/mozmeao/snippets-service/blob/2f84e39574bd496921a3defc496888c8ff8c66d0/snippets/base/templates/base/includes/snippet_as.js#L234). Now we need to provide that information.
Using `browser.search.region` is equivalent because Search services calls the same endpoint to get country code [0] [1].
I also updated the remote snippets url, previously it was poiting to a static bundle.
[0] https://searchfox.org/mozilla-central/rev/9e7995b3c384945740985107a4de601b27904718/toolkit/component …

Fix Bug 1484207 - Add geo and firefox version targeting getters

---

content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
lib/CFRPageActions.jsm
test/browser/browser_asrouter_cfr.js
test/unit/asrouter/CFRPageActions.test.js
test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx

Turned the usage examples from https://github.com/mozilla/activity-stream/commit/21268904be632c4d74f1fa981e852412a94794ef#r30406394 into unit tests.

Fix Bug 1490241 - CFR fluent and string overrides should both have attributes

---

mochitest.sh

Finish the followup from https://github.com/mozilla/activity-stream/pull/4254#issuecomment-407041386 and fix broken tests introduced by the new files from #4294

Fix Bug 1491944 - Run all_files_referenced on taskcluster

---

content-src/components/CollapsibleSection/CollapsibleSection.jsx

To verify:
* Make sure collapsing and expanding still works
* Make sure you can't tab through top sites, for example, while they are collapsed

Fix Bug 1485626 - Tab_Index reaches elements inside collapsed menus in activity stream

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

This bug was caused by [this line](https://github.com/mozilla/activity-stream/blob/d2c948f0fddd54335fca6fcfab3c64436727b3d2/lib/ASRouter.jsm#L717) in the impression cleanup. We filter out all the provider impressions older than the longest cap period (from `getLongestPeriod`), and the provider cap period was given as `"daily"` i.e. not a number, so all the provider impressions were getting removed.
I think the most straightforward solution to this is to replace all aliases like `"daily"` with their appropriate numerical values when we load the providers/messages so that we don't have to consider these special cases each time we use the frequency caps.

Fix Bug 1492454: Normalise ASRouter frequency caps

---

lib/SnippetsFeed.jsm

Looks like we missed backporting this bug back in August:
See [mozilla-central](https://searchfox.org/mozilla-central/source/browser/components/newtab/lib/SnippetsFeed.jsm#193) v.s. [activity-stream/master](https://github.com/mozilla/activity-stream/blob/master/lib/SnippetsFeed.jsm#L193)

Backport Bug 1485305

---

test/browser/browser.ini
test/browser/browser_asrouter_cfr.js

This reverts https://github.com/mozilla/activity-stream/commit/89f12a8030bcb8e53018b829c2175b5261bdb7c4 and fixes the test. Try run https://treeherder.mozilla.org/#/jobs?repo=try&revision=d24d95071523427d57b0befae3073ff71d293313&selectedJob=200464695

Fix Bug 1492777 - Failing CFR mochitest browser_asrouter_cfr.js 

---

content-src/asrouter/asrouter-content.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
lib/ASRouterPreferences.jsm
lib/TelemetryFeed.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/lib/TelemetryFeed.test.js

Turn on snippets by running this in the browser:
```js
Services.prefs.setStringPref(
"browser.newtabpage.activity-stream.asrouter.messageProviders",
JSON.stringify([{"id":"onboarding","type":"local","localProvider":"OnboardingMessageProvider","enabled":true,"cohort":1},{"id":"snippets","type":"remote","url":"https://snippets.cdn.mozilla.net/us-west/bundles/bundle_d6d90fb9098ce8b45e60acf601bcb91b68322309.json","updateCycleInMs":14400000,"enabled":true},{"id":"cfr","type":"local","localProvider":"CFRMessageProvider","enabled":true,"cohort":0}])
);
```
- Ensure snippets are running on new tab page.
- Turn off the user pref for snippets on about:preferences#home
- Ensure snippets are no longer showing up
- Turn the pref back on
- Ensure snippets are showing up again
Create a new profile …

Bug 1492942 - Snippets should respect onboarding, user pref

---

content-src/asrouter/templates/CFR/templates/ExtensionDoorhanger.schema.json
lib/CFRMessageProvider.jsm
lib/CFRPageActions.jsm
test/unit/asrouter/CFRPageActions.test.js
test/unit/asrouter/templates/ExtensionDoorhanger.test.jsx

Fetch the correct url for the latest xpi for an addon given it's GUID.

Fix Bug 1494275 - CFR can wrongly recommend outdated versions of the addons

---

content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss
content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss

Before: 
After:
We don't have specs yet for dark theme for onboarding modal in general so leaving it as original light theme specs for now

Fix Bug 1463775 - Buttons from the new onboarding have the wrong highlight on Dark theme

---

lib/OnboardingMessageProvider.jsm

I was shallow copying `msg` before and so it was changing `ONBOARDING_MESSAGES` and then the next time we looked up the strings and passed them into `L10N` they no longer had `string_id` and the function would throw, giving us an error.
I'm deep copying now - any more elegant solutions for deep copying the entire nested object @k88hudson ?

Fix Bug 1495546 - Localization fails in OnboardingMessageProvider if we've already localized strings before

---

content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
docs/v2-system-addon/data_events.md
lib/TelemetryFeed.jsm
test/unit/lib/TelemetryFeed.test.js

Highlights of this patch:
* Get rid of the `includeClientID` flag for AS router metrics
* Add two new metrics policies for Snippets and Onboarding, respectively

Fix Bug 1485069 - Add client_id for Snippets reporting

---

lib/ActivityStream.jsm
lib/PrefsFeed.jsm

wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1495517 to land in central

Backport Bug 1495517 - Migrate improvesearch.topSiteSearchShortcuts pref from ActivityStream.jsm to firefox.js r=k88hudson

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/components/Button/_Button.scss
content-src/asrouter/components/SnippetBase/SnippetBase.jsx
content-src/asrouter/components/SnippetBase/_SnippetBase.scss
content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
content-src/asrouter/templates/NewsletterSnippet/_NewsletterSnippet.scss
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/_SimpleSnippet.scss
content-src/styles/_activity-stream.scss
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/constants.js
test/unit/asrouter/templates/NewsletterSnippet.test.jsx

Working demo https://snippets-admin.moz.works/show/7894/
In order to test this 
```javascript
Services.prefs.setStringPref(
"browser.newtab.activity-stream.asrouter.whitelistHosts",
"[\"gist.githubusercontent.com\"]"
);
```
Restart the browser.
Then navigate to `about:newtab?endpoint=https://gist.githubusercontent.com/piatra/70234f08696c0a0509d7ba5568cd830f/raw/f5bdddaa700390532fb70cfc33348d42aef6ba4a/messages.json`
#1st Screen
#2nd Screen (after clicking the button)
Content isn't really important, just overall layout and function.

Fix Bug 1492086 - Add ASR Snippets Newsletter template

---

lib/ASRouter.jsm
test/unit/asrouter/MessageLoaderUtils.test.js

This PR adds an additional `telemetryInfo` parameter (introduced in [Bug 1433334](https://bugzilla.mozilla.org/1433334)) to the `AddonManager.getInstallForURL` call (and add an additional assertion in the existing unit test that cover that ActivityStream feature).
This additional `telemetryInfo` parameter ensures that we can store the original "installation source" and be able to include it into the addonsManager telemetry events related to the addons installed from ActivityStream (e.g. when the addon has been disable/enabled/uninstalled by the users, even across Firefox restarts).

Fix Bug 1496167 - Add installation source to addons installed from activitystream

---

content-src/asrouter/components/SnippetBase/SnippetBase.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json

Added `block_button_text` as alt text to the dismiss button. The translation and english fallback should come from snippets endpoint.
@glogiotatidis r?

Fix Bug 1477633 - Add tooltip text to dismiss button

---

common/Actions.jsm
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

Preview snippet to test https://gist.githubusercontent.com/piatra/d45d10f1aee80a5ac46c9a664cab1f44/raw/0214adecb154d3004c699c59266fda1bc9033d28/gistfile1.txt (clicking the button should open a page with a "register for firefox accounts" form).

Fix Bug 1496352 - Add SHOW_FIREFOX_ACCOUTS Router action

---

lib/TopStoriesFeed.jsm
test/unit/lib/TopStoriesFeed.test.js

Merge after https://bugzilla.mozilla.org/show_bug.cgi?id=1493041  has landed on beta.

[Uplift backport] Bug 1493041 - Topstories feed uninit can remove idle-daily observer before init has a chance to add it 

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

The rename in https://github.com/mozilla/activity-stream/commit/47f11743abcea792122a5a1d24e5b6dd370e6cc3 broke CFR addon installs. 
INSTALL_ADDON_FROM_URL was not used by snippets and the message provider was not updated.
I looked into adding a mochitest for end to end testing of the install flow but because of 
[fetchLatestAddonVersion](https://github.com/mozilla/activity-stream/blob/d2725fa471dbd348987e40782e13e0226ff57148/lib/CFRPageActions.jsm#L407) making a network request this is not possible now. Maybe by mocking the url through `forceRecommendation` I'll look into this separately.

Fix Bug 1497261 - Revert parameter rename

---

lib/ActivityStream.jsm

This is wanted in 63, I think this is all there is to the fix, right @Mardak

Fix Bug 1495768 - add Amazon to Search Shortcuts for Austria

---

lib/PlacesFeed.jsm
test/unit/lib/PlacesFeed.test.js
test/unit/unit-entry.js

Blocked on Bug 1426245 landing in central first. https://bugzilla.mozilla.org/show_bug.cgi?id=1426245
This backports the changes from PlacesFeed.jsm, but also fixes the tests, and adds 2 trailing commas to PlacesFeed.jsm, just as heads up for next export.
I'm assuming similar changes are to come with `onItemRemoved` so we might want to refactor PlacesFeed.jsm at some point when BookmarksObserver won't be valid anymore.

Backport - Replace nsINavBookmarksService::onItemAdded with 'page-bookmarked'

---

content-src/asrouter/docs/targeting-attributes.md
lib/ASRouterTargeting.jsm
lib/CFRMessageProvider.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/CFRMessageProvider.test.js

Using targeting was the easiest way to do this - alternatively we can just not enable all of CFR if this pref is false. But CFR may not be just add-ons, so it might not be good to disable it altogether based off this pref. 
To test this, you can just make sure you see a recommendation, and then flip the pref to false and ensure the recommendation is not shown. Chances are on new profiles the pref doesn't exist (that's why we fallback to `true`), so you may need to create the pref

Fix Bug 1494778 - CFR should respect the xpinstall.enabled pref

---

content-src/components/Sections/_Sections.scss

When compact cards were added and we fit 4 cards on a row, this needed to be adjusted for a 4th child
Before:
After:

Fix Bug 1485633 - Context menu is displayed wrong for the last Highlight from a row

---

content-src/components/TopSites/_TopSites.scss

this was bothering me
Before:
After:

Fix Bug 1484249 - Remove horizontal scrollbar in modal

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/components/RichText/RichText.jsx
content-src/asrouter/components/SnippetBase/SnippetBase.jsx
content-src/asrouter/rich-text-strings.js
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
content-src/lib/snippets.js
lib/ASRouter.jsm
lib/ASRouterPreferences.jsm
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/asrouter/RichText.test.jsx
test/unit/asrouter/SnippetsTestMessageProvider.test.js
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/SubmitFormSnippet.test.jsx

This patch refactors the richtext stuff to a new `RichText` component and adds some test content that is only available when `asrouter.devtoolsEnabled` is on.
To test, starting with default settings (`./mach run --temp-profile`) 
1. Ensure you still see legacy snippets as normal on `about:newtab`
2. Set `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` to `true`
3. Open `about:newtab#asrouter`
4. Ensure you don’t see legacy snippets
5. Ensure you see `snippets_local_testing` in the list of providers; try testing each of the test snippets.

Snippets RichText component and debug content

---

content-src/asrouter/components/ModalOverlay/_ModalOverlay.scss

Fix Bug 1499068 - Adjust modal button to have variable width

---

lib/ASRouterTargeting.jsm
lib/ManualMigration.jsm
lib/SnippetsFeed.jsm
test/browser/browser_asrouter_targeting.js
test/unit/lib/ManualMigration.test.js
test/unit/lib/SnippetsFeed.test.js

r?@piatra Took a while to finally track down why tests weren't passing and turns out `await onAction` wasn't actually waiting because it wasn't returning a Promise. I also simplified getting a custom test value by optionally stashing a `fakeProfileAge.created`.
https://hg.mozilla.org/mozilla-central/rev/3edf43a3f1a4

Port Bug 1497960: Make ProfileAge return the same instances for the same profile directory and preload times.json to avoid data races. r=janerik

---

content-src/asrouter/components/SnippetBase/_SnippetBase.scss

Fix Bug 1496785 - change snippet links to bold weight in Dark theme

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/components/Button/_Button.scss
content-src/asrouter/components/RichText/RichText.jsx
content-src/asrouter/rich-text-strings.js
content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.jsx
content-src/asrouter/templates/SendToDeviceSnippet/isEmailOrPhoneNumber.js
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
content-src/asrouter/templates/SubmitFormSnippet/_SubmitFormSnippet.scss
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/SnippetsTestMessageProvider.test.js
test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx
test/unit/asrouter/templates/SubmitFormSnippet.test.jsx
test/unit/asrouter/templates/isEmailOrPhoneNumber.test.js

Adds the Send to Device template. Also fixes:
* Privacy links should not auto-block
* Minor style issues (wrong border colour on buttons)
[References]
https://snippets-admin.moz.works/show/7924/
https://snippets-admin.moz.works/show/7991/
1. Set `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` to `true` to enable test data.
2. Open `about:newtab#asrouter`
3. Trigger the `SNIPPETS_SEND_TO_DEVICE_TEST` snippet
4. Try clicking on the first button to open the form.
5. Try clicking on the “Learn more” link in the disclaimer text. Note that it should not block/close the snippet and open in a new window.
6. Try entering some invalid text (not a phone number) such as “test123”. Attempt to submit; you should see an error message.
7. Change the text to a valid phone number (example: …

Bug 1492088 - Add ASR Send to device template

---

content-src/asrouter/docs/targeting-attributes.md
lib/ASRouterTargeting.jsm
test/browser/browser_asrouter_targeting.js
test/unit/unit-entry.js

This is the relevant idl file. https://searchfox.org/mozilla-central/source/toolkit/mozapps/update/nsIUpdateService.idl#246
To test I just used the `isMatch` method from ASRouterTargeting. Not sure if this can be automated since it makes a network request.
edit: need to update the docs.

Fix Bug 1492853 - Add isUpdated targeting parameter

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/Base/Base.jsx
lib/ASRouter.jsm
lib/ASRouterPreferences.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/unit-entry.js

A big part of this change is indentation so I would recommending viewing this with https://github.com/mozilla/activity-stream/pull/4508/files?w=1
This patch adds some additional utilities to `about:newtab#asrouter`, including
* A way to enable/disable providers via the UI;
* A way to filter the messages shown by provider;
* A way to reset the preference via the UI
* Turn on devtools by setting `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` to `true`
* Visit `about:newtab#asrouter`
* Try enabling/disabling different providers; see if their messages show up/disappear on the page
* Try the messages filter dropdown under the "Messages" section
* After changing some settings, try the "Restore defaults" button and ensure …

Add enable/disable/reset devtools for ASRouter

---

lib/ASRouterPreferences.jsm
lib/ActivityStream.jsm
test/unit/asrouter/ASRouterPreferences.test.js

No UI for this yet. To test:
1. Ensure `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` is on
2. about about:newtab#asrouter
3. Ensure `browser.newtabpage.activity-stream.asrouter.userprefs.cfr` is true by default in about:config
4. Ensure 'cfr' shows up in the dropdown menu for messages on the debug page
5. set `browser.newtabpage.activity-stream.asrouter.userprefs.cfr` to false
6. Ensure 'cfr' is no longer in the dropdown for messages on the debug page

Bug 1500518 - Add user preference for CFR

---

docs/v2-system-addon/1.GETTING_STARTED.md

From inspecting the commands in the manifest it seems like the compiled AS folder is being generated in a different location now.

Folder path tweak for docs

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss
lib/ASRouter.jsm
lib/ASRouterPreferences.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterPreferences.test.js

Adds support for setting user preferences via UI. Test by visiting `about:newtab#asrouter` with `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` on.

(nobug) Add more support for setting user preferences in ASR devtools

---

aboutNewTabService.js
test/browser/browser_packaged_as_locales.js
test/xpcshell/test_AboutNewTabService.js

Waiting on TC to see it green. Also the backport failed eslint so there's an extra commit there.

Backport Bug 1472212 - Update URLs to include the noscripts version in xpcshell and browser tests for newtab. r=Mardak

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm

I added `|| "undefined"` because targeting parameters typos wouldn't output anything in the Result field.

(nobug): Report JEXL syntax errors in ASRouter Admin

---

package-lock.json

1.2.0 has a reported security vulnerability
See: https://nvd.nist.gov/vuln/detail/CVE-2018-16469

Bug 1503897 - Upgrade merge sub-dependency to 1.2.1

---

content-src/components/TopSites/TopSite.jsx
jar.mn
test/unit/content-src/components/TopSites.test.jsx

r?@sarracini Package the files that are already there with jar.mn. Also fixed a react dev warning that I saw when making sure noscripts loaded:
```
Warning: Received `false` for a non-boolean attribute `href`.
If you want to write it to the DOM, pass a string instead: href="false" or href={value.toString()}.
If you used to conditionally omit it with href={condition && value}, pass href={condition ? value : undefined} instead.
in a (created by TopSiteLink)
in div (created by TopSiteLink)
…```

Fix Bug 1504754 - Debug noscripts version of new tab page need to be packaged

---

content-src/asrouter/README.md
content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss
content-src/lib/snippets.js
lib/ASRouterPreferences.jsm
lib/ActivityStream.jsm
lib/CFRMessageProvider.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/asrouter/CFRMessageProvider.test.js
test/unit/content-src/lib/snippets.test.js
test/unit/unit-entry.js

This patch moves our various configurations to a pref branch for ASR rather than a single prefs to support the shield roll-out mechanism. It also turns on snippets in nightly and CFR for all channels.
Please test with the following steps:
1. With a temp-profile/new profile, turn on the devtoolsEnabled pref and visit about:newtab#asrouter
2. Ensure CFR is on by default and the 3-lifetime cap variant is the default
3. Try turning different providers on/off.
4. With ASR snippets disabled, ensure legacy snippets are properly loaded in about:newtab by opening the console.
5. With ASR snippets enabled, ensure you see actual content on new tab pages.

Move to pref branch for ASR

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js

To test this: 
1. Open about:newtab#asrouter
2. Show snippets test provider messages
3. click "Show" next to `SIMPLE_TEST_1_SAME_CAMPAIGN`
4. On the actual snippet that appears, click the x to close/block the snippet
5. Ensure that BOTH `SIMPLE_TEST_1_SAME_CAMPAIGN` and `SIMPLE_TEST_1` are now blocked
6. Restart, ensure they are still blocked
7. Try unblocking one, ensure both are unblocked

Bug 1506225  - Support blocking by campaign

---

content-src/components/Sections/Sections.jsx

Changed these to be spans. We still want background-image property because we use `-moz-context-properties` to set the color.
Suggestion from https://bugzilla.mozilla.org/show_bug.cgi?id=1506592#c13
Before:

Fix Bug 1506592 - Broken image icon for empty sections

---

lib/PersonalityProvider.jsm
test/unit/lib/FilterAdult.test.js
test/unit/lib/PersistentCache.test.js
test/unit/lib/PersonalityProvider.test.js
test/unit/lib/TopStoriesFeed.test.js
test/unit/unit-entry.js

To test:
1. Make a new profile, but don't log into it.
2. Go into that profile's dir, and paste in a places.sqlite from an existing profile to get a good chunk of history to work with.
3. Create a user.js file with this in it:
```
user_pref("services.settings.server", "https://kinto.dev.mozaws.net/v1");
user_pref("services.settings.verify_signature", false);
```
4. Now run the profile.
5. In the browser debugger, paste in `Services.obs.notifyObservers(null, "idle-daily");`
6. Make an insignificant change to the pref browser.newtabpage.activity-stream.feeds.section.topstories.options to trigger a fresh cache.
Expected: you should now be seeing personalized stories on about:home.

 Fixes bug 1507973 - v2 with attachments for personality provider in activity stream.

---

test/unit/content-src/components/ASRouterAdmin.test.jsx

A few unit tests mostly checking that providers render and the buttons block and preview.
I think it's useful to bootstrap the file to make it easier to add tests in the future.

(nobug): Add unit tests for ASRouterAdmin

---

package-lock.json

Small change that shows up on a new npm install (npm v.6.4.1)

(nobug) package-lock update to https link

---

content-src/asrouter/components/SnippetBase/_SnippetBase.scss
content-src/asrouter/templates/EOYSnippet/EOYSnippet.jsx
content-src/asrouter/templates/EOYSnippet/_EOYSnippet.scss
content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.jsx
content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.jsx
content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/templates/EOYSnippet.test.jsx
test/unit/asrouter/templates/FXASignupSnippet.test.jsx
test/unit/asrouter/templates/NewsletterSnippet.test.jsx
test/unit/asrouter/templates/SendToDeviceSnippet.test.jsx

This addresses 1509810 and 1509851.
I also updated the tests to create assertions out of every schema property with a `default` field so that we don't miss them anymore. Meanwhile I found some minor inconsistencies which I also updated.
Regarding `donation_form_url` it looks like setting `form_action` to a URL with GET parameters will drop those parameters on form submit. Workaround was to convert those parameters to `input[type=hidden]`. This needs an update on the snippets side: the url needs to contain a `?` so we know where the paramters begin in the url. This doesn't seem to be an issue and support in the legacy implementation as well https://github.com/mozmeao/snippets/blob/94b18ab63703ad339b24db206e065061aaf0b30f/activity-stream/mofo-eoy-2017.html#L293 cc @glogiotatidis

Fix Bug 1509810 - Add missing defaults for snippet templates

---

aboutNewTabService.js
bin/render-activity-stream-html.js
test/xpcshell/test_AboutNewTabService.js

r?@k88hudson Instead of packaging the file that was being built, don't bother building a -debug-noscripts.html because it's the same as -noscripts.html files that are already packaged and localized. Turns out the dynamic script loader already supports using -dev scripts, so we just needed to fix the url being loaded.
Eventually when privileged content process is the only way to load new tab, a bit of code can be simplified and cleaned up. But until then, we have the static debug with-scripts and dynamic debug no-scripts.

Fix Bug 1504754 - Debug noscripts version of new tab page fail to load

---

content-src/components/CollapsibleSection/CollapsibleSection.jsx

This removes the use of React's onMouseEnter/onMouseLeave, which causes React to add a document-level mouseenter/mouseleave/mousemove handler. This handler causes any mouse movement to trigger an event (which React eventually throws away).
This patch instead manually creates a listener only for the elements we care about.

Fix Bug 1503632, reduce CPU usage when moving mouse on newtab

---

lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/templates/OnboardingMessage.test.jsx
test/unit/unit-entry.js

In order to test this go to `about:newtab#asrouter` and use the force attribution button at the button of the page. After that navigate to `about:welcome` and you should get the onboarding message that prompts you to install the addon. You can change it to test with a different addon: you can use the following value for the `content` field (again on the `about:newtab#asrouter` page) `jid1-MnnxcxisBPnSXQ@jetpack` and this should force Privacy Badger as a message.
Requires #4587 to land first.

Fix Bug 1511165 - about:welcome addon card on windows says "addon name"

---

content-src/asrouter/components/SnippetBase/SnippetBase.jsx
test/unit/asrouter/templates/SubmitFormSnippet.test.jsx

In the previous snippets implementation the dismiss button had the same behavior as the block button and sent the same telemetry ping. We took a decision to make `dismiss` only remove the snippet for a particular impression (but not block it so that it might show up later) but we never had a different telemetry event for it.

Fix Bug 1515026 - Send telemetry ping for dismiss events

---

content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss

r? @ScottDowne or @gvn 
Before:
After:

fix(styles): Remove title alignment that affect other sections for now

---

content-src/components/Search/_Search.scss

Bug 1517713 - [RTL] Localized "Search the Web" string is LTR'd

---

content-src/components/Search/Search.jsx
content-src/components/Search/_Search.scss

Before:
After:
With hand-off disabled:

Fix Bug 1517745 - Remove arrow from search bar when hand-off enabled

---

mochitest.sh

Directly fixing test failures (turning off `handoffToAwesomebar` pref in `browser.ini`s) as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1516272 export, so probably don't want to merge this yet…

Fix Bug 1517327 - Search telemetry failures not caught by taskcluster

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/MessageLoaderUtils.test.js

We store `messageBlockList` in indexedDB. Every time AS initializes (and in some other cases) we re-read the `exclude` list and `concat` to the `messageBlockList` without checking if we're duplicating.

(nobug) - Prevent duplicate ids in the messageBlockList

---

test/unit/common/Reducers.test.js

The test is not affected because [0] on `SNIPPETS_RESET` the reducer always returns `INITIAL_STATE.Snippets` regardless of the initial state passed in the args.
[0] https://github.com/mozilla/activity-stream/blob/c90b29e394d1977121d031cc72652382ff9e29d6/common/Reducers.jsm#L420-L421

Bug 1517525 - Spelling issue for Reducers.test.js initial state

---

lib/AboutPreferences.jsm
locales-src/en-US/strings.properties
test/unit/lib/AboutPreferences.test.js

In order to test this 
* set `browser.newtabpage.activity-stream.discoverystream.config` to have `enable` set to true
* navigate to `about:preferences#home`

Bug 1515078 - Add opt out UX in about:preferences for Pocket Newtab

---

lib/ASRouter.jsm
lib/ASRouterTriggerListeners.jsm
test/unit/asrouter/ASRouterTriggerListeners.test.js

This should help us ensure we're not trying to add that listener too early in the startup process. 
I have a try run https://treeherder.mozilla.org/#/jobs?repo=try&revision=942859ad6573d7f6c7e203a8004685de685f0f8c&selectedJob=213978989 that shows a failure linking to the same issue but I think it's missclassified.
Checking the failure logs shows
```
TEST-UNEXPECTED-FAIL | browser/base/content/test/plugins/browser_CTP_drag_drop.js | leaked 1 window(s) until shutdown [url = http://127.0.0.1:8888/browser/browser/base/content/test/plugins/plugin_test.html]
```
This does not correspond to the failures associated with this bug(s) it should specifically mention `win.gBrowser is undefined;`

Fix Bug 1509755 - Wait for browser initialization to finish before adding CFR trigger listeners

---

content-src/components/ASRouterAdmin/ASRouterAdmin.scss

Test plan:
1. Ensure you have devtools enabled via [these instructions](https://docs.google.com/document/d/1iySmNA2tBl3ApLuJtP7UBlPwNx9sH1SmK-jG6exvMQ0/edit#heading=h.3zj0kjmo4xno)
2. Make your window size ~500px wide
3. Visit about:newtab#devtools-ds. Ensure you can use the enabled/disabled checkbox on the DiscoveryStream section and that devtools are no longer covered by the sidebar

Bug 1520259 - Add space for devtools fixed sidebar

---

content-src/asrouter/templates/ReturnToAMO/_ReturnToAMO.scss

Details about the changes are [in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1513906)
Note: RTAMO is currently disabled via pref.
To trigger the message:
* set `browser.newtabpage.activity-stream.asrouter.providers.onboarding` to `{"id":"onboarding","type":"local","localProvider":"OnboardingMessageProvider","enabled":true,"exclude":[""]}`
* navigate to `about:newtab#devtools-targeting` and click the `Force Attribution` button
* navigate to `about:welcome` and you will get the message

Bug 1513906 - Polish ReturnToAMO screen

---

content-src/components/ASRouterAdmin/ASRouterAdmin.scss

After
Before
And doesn't regress light theme

(nobug) - Improve ASRouterAdmin color contrast in dark theme

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/styles/_variables.scss
test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx

This stands up a basic list component for DiscoveryStream.
How to test:
* go to about:config
* search for stream.config
* set that preference to {"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=control"}
* open a new tab
The list is the "Recommended by Pocket" is the thing to look at.  
Known bugs are already captured as dependents of the ds-list-component bug: https://bugzilla.mozilla.org/showdependencytree.cgi?id=1514020&hide_resolved=0
@ScottDowne A review would be great.  I'll wait for you to land bug 1519484 before I land this so that TopSites doesn't have a weird intermediate state due to me adding the 936px width constraint here.

Bug 1519766 - standup list component for DiscoveryStream

---

content-src/components/Search/Search.jsx
lib/PlacesFeed.jsm
test/unit/content-src/components/Search.test.jsx
test/unit/lib/PlacesFeed.test.js

To test:
* start typing on the in-content search, hand-off should happen and in-content search should disappear
* hit the "ESC" key. the in-content search should re-appear

Bug 1519141 - "Esc" should make the in-content search re-appear.

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
test/unit/content-src/components/DiscoveryStreamBase.test.jsx

r?@ScottDowne This assumes an optional `styles` property on a component.
If you set `browser.newtabpage.activity-stream.discoverystream.config` to
```
{"enabled":true,"layout_endpoint":"data:,%7B%22layout%22%3A%5B%7B%22width%22%3A12%2C%22components%22%3A%5B%7B%22styles%22%3A%7B%22%22%3A%22background%3Aurl(https%3A%2F%2Fmozilla.org)%3Btransition%3Abackground-color%201s%22%2C%22%3Ahover%22%3A%22background-color%3Argba(0%2C0%2C255%2C.5)%22%2C%22%7B%7D%22%3A%22top%3A0%22%2C%22*%22%3A%22color%3Ared%22%2C%22p%22%3A%22transform%3Arotate(180deg)%3Btext-transform%3Auppercase%22%2C%22.ds-header%3A%3Abefore%2Cp%3Anth-child(3)%3A%3Abefore%22%3A%22content%3A'%F0%9F%91%8D'%22%7D%2C%22type%22%3A%22Hero%22%2C%22header%22%3A%7B%22title%22%3A%22Recommended%20by%20Pocket%22%7D%2C%22feed%22%3A%7B%22url%22%3A% …
```

Bug 1513311 - Allow remote custom CSS to adjust section and/or card styles

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/lib/selectLayoutRender.js

To test:
1. set your browser.newtabpage.activity-stream.discoverystream.config pref to `{"enabled":true,"layout_endpoint":"https://gist.githubusercontent.com/ScottDowne/1be633daea7d1ce65a8ca903a3be9ae9/raw/3d51663327126879f6fa1c6b3e7730e7805c9e1e/spocs"}`
2. Load a new tab, take note of the 3rd card in both the card grid and hero grid.
3. Refresh a couple times, noting the 3rd card in each refresh.
Expected: The third position on each hero and card component has a 50% chance to be a spoc.
There are 4 combinations based on the rolls you get.
1. where both rolls fail, and in this case you see the same card in both positions in both components because they share the same feed.
2. where the card component rolls a spoc and the hero does not.
3. where hero has a spoc and card doesn't.
4. And …

bug 1520893 - Display spocs

---

lib/AboutPreferences.jsm
test/unit/lib/AboutPreferences.test.js

[`"individual-opt-out"`](https://searchfox.org/mozilla-central/rev/bee8cf15c901b9f4b0c074c9977da4bbebc506e3/toolkit/components/normandy/content/about-studies/about-studies.js#189) is the telemetry event name used when unenrolling from an experiment on the `about:studies` page. We could change that to something specific to `about:preferences` if we're interested in the data.
I was not familiar with how Normandy chooses users and toggles preferences. Specifically what happens if we roll out from 1% to 5% but before the second rollout some users voluntarily leave the experiment.
> because of the sampling characteristics of Normandy, if you increase from 1% to 5%, the additional 4% are guaranteed to be distinct from the original 1%

Bug 1515078 - Use PreferenceExperiments API to unenroll from Pocket Newtab experiment

---

content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss

How to test:
* In a clean profile, set your computer's OS to use dark theme (on Mac, this is System Preferences -> General).
* Open a new tab
* For the pocket cards, the title and excepts should be a legible light grey
Then, to ensure that this fix hasn't regressed the original thing it was intended to address.
* Reset your computer's OS theme use a light theme
* go to about:config
* search for stream.config
* set that preference to {"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}
* open a new tab
Verify that the text in the title of the Trending Stories list items is #0C0C0D

Bug 1520854 - make text color in AS work again in dark theme

---

lib/ActivityStream.jsm

`dev-test-1` is intended just for devs, so `control` feels like a sensible default.

NOBUG – Use `control` layout as default

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
content-src/components/DiscoveryStreamComponents/List/_List.scss

Looking for a quick-turnaround review so I can get this (layout-breaking) bug in before the impending export and tidy up individual bits of the lists later.  Whoever wants this, feel free to take it!
How to test:
* go to about:config
* search for stream.config
* set that preference to {"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}
* open a new tab
The various trending stories should all be appropriate widths.
Things to note:
* some horizontal rules above or below individual stories may be incorrectly there or incorrectly missing.  https://bugzilla.mozilla.org/show_bug.cgi?id=1521119 has been filed.
Known bugs are already captured as dependents of the ds-list-component bug: …

Bug 1519775 - Make one and two-column lists work

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/components/DiscoveryStreamComponents/Navigation/Navigation.jsx
content-src/components/DiscoveryStreamComponents/Navigation/_Navigation.scss
content-src/components/DiscoveryStreamComponents/SectionTitle/SectionTitle.jsx
content-src/components/DiscoveryStreamComponents/SectionTitle/_SectionTitle.scss
content-src/styles/_activity-stream.scss

I've been testing with this: https://gist.githubusercontent.com/ScottDowne/84457bf09597afe67926cca558f20d22/raw/e42431c06c21867388468e8ab734b394c32f9a77/title-nav
changing out things as I need.

Bug 1519243 - Split title component into two, the new one is navigation

---

content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss

Testing instructions.
1. Ensure the new tab is the regular version by default.
2. In `about:config`, change  `browser.newtabpage.activity-stream.discoverystream.config` to be `{"enabled":true,"layout_endpoint":"https://gist.githubusercontent.com/ScottDowne/e8ad372bc57ed3feba0bf02f89473fc9/raw/74daf564fea3e41e1ef24c39b18690623679182b/mrspocs"}`
3. Ensure new tab is rendering a bunch of spocs with the text "Sponsored by..." in a few. Specifically, it's in the last two on the card grid, and the first and last on the hero.
4. Reset the pref, ensure everything is back to normal.

Bug 1520898 - Display spoc context.

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx

To test:
1. Ensure the new tab is the regular version by default.
2. In `about:config`, change  `browser.newtabpage.activity-stream.discoverystream.config` to be `{"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}`
3. Ensure new tab is rendering components with readable headers for List, Hero, and top sites.
4. Reset the pref, ensure everything is back to normal.

Bug 1521615 - Dry out header css for reusage usage with top sites.

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss

This is on top of #4698 so look at https://github.com/mozilla/activity-stream/commit/ee3568cb140997bd82b1ae1dfb32e8ae0994c01a . r?@ScottDowne or @dmose 
No images and with images (+ numbers)

Bug 1519774 - implement lists without images

---

content-src/components/DiscoveryStreamComponents/List/_List.scss

r?@piatra or @dmose 
Before
After

Bug 1521891 - portrait images in list items should correctly cover 72x72 box

---

content-src/components/DiscoveryStreamComponents/List/_List.scss

This is on top of #4702. r?@piatra or @dmose 
Before:
After:
And just to see the non-images not affected.. all together!

Bug 1521888 - add padding between ds-list-item-text and the image to the right, as per spec

---

content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/styles/_variables.scss

How to test:
* go to about:config
* search for stream.config
* set that preference to {"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}
* open a new tab
Inspect the long horizontal rule at the top of the one of the list.  Also inspect the shorter line (which is implemented as a border) above one of the .ds-items.  Both should be 1 pixel thick, and the color of the lines should be #D7D7DB (which is the same as rgb(215, 215, 219)).

Bug 1521886 - update thicknesss/color of ds-list horizontal rules

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

Note: if there is a network connection issue and install fails the message is not blocked. I think this behavior makes sense, the user can retry as opposed to now when the message goes away forever after the first click regardless of outcome.
Testing:
1. Enable RTAMO steps here
* enable `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled`
* set `browser.newtabpage.activity-stream.asrouter.providers.onboarding` to `{"id":"onboarding","type":"local","localProvider":"OnboardingMessageProvider","enabled":true,"exclude":[]}`
* navigate to `about:newtab#devtools-targeting` and scroll to the bottom
* click `Force attribution`
* navigate to `about:welcome` and confirm that the RTAMO message is shown
2. Install the addon and ensure the switch to the 3 onboarding messages happens after …

Bug 1519342 - Show Onboarding card after RTAMO addon install

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss

2/3 Hero Before
2/3 Hero After
Hero Before
Hero After
There are changes to the Card component as well but it's very hard to notice the difference with a side by side photo, it's easier to toggle the property when reviewing and notice the difference. Example:
Before
After

(nobug) - Center Card images

---

content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/HorizontalRule/HorizontalRule.jsx
content-src/components/DiscoveryStreamComponents/HorizontalRule/_HorizontalRule.scss

Sorry had to do this, it was hurting my eyes 😜 
Reference design: https://www.figma.com/file/B1eynmsVDYKdpDWZhP8xYBWq/User-Research-Layout-Prototypes
Test steps:
1. Set `browser.newtabpage.activity-stream.discoverystream.config` pref to: `
{"enabled":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}`
2. Check to make sure the horizontal line under the "Best of the Web" heading at the top is a light grey colour and 2px high.

Bug 1522233 - Add styling for HorizonalRule

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/styles/_mixins.scss
content-src/styles/_theme.scss
test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx

The duplication was hurting my eyes ;) r? @k88hudson Not sure if it's better as a mixin or a css class that each div additionally sets.. Also, turns out img with no image has some default border that can't be overridden??
Before
After

Bug 1519773 - implement image placeholder style for list items

---

content-src/components/Base/Base.jsx
content-src/components/ErrorBoundary/_ErrorBoundary.scss

Adds a simple error boundary for DiscoveryStream.
To test this, you will need to apply this patch:
```diff
diff --git a/content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx b/content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
index 6d946618..cc13d287 100644
--- a/content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
+++ b/content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
@@ -193,6 +193,7 @@ export class _DiscoveryStreamBase extends React.PureComponent {
}
render() {
+    throw new Error("Oops!");
const {layoutRender} = this.props.DiscoveryStream;
const styles = [];
return (
```
Ensure you can still use search with this error being thrown.

Bug 1520849 - Add error boundary for DiscoveryStream

---

lib/ActivityStream.jsm
lib/TopSitesFeed.jsm
test/browser/browser_topsites_contextMenu_options.js
test/browser/browser_topsites_section.js
test/unit/lib/TopSitesFeed.test.js

This enables @amazon in only 6 countries: DE, FR, GB, IT, JP, US
And it skips pinning a shortcut if it matches your current default search engine.
To verify, I fired up a local clean build and it only pinned Amazon instead of both Google and Amazon.

Bug 1520853 - update default search shortcuts config for Fx66

---

content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/lib/truncate-text.js
test/unit/content-src/lib/truncate-text.test.js

r?@piatra or @gvn Moved `truncateText` to its own file with tests. Made it slightly smarter about whitespace. Oh and switched to `…`

Bug 1521915 - replace DiscoveryStream three-period ellipses with a single unicode ellipsis character

---

content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss

r?@ScottDowne or @dmose Gets rid of the <b> and just sets the weight correctly on the div. Sets a fixed circle size.

Bug 1522865 - Adjust list title weight and numbered circle

---

lib/DiscoveryStreamFeed.jsm
test/unit/lib/DiscoveryStreamFeed.test.js

This patch adds a periodic check after every system tick (i.e. 5 minutes) and refactors some of the fetching into a single function. If the cache has expired, a refresh will occur.
I think this one is going to be hard to manually QA, but I'll try to think of something

Bug 1518261

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx

Based on the changes in https://app.swaggerhub.com/apis-docs/PocketNewTab/FirefoxHome/0.7

Bug 1523381 - Update max items for Pocket API endpoint 0.7

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/DSMessage/DSMessage.jsx
content-src/components/DiscoveryStreamComponents/DSMessage/_DSMessage.scss
content-src/styles/_activity-stream.scss

1. Set `browser.newtabpage.activity-stream.discoverystream.config` to `{"enabled":true,"show_spocs":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}`
2. Verify that Message component layout matches [comp](https://bug1524322.bmoattachments.org/attachment.cgi?id=9040475)

Bug 1524322 – Add Message component

---

test/browser/browser_discovery_styles.js

Against master to get other ports so automation is hopefully green. Locally looks good without seeing:
```
Entering test bound test_url_filtering
FATAL ERROR: Non-local network connections are disabled and a connection attempt to img-getpocket.cdn.mozilla.net (23.210.237.36) was made.
You should only access hostnames available via the test networking proxy (if running mochitests) or from a test-specific httpd.js server (if running xpcshell tests). Browser services should be disabled or redirected to a local server.
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
Exiting due to channel error.
…
ERROR TEST-UNEXPECTED-FAIL | browser/components/newtab/test/browser/browser_discovery_styles.js | application terminated with exit code 1
```

Port Bug 1525134 - Remove remote url from browser_discovery_styles.js r=andreio

---

lib/ActivityStream.jsm

This was regressed by #4754. Not sure if this needs a bug for uplift as we probably won't be uplifting the regressing bug (opt out handling for default on in nightly). But I suppose if we do uplift it, this should be uplifted with it together.
r?@k88hudson or @piatra Not sure if we should long term just make PrefsFeed track/dispatch any pref under the branch instead of only accepting those that were set by default… ?

Followup Bug 1521084 - Add default pref for impressions so it gets into redux state

---

lib/ActivityStream.jsm

The result of this patch should be that pocket is on by default for US/CA nightly users (not other channels). SPOCs should only be on by default in the US

Bug 1523703 - Pref on Pocket Newtab experience in Nightly for EN and CA

---

docs/v2-system-addon/data_events.md
lib/DiscoveryStreamFeed.jsm
test/unit/lib/DiscoveryStreamFeed.test.js

This adds various metrics to measure:
* the request time to fetch layout, spocs, and component feed on browser start-up and pref change. It won't record telemetry 1) if the cache is not expired, 2) subsequent loads after the first fetch  
* the total duration for the data completeness on browser start-up, which includes fetches to the endpoints, cache loads, and other data preparation
* cache age in second, which will be calculated based on the oldest `lastUpdated` in the cache file

Bug 1525391 - Collect telemetry for request time and cache age for Pocket

---

mochitest.sh

Checking taskcluster first… before r? @piatra or @k88hudson

(no bug) - Fix taskcluster by actually using packaged dist files for referenced test

---

lib/AboutPreferences.jsm
lib/DiscoveryStreamFeed.jsm
locales-src/en-US/strings.properties
test/unit/lib/AboutPreferences.test.js
test/unit/lib/DiscoveryStreamFeed.test.js

The issue I ran into while implementing this: 
tldr 2 checkboxes linking to the same preference (`showSponsored`) doesn't work.
Currently in `about:preferences` we hide the default prefs (via CSS) and append the experiment preferences. In this bug we add a checkbox (for the experiment prefs) to toggle spocs. This checkbox links to the same pref as TopStories section (`.showSponsored`) essentially having 2 checkboxes linking to the same preference, [which is not allowed](https://searchfox.org/mozilla-central/rev/5e3bffe964110b8d1885b4236b8abd5c94d8f609/toolkit/content/preferencesBindings.js#35).
And there doesn't seem to be a way to unlink a binding between an element and a pref so my solution was to just reload the page if the user leaves the experiment. 
I could also reach into …

Bug 1525366 - Show user preference for SPOCs if Discoverystream is on

---

content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss

Repro steps:
- Set `browser.newtabpage.activity-stream.discoverystream.config` to `{"enabled":true,"show_spocs":true,"layout_endpoint":"https://getpocket.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=dev-test-all"}`
- Compare Hero layouts in build to those in the [Figma](https://www.figma.com/file/HAk87Z6QBcu6YxBIoXN6LJcU/Firefox-Home-Modules?node-id=9%3A15)

Bug 1527397 – Refactor Hero's full width layout

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss

Testing enabled / opt-out:
1. Turn on new tab devtools: Set `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` to `true`.
2. Navigate to about:newtab#devtools-ds
3. Make sure the enabled checkbox is checked. Ensure discovery stream is visible on another tab.
4. Go to about:preferences#home and click the "Turn off discovery stream" button.
5. On about:newtab#devtools-ds, ensure that the enabled checkbox is now unchecked and you see the message "(Note: User has opted-out. Check this box to reset)" next to the checkbox.
6. Check the enabled box. Ensure that discovery stream now shows up again on a new tab page and the opt-out message has disappeared next to the checkbox.
Testing layout variants.
1. On about:newtab#devtools-ds, ensure discovery stream is enabled.
2. Check the …

Bug 1527980 - Add devtools for resetting and picking a layout variant

---

AboutNewTabService.jsm
NewTabComponents.manifest
components.conf
moz.build

https://hg.mozilla.org/mozilla-central/rev/8276ffc51b70
r?@ncloudioj Almost a plain copy but there was a rename frmo aboutNewTabService.js to AboutNewTabService.jsm. Also, needed to fix a couple lint errors.

 Port Bug 1524688: Part 61 - Convert AboutNewTabService to static registration. r=mconley

---

content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss

Fixes regression from https://github.com/mozilla/activity-stream/pull/4743/files#diff-cf1c6bc5f41ffdc4fb0575d6987f3311L77

Followup Bug 1522832 - Restore header-and-excerpt div

---

lib/CFRPageActions.jsm
test/unit/asrouter/CFRPageActions.test.js

You can't really test this from ASRouter debug because we check for `https`.
Besides the changes mentioned in the bug in order to implement `and going back to the page where they remember seeing it in order to recover the message` I added an extra field `retain` that delays deleting the recommendation by 1 navigation step.
Trigger the CFR message, navigate away and then click back.
The puzzle piece icon will still be present on the original page where the message was shown.
When navigating away a second time the recommendation will be permanently deleted.

Bug 1503693 - CFR button should persist in the URL bar until excused

---

lib/ASRouter.jsm

I don't think this ever worked:
When we're turning CFR off we call `cleanupImpressions` that calls `_cleanupImpressionsForItems` and updates the store with the new impression numbers.
When we block we never called `store.set` for impressions.

Bug 1529334 - Blocking/unblocking CFR doesn't clear impressions

---

lib/FaviconFeed.jsm

Will requires [Bug 1528704](https://bugzilla.mozilla.org/show_bug.cgi?id=1528704) to be taken into account by Remote Settings

Bug 1527945 - Disable sync on .get() for Tippytop

---

lib/CFRPageActions.jsm
test/unit/asrouter/CFRPageActions.test.js

Just renamed a few things so they more clearly indicate what's going on

Rename, split up functions for CFR

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/SafeAnchor/SafeAnchor.jsx

r?@k88hudson or @punamdahiya Tested with https://gist.githubusercontent.com/punamdahiya/44f78e2f338cbf95f5c28d31faed4639/raw/1c61974ca8ebd02431512d9425031e3a9c8e04f4/test-message-feed.json which has a "bill gates" article with javascript uri. Still sends telemetry that a click was attempted but doesn't open the link. Other links open fine with referrer:
And for spoc:
Also checked that links for navigation don't send referrer:

Bug 1533089 - HTTP Referer not set when clicking articles

---

lib/ActivityStream.jsm
lib/DiscoveryStreamFeed.jsm
test/browser/browser.ini
test/unit/lib/DiscoveryStreamFeed.test.js

r?@ScottDowne This adds a prefix check based on a string pref. I was thinking maybe just a plain boolean but that loses out on some flexibility if we ever needed to change the pref to something else for Release users…
Also, I guess we'll need to let people know to set the pref to something like "http" if using custom endpoints.

Bug 1521203 - Ensure appropriate resource requests for endpoints (layout, feed, spoc)

---

content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/styles/_mixins.scss

Repro: https://bugzilla.mozilla.org/show_bug.cgi?id=1534278#c0

Bug 1534278 –  Remove Extra borders on Hero cards on Dark theme

---

lib/CFRMessageProvider.jsm

When we fetch addon information [we only replace the install url](https://github.com/mozilla/activity-stream/blob/7b98ad991489a79e31c20378ea49eefe39737917/lib/OnboardingMessageProvider.jsm#L216). `amo_url` is used for the [`Learn More`](https://github.com/mozilla/activity-stream/blob/7b98ad991489a79e31c20378ea49eefe39737917/lib/CFRPageActions.jsm#L373) link in the dropdown panel.
AMO takes care of redirecting the user to the correct locale for the page based on the browser language settings. We just need to drop `en-US` from the URL.

Bug 1535464 - Update CFR addon Learn More links

---

content-src/asrouter/asrouter-content.jsx
content-src/lib/constants.js
test/unit/asrouter/asrouter-content.test.jsx

Based on Giorgos' request https://bugzilla.mozilla.org/show_bug.cgi?id=1510335#c4
Specify the theme variant in a query parameter `about:newtab?endpoint=...&theme=dark`
Initially tried using the `LightweightThemeManager.jsm` to pass down the theme variables but it turns out they [specify values using hex format](https://searchfox.org/mozilla-central/rev/4763b8d576ce52625d245d1ab6d9404ea025b026/browser/components/BrowserGlue.jsm#1089) but the content theme manager [expects rgba](https://searchfox.org/mozilla-central/rev/4763b8d576ce52625d245d1ab6d9404ea025b026/browser/base/content/contentTheme.js#145).  
None of the modules export functions to convert so I ended up adding the dark theme values we need to `./constants.js`
f?

Bug 1510335 - Set theme variant using query parameter

---

lib/ASRouterTriggerListeners.jsm
lib/CFRMessageProvider.jsm
test/unit/asrouter/ASRouterTriggerListeners.test.js
test/unit/asrouter/CFRMessageProvider.test.js

The way I'm handling redirects is to additionally check the original request host against the hosts defined in the message.
For example if `de.quora.com` fails the initial check but we initially navigated to `quora.com` then the check will now pass.
This doesn't mean that `bar.mozilla.com` will match for `mozilla.com` because we check that `(originalLocation !== location)` before trying the second lookup so it's only for redirects when this check would return true.

Bug 1530359 - Handle URL redirects for CFR triggers

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/MessageLoaderUtils.test.js
test/unit/content-src/components/ASRouterAdmin.test.jsx

This adds a new section in ASRouterAdmin where you can see all logged errors.
I've broken down the `_remoteLoader` to report missing messages, response failures or failures to parse json. Also all calls to `Cu.reportError` now go through the same function that captures them to be displayed in the admin panel.

Bug 1530714 - Report ASRouter errors in ASRouterAdmin

---

lib/ASRouter.jsm

I guess these steps can be put into a test document after they are verified to work. This one liner patch is required because we don't need to filter messages by locale like we originally planned.
**1. Setup the Remote Settings dev server with the CFR messages.**
Note that the dev server gets wiped every 24 hours so this will be have to be done once a day. You can check if there currently are any messages [here](https://kinto.dev.mozaws.net/v1//buckets/main/collections/cfr/records).
```bash
SERVER=https://kinto.dev.mozaws.net/v1
curl -X PUT ${SERVER}/accounts/devuser \
-d '{"data": {"password": "devpass"}}' \
-H 'Content-Type:application/json'
BASIC_AUTH=devuser:devpass
CID=cfr
curl -X PUT ${SERVER}/buckets/main/collections/${CID} \
-H 'Content-Type:application/json' \
-u ${BASIC_AUTH} …
```

How to setup Remote Settings CFR with dev server

---

karma.mc.config.js

I broke down our frontend code into 3 different patterns/categories and added thresholds for each of them.
```javascript
// All DS components
"content-src/components/DiscoveryStreamComponents/**/*.jsx"
// All asrouter components
"content-src/asrouter/**/*.jsx"
// Everything else
"content-src/components/**/*.jsx"
```
Coverage varies among these categories: asrouter baseline is now around 50% while some DS components have no tests making the baseline be 0.
The issue I ran into is that `karma-coverage-istanbul-reporter` does not implement a [`excludes` (or similar) filter for the `global`](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/df3d5df236e6abd18911a8c0783e6a11dfd98bf9/src/reporter.js#L125-L138) threshold declarations. This means that the `global` requirements …

Bug 1445352 - Add code coverage for .jsx files

---

.eslintrc.js
bin/strings-import.js
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
lib/PersonalityProvider.jsm
package-lock.json
package.json
ping-centre/PingCentre.jsm
test/browser/browser_activity_stream_strings.js
test/unit/ping-centre/PingCentre.test.js

There were 2 occurrences in `PingCentre` and 1 in `PersonalityProvider` that were an actual issue because that code runs in the main process. The content process occurrence is a false positive (the request object includes `credentials: omit`) and the others are just built time usages.
I've looked into `no-restricted-syntax` but it seems to completely forbid usage of certain features regardless of how they are used/their options.

(nobug) - Ensure fetch calls don't include credentials

---

content-src/asrouter/schemas/message-format.md
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/ASRouterTriggerListeners.jsm
lib/CFRMessageProvider.jsm
test/browser/browser_asrouter_cfr.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterTriggerListeners.test.js

Work on top of #4859, ~~which needs to land first.~~
One issue I ran into here: 
* ASRouterTargeting checks that the selected message has a `trigger param` that matches the `host`
* https://github.com/mozilla/activity-stream/compare/master...piatra:bug1533359?expand=1#diff-60f0c109d5c368ec6a6b11e2f311b3efR340
* For patterns this check will fail (we would compare `*.foo.com` with `bar.foo.com`) ~~because `MatchPattern` is not available to content~~
* This needs to be fixed when we want to land two different messages that use the same `frequentVisits` trigger
* - [x] create follow up bug -- https://bugzilla.mozilla.org/show_bug.cgi?id=1540182

Bug 1533359 - Targeting support for any subdomain

---

lib/PersistentCache.jsm
test/unit/lib/DiscoveryStreamFeed.test.js
test/unit/lib/PersistentCache.test.js

Bug 1540765 - PersistentCache should do JSON parsing off of the main thread

---

common/Actions.jsm
content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
docs/v2-system-addon/data_events.md
lib/TelemetryFeed.jsm
test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx
test/unit/lib/TelemetryFeed.test.js

This adds a new ping for content loaded event in Discovery Stream. Similar to impression pings, it relies on the page visibility, but not the individual visibility.
NB:
* This needs a data review
* Requires a schema change in both old&new data pipeline.

Bug 1530740 - Add loaded content ping for Discovery Stream

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/TopSites/SearchShortcutsForm.jsx
karma.mc.config.js
test/unit/content-src/components/DiscoveryStreamBase.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/CardGrid.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSMessage.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/HorizontalRule.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/Navigation.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/SafeAnchor.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/SectionTitle.test.jsx
test/unit/content-src/components/TopSites/SearchShortcutsForm.test.jsx

After: 
Added unit tests to bump our coverage to where the report is mostly green/gray making it easier to spot issues when trying to land new code.
ASRouterAdmin has a threshold set to 0 so adding new code there won't require any tests (that's the only one showing up in red).

Bug 1541359 - Chore: Increase our frontend code coverage

---

docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/MessageLoaderUtils.test.js

To manually test, you can configure CFR to use a Remote Settings loader and enable A-S telemetry and logging:
```javascript
Services.prefs.setStringPref("browser.newtabpage.activity-stream.asrouter.providers.cfr", JSON.stringify({"id":"cfr-remote","enabled":true,"type":"remote-settings","bucket":"cfr","frequency":{"custom":[{"period":"daily","cap":1}]},"categories":["cfrAddons","cfrFeatures"]}));
Services.prefs.setBoolPref("browser.newtabpage.activity-stream.telemetry", true);
Services.prefs.setBoolPref("browser.ping-centre.log", true);
```
Then restart the browser and look in the browser console for the "activity_stream_undesired_event" ping:
```
TELEMETRY PING: {"locale":"en-US","topic":"activity-stream","client_id":"3afcfb54-1735-0f4e-b77a-459a0cdd4a07","version":"68.0a1","release_chann …
```

Bug 1542792 - Add telemetry to record undesired events for CFR remote messages

---

content-src/components/CollapsibleSection/CollapsibleSection.jsx
content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamBase/_DiscoveryStreamBase.scss
content-src/components/DiscoveryStreamComponents/TopSites/TopSites.jsx
content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
content-src/components/SectionMenu/SectionMenu.jsx
content-src/components/TopSites/TopSites.jsx
lib/ActivityStream.jsm
test/unit/content-src/components/DiscoveryStreamBase.test.jsx

r? @punamdahiya This is on top of #4892 and should probably land after your #4886 to actually get top sites or pocket section to hide. But if it does land ahead of the preferences PR, it will still mostly work.
`basic` with collapsed top sites and showing menu for pocket
`66-release-2-above-2-below-1` with top sites menu open
---
Original:
@punamdahiya @k88hudson Looks like this approach of extracting the first `TopSites` and first `Message` works for various layout json. Still need to fix up styling and the section menu options.
66-release-2-above-2-below-1 (individual topsite row followed by individual message row)
dev-test-all (custom Message title, many "row"s with components scattered)
basic (single 12-width "row" with many components)
66-beta-2-complex (individual topsite row …

Bug 1535773 - Allow collapsing of top sites and the rest of Discovery Stream content

---

bin/render-activity-stream-html.js
locales-src/en-US/strings.properties

r? @piatra or @k88hudson We forgot to remove a couple of strings in https://github.com/mozilla/activity-stream/pull/4886#discussion_r274426369 Then I realized the export still contained strings for other locales that we no longer used, so fixed that too. A second `Object.assign({}, ...spread)` to combine arbitrary number of objects! 😉

(nobug) - Remove unused strings and exclude them from export

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss
content-src/components/ASRouterAdmin/SimpleHashRouter.jsx
content-src/components/Base/Base.jsx
content-src/styles/_activity-stream.scss
test/unit/content-src/components/ASRouterAdmin.test.jsx
test/unit/content-src/components/Base.test.jsx

This is needed so we can test the below-search-bar snippet.
This change ensures that a button shows up on ALL newtab pages when the `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` pref is on, but that the devtools are only actually loaded when it's clicked / when the URL has `#devtools` or `#asrouter in it`.
It also allows collapsing/hiding of the devtools.
QA steps:
- set your `browser.newtabpage.activity-stream.asrouter.providers.snippets` pref to `{"id":"snippets","enabled":true,"type":"remote","url":"https://snippets.cdn.mozilla.net/%STARTPAGE_VERSION%/%NAME%/%VERSION%/%APPBUILDID%/%BUILD_TARGET%/%LOCALE%/release/%OS_VERSION%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/","updateCycleInMs":14400000}`
- set your devtools pref to `false`. Ensure you see snippets but you don't see …

Bug 1544867 - Make AS devtools collapsible

---

content-src/components/ManualMigration/_ManualMigration.scss

Bug 1543723 - The import message icon is cut when the screen is horizontally resized to less than half screen

---

lib/ActivityStream.jsm
test/browser/browser_asrouter_cfr.js

I want to land this dummy provider to unblock landing code, later we can move the preference to `firefox.js`.
I added a mochitest to verify that provider id and pref id match. I didn't realize this is required. It's because we use the `provider.id` [to update the correct pref](https://github.com/mozilla/activity-stream/blob/8b20ec0902e5109303c2fe30a32fda7cf33d74e8/lib/ASRouterPreferences.jsm#L98).
Along with this I also created a script to automate publishing messages to kinto.
```javascript
// Make sure you are using the dev server
Services.prefs.setStringPref("services.settings.server", "https://kinto.dev.mozaws.net/v1");
Services.prefs.setBoolPref("services.settings.verify_signature", false);
```
It reads a message from a file from disk (`message.json`) and publishes it to kinto.
1. …

Bug 1543108 - Land a new provider for CFR FxA messages

---

content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss

Repro:
1. Load up `dev-test-all` layout.
2. Verify that bottom left and bottom right corners of images in bordered cards are not rounded.

Bug 1545455 - Bottom corners of images in bordered cards should be rounded

---

lib/TopSitesFeed.jsm
test/unit/lib/TopSitesFeed.test.js

r?@rlr https://hg.mozilla.org/mozilla-central/rev/aa8babb8b1ee

Port 1518545 - Remove the superfluous 'engine-current' Search Service observer topic in favour of 'engine-default'. r=daleharvey

---

bin/render-activity-stream-html.js

Finally figured this out while I was looking into pre-rendering stuff.
Test failures before were happening because our script injection was happening from an inline script that we render for the non-noscript version (which is currently on in release and asan builds but not nightly)
To manually test all variants, check:
* prerendered (turn ds off)
* noscripts on (default on nightly)
* noscripts off: set `browser.tabs.remote.separatePrivilegedContentProcess` to `false`
* `browser.newtabpage.activity-stream.debug` on
I'm a bit worried this could result in a perf hit since loading an external resource is likely to be a bit slower than inline, what do you think?
Tests: https://treeherder.mozilla.org/#/jobs?repo=try&revision=60d5046b3ccc0d8ea5a245ce8c82de691a45f582

Bug 1500061 - Switch to regular script tags, tighten CSP

---

content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
content-src/components/ASRouterAdmin/ASRouterAdmin.scss

At aaron's request, slight design change for the devtools button.

(nobug) Make button for collapsing devtools less prominent

---

content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/components/DiscoveryStreamComponents/TopSites/_TopSites.scss
content-src/styles/_mixins.scss
content-src/styles/_variables.scss

Testing:
- Set `browser.newtabpage.activity-stream.discoverystream.config` to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=dev-test-all"}`
- Tab through all items and confirm focus states match [spec](https://www.figma.com/file/0xZkmT86rSXbGRB4eIvrn0ts/New-Tab-Spec-for-Fx-v68?node-id=383%3A1)

Bug 1535448 - Handle focus state while navigating with keyboard

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/docs/targeting-attributes.md
content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
lib/ASRouterTargeting.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouterTargeting.test.js
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/OnboardingMessage.test.jsx

I this option, instead of using `bundled` I added `cards` as a subproperty of of a new `TRAILHEAD` message 
we could modify getBundled... to actually add them in

Trailhead basic flow with single message, no bundles

---

content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
data/trailhead.ftl
jar.mn
lib/OnboardingMessageProvider.jsm

r?@k88hudson or @rlr Dynamically adds `<link rel=localization>` to activate fluent-dom. Existing onboarding happens to not do anything with the data-l10n-id as nothing is watching for those attributes. Do we need/want to remove the links on unmount? I suppose dismissing with Start Browsing could just hide the modal. Although I suppose we don't want to unnecessarily keep re-adding the links?
FYI, the strings appear at `resource:///localization/en-US/trailhead.ftl` (note extra /)

Bug 1546683 - Use fluent to localize trailhead first run

---

content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
lib/OnboardingMessageProvider.jsm

r?@k88hudson This removes the `L10N.formatMessages` step for onboarding and duplicates the fluent loading for `OnboardingMessage`. Looking at the PR now, I suppose I could have left the messages untouched and grabbed string_id in the OnboardingMessage.jsx instead… Also, see related #4950.

(nobug) - Switch existing onboarding to use fluent-dom

---

content-src/asrouter/templates/Trailhead/Trailhead.jsx
content-src/asrouter/templates/Trailhead/Trailhead.scss
content-src/styles/_variables.scss
data/trailhead.ftl
lib/OnboardingMessageProvider.jsm

r?@k88hudson This updates to the finalized strings and adjusts the layout. This also adds the ONBOARDING_MESSAGES with at least the string portion. This could land without #4949 as it also removes the `L10N.formatMessages` step but it would break old onboarding.

(nobug) - Update finalized strings for layout and cards

---

common/Actions.jsm
lib/TelemetryFeed.jsm

This is to match the [name change](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/327/files) of the telemetry endpoint for SPOCS Fill.

Bug 1535717 - Update telemetry endpoint for Spocs Fill

---

common/Reducers.jsm
content-src/asrouter/schemas/panel/cfr-fxa-bookmark.schema.json
content-src/components/ASRouterAdmin/ASRouterAdmin.jsx
lib/ASRouter.jsm
lib/ASRouterPreferences.jsm
lib/BookmarkPanelHub.jsm
lib/PanelTestProvider.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/asrouter/PanelTestProvider.test.js
test/unit/asrouter/schemas/panel/cfr-fxa-bookmark.schema.test.js
test/unit/common/Reducers.test.js
test/unit/lib/BookmarkPanelHub.test.js

I've changed the local providers to be lazily loaded with `defineLazyGlobalGetters`. And they are added only if `devtoolsEnabled`.
I assumed we'll be adding more and each will have their own file.
I also found some more code related to snippets that should have been removed. `allowLegacySnippets` in the `Reducer` state and in `ASRouterPreferences`.

Bug 1546898 - Bookmark Panel QA test provider

---

lib/DiscoveryStreamFeed.jsm
test/unit/lib/DiscoveryStreamFeed.test.js

To test.
1. You need something to delay a server response longer than 45 seconds, I made this https://github.com/ScottDowne/fetch-delay after another remote service failed me too many times. You can use something else but for the purposes of these test steps I'll be using the above.
2. After cloning fetch delay, run npm install and node start.js
4. Set this pref `browser.newtabpage.activity-stream.discoverystream.endpoints` to `https,http`
3. In the browser, set this pref `browser.newtabpage.activity-stream.discoverystream.config` to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":false,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"http://localhost:3000/?delay=50&url=https%3A%2F%2Fgetpocket.cdn.mozilla.net%2Fv3%2Fnewta …

Bug 1548353 - Timeout DS fetches after 45 seconds.

---

lib/ActivityStream.jsm

Let's turn this on since no messages are published yet.

(nobug) - Turn on CFR FxA remote provider

---

docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/BookmarkPanelHub.jsm
test/unit/lib/BookmarkPanelHub.test.js

Adds user telemetry for impression, click and dimiss. Requires #4935 to land first.

Bug1548520 - Add user telemetry for click events

---

content-src/asrouter/templates/Trailhead/_Trailhead.scss

I just realized we dont have any `:focus` styles on the email field. I'm checking with Aaron to see if he wants to add that.

Bug 1549716 - The email input field border wrongly remains red after clearing an invalid email

---

bin/render-activity-stream-html.js
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/components/ModalOverlay/ModalOverlay.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/Trailhead.test.jsx

r?@rlr Needed to do some document passing to get testing happy. You can test accessibility from devtools to see what a screenreader would "see" so changes here make the stuff behind modal "hidden" and correctly identifies the modal as a "dialog" with header. PR also makes tabbing cycle through just the dialog instead of to cards/topsites/etc behind. I'll rebase on your changes in #4985 as there'll be test merge conflicts.
before (shows cards, search, etc):
after (dialog only):

Bug 1548268 - Improve accessibility of trailhead flow

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

r?@rlr Seems simple enough ? cc @mythmon
Here's some screenshots using user_id from https://bugzilla.mozilla.org/show_bug.cgi?id=1547062#c8
`user_id="1"  {"experiment":"interrupts","interrupt":"nofirstrun"}`
`user_id="12" {"experiment":"interrupts","interrupt":"cards","triplet":"supercharge"}`

Bug 1549846 - Set normandy-targetable string pref for interrupt survey

---

lib/OnboardingMessageProvider.jsm

This isn't needed for current export and it actually makes us do an additional change in the next export reverting  https://hg.mozilla.org/mozilla-central/rev/c688fc5b2c0b
We'll want this as part of the uplift to avoid needing the all_files_referenced change as part of the uplift.

Port 1549906 - Use brandings.ftl to allow OnboardingMessageProvider.jsm to use new strings

---

content-src/lib/selectLayoutRender.js
test/unit/content-src/lib/selectLayoutRender.test.js

To test:
Turn off either topsites, or topstores, by clicking the gear in the topright of about:home
It should disable either of those, but display the other one, and not look broken.
If you see "Oops, something went wrong loading this content.
Refresh page to try again." or a topstories message title with no topstories, it's broken.

Bug 1550053 - Fix busted topsites and topstores configs enable/disable

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss

QA: Run `dev-test-all` layout and compare to requests in [1546733](https://bugzilla.mozilla.org/show_bug.cgi?id=1546733)

Bug 1546733 - [Card] Place source above title and adjust vertical spacing

---

test/unit/unit-entry.js

Ran into this test failure when rebasing onto beta. Looks like some dependency was stricter back then even though `await 0` is valid.
```
You may only yield a function, promise, generator, array, or object, but the following was passed: "0"
```

(nobug) - Have ratioSample resolve 0 instead of return 0

---

lib/OnboardingMessageProvider.jsm

r?@piatra Restores the code that was moved into incorrect `template === "onboarding"` condition.
Reuses the existing ` if (msg.template === "return_to_amo_overlay") {`
before:
after:

Bug 1550438 - Return-to-AMO strings need to be formatted

---

content-src/styles/_mixins.scss

r?@gvn or @punamdahiya This adds the ellipsis while not touching the existing behavior. Seems like there's potential for cleanup but maybe do that later? Notably split apart the dual aspect of this mixin in setting font size as well as limiting lines.
before:
after:

Bug 1417163 - Show ellipsis at end of long title and description texts with line-clamp

---

content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
test/unit/asrouter/templates/Trailhead.test.jsx

Bug 1550566 - Retrieve `deviceID` parameter from FxA metrics endpoint and append as additional query parameter for FxA flows

---

content-src/asrouter/templates/Trailhead/_Trailhead.scss

r?@rlr or @k88hudson I tried to maintain the existing single-line button positioning/sizing/spacing. You can test this by changing onboarding.ftl:
```
onboarding-send-tabs-button =
Commencer à utiliser
« Envoyer l’onglet »
```
Before:
After:

Bug 1551832 - Onboarding button label not wrapping

---

lib/ASRouter.jsm
test/unit/asrouter/ASRouter.test.js

The fix I went with is that if the browser has AMO attribution data, experiment branch generation for trailhead will be skipped. It will *not* skip branch generation for other types of attribution.
This implementation assumes that attribution data will be constant, which I think is a safe assumption.

Bug 1550649 - Should not roll trailhead branch if has addons attribution data

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss
content-src/styles/_activity-stream.scss

r?@punamdahiya or @gvn The List's domain isn't a sibling of the title/excerpt, so it needed to be handled differently.
Tested with:
```diff
diff --git a/content-src/lib/selectLayoutRender.js b/content-src/lib/selectLayoutRender.js
--- a/content-src/lib/selectLayoutRender.js
+++ b/content-src/lib/selectLayoutRender.js
@@ -109,8 +109,11 @@ export const selectLayoutRender = (state, prefs, rickRollCache) => {
for (let i = 0; i < items; i++) {
data.recommendations[i] = {
...data.recommendations[i],
pos: positions[component.type]++,
+        title: `${data.recommendations[i].title} `.repeat(3),
+        excerpt: `${data.recommendations[i].excerpt} `.repeat(3),
+        domain: data.recommendations[i].domain.repeat(3),
};
}
return {...component, data};
```
Before:
After:

Bug 1528447 - Long source domains should get truncated with ellipsis

---

lib/ASRouter.jsm

r?@rlr or @k88hudson Based on the information from
https://bugzilla.mozilla.org/show_bug.cgi?id=1548072#c5
"interrupts": `we decided to enrol 25% of new profiles for 4 weeks`
https://bugzilla.mozilla.org/show_bug.cgi?id=1549895#c1
"triplets": `the 75% of new clients who aren't enrolled in bug 1548072`
I did ni?felix just to double check but will probably be out until Tuesday.

Bug 1550217 - Pref on Trailhead with desired experimentation for 67.0.5

---

test/browser/browser.ini
test/browser/browser_asrouter_bookmarkpanel.js

Turning off `browser.newtabpage.activity-stream.asrouter.devtoolsEnabled` because it's currently a workaround to always show the bookmark panel message when that pref is set to true.

Bug 1548516 - Add mochitest coverage for bookmark panel message

---

lib/ASRouterPreferences.jsm
lib/ActivityStream.jsm
lib/PrefsFeed.jsm
test/unit/asrouter/ASRouterPreferences.test.js
test/unit/lib/ActivityStream.test.js
test/unit/lib/PrefsFeed.test.js

I've additionally remove 
* `browser.newtabpage.rows` pref migration (this landed in Firefox 63) https://bugzilla.mozilla.org/show_bug.cgi?id=1474411
* `collapsed*` pref migration (This landed in Firefox 61) https://bugzilla.mozilla.org/show_bug.cgi?id=1445157
I can revert them if it still makes sense to keep them around.

Bug 1531734 - Remove pref migration code in FFx69

---

content-src/components/CollapsibleSection/CollapsibleSection.jsx

The attribute is set to mirror the collapsed prop with `!collapsed`.

Bug 1553234 - Set the aria-expanded attribute of collapsible sections

---

lib/DiscoveryStreamFeed.jsm

QA:
- Open default layout
- Confirm that you see a non broken emoji after the "Tech" section header:

Bug 1548043 - Changing to personal computer emoji for wider support

---

content-src/components/Card/Card.jsx
content-src/components/CollapsibleSection/CollapsibleSection.jsx
content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
content-src/components/TopSites/TopSite.jsx

This should solve the tab-order issue for topsites links and Pocket cards - I've also added appropriate roles/labels to any components that have context menus.
Please let me know if you see any that are missing!

Bug 1554293 - Make sure pocket cards are optimized for screen readers

---

content-src/styles/_activity-stream.scss

Well, guys, I ve found a problem:
If you open New Tab, and open it's source code, you will see this line:
resource://activity-stream/css/activity-stream.css
In that file you will see this line under body element properories:
overflow-y: scroll;
To prevent the behavior, noticed in this bug, you should change it to auto.

Bug 1466888 - Empty scrollbar on blank page

---

.eslintrc.js
bin/bug_xxx_newtab.py
content-src/components/CollapsibleSection/_CollapsibleSection.scss
content-src/components/TopSites/TopSiteForm.jsx
content-src/components/TopSites/TopSiteFormInput.jsx
locales-src/en-US/strings.properties
locales-src/newtab.ftl
test/unit/content-src/components/TopSites.test.jsx

Made changes in the TopSites dialog to move to Fluent. Did not touch footer components because they get reused in another component.

Bug 1556887 - Convert strings in Top Sites dialog to use fluent (header and body)

---

content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
lib/TelemetryFeed.jsm
test/unit/lib/TelemetryFeed.test.js

To test:
1. Set this pref `browser.newtabpage.activity-stream.discoverystream.endpoints` to "https,http"
2. Set this pref `browser.newtabpage.activity-stream.discoverystream.config` to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://gist.githubusercontent.com/ScottDowne/b85c57830405db12a18222ca62b4a3f6/raw/8febea501f10ad43aa2ca9f90b531bdd40136127/adzerk-layout"}`
3. Ensure you can see telemetry events
4. Open a new tab, you should see a layout of weird cards, heros, and lists.
5. You should see 6 spocs total.
6. Open your jsdebugger
7. Ensure click and view ping events have the shim prop being passes in for spocs, and not for regular cards.

Bug 1550119 - Pass Adzerk shim to spoc click and view pings.

---

lib/ActivityStream.jsm
lib/DiscoveryStreamFeed.jsm
test/unit/lib/DiscoveryStreamFeed.test.js
test/unit/unit-entry.js

At the moment testing this is just a matter of turning on spocs and making sure they still render.
Testing that the actual pocket id works when passed in is hard given the server still hasn't be made to handle this. This part can have a larger round of QA as different pieces for this integration fall into place. That said, if you have reason to suspect I am not properly passing in the pocket id, you should def call it out.
Part of what we're doing with this is passing in the client id to pocket's spoc endpoint. (@ncloudioj do you know what kind of specialized reviews I may need for that?)
We needed to update this fetch to be post, and not get, because of the new id.
And on a personal level, I wanted to include in this is not need to rely on a pref. So, these changes should be backwards …

Bug 1550115 - Include impression id to spoc request.

---

content-src/components/ContextMenu/ContextMenu.jsx
test/unit/content-src/components/ContextMenu.test.jsx

added ArrowUp and ArrowDown listeners to the onKeyDown event on context menus; handled focus with DOM targeting. May try to switch to React refs to make the function a little more resilient.

Bug 1554734 - Also support context-menu arrow key navigation 

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss

Testing: Confirm that hovering over context menu preserves the hover state on the rest of the card.

Bug 1552937 - Preserve hover state on cards when hovering over context menu

---

content-src/asrouter/templates/EOYSnippet/EOYSnippet.schema.json
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.jsx
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json

Bug 1551711 - Added alt-text prop to all snippet schemas that include an icon.

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx

1. Clone this repo locally https://github.com/ScottDowne/test-data
2. Run npm install
3. Run node start.js
1. Set this pref `browser.newtabpage.activity-stream.discoverystream.endpoints` to "https,http"
2. Set this pref `browser.newtabpage.activity-stream.discoverystream.config` to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://gist.githubusercontent.com/ScottDowne/1a08ca9f15ceb4ea0aafb9532e5d1381/raw/eef821bf4f40594d3c12ea684df3bdef8508a84e/adzerk-layout-2"}`
3. Ensure you can see telemetry events
4. Open a new tab, you should see a layout of weird cards, heros, and lists.
5. You should see 6 spocs total.
6. Open your browser toolbox (tools -> web developer …

Bug 1558903 - Passing proper shims for specific events.

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/Highlights/Highlights.jsx
content-src/components/DiscoveryStreamComponents/Highlights/_Highlights.scss
content-src/components/Sections/Sections.jsx
content-src/styles/_activity-stream.scss
lib/AboutPreferences.jsm
lib/ActivityStream.jsm
test/browser/browser_highlights_section.js
test/unit/content-src/components/DiscoveryStreamComponents/Highlights.test.jsx
test/unit/lib/AboutPreferences.test.js

r?@ScottDowne Wraps similar to what we did for TopSites and adjusting the styling to fit with discoverystream cards:

Bug 1536285 - Add Highlights as the final discovery stream section

---

bin/bug_xxx_newtab.py
content-src/components/Card/Card.jsx
content-src/components/CollapsibleSection/CollapsibleSection.jsx
content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
content-src/components/TopSites/TopSite.jsx
locales-src/en-US/strings.properties
locales-src/newtab.ftl

Adding on fluent migrations to @AllegroFox  work in #5099. 
Tooltips on
- Sections
- Top Sites and empty Top Site boxes 
- Pocket Cards
- Highlights (downloaded items and websites)

Bug-1556039 - Fluent changes to 1556039 (removal of sr-only) spans

---

lib/SectionsManager.jsm
locales-src/en-US/strings.properties

@Mardak . Following #5127 (checkout last commit until it gets merged). 
Fortunately, the "header_recommended_by" was originally used in two different places, one for about prefs and one for newtab pocket section. But, "pocket_how_it_works" was shared from one source. Made changes ontop of #5127 to keep newtab fluent changes.

Bug 1561414 - Fixing unintended changes to About:Prefs that uses same strings in newtab pocket section

---

bin/bug_1485002_newtab.py
content-src/components/TopSites/SearchShortcutsForm.jsx
content-src/components/TopSites/TopSiteForm.jsx
locales-src/newtab.ftl
test/unit/content-src/components/TopSites.test.jsx

Resolving Fluent comment feedback in #5083. 
- ##'s have a new line after them.
- ##'s end in a "." so that there is a separator when concatenated with single-hash comments.
-  Changed Open File location label to only handle "macos" (show in finder) and "other" (Open Containing Folder).
- Migrated and renamed some strings.

Resolving feedback on Fluent comments in PR 5083

---

README.md
lib/HighlightsFeed.jsm
test/unit/lib/HighlightsFeed.test.js

r?@gvn or @ScottDowne Just removes the old special behavior of always putting bookmarks first even when it's just a history page that happens to be bookmarked. (Still keeps the special behavior of putting recent bookmark/pocket/download first before history.)

Bug 1559689 - Allow history highlights that happen to be bookmarked to appear in normal history order

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss

To test:
1. Set your `browser.newtabpage.activity-stream.discoverystream.config` pref to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":true,"personalized":false,"layout_endpoint":"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=basic"}`
2. Load a new tab until you see a spoc in the 3rd spot.
3. Inspect the middle stories body text in the firefox inspector. It should look something like `<p class="excerpt clamp"></p>`
4. Remove the `clamp` from the class list.
5. Make the `p` text much longer, until you end up with something like this screenshot: 
ensure the sponsored by text is aligned on the bottom like the screen shot, and that it's aligned with the text in the …

Bug 1560235 - Fixing alignment issue and regression.

---

lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/MessageLoaderUtils.test.js
test/unit/asrouter/templates/OnboardingMessage.test.jsx

This PR contains a small set of proposed changes to ensure that the addons installed from ActivityStream for the RTAMO onboarding are marked with "rtamo" as their install telemetry source (as it has been discussed in [Bug 1549770](https://bugzilla.mozilla.org/show_bug.cgi?id=1549770), which has also attached the new data review request related to this change).

Bug 1549770 - Addons installed from RTAMO should have rtamo as install telemetry source

---

lib/ActivityStream.jsm
lib/DiscoveryStreamFeed.jsm
test/unit/lib/DiscoveryStreamFeed.test.js

To test:
1. Set `browser.newtabpage.activity-stream.discoverystream.config` to `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":true,"personalized":false,"layout_endpoint":"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=basic"}`
2. Load a new tab
Ensure you see spocs.
Also try opting out of spocs, ensure that works.
For the most part you shouldn't notice anything changing.

Bug 1562009 - Turn on ad server

---

.eslintrc.js
bin/bug_1556895_newtab.py
content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
lib/OnboardingMessageProvider.jsm
locales-src/en-US/strings.properties
locales-src/onboarding.ftl
test/unit/asrouter/templates/Trailhead.test.jsx

Migrating about:welcome strings to fluent
- Migrate old about:welcome (StartupOverlay.jsx) to fluent (Done)
- Update now broken files using about:welcome strings (Done 7/1)

Bug 1556895 - Convert first run strings in about:welcome and startup overlay to use fluent

---

test/browser/browser.ini

Our mochitests were logging errors like
```
GECKO(27292) JavaScript error: , line 0: uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider.
0:07.55 INFO Console message: [JavaScript Error: "uncaught exception: [fluent][resolver] errors in en-US/newtab-section-header-pocket: ReferenceError: Unknown variable: provider."]
```
These didn't prevent any builds from failing but were appearing frequently in terminal.  Previously, we weren't providing a provider in browser.ini which caused an appropriate reference error.
Tests:
./mach mochitest browser/components/newtab/test/browser

(no bug) - Fixing browser.ini to fix mochitests logging fluent ReferenceErrors

---

content-src/components/Card/Card.jsx
content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
content-src/components/TopSites/TopSite.jsx
test/unit/content-src/components/Card.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSLinkMenu.test.jsx
test/unit/content-src/components/TopSites.test.jsx

With the way we were creating JSON strings we were getting an incorrect JS string value.
```
<button aria-haspopup="true" data-l10n-id="newtab-menu-content-tooltip" data-l10n-args="{ &quot;title&quot;: &quot;Resolving Error: &quot;Objects are not valid as a React child&quot;&quot; }" class="context-menu-button icon"></button>
{ "title": "Resolving Error: "Objects are not valid as a React child"" }
```
Fixing this in other places we use data-l10n-args

Bug 1563127 - Fixing invalid JSON from manual string injection

---

lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/browser/browser.ini
test/browser/browser_onboarding_rtamo.js

~~Also a TC run that includes Windows: https://treeherder.mozilla.org/#/jobs?repo=try&revision=fa318b376d5e7bbcd77ec91fc94f037bd9dfa3b4~~
Finally got it green on windows https://treeherder.mozilla.org/#/jobs?repo=try&revision=7a6b54ee8dc82ee5b95952b9a6659addb6420033
TC is not relevant here only Win & OSX so we should notice any regressions when testing locally or exporting.

(nobug) - Add mochitest for ReturnToAMO component

---

lib/ActivityStream.jsm
test/browser/browser.ini
test/browser/browser_discovery_render.js

r?@ScottDowne Adds a test similar to browser_as_render and browser_discovery_styles. To be clear, this doesn't fail without your expired fix #4930 because there's no network connections allowed, so spocs never get updated anyway. This is just basic rendering test with an extra reload thrown in for fun.
Also adds a developer XXX comment/warning re: hardcoded_layout.

(nobug) - Add basic discovery stream rendering mochitest

---

lib/DownloadsManager.jsm
test/unit/lib/DownloadsManager.test.js

r?@ScottDowne or @gvn Turns out we broke this in #4459 when trying to avoid high CPU issues for people with data uri downloads. So here restore the blocked links check but specially ignore long urls.

Bug 1559548 - Dismissing a download highlight makes it go away and reappear

---

content-src/asrouter/templates/Trailhead/_Trailhead.scss

Removed max-height css rule for trailhead cards to prevent the cards from overlapping with the main page body.

Bug 1557304 - “About:welcome” cards overlapping issue with the browser resized to minimum width

---

content-src/asrouter/asrouter-content.jsx

r?@rlr or @piatra I clicked the [Show] button for WHATS_NEW_70_1 in devtools and it resulted in a react failure "Oops, something went wrong loading this content."

(nobug) - Ignore whatsnew when rendering snippets

---

content-src/asrouter/docs/targeting-attributes.md
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js

You can see the UpdateManager in action on `about:support` with a real profile 
`previousFirefoxVersion` will return the very first firefox version used with the current profile (69.0a1 as seen in my screenshot) so it could be named better, I'm open to suggestions.
Testing this might be tricky so I'm thinking we merge `whatsnew-panel` branch into master to get this into Nightly sometime this week. Then QA can verify/validate the method.

Bug 1564898 - Use UpdateManager to get the earliest Firefox version used

---

content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
content-src/asrouter/templates/Trailhead/_Trailhead.scss

https://bugzilla.mozilla.org/show_bug.cgi?id=1554666
In the codebase there's a media query to shrink the size of this image after 850px break point, so looks like the images are supposed to shrink. Though, the cards going into a different row should probably have a consistent height.
Commit will keep consistent height if a card breaks into a new row and the image shrinking break point is updated.
https://drive.google.com/open?id=1EGgdmOMFlSu7LoyNNWK-mhpt6qNOp51O

Bug 1554666 - Updated image resizing breakpoint and added grid-auto-rows to keep equal row height

---

lib/ASRouterTargeting.jsm
lib/AboutPreferences.jsm
lib/LinksCache.jsm
lib/PersistentCache.jsm
lib/Tokenize.jsm
test/unit/asrouter/ASRouterTargeting.test.js
test/unit/lib/AboutPreferences.test.js
test/unit/lib/LinksCache.test.js
test/unit/lib/PersistentCache.test.js

r?@piatra (Generally good to look at PRs ignoring whitespace now with prettier. From Files changed -> gear icon -> Just for now Hide whitespace changes)
- ASRouterTargeting: converted to plain async dropping the explicit reportError
- AboutPreferences: deleted `strings` helper and related cleanup
- LinksCache: kept async but added try/catch to reject
- PersistentCache: kept async but added try/catch around remaining potential failure
- Tokenize: eslint rule says regex `/[MCP]/` (pretend MCP is a visually single unicode character but actually multiple characters) is dangerous because it matches on the individual "M" "C" or "P" characters, but in this case, we're matching the whole token anyway, so ignore

Bug 1564124 - Fix eslint issues for no-async-promise-executor and no-misleading-character-class

---

lib/OnboardingMessageProvider.jsm
lib/PanelTestProvider.jsm
test/unit/asrouter/PanelTestProvider.test.js
test/unit/lib/ToolbarBadgeHub.test.js
test/unit/lib/ToolbarPanelHub.test.js

With this patch you can still trigger the badging from devtools, but the actual messages don't show up in the panel. I guess because they aren't really loaded into ASRouter (?).

(nobug) Move the What's New and Badge test messages to PanelTestProvider.jsm

---

bin/render-activity-stream-html.js

(nobug) - Use older trimLeft instead of es2019 trimStart

---

lib/ToolbarBadgeHub.jsm
test/unit/lib/ToolbarBadgeHub.test.js

It was calling `add` instead of `remove`.

(nobug) - Restore the default icon style after removing the badge

---

lib/ToolbarPanelHub.jsm
test/unit/lib/ToolbarPanelHub.test.js

The branch is on top of #5180 that's why the extra part, only changes in `ib/ToolbarPanelHub.jsm` should be considered.

Bug 1564568 - Hide What's New toolbar button after the user dismisses the panel

---

.eslintrc.js
content-src/components/DiscoveryStreamComponents/DSEmptyState/DSEmptyState.jsx
locales-src/newtab.ftl
test/unit/content-src/components/DiscoveryStreamComponents/DSEmptyState.test.jsx

Thinking about calling fluent headers for Discovery Stream like "Empty Section (Content Discovery Experience)", since the old experience of activity stream is still here with similar strings.

Bug 1556862 - Localizing empty discovery stream messages

---

webpack.system-addon.config.js

r? @k88hudson Adds a banner satisfying a valid "license" https://searchfox.org/mozilla-central/source/tools/lint/license/valid-licenses.txt
Diff on m-c side:
```diff
diff --git a/browser/components/newtab/data/content/activity-stream.bundle.js b/browser/components/newtab/data/content/activity-stream.bundle.js
--- a/browser/components/newtab/data/content/activity-stream.bundle.js
+++ b/browser/components/newtab/data/content/activity-stream.bundle.js
@@ -1 +1,2 @@
+/*! THIS FILE IS AUTO-GENERATED: webpack.system-addon.config.js */
/******/ (function(modules) { // webpackBootstrap
```
(Note if testing locally, you'll need to enable license linting of .js files https://searchfox.org/mozilla-central/rev/15be167a5b436b57fef944b84eef061d24c1af8c/tools/lint/license.yml#23-24 )

Bug 1565088 - Add AUTO-GENERATED message to top of bundle.js to satisfy license lint

---

docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/ToolbarBadgeHub.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/lib/ToolbarBadgeHub.test.js

I'll follow up with a data review as well. This PR adds 2 events for `IMPRESSION` and `CLICK` for the toolbar badges.
To test this you can enable the badge in ASR admin under `panel_test_provider` -> `FXA_ACCOUNTS_BADGE`.

Bug 1561554 - Add telemetry events for notification badges

---

lib/ToolbarBadgeHub.jsm
lib/ToolbarPanelHub.jsm
test/unit/lib/ToolbarBadgeHub.test.js
test/unit/lib/ToolbarPanelHub.test.js

To test for this have
Pref | Value
--- | ---
browser.newtabpage.activity-stream.asrouter.providers.panel_local_testing | {"id":"panel_local_testing", "cohort": "SHOW_TEST"}
browser.messaging-system.whatsNewPanel.enabled | false
Then when changing `browser.messaging-system.whatsNewPanel.enabled` to `true` the Whats New gift icon should appear.

Bug 1566372 - Listen for pref changes as a way to trigger notifications

---

lib/ASRouter.jsm
lib/ToolbarPanelHub.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/lib/ToolbarPanelHub.test.js

You can test this in ASR admin with and without setting 
Pref | Value
--- | ---
browser.newtabpage.activity-stream.asrouter.providers.panel_local_testing | {"id":"panel_local_testing", "cohort": "SHOW_TEST"}
The button and badge should not show up when the pref is not set.

Bug 1566460 - Don't show the panel if there are no messages

---

content-src/components/SectionMenu/SectionMenu.jsx
test/unit/content-src/components/SectionMenu.test.jsx

Original bug
https://bug1554961.bmoattachments.org/attachment.cgi?id=9067993
Dispatching an additional action to expand if the current action is adding a top site or search engine.
https://drive.google.com/file/d/1GpSV2pAJ2sMCBbHaqoGXqN1J5v_M29Fs/view?usp=sharing

Bug 1554961 - Adding a Top Site/Search Engine in a collapsed section is buggy.

---

.eslintrc.js
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/FirstRun/FirstRun.jsx
content-src/asrouter/templates/FirstRun/Interrupt.jsx
content-src/asrouter/templates/FirstRun/Triplets.jsx
content-src/asrouter/templates/FirstRun/addUtmParams.js
content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/browser/browser_onboarding_rtamo.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/constants.js
test/unit/asrouter/templates/FirstRun.test.jsx
test/unit/asrouter/templates/Interrupt.test.jsx
test/unit/asrouter/templates/Trailhead.test.jsx
test/unit/asrouter/templates/Triplets.test.jsx
test/unit/content-src/components/ReturnToAMO.test.jsx
test/unit/content-src/components/StartupOverlay.test.jsx
test/unit/content-src/components/addUtmParams.test.js

In this PR I refactored the first run experience to:
* Remove the old modal onboarding code
* Make the triplets independent of the trailhead modal / i.e. work with return to AMO and the overlay experience (so we can experiment with any combination)
* Move some of the shared logic around hiding/showing/adding fluent files etc. into a single `FirstRun` component.
I wrote it with hooks initially (see ff9a667) but I encountered some weird test failures around portals that I think are because of enzyme. Maybe in a future PR we could try restoring it.
Whereas the old code in `asrouter-content.jsx` had different methods for rendering the various onboarding experiences, I've refactored it to have a more component-based structure
```jsx
<FirstRun> 
<Interrupt />
<Triplets />
</FirstRun>
```
Where …

Bug 1560065 - Refactor first run for skyline, replace modal onboarding with triplets

---

docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/ToolbarPanelHub.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/lib/ToolbarPanelHub.test.js

Adds pings for:
* Showing the panel 
* Either from the application menu
* or from the toolbar button
* Clicking on a message
* Seeing a message (impression)
* the idea here is that messages could be user targeted (not everyone sees the same set)
* my current implementation sends 1 ping per message with the `message.id` and the `IMPRESSION` event the very first time you open the panel (no mater how many times you open the panel)
* @ncloudioj is there a different way to report on this that would make it easier for data reporting?

Bug 1561625 - Add telemetry events for What's New panel

---

lib/PanelTestProvider.jsm

QA noticed the badge wasn't going away after 4 days.
The `foo[.method == ...]` syntax is used to filter an array of objects that have the `method` property.
```
[{method: "foo", ...}, {method: "bar", ...}]
```
In this case `messageImpressions` is an `Object` where the keys are the message ids so we can use the regular methods to access object values.
```
{"WHATS_NEW": [...], "BAR": ...}
```

(nobug) - Fix What's New badge targeting expression

---

test/browser/browser.ini
test/browser/browser_asrouter_bookmarkpanel.js
test/browser/browser_asrouter_toolbarbadge.js

Some basic mochitest coverage for the `ToolbarBadgeHub`. It badges the fxa button (with and without delay) and checks that clicking the button dismisses the badge.

(nobug) - Add mochitest for toolbar badging behavior

---

content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/FirstRun/FirstRun.jsx
docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/unit/asrouter/ASRouter.test.js

This is a first pass at adding an "extended triplets" that stick around for longer than just first run.
I added some basic frequency capping (4x a day) and profile age targeting for testing.
To test manually,
- Try opening a bunch of new tabs (on a new-ish profile). The first four should have cards on them.
- Block/unblock `EXTENDED_TRIPLETS_1` to clear frequency caps
- On a new tab, try blocking the  card panel at the top left. You should no longer see cards show up on a refresh
No tests yet, I'll add if we think this is a good approach.

Bug 1568909 - Show triplets for extended period after first run

---

content-src/asrouter/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json
content-src/asrouter/templates/OnboardingMessage/UpdateAction.schema.json
lib/ASRouter.jsm
lib/PanelTestProvider.jsm
lib/ToolbarBadgeHub.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/PanelTestProvider.test.js
test/unit/lib/ToolbarBadgeHub.test.js

Adds a new action id `"moments-wnp"` that can set the value of `.homepage_override.once` pref.
Values to be set are defined through the `data` field of the `content.action` payload in the message.
Not sure if for messages such as `profile age == ONE_YEAR` where `expire` would not be defined in the message we have to set it when the message is selected.
Do we have other/more scenarios we want to handle?

Bug 1569020 - Add a new badge action for setting homepage_override pref

---

lib/ASRouter.jsm
lib/ToolbarBadgeHub.jsm
test/unit/lib/ToolbarBadgeHub.test.js

There were two separate issues preventing the `reset & recheck` behavior:
* `unblockMessageById` was not bound to `ASRouter` so unblocking the message failed. The pref would not get set back again.
* because `update_action` messages don't show an actual badge the cleanup process would never happen. The map that holds the window reference was always populated and would skip the message a second time around

Bug 1571846 - Moments pref reset issue

---

lib/ActivityStream.jsm

Testing:
- Set `browser.search.region` to `CA`
- Toggle `extensions.langpacks.signatures.required` to `false`
- Toggle `xpinstall.signatures.required` to `false`
- Toggle `intl.multilingual.downloadEnabled` to `true`
- Toggle `intl.multilingual.enabled` to `true`
- Open `https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/mac/xpi/firefox-70.0a1.en-CA.langpack.xpi` in build and install
- In `about:preferences` click "Set Alternatives" under "Language", move "English (Canada)" to the top position, click OK, click "Apply And Restart"
- Confirm that DS is enabled in new tab
(Repeat for the `en-GB` langpack)
Approved matrix of enabled geo+locale combos: https://docs.google.com/document/d/1EXMtfPOzcgBrYNVjr8rsA0FymCZm7refUcHrUbp2onE/edit#

Bug 1567272 - Enabling DS for CA

---

common/Actions.jsm
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/FirstRun/FirstRun.jsx
content-src/asrouter/templates/FirstRun/addUtmParams.js
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/templates/FirstRun.test.jsx

This adds a new user action to ASRouter that allows users to directly authenticate with Firefox Monitor via a URL, similar to how the What's New Page does it.
I have a few questions about the best way to implement this, noted below in comments, before I add tests.

Bug 1570026 - Monitor action for snippets

---

mochitest.sh

r?@punamdahiya or @ScottDowne This was added in https://bugzilla.mozilla.org/show_bug.cgi?id=1568617

(nobug) - Run test for webextension topSites that uses redux state

---

content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
content-src/components/DiscoveryStreamComponents/DSContextFooter/_DSContextFooter.scss
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/components/DiscoveryStreamComponents/List/_List.scss
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/Hero.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx

Edit: New animations further down (change to Fade instead of Rotate)
~~*Look at last commit only until I rebase this after b_1540842.~~
Adding the DSContextFooter to the Hero and List components.
Animations
Hero - https://drive.google.com/open?id=1JCpnuzHaLFUJNTvyjfRkvCUFXQALk8ci
List - https://drive.google.com/open?id=1kMHnDZ0zIRczyF4dkcJeVOcbWIR7XV-Y

Pocket New Tab should display "Save to Pocket" for Hero and List components

---

content-src/asrouter/templates/Trailhead/_Trailhead.scss

To test this:
- Turn discovery stream off
- Collapse all your sections
- Open devtools, trigger EXTENDED_TRIPLETS_1  (or just launch with `--new-profile`)
- Make your window vertically large
- Ensure you don't see a large gap between the triplets and the search

Bug 1571442 - Search box shouldn't move down with extended Triplets on

---

content-src/components/DiscoveryStreamComponents/CardGrid/_CardGrid.scss
content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss

To test:
1. Open a new tab
2. Ensure we see pocket stories with at max 4 lines of text.
3. Ensure cards in a single row are all the same height, based on the height of the tallest card.

Bug 1573204 - Adding an extra line to pocket stories

---

lib/DiscoveryStreamFeed.jsm

To test, this is mostly a tiny refactor, so regression testing is probably the best bet, things should work as they always did.

Bug 1572841 - Avoid loading JSMs eagerly in Discovery Stream

---

lib/OnboardingMessageProvider.jsm
lib/ToolbarPanelHub.jsm
locales-src/asrouter.ftl

r? @k88hudson or @piatra Just adds asrouter.ftl if necessary and convert raw strings to `string_id`s
Before (hardcoded "Firefox"):
After:

Bug 1572441 - Localize Protection panel message

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss
content-src/components/DiscoveryStreamComponents/Hero/_Hero.scss
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx

To test:
1. Go to newtab.
2. Inspect a card, and look for these: `<div class="ds-card">`
3. Scroll down a bit.
Expected: Initially, any cards above the fold should be `<div class="ds-card">` and any below the fold should be  `<div class="ds-card placeholder">` and be empty (so they render fast) . As you scroll, they should update with their content.

Bug 1573206 - Testing a render change

---

content-src/components/DiscoveryStreamComponents/CardGrid/CardGrid.jsx
content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/DSContextFooter/DSContextFooter.jsx
content-src/components/DiscoveryStreamComponents/DSContextFooter/_DSContextFooter.scss
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSContextFooter.test.jsx

Adding an "engagement" propery that displays "Fresh", "Popular" or nothing for Hero, List, and DSCards (CardGrid)
Will come from the server in b_1566707
`
{
feeds:
{
data:
{
recommendations: [
{
domain: ‘’,
excerpt: ‘’,
id: ‘’,
title: ‘’,
url: ‘’,
….
engagement: "Popular",
}]
}
}
}`

Bug 1565709 Story Engagement to pocket cards

---

content-src/asrouter/docs/targeting-attributes.md
content-src/asrouter/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json
content-src/asrouter/templates/OnboardingMessage/UpdateAction.schema.json
docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/ASRouterTargeting.jsm
lib/BookmarkPanelHub.jsm
lib/OnboardingMessageProvider.jsm
lib/PanelTestProvider.jsm
lib/ToolbarBadgeHub.jsm
test/browser/browser_asrouter_targeting.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/ASRouterFeed.test.js
test/unit/asrouter/ASRouterTargeting.test.js
test/unit/asrouter/PanelTestProvider.test.js
test/unit/asrouter/templates/OnboardingMessage.test.jsx
test/unit/lib/BookmarkPanelHub.test.js
test/unit/lib/ToolbarBadgeHub.test.js
test/unit/ping-centre/PingCentre.test.js
test/unit/unit-entry.js

This uplifts 10 Badge bugs:
https://bugzilla.mozilla.org/buglist.cgi?f1=blocked&o1=allwords&v1=1560987&resolution=FIXED
Excluding:
- Bug 1561547 - Use Messaging System to badge the FxA accounts toolbar button
- Bug 1563733 - Use Messaging System to badge the What's New toolbar button
Including: 2 (nobug)
```
27b79564 Bug 1561536 - Add new message schema and template type for feature callouts (#5133)
d8570e05 Bug 1561540 - CFR messages should have a priority field that allows sorting (#5156)
7c9f5603 Bug 1564898 - Use UpdateManager to get the earliest Firefox version used (#5165)
6ebba35b Bug 1564811 - Badge actions can define a timeout delay after which the action is executed (#5170)
90b5eea2 (nobug) Move the What's New and Badge test messages to PanelTestProvider.jsm (#5171)
23e918ca …
```

Uplift Bug 1567601 - New "Moments" Page

---

common/Actions.jsm
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.jsx
content-src/asrouter/templates/SimpleBelowSearchSnippet/SimpleBelowSearchSnippet.schema.json
content-src/asrouter/templates/SimpleBelowSearchSnippet/_SimpleBelowSearchSnippet.scss
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.schema.json
content-src/components/Base/_Base.scss
content-src/components/Search/_Search.scss
lib/SnippetsTestMessageProvider.jsm
test/unit/asrouter/asrouter-content.test.jsx

This uplifts 5 bugs:
https://bugzilla.mozilla.org/buglist.cgi?keywords=github-merged&o1=allwords&v1=1569300&f1=blocked
```
5118b78c Bug 1569597 - Updated schema & template, added test snippet with corr… (#5208)
5ea99ba1 Bug 1571435 - Overrode the .active class for snippets with buttons, to prevent a double highlight. (#5224)
70b63230 Bug 1571441 - Fixed snippet width and block button position on smaller screens (#5227)
9e70a342 Bug 1570026 - Part 1. Add Monitor action for snippets
46821636 Bug 1572463 - Fixes for the Special Monitor Snippet (#5235)
```
Needed to resolve conflicts in https://github.com/mozilla/activity-stream/commit/083792d8cff311fd2b9c2a6c8779baec8d5b6a5b for not uplifting https://github.com/mozilla/activity-stream/commit/fe05904ed881d799a6e53d8fbe36976e33fe127c in this …

Uplift Bug 1569300 - Special Monitor Snippet

---

.eslintrc.js
content-src/asrouter/asrouter-content.jsx
content-src/asrouter/templates/FirstRun/FirstRun.jsx
content-src/asrouter/templates/FirstRun/Interrupt.jsx
content-src/asrouter/templates/FirstRun/Triplets.jsx
content-src/asrouter/templates/FirstRun/addUtmParams.js
content-src/asrouter/templates/OnboardingMessage/OnboardingMessage.jsx
content-src/asrouter/templates/OnboardingMessage/_OnboardingMessage.scss
content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx
content-src/asrouter/templates/StartupOverlay/StartupOverlay.jsx
content-src/asrouter/templates/Trailhead/Trailhead.jsx
content-src/asrouter/templates/Trailhead/_Trailhead.scss
docs/v2-system-addon/data_events.md
lib/ASRouter.jsm
lib/OnboardingMessageProvider.jsm
test/browser/browser_aboutwelcome.js
test/browser/browser_onboarding_rtamo.js
test/unit/asrouter/ASRouter.test.js
test/unit/asrouter/asrouter-content.test.jsx
test/unit/asrouter/constants.js
test/unit/asrouter/templates/FirstRun.test.jsx
test/unit/asrouter/templates/Interrupt.test.jsx
test/unit/asrouter/templates/Trailhead.test.jsx
test/unit/asrouter/templates/Triplets.test.jsx
test/unit/content-src/components/ReturnToAMO.test.jsx
test/unit/content-src/components/StartupOverlay.test.jsx
test/unit/content-src/components/addUtmParams.test.js

This is on top of a dummy `beta-wip` branch that merges `beta-monitor` #5244 (for "1570026 part 1") and `beta-moments` #5250 (for triggerParams).
This uplifts 9 Extended bugs:
https://bugzilla.mozilla.org/buglist.cgi?f1=blocked&o1=allwords&v1=1569303&resolution=FIXED
```
fe05904e Bug 1560065 - Refactor first run to separate Interrupts and Triplets
cdd41d99 Bug 1560065 - Converted hooks to class component due to failing tests
d40f56fd Bug 1568909 - Show triplets for extended period after first run
82187f91 Bug 1570026 - Part 2. Refactor FirstRun to use generic fetchFlowParams
2fa2908c Bug 1571817 - Hold back rollout test for Extended Triplets (#5233)
469c7ee7 Bug 1572378 - Unable to install extension from RTAMO overlay (#5234)
00243975 Bug 1570754 - Add delay to clearing triplets and …
```

Uplift Bug 1569303 - Extended First Run Triplets

---

lib/DiscoveryStreamFeed.jsm
lib/PrefsFeed.jsm
lib/TopStoriesFeed.jsm
test/browser/browser.ini
test/unit/lib/DiscoveryStreamFeed.test.js
test/unit/lib/TopStoriesFeed.test.js

To test:
First pref:
1. Set `browser.newtabpage.activity-stream.discoverystream.enabled` to `true`
2. Restart, and ensure new tab shows 7 rows of story cards.
3. Set it to false, restart, and ensure we now see the old AS.
Next pref:
1. Set `browser.newtabpage.activity-stream.discoverystream.hardcoded-basic-layout` to true.
2. Set `browser.newtabpage.activity-stream.discoverystream.enabled` to `true`
3. Restart, ensure you see DS enabled with 3 cards.
4. Set it back to false, and restart, ensure you see the old AS with 3 cards.
5. Attached screen shots for each version of 3 cards to help verify. (DS 3 card experience and AS 3 card experience). Notice the slight difference in the popular topics section under the cards.
DS 3 card experience:
AS 3 card experience:
Third pref:
1. Ensure you …

Bug 1573930 - FF prefs to control DS

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
lib/DiscoveryStreamFeed.jsm
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx

Pre-req:
Direct response promo/spoc with cta property set returned by Adzerk server https://spocs.getpocket.com/spocs
QA steps:
1. Set browser.newtabpage.activity-stream.discoverystream.endpoints to https://,http://
2. Set browser.newtabpage.activity-stream.discoverystream.config "hardcode_layout" as false
3. To test Link CTA variant
Set browser.newtabpage.activity-stream.discoverystream.config layout_endpoint as
https://layout-variants-70.web.readitlater.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4&layout_variant=3-col-7-row-cta-link
4. To test Button CTA variant
Set browser.newtabpage.activity-stream.discoverystream.config layout_endpoint as
https://layout-variants-70.web.readitlater.com/v3/newtab/layout?version=1&consumer_key=40249-e88c401e1b1f2242d9e441c4& …

Bug 1575108 - Update DSCard component to use cta_variant string values

---

locales-src/asrouter.ftl

This is still WIP but probably good enough to get a first pass making sure we've got the desired strings. This is on top of #5267 to rename the ftl message ids for the blocked related items.
Theoretically https://docs.google.com/presentation/d/17BCPTuDWVSnLcLuFx-HFa4ESCpIH8A-Ss9V7F2m8rFQ/edit#slide=id.g5e3431b199_0_0 and https://docs.google.com/presentation/d/17BCPTuDWVSnLcLuFx-HFa4ESCpIH8A-Ss9V7F2m8rFQ/edit#slide=id.g5e44344997_3_0 are "finalized" but sounds like usage of "Protection Report" has some questions.
From those 2 pages, there's:
1) firefox 70 hero
2) protection report 
a. for >= 100 blocked items
b. fewer than 100 blocked items
3) lockwise
a. password sync not on
b. password sync on
4) firefox 70 release notes

Bug 1561370 - Land strings and images for Firefox 70 What's New messages

---

mochitest.sh

I've hit this and seems like TC is having the same issues 
See `dev-platform` email "Watch out for build issues on non-Unicode systems"

Test to see if TC builds work after removing `objdir`

---

lib/OnboardingMessageProvider.jsm
lib/PanelTestProvider.jsm
test/unit/asrouter/PanelTestProvider.test.js
test/unit/lib/ToolbarBadgeHub.test.js

There's no risk of showing up accidentally because there are no what's new messages yet.

Bug 1575888 - Enable the What's New toolbar badge

---

content-src/components/DiscoveryStreamImpressionStats/ImpressionStats.jsx
test/unit/content-src/components/DiscoveryStreamComponents/ImpressionStats.test.jsx

To test:
2. Update `browser.newtabpage.activity-stream.discoverystream.config` with `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://5ad1b408-b40a-4a49-b6ec-27473d192df0.mock.pstmn.io"}`
3. Open a new tab, should see a sponsored topsite.
4. Open the console.
5. Dismiss the sponsored topsite.
expected. no errors in the console.

Bug 1577345 - Intersection observer prop update bug

---

test/browser/browser.ini
test/browser/browser_asrouter_whatsnewpanel.js

The test opens the panel, clicks Whats New and checks the correct number of messages are rendered.

(nobug) - Mochitest: messages are rendered in the What's New panel

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
content-src/components/DiscoveryStreamComponents/DSTextPromo/DSTextPromo.jsx
content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss

To test:
2. Update `browser.newtabpage.activity-stream.discoverystream.config` with `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://5ad1b408-b40a-4a49-b6ec-27473d192df0.mock.pstmn.io"}`
expected: Should see a Netflix logo in the TextPromo with actual pixel size of 40x40 (or 80x80 depending on screen density)

Bug 1577348 - Use dsimage in dstextpromo; add alt text and rounding to dsimage

---

lib/ASRouter.jsm

Issue here is logging into sync causes services.sync.username pref to change which triggers [onPrefChange](https://github.com/mozilla/activity-stream/blob/master/lib/ASRouter.jsm#L523) adding Extended Triplets message  to list of invalid messages. 
Invalid messages gets cleared by [AS_ROUTER_TARGETING_UPDATE handler](https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/asrouter-content.jsx#L257)
Fix in patch assumes we want to show extended triplets if its visible while sync pref change.

Bug 1575820 - Show extended triplets on new tab after sync login

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx

Hard to test, in general making sure all rows of cards appear is probably good enough for regression testing.
1. Set `browser.newtabpage.activity-stream.discoverystream.enabled` to true
2. Load a new tab.
3. wait a few seconds.
4. Scroll from top to bottom
Expected: cards should be already loaded as you scroll, or fade in.
Not Expected: If you see no cards at all, or if cards don't fade in/are not already loaded.
To test the actual bug, I've only reproduced it a few times.
1. Set `browser.newtabpage.activity-stream.discoverystream.enabled` to true
2. Open the page's console.
3. toggle `browser.newtabpage.activity-stream.discoverystream.enabled` a few times.
Expected: no console errors.
Not expected: console error for "Warning: Can't perform a React state update on an unmounted component. …

Bug 1579480 - newtab DS cards not removing idle callback

---

lib/ASRouter.jsm
lib/ASRouterTriggerListeners.jsm
test/unit/asrouter/ASRouterTriggerListeners.test.js
test/unit/unit-entry.js

There was a lot of code duplication between the two triggers so I'm happy we're able to remove most of it.
For testing I enabled the local CFRMessageProvider and set targeting to `"true"` to ensure everything triggers instantly.

Bug 1561880 - Refactor browser window listeners to use EveryWindow.jsm

---

lib/ActivityStream.jsm
test/unit/lib/ActivityStream.test.js
test/unit/utils.js

r?@ScottDowne or @k88hudson Similar to #4531 except handle dynamic prefs to reuse existing defaults while still allowing a temporary default (for dummy geo).
You can test with the existing `firefox.js` to dynamically set on geo change for a new profile. Then also test with an explicit `false` pref (as well as `true`).

Bug 1559185 - Use existing default prefs for dynamic prefs too

---

lib/ASRouter.jsm
lib/ToolbarPanelHub.jsm
test/unit/asrouter/ASRouter.test.js
test/unit/lib/ToolbarPanelHub.test.js

So far the `Show` button in our devtools didn't work for what's new messages.
With this PR clicking show will
* set the panel content to that specific message
* restore the original panel content after the panel is hidden
Works best with the `Disable Pop-up Autohide` feature of the Browser Toolbox but it's not required (clicking show and then opening the panel also works).
No support for multiple messages at once.
0. Have
Pref name | Prev Value
--- | ---
browser.newtabpage.activity-stream.asrouter.providers.panel_local_testing | {"id":"panel_local_testing", "cohort": "SHOW_TEST"}
browser.newtabpage.activity-stream.asrouter.devtoolsEnabled | true
1. Confirm the panel is visible and populated with messages (might require a restart)
1. In ASRDevtools (`about:newtab#asrouter`)
2. Select the …

Bug 1561942 - Messaging System devtools support for What's New panel

---

content-src/asrouter/components/ConditionalWrapper/ConditionalWrapper.jsx
content-src/asrouter/templates/FXASignupSnippet/FXASignupSnippet.schema.json
content-src/asrouter/templates/NewsletterSnippet/NewsletterSnippet.schema.json
content-src/asrouter/templates/SendToDeviceSnippet/SendToDeviceSnippet.schema.json
content-src/asrouter/templates/SimpleSnippet/SimpleSnippet.jsx
content-src/asrouter/templates/SubmitFormSnippet/SubmitFormSnippet.schema.json
contributing.md
lib/SnippetsTestMessageProvider.jsm

- FXASignupSnippet
- NewsletterSnippet
- SendToDeviceSnippet
Update link to unit testing guide in docs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1546165

[fix bug 1546165] Add optional heading/icon to snippets:

---

content-src/components/DiscoveryStreamComponents/DSDismiss/DSDismiss.jsx
content-src/components/DiscoveryStreamComponents/DSDismiss/_DSDismiss.scss
content-src/components/DiscoveryStreamComponents/DSTextPromo/_DSTextPromo.scss
content-src/styles/_mixins.scss

To test:
2. Update `browser.newtabpage.activity-stream.discoverystream.config` with `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://5ad1b408-b40a-4a49-b6ec-27473d192df0.mock.pstmn.io/layout-1577654"} `
3. Verify requested changes [per ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1577655)

Bug 1577655 - Dismiss wrapper design tweaks

---

lib/ASRouterTriggerListeners.jsm
lib/PanelTestProvider.jsm
test/unit/asrouter/PanelTestProvider.test.js

I added support to `openURL` trigger for [`MatchPattern`s](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) and landed a testable CFR that recommends Firefox Send.

Bug 1569700 - CFR: recommend firefox send for PDFs

---

ping-centre/PingCentre.jsm
test/unit/ping-centre/PingCentre.test.js
test/unit/unit-entry.js

Test instructions:
* Flipping `browser.newtabpage.activity-stream.telemetry` and `browser.newtabpage.activity-stream.telemetry.structuredIngestion`
* Open Browser Toolbox from the Tools menu and switch to the `Network` tab
* Open a newtab, and scroll down until you see some Pocket stories, and then close the tab
* Check the `Domain` column, and look for `incoming.telemetry.mozilla.org`
* Click on any entry, make sure the `Requeset headers` from the `Headers` section in the side view contains `"Content-Encoding": gzip`, and the value in the `Params` section is in binary format

Bug 1581209 - enable gzip compression for Structure Ingestion payload

---

content-src/asrouter/docs/targeting-attributes.md
lib/ASRouterTargeting.jsm
test/browser/browser_asrouter_targeting.js
test/unit/unit-entry.js

I'm exposing the `cfrFeatures` and `cfrAddons` user prefs to be used in targeting expressions. We can then update targeting on required messages to prevent showing them.
I've combined all `defineModuleGetter` calls into 1 `defineLazyModuleGetters` call and converted all preference accesses to use `defineLazyPreferenceGetter`. 
It's not very thorough but I am seeing some small improvements comparing two profiles with/without (compared 3 separate runs and results seems in favor of profile 2 every time).
Profile 1 is without the patch Profile 2 is with.
https://profiler.firefox.com/compare/calltree/?globalTrackOrder=0-1-2&implementation=js&localTrackOrderByPid=88621%20from%20profile%201-0~89339%20from%20profile%202-0~&profiles[]=https%3A%2F%2Fperfht.ml%2F3066ph6&profiles[]=https%3A%2F%2Fperfh …

Bug 1570332 - Expose user prefs values to targeting expressions

---

content-src/asrouter/templates/OnboardingMessage/WhatsNewMessage.schema.json
lib/PanelTestProvider.jsm

I think a reason this was skipped is because it wasn't part of the schema.

Bug 1582005 - Add bucket_id as a required field

---

lib/ToolbarPanelHub.jsm
test/unit/lib/ToolbarPanelHub.test.js

The current behavior is that [PanelMultiView triggers](https://searchfox.org/mozilla-central/rev/7531325c8660cfa61bf71725f83501028178cbb9/browser/components/customizableui/PanelMultiView.jsm#1830-1837) `doCommand` and dispatches `mousedown` and `click` events on keyboard events to the focused element.
We currently don't do anything for `doCommand` and the navigation happens because of the `click` event that's being dispatched.
The bug is caused because on `Space` events on the link element, we go through the flow described above and additionally another `click` event happens on the [`messageEl`](https://github.com/mozilla/activity-stream/blob/4d9d4cc21856beb4261214aee8420f1adfa3babb/lib/ToolbarPanelHub.jsm#L275). 
I couldn't figure out where this is coming from so instead I switched to a …

Bug 1582061 - What's New links open twice when accessed with 'Space' key

---

test/browser/browser_onboarding_rtamo.js

The issue is caused by `browser_onboarding_rtamo.js` that doesn't properly cleanup the attribution data. Mochitests use a fresh profile on every run but attribution data is persisted to disk.
Cleanup is different between mac and windows because the APIs are platform specific and `AttributionCode.jsm` doesn't expose a unified API to restore everything.

Bug 1584625 - browser_aboutwelcome.js mochitest fails when run twice

---

content-src/components/TopSites/TopSite.jsx
docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
test/schemas/pings.js
test/unit/content-src/components/TopSites.test.jsx

This adds a new card_type `spoc` to identify a SPOC top site. When one clicks or dismisses a SPOC top site, we will include this value into the telemetry ping so that click-through rate and dismissal rate could be calculated accordingly.
Note that the icon type `custom-screenshot` is not a new addition but a document miss when we implemented the custom top site feature, added it back in for the completeness.
This needs a data review.
@punamdahiya Scott is on PTO now, could you take a look at this one?

Bug 1576680 - Telemetry additions for SPOC Topsites

---

content-src/components/DiscoveryStreamComponents/DSPrivacyModal/DSPrivacyModal.jsx
content-src/lib/link-menu-options.js
docs/v2-system-addon/data_events.md
test/schemas/pings.js
test/unit/content-src/components/DiscoveryStreamComponents/DSPrivacyModal.test.jsx

You can verify the new telemetry by enabling the telemetry [logging](https://github.com/mozilla/activity-stream/blob/master/content-src/asrouter/docs/debugging-docs.md#how-to-test-telemetry-pings).

Bug 1578579 - Add telemetry for ad privacy info

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/DSLinkMenu/DSLinkMenu.jsx
content-src/components/DiscoveryStreamComponents/Hero/Hero.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
content-src/lib/link-menu-options.js
lib/ActivityStream.jsm
lib/DiscoveryStreamFeed.jsm
lib/PlacesFeed.jsm
test/unit/content-src/components/DiscoveryStreamComponents/DSDismiss.test.jsx
test/unit/lib/DiscoveryStreamFeed.test.js

To test:
1. Ensure `browser.newtabpage.activity-stream.discoverystream.enabled` is true.
2. Ensure `browser.newtabpage.activity-stream.discoverystream.config` is enabled along with spocs, example: `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":true,"personalized":false,"layout_endpoint":"https://getpocket.cdn.mozilla.net/v3/newtab/layout?version=1&consumer_key=$apiKey&layout_variant=basic"}`
3. Ensure `browser.newtabpage.activity-stream.discoverystream.endpoints` is set to `http,https` to allow the custom spoc url used for testing.
4. Set `browser.newtabpage.activity-stream.discoverystream.spocs-endpoint` to `https://e5e8374d-fffa-4a77-a604-31603852b6fd.mock.pstmn.io/t-1579966`
5. Open a new tab.
6. Dismiss the …

Bug 1579966 - Campaign id blocks

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss

Test steps: https://bugzilla.mozilla.org/show_bug.cgi?id=1585387#c0

Bug 1585387 - The font of the hyperlink and button label from the sponsored content cards is wrongly set to "Regular" instead of "Semibold"

---

content-src/asrouter/templates/OnboardingMessage/ToolbarBadgeMessage.schema.json
lib/OnboardingMessageProvider.jsm
lib/ToolbarBadgeHub.jsm
locales-src/asrouter.ftl
test/unit/lib/ToolbarBadgeHub.test.js

This is one idea for fixing the notification description, posting this for discussion.
I've used the OSX VoiceOver software to test this. The screenshot shows the button description as "What's New New feature": a combination of the button's own description and the element referred to via `aria-labelledby`.
The idea is to use the hidden elements associated with any `toolbarbutton` [that has a badge](https://searchfox.org/mozilla-central/rev/f1e99da78fe6c3c68696358dac06aed90f8112d3/toolkit/content/widgets/toolbarbutton.js#110) to hold the button description.
[One issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1576510#c1) described in the bug comment was related to the string needed to describe the notification. I think we have more flexibility here because we can have a set of strings …

Bug 1576510 - Use aria-labelledby to add additional description information to badged toolbar buttons

---

content-src/components/DiscoveryStreamComponents/DSImage/DSImage.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSImage.test.jsx

1. Set `browser.newtabpage.activity-stream.debug` to true
2. Open a new tab
3. Open about:config
4. Toggle `browser.newtabpage.activity-stream.discoverystream.enabled` on and off, a few times.
5. Check console.
Expected, no errors about setState on unmounted dsimage. "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."

Bug 1587926 - Idle callback with dsimage

---

content-src/asrouter/templates/Trailhead/_Trailhead.scss

~~@k88hudson As far as I can tell & observe this isn't causing any regressions, but since the modal is used by trailhead I figured you might be able to give a 2nd opinion there. Positioning is `fixed` by default and this was overriding to `absolute` – unsure why. 🤔~~
Test steps: https://bugzilla.mozilla.org/show_bug.cgi?id=1589025#c0

Bug 1589025 - Displaying privacy modal in correct position

---

content-src/components/DiscoveryStreamComponents/DSCard/_DSCard.scss

Test steps: See https://bugzilla.mozilla.org/show_bug.cgi?id=1583845#c0
**Note:** To see a CTA button you'll need to use this value for `browser.newtabpage.activity-stream.discoverystream.config`
`{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://e5e8374d-fffa-4a77-a604-31603852b6fd.mock.pstmn.io/1583845-layout"}`

Bug 1583845 - Fixing CTA button colors

---

.taskcluster.yml

Hi!
I work on the Taskcluster team at Mozilla, and I'm writing to let you know about an upcoming change to our deployment of Taskcluster that will affect this project's use of Taskcluster for CI/CD.
We're splitting Taskcluster for Firefox CI and Taskcluster for community projects into separate deployments. The current integration will continue to work through November 9th, at which point this change will be needed for your Taskcluster integration to continue to work.
The first step of the conversion work happened here: https://github.com/mozilla/activity-stream/pull/5288, that PR upgraded the syntax of the taskcluster.yml file and Github integration to [v1](https://docs.taskcluster.net/docs/reference/integrations/github/taskcluster-yml-v1).
There are two next steps:
- changing the Github …

Bug 1574657: switch taskcluster provisionerId/workerType for community deployment

---

content-src/components/TopSites/TopSitesConstants.js

To test:
2. Update `browser.newtabpage.activity-stream.discoverystream.config` with `{"api_key_pref":"extensions.pocket.oAuthConsumerKey","collapsible":true,"enabled":true,"show_spocs":true,"hardcoded_layout":false,"personalized":false,"layout_endpoint":"https://5ad1b408-b40a-4a49-b6ec-27473d192df0.mock.pstmn.io"}`
3. Click the three dot context menu on Netflix top site. You should see "Our sponsors & your privacy". Clicking it should show privacy modal.

Bug 1594173 - Add Ad Privacy Info Modal to Top Sites Tile

---

lib/ActivityStream.jsm
lib/TelemetryFeed.jsm
ping-centre/PingCentre.jsm
test/unit/lib/TelemetryFeed.test.js
test/unit/ping-centre/PingCentre.test.js

This is the part 2 of https://phabricator.services.mozilla.com/D53875, which shuts off all the telemetry in Activity/Discovery Stream to Tiles data pipeline.

Bug 1597697 - Stop sending pings to Tiles data pipeline

---

content-src/components/DiscoveryStreamBase/DiscoveryStreamBase.jsx
content-src/components/DiscoveryStreamComponents/DSMessage/DSMessage.jsx
content-src/components/DiscoveryStreamComponents/Navigation/Navigation.jsx
content-src/lib/selectLayoutRender.js
lib/ActivityStream.jsm
lib/DiscoveryStreamFeed.jsm
lib/PrefsFeed.jsm
test/unit/content-src/components/DiscoveryStreamBase.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/DSMessage.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/Navigation.test.jsx
test/unit/content-src/lib/selectLayoutRender.test.js
test/unit/lib/ActivityStream.test.js
test/unit/lib/DiscoveryStreamFeed.test.js

A note, this relies on https://phabricator.services.mozilla.com/D53236 in MC to properly enabled 7 rows in English based locales. So if you happen to be using this patch locally without the above MC patch, you need to create this pref `browser.newtabpage.activity-stream.discoverystream.lang-layout-config` with the value `en`
To test:
1. Setup a profile enabled with DE. You can find help with how to do that here: https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/geo_locale.md
2. Enable Discovery Stream.
3. Load a new tab.
Expected: no spocs, no english strings, no navigation component under cards, and complete new content that's de based. Also check that en-US/en-CA has not changed. Also, DE should only be 1 row of content. You can change the value in …

Bug 1567273 - Enable DE using Discovery Stream

---

lib/TelemetryFeed.jsm
test/unit/lib/TelemetryFeed.test.js

This migrates all Event pings in AS/DS to the Structured Ingestion pipeline.
Steps to test:
* Turn on PingCentre logging
* Turn on AS Telemetry as well as Structured Ingestion by flipping "activity-stream.telemetry" and "activity-stream.telemetry.structuredIngestion"
* Click any card on the newtab page, or search in the search box
* You should see events ping logged in the browser console
* You can further check if those pings made to the database by using this [query](https://sql.telemetry.mozilla.org/queries/65254/source), note that you might need to change the date in it.

Bug 1597697 - Migrate events ping to the new data pipeline

---

content-src/components/DiscoveryStreamComponents/DSCard/DSCard.jsx
content-src/components/DiscoveryStreamComponents/List/List.jsx
docs/v2-system-addon/data_dictionary.md
docs/v2-system-addon/data_events.md
test/schemas/pings.js
test/unit/content-src/components/DiscoveryStreamComponents/DSCard.test.jsx
test/unit/content-src/components/DiscoveryStreamComponents/List.test.jsx

This adds a `card_type` field to the `CLICK` ping for Top Stories. Note that this doesn't change the Pocket telemetry (i.e. with `impression_id` and `tile_id`), but the user event ping, which contains `client_id` without `tile_id`. Per bug 1597492, this will be useful for us to study the user engagement of Top Story related experiments. 
This requires a data review.

Bug 1597492 - Add Pocket tile type to Top Story click ping
