- .travis.yml
- package.json
Forgot a dependency here. Added bundle to travis so we make sure we don't break it.
@oyiptong or @rlr R?
> chore(npm): Add cpx dependency, add bundle task to ci

- .eslintrc
> chore(lint): ensure there are no trailing spaces

- .gitignore
> chore(git): ignore xpi files

- content-src/actions/action-manager.js
- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/Base/Base.js
- content-src/components/Base/Base.scss
- content-src/components/Header/Header.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/lib/shim.js
- content-src/main.scss
- content-src/reducers/reducers.js
- content-src/styles/variables.scss
- content-test/components/ActivityFeed.test.js
- package.json
This implements the ActivityFeed component + tests
> Implement ActivityFeed component

- content-src/components/Base/Base.js
- content-src/components/Base/Base.scss
- content-src/components/Header/Header.js
- content-src/components/Header/Header.scss
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/NewTabPage/NewTabPage.scss
- content-src/components/Routes/Routes.js
- content-src/components/TimelinePage/TimelinePage.js
- content-src/components/TimelinePage/TimelinePage.scss
- content-src/main.js
- content-src/main.scss
- content-src/styles/variables.scss
- content-test/components/ActivityFeed.test.js
- content-test/components/NewTabPage.test.js
- content-test/components/Routes.test.js
- content-test/components/TimelinePage.test.js
- content-test/test-utils.js
- package.json
This
* adds hashed base routing (see `components/Routes`)
* moves the new tab specific stuff into a `NewTabPage` component
* adds a `TimelinePage` component`
* adds a location dropdown to header
* tests
> #44: Add routing, timeline page

- npm-shrinkwrap.json
> chore(npm): #77 Update npm-shrinkwrap.json

- .gitignore
- content-src/components/Base/Base.js
- content-src/components/Header/Header.js
- content-src/components/Header/Header.scss
- content-src/components/NewTabPage/NewTabPage.scss
- content-src/components/Routes/Routes.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TimelinePage/TimelinePage.js
- content-src/components/TimelinePage/TimelinePage.scss
- content-src/main.scss
- content-src/static/activity-streams.html
- content-src/styles/variables.scss
- content-test/components/Header.test.js
- data/content/activity-streams.html
Adds font-awesome (for now) and some other little style improvements
> style(content): Minor style improvements, font-awesome

- content-src/components/Header/Header.scss
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TimelinePage/TimelinePage.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/styles/variables.scss
> #114 Placeholder boxes for spotlight and top sites components

- content-src/lib/fake-data.js
Lamest PR of all time, but my eyes cannot unsee.
> chore(typo): Fixing Facebook typo in fake shim data

- lib/ActivityStreams.js
- test/test-awesomebar-empty.js
> feat(addon-ui) #94 hide url in awesomebar

- .jpmignore
- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- yamscripts.yml
> feat(changelog): Adding CHANGELOG.md (via npm run changelog)

- .sass-lint.yml
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/Header/Header.scss
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TimelinePage/TimelinePage.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/lib/utils.js
- content-src/styles/variables.scss
- content-test/components/Spotlight.test.js
- content-test/lib/utils.test.js
> style(content): A bunch of small tweaks to get closer to spec

- lib/ActivityStreams.js
- lib/TabTracker.js
- lib/main.js
- test/test-TabTracker.js
> feature(addon): #28 Tab open time data collection.

- content-src/actions/action-manager.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
> Closes #149 - Implement delete history API

- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/Base/Base.scss
- content-src/components/Header/Header.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/NewTabPage/NewTabPage.scss
- content-src/components/Search/Search.js
- content-src/components/Search/Search.scss
- content-src/components/SiteIcon/SiteIcon.scss
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TimelinePage/TimelinePage.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/main.scss
- content-src/styles/variables.scss
- content-test/components/Header.test.js
- content-test/components/Search.test.js
- content-test/components/Spotlight.test.js
Design reference is: http://people.mozilla.org/~shorlander/activity-stream/activity-stream-04/start-page.html#
This implements the new layout design for new tab, including a "dummy" search component that will be fleshed out in future versions.
Mostly style updates, although I made the image selection for Spotlight slightly more sophisticated/added tests.
Fixes #163
> feat(content): #163 New layout for new tab

- lib/ActivityStreams.js
- test/test-awesomebar-empty.js
I love this!
R? @k88hudson @oyiptong 
Fixes #174
> fix(addon): #174 Fix this this issue

- package.json
- yamscripts.yml
oops! sorry @jaredkerim 
Fixes #188
> fix(npm): fix once command

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/TimelinePage/TimelinePage.js
- content-src/lib/fake-data.js
- content-test/components/ActivityFeed.test.js
- content-test/components/NewTabPage.test.js
- content-test/components/TimelinePage.test.js
- package.json
F? @k88hudson what do you think of this approach?
I basically created a `GroupedActivityFeed` component. That way we can still use the normal `ActivityFeed` for the bookmarks/top activity feed. Then the history feed uses the new component.
Fixes #160
> feat(content) #160 date handling

- lib/PlacesProvider.js
- test/test-PlacesProvider.js
> Closes  #165 - Add bookmark status to Recent Links API query

- content-src/actions/action-manager.js
- content-src/components/Base/Base.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
r+ in https://github.com/mozilla/activity-streams/pull/203.
Recreating PR to rebase on top of master
Approved by @oyiptong
> Closes #164 - Time-constrained top frecent links API

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/lib/fake-data.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
> Closes #204 - Unify timestamps across PlacesProvider queries and tests

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-test/components/ActivityFeed.test.js
I need to update this after https://github.com/mozilla/activity-streams/pull/208 lands
Fixes #210
> fix(content): #210 show real bookmark ui in ActivityFeed

- content-src/lib/embedly-middleware.js
- content-src/lib/parse-url-middleware.js
- content-src/lib/utils.js
- content-test/lib/utils.test.js
> feat(embedly): Remove basic auth and query string data for embedly requests

- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Search/Search.js
- content-test/components/Search.test.js
Just a couple of little touch-ups before we ship alpha
> Alpha fixes

- package.json
> fix(addon): make addon run on Firefox 45

- content-src/components/TimelinePage/TimelinePage.js
> fix(props): Convert GroupedActivityFeed length to number in jsx

- .travis.yml
Trying something @pdehaan suggested, described here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
Also disables emails
Fixes #216
> Travis configuration tweaks

- content-src/components/Base/Base.js
- content-src/components/Base/Base.scss
- content-src/components/Header/Header.js
- content-src/components/Routes/Routes.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-src/components/TimelinePage/TimelinePage.js
- content-test/components/TimelinePage.test.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
- test/test-TabTracker.js
This adds sub-routing to the Timeline view, and a bookmark filter for the Timeline layout.
For now this is basically the same layout as "All", but it may change in the future.
I also added the `Header` component to the `TimelinePage` page instead of `Base`.
Fixes #225 
Fixes #171
> feat(content): #225 Bookmarks filter on Timeline

- lib/PlacesProvider.js
- test/test-PlacesProvider.js
Decided to be simple, @oyiptong  let me know if you want something more thoughtful
Fixes #173
> Closes #173 - Filter out URLs with "places" url scheme

- content-src/components/Spotlight/Spotlight.js
- content-test/components/Spotlight.test.js
r? @k88hudson /cc @nchapman 
Fixes #192
> fix(entropy): Grab the first available image instead of highest entropy

- content-src/actions/action-manager.js
- content-src/components/Base/Base.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/lib/fake-data.js
- content-src/reducers/reducers.js
- lib/ActivityStreams.js
- lib/SearchProvider.js
- lib/main.js
- test/test-SearchProvider.js
r? @k88hudson @oyiptong 
Fixes #243 
Fixes #150
> fix(addon): #243 execute search with correct engine

- lib/ActivityStreams.js
- lib/TabTracker.js
- lib/TelemetrySender.js
- test/test-TabTracker.js
> fix(addon): #209 Save tab data in memory instead of simple storage and send notification on tab session completion.

- content-src/components/Routes/Routes.js
> fix(content): #262 s/componentDidUnmount/componentWillUnmount/

- config.default.yml
- config.production.yml
> chore(https): use https for embedly proxy

- CHANGELOG.md
> chore(changelog): 1.0.2 changelog

- content-src/components/SiteIcon/SiteIcon.js
- content-test/components/SiteIcon.test.js
r? @k88hudson @pdehaan 
Fixes #185
> fix(content) #185 convert protocol relative URLs to https

- content-src/actions/action-manager.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-src/lib/fake-data.js
- content-src/reducers/reducers.js
- content-src/selectors/selectors.js
- content-test/components/NewTabPage.test.js
- content-test/components/TimelinePage.test.js
- content-test/selectors/selectors.test.js
- content-test/test-utils.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
* Updates `NewTabPage` to use `FrecentHistory` instead of `History`
* Fixes bug where `FRECENT_LINKs_REQUEST` wasn't being listened for (d452ffb)
* Adjusts `getFrecentLinks` query to prioritize bookmarks (34bb017)
* Adds local sorting by date in `TopActivity`
> Update new tab page to use FrecentHistory

- .sass-lint.yml
- content-src/components/DebugPage/DebugPage.js
- content-src/components/DebugPage/DebugPage.scss
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/NewTabPage/NewTabPage.scss
- content-src/components/Routes/Routes.js
- content-src/main.scss
- content-src/styles/variables.scss
- package.json
I was thinking this might be useful for debugging -- it adds a little link in the bottom right corner if you hover over it for 0.2s.
What do you think @nchapman @pdehaan?
> chore(content): add hidden debug page

- .eslintrc
> chore(lint): Disable ESLint 'no-shadow' and 'no-warning-comments' rules

- data_dictionary.md
> docs(typo): Change about:newtab to 'Activity Stream'

- content-src/components/ActivityFeed/ActivityFeed.js
- content-test/components/ActivityFeed.test.js
> fix(activityfeed): Use fallback hostname if page doesnt have title

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/Base/Base.scss
- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/SiteIcon/SiteIcon.scss
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/lib/fake-data.js
- content-src/lib/shim.js
- content-src/lib/utils.js
- content-src/main.scss
- content-src/selectors/selectors.js
- content-src/styles/variables.scss
- content-test/components/SiteIcon.test.js
- content-test/components/TopSites.test.js
- content-test/lib/utils.test.js
- content-test/selectors/selectors.test.js
> feat(content): #193 improve icons

- content-src/actions/action-manager.js
- content-src/components/Base/Base.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/reducers/reducers.js
- content-src/selectors/selectors.js
- data/content-bridge.js
- dev-prefs.json
- lib/ActivityStreams.js
- lib/PerfMeter.js
- package.json
- test/test-PerfMeter.js
> Closes #19 - Instrument add-on for performance

- lib/ActivityStreams.js
- lib/Memoizer.js
- package.json
- test/resources/activity-streams-places-changes.html
- test/test-Memoizer.js
- test/test-caching.js
- test/test-workers.js
> feat(addon): #295 places query caching

- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
This adjusts NewTab to show recent history in TopActivity instead of FrecentHistory
> feat(content): #302 Tweak selectors for NewTabPage

- dev-prefs.json
- lib/ActivityStreams.js
- lib/TelemetrySender.js
- lib/main.js
- package.json
- test/test-TelemetrySender.js
- yamscripts.yml
> feat(addon): #291 Setup ping for tab tracking telemetry.

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-test/components/ActivityFeed.test.js
> fix(content) #314 remove date subtitles and show .calendar() on side

- lib/PlacesProvider.js
- test/test-PlacesProvider.js
> Closes #312 - Add before/after filters to getRecentBookmarks

- content-src/actions/action-manager.js
- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/LoadMore/LoadMore.js
- content-src/components/LoadMore/LoadMore.scss
- content-src/components/Loader/Loader.js
- content-src/components/Loader/Loader.scss
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-src/components/TimelinePage/TimelinePage.js
- content-src/main.scss
- content-src/reducers/reducers.js
- content-src/styles/variables.scss
- content-test/components/LoadMore.test.js
- content-test/components/Loader.test.js
- content-test/components/TimelinePage.test.js
- content-test/test-utils.js
- lib/ActivityStreams.js
This fixes half of #222, the rest is blocked by https://github.com/mozilla/activity-streams/issues/312
> feat(content): Add pagination to TimelineHistory

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-test/components/ActivityFeed.test.js
> fix(content): make entire activity item row clickable

- content-src/components/ActivityFeed/ActivityFeed.scss
r? @k88hudson (since I stole your `flex-shrink` solution)
Fixes #313 
Fixes #327
> fix(css): Fix mis-aligned ActivityStream icons

- content-src/selectors/selectors.js
> fix(content): #337 Use white bg as default SiteIcon bg

- lib/ActivityStreams.js
- lib/PerfMeter.js
- lib/TabTracker.js
- lib/TelemetrySender.js
- lib/main.js
- package.json
- test/test-TabTracker.js
- test/test-TelemetrySender.js
We did not turn on telemetry by default.
This PR fixes this.
r? anyone?
> Turn on telemetry

- README.md
- common/action-manager.js
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-test/components/TimelinePage.test.js
> feat(content): #222 add bookmarks pagination

- webpack.config.js
This doesn't actually cause a bug but prevents one from happening in the future
> fix(build): Add common dir to webpack

- .jpmignore
r? @k88hudson @oyiptong 
Fixes #357
> fix(xpi): Remove /test/ directory from generated XPI

- lib/TabTracker.js
- test/test-TabTracker.js
> Closes #308 - Add load latency to telemetry ping

- content-src/components/ActivityFeed/ActivityFeed.js
- content-test/components/ActivityFeed.test.js
> fix(ActivityFeed): Make date/time formats consistent

- README.md
r? @pdehaan or @rlr 
fixes #252
> chore(readme): #252 Update readme to reflect action schema

- content-src/components/TimelinePage/TimelineBookmarks.js
> fix (content): #272 display bookmarked date on Bookmarks timeline

- content-src/components/Header/Header.js
- content-src/components/Header/Header.scss
- content-src/components/TimelinePage/TimelinePage.js
- content-test/components/Header.test.js
We don't need the dropdown for now since it doesn't do much, but we will in the future.
Fixes #422
> fix(content): #422 disable menu on header

- content-src/components/NewTabPage/NewTabPage.js
> fix(newtab): Set ActivityFeed length to 10 items

- content-src/components/TimelinePage/TimelineBookmarks.js
> fix(bookmarks): Remove Highlights from Bookmarks page

- lib/TabTracker.js
- test/test-TabTracker.js
> Closes #430 - Add page identifier to tab-session ping

- content-src/components/NewTabPage/NewTabPage.js
> fix(newtab): Add Timeline button to Recent Activity

- common/action-manager.js
- lib/ActivityStreams.js
- lib/TabTracker.js
- lib/TelemetrySender.js
- test/test-TabTracker.js
> feature(addon): #427 Addon handling of UX user event notifications.

- common/action-manager.js
- common/event-constants.js
- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/Base/Base.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-src/components/TopSites/TopSites.js
- content-test/components/ActivityFeed.test.js
- content-test/components/NewTabPage.test.js
- content-test/components/Spotlight.test.js
- content-test/index.js
- content-test/selectors/selectors.test.js
- lib/ActivityStreams.js
- lib/TabTracker.js
- test/test-TabTracker.js
Including clicks, deletes, shares, search, load more
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/465)
> Instrument user events

- dev-prefs.json
- package.json
r? @jaredkerim
Fixes #463 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/474)
> closes #463: change embedly proxy target to staging environment

- content-src/selectors/selectors.js
topActivityRows is already using History, but this was wrong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/486)
> fix(content): #396 Use history in TopActivity

- lib/TabTracker.js
- test/test-TabTracker.js
Fixes #366 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/478)
> Closes #366 - Investigate why and when tab ping session duration is 0

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/TopSites/TopSites.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/485)
> chore(content) #91 Use timestamp for keys

- bin/generate-html.js
Fixes #310 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/499)
> chore(content): #310 Add meta tag for CSP.

- content-src/components/TopSites/TopSites.js
- content-src/main.scss
Fixes #386 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/508)
> style(content): #386 bring top sites border to top

- package.json
Fixes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/495)
> fix(icon): Add icon to about:addons

- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/Base/Base.scss
- content-src/components/Search/Search.js
- content-src/components/Search/Search.scss
- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TopSites/TopSites.scss
- content-src/main.scss
- content-src/selectors/selectors.js
- content-src/static/img/glyph-forward-16-white.svg
- content-src/styles/variables.scss
Fixes #396, Fixes #489, Fixes #498, Fixes #502 
This should also fix:
#498 Highlight boxes are different sizes
#502 Long titles have a bit of overflow on highlights
#489 Fallback icons aren't square
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/511)
> style(content): #396 Fix spacing, colors, fonts

- lib/PreviewProvider.js
- test/test-PreviewProvider.js
r? @k88hudson
Fixes #513 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/519)
> fix(caching): #513 handle toggling rich previews properly

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/522)
> Add TestPilot badge to README

- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
r? @k88hudson
Fixes #490 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/516)
> fix (content): #490 apply block list to selectSpotlight

- lib/TabTracker.js
- test/test-TabTracker.js
Fixes #501
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/524)
> Closes #501 - Remove "source" property for tab session duration ping

- content-src/components/Spotlight/Spotlight.js
- content-src/lib/shim.js
- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
I also added a couple of things to shim so we can see changes more easily
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/528)
> feat(content): Empty case for highlights

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/ActivityFeed/ActivityFeed.scss
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-test/components/ActivityFeed.test.js
Adds date headings to Timeline, only shows date headings at the top of a day
Fixes #398 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/534)
> feat(content): #398 Show date headings on Timeline

- content-src/components/ActivityFeed/ActivityFeed.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/536)
> style(content): #526 Fix star position

- lib/PerfMeter.js
- test/test-PerfMeter.js
Fixes #311 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/530)
> Closes #311 - A performance logger that collects statistics

- lib/ActivityStreams.js
- package.json
- test/test-ActivityStreams-private-browsing.js
r? @oyiptong 
I may have just had a shot after getting the tests to work without any help 🎉. I'll revisit the tests in that other PR now that I am feeling lucky.
Fixes #532 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/538)
> fix (addon): #532 no activity stream for private browsing windows

- content-src/components/DebugPage/DebugPage.js
- content-src/components/DebugPage/DebugPage.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/537)
> chore(debugger): Added ui component and data source tester

- lib/PreviewProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/540)
> fix(addon): #539 Add v to list of allowed query params

- lib/PerfMeter.js
- test/test-PerfMeter.js
r? @oyiptong 
oy. Let me know about my attempt to test this :eyes:
Fixes #460 
Fixes #467 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/514)
> fix (addon): #460, #467 fix for tab restore

- content-src/static/img/glyph-activityStream-16.svg
- content-src/static/img/list-icon.svg
Had to update the icon so it’s not mistaken for the bookmarks
door-hanger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/544)
> New icon for the add-on

- content-test/components/ActivityFeed.test.js
- content-test/components/Spotlight.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/548)
> tests(content): #462 Fix intermittent test failure issue

- content-src/components/DeleteMenu/DeleteMenu.js
- content-test/components/DeleteMenu.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/569)
> fix(content): Updating wording of block action

- package.json
- yamscripts.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/567)
> fix(jpm): Use stable for npm run firefox

- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
Fixes #554
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/566)
> fix(content): #554 only include default sites if init is true

- content-src/components/DebugPage/DebugPage.js
Fixes #574 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/575)
> fix(debug): #574 Use Highlights on debug page

- .jpmignore
- .travis.yml
- artifacts/latest/latest.html
- bin/continuous-integration.sh
- fabfile.py
This change in automation deploys to the bucket at https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html
We'll know if the "master"-only branch works when we merge this PR
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/580)
> Continuous deployment

- data_events.md
- lib/TelemetrySender.js
- test/test-TelemetrySender.js
I'm also gonna write up a script for checking each event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/587)
> Telemetry logging

- content-src/components/Search/Search.js
Fixes #590 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/591)
> fix(content): #590 Update search placeholder

- content-src/components/ActivityFeed/ActivityFeed.js
- content-test/components/ActivityFeed.test.js
Fixes #592 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/593)
> fix(content): #592 Change date format for headers

- package.json
Stole the description from https://testpilot.firefox.com/experiments.
We should still probably fix #599 before public release.
Fixes #492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/600)
> chore(addon): Update description in package.json

- common/action-manager.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- package.json
- test/test-ActivityStreams-places-caching.js
- test/test-PlacesProvider-blockedURLs.js
- test/test-PlacesProvider.js
This provides the data backend as well as content API to block links.
It provides the ability to:
1. block a url
2. unblock a url (e.g. for an undo functionality)
3. unblock all urls
r? @k88hudson since you'll be the consumer of this API
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/598)
> 484 persist block list

- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
/cc @nchapman
Fixes #620 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/621)
> fix(content): #620 Fix top site containers

- lib/PlacesProvider.js
- test/test-PlacesProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/623)
> fix(addon): #608 Order bookmarks by date created instead of date modified

- content-src/components/LoadMore/LoadMore.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/634)
> style(content) #586 align loading spinner

- package.json
r? @oyiptong
Fixes #622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/628)
> chore(package): Add Test Pilot link in package description

- lib/ActivityStreams.js
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/635)
> feat(previews): do not wait on embedly call to return links

- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/TimelinePage/TimelineBookmarks.js
- content-src/components/TimelinePage/TimelineHistory.js
- content-src/main.scss
This should help a bit to make the UI feel less "janky" on first load
Fixes #610 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/645)
> style(content): #610 Fade in main sections on init

- package.json
r? @emtwo
Fixes #565 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/644)
> chore(previews): #565 use prod embedly proxy

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/653)
> fix travis error

- lib/PreviewProvider.js
- test/test-PreviewProvider.js
r? @oyiptong @k88hudson
Fixes #646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/654)
> fix (addon): #646 do not throw exception on invalid uri component

- README.md
- artifacts/latest/latest.html
- fabfile.py
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/667)
> chore(meta): drop plural from activity stream in addon metadata

- README.md
Change from `npm tests` to `npm test` on the readme page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/672)
> Correct running tests command

- common/action-manager.js
- common/event-constants.js
- lib/ActivityStreams.js
- lib/PlacesProvider.js
- test/test-PlacesProvider.js
Fixes #670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/683)
> feat(addon): add the API to remove a bookmark

- lib/PreviewProvider.js
- test/test-PreviewProvider.js
@jaredkerim r? 😸
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/686)
> fix(addon): #671 Reduce duplicate queries to embedly

- lib/PreviewProvider.js
- test/test-PreviewProvider.js
easy peasy lemon squeeze @jaredkerim r?
Fixes #679 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/688)
> feat(addon): #679 Send addon version to embedly proxy

- test/test-PreviewProvider.js
@jaredkerim r? 
Just a quick little test
Fixes #428 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/689)
> tests(addon): #428 Ensure embedly client throws out non-requested responses

- .sass-lint.yml
Fixes #690 
@sarracini
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/691)
> fix(lint): order sass rules by alphabetical order

- lib/ActivityStreams.js
- lib/PreviewProvider.js
- test/test-PreviewProvider.js
Working on a test for it now, but this fixes the null problem. yay!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/697)
> fix(addon): #518 Fix Embedly proxy receiving null URLs

- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/SiteIcon/SiteIcon.scss
- content-test/components/SiteIcon.test.js
@k88hudson r?
Fixes #632 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/734)
> fix(content): #632 Bug 1269777 - Google search string from context menu wrongly searches

- lib/SearchProvider.js
@oyiptong r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/736)
> fix(addon): Bug 1273164 - The search bar from New Tab page is no longer working on latest Nightly version

- content-src/components/Search/Search.js
- content-src/components/Search/Search.scss
- content-test/components/Search.test.js
@k88hudson r? :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/738)
> fix(content): #723 Bug 1273923 - Remove 'Please fill out this field' tooltip

- lib/ActivityStreams.js
- test/lib/cachePromises.js
- test/test-ActivityStreams-async-preview-cache-rebuild.js
- test/test-ActivityStreams-places-caching.js
r? @oyiptong 
What do you think? How will this interact with the preview cache timing out in a longer period?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/742)
> fix (addon): #663 rebuild the places cache after 30 minutes

- data_dictionary.md
@ncloudioj r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/749)
> Add a description of performance ping #705

- lib/ActivityStreams.js
- lib/PreviewProvider.js
- lib/TabTracker.js
- lib/TelemetrySender.js
- test/test-PreviewProvider.js
- test/test-TabTracker.js
@jaredkerim r? 🐱
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/758)
> feat(metrics): #705 Collect proxy telemetries from addon

- dev-prefs.json
Fixes #737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/744)
> fix(prefs): Switch to production embedly-proxy URL

- lib/TabTracker.js
- test/test-TabTracker.js
Fixes #760 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/771)
> fix(addon): #760 Add pageshow event to keep track of clicks on the 'back' button.

- lib/TabTracker.js
- test/test-TabTracker.js
Fixes #759 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/780)
> fix(addon): #759 Add session_id for all pings.

- content-src/components/TimelinePage/TimelineFeed.js
r? @k88hudson what you think of this way to fix it?
Fixes #774 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/786)
> fix (content): #774 fix zoom, resize, high res issues

- common/action-manager.js
- common/event-constants.js
- content-src/lib/shim.js
- content-src/store.js
- lib/ActivityStreams.js
- test/test-ActivityStreams-message-passing.js
- test/test-ActivityStreams-places-caching.js
- test/test-TabTracker.js
- Adds constants for addon-to-content, content-to-addon
- Consolidates listeners for addon's communication with content
- Consolidate listeners for places change events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/791)
> Refactor listeners

- lib/TabTracker.js
- test/test-TabTracker.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/809)
> fix(addon): #808 fix uncertain load_reason for the back button

- lib/ActivityStreams.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/823)
> fix(addon): #821 - increase group size for experiment delete menu

- common/action-manager.js
- content-src/components/Base/Base.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Search/Search.js
- content-src/components/Search/Search.scss
- content-src/lib/fake-data.js
- content-src/reducers/reducers.js
- content-src/reducers/setSearchContent.js
- content-src/static/img/glyph-search-history.svg
- content-src/styles/variables.scss
- content-test/components/NewTabPage.test.js
- content-test/components/Search.test.js
- lib/ActivityStreams.js
- lib/SearchProvider.js
- test/test-SearchProvider.js
This is the giant PR which got split into #797 for addon-side work and #798 for content-side work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/799)
> feat(addon): Get Search working in Activity Stream

- content-src/components/Search/Search.js
- content-test/components/Search.test.js
Ooops
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/827)
> fix(content): Fix suggestion index

- lib/ActivityStreams.js
- test/test-ActivityStreams-home-page.js
r? @oyiptong
Fixes #724 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/785)
> feat (addon): #724 set home page to Activity Stream

- lib/ActivityStreams.js
- test/test-TabTracker.js
Fixes #790 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/795)
> feat(addon): #790 collect uninstall event pings

- content-src/components/LinkMenu/LinkMenu.js
- content-src/components/NewTabPage/NewTabPage.scss
- content-test/components/LinkMenu.test.js
Quick fix for this one. R? @oyiptong @sarracini or @rlr?
Fixes #833 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/839)
> fix(content): #833 Separator for delete is in the wrong place

- content-src/components/Search/Search.js
@rlr r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/866)
> fix(content): #843 Fix delete key bindings for search

- content-src/components/Search/Search.scss
- content-src/styles/variables.scss
@k88hudson super quick r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/865)
> fix(content): #846 Normal Select cursor changes to Text Select cursor

- content-src/components/Search/Search.scss
@k88hudson r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/850)
> fix(content:): #844 Add text wrapping to search string

- lib/PreviewProvider.js
😼 @jaredkerim r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/867)
> fix(addon): #694 Remove unused newOnly flag

- content-src/components/LinkMenuButton/LinkMenuButton.scss
- content-src/components/Search/Search.js
- content-src/components/Search/Search.scss
- lib/SearchProvider.js
Fixes  #854 #846
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/869)
> fix(content): #846 Change cursor, center dots, and bold search string

- lib/ActivityStreams.js
- lib/PreviewProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/872)
> fix(addon): #741 Refactor PreviewProvider to hide link processing

- lib/PreviewProvider.js
- test/test-PreviewProvider.js
🎉 r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/873)
> fix(addon): Make private functions private in PreviewProvider

- content-src/components/LinkMenu/LinkMenu.js
- content-test/components/LinkMenu.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/889)
> fix(content): #887 Only hide delete options on bookmarks page

- addon-src/vendor.js
- content-src/components/LinkMenu/LinkMenu.js
- content-src/lib/fake-data.js
- content-src/reducers/Experiments.js
- content-src/reducers/reducers.js
- content-test/components/LinkMenu.test.js
- content-test/experiments.test.js
- content-test/reducers/Experiments.test.js
- experiments.json
- experiments_how_to.md
- lib/ActivityStreams.js
- lib/ExperimentProvider.js
- lib/TabTracker.js
- lib/vendor-src.js
- test/test-ExperimentProvider.js
- test/test-TabTracker.js
- webpack.addon.config.js
This patch adds a experiment definition framework in the form of a json file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/886)
> Experiment definition framework

- content-src/components/LinkMenu/LinkMenu.js
- content-src/lib/fake-data.js
- content-src/reducers/Experiments.js
- content-test/components/LinkMenu.test.js
- content-test/reducers/Experiments.test.js
- experiments_how_to.md
- lib/ExperimentProvider.js
- test/test-ExperimentProvider.js
This was causing possible bug vectors; also, this is simpler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/902)
> Make experiments less deeply nested

- lib/MetadataStore.js
- test/test-MetadataStore.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/909)
> chore(metadata): #908 Allow partial inserts to MetadataStore

- lib/RecommendationProvider.js
- package.json
- test/test-RecommendationProvider.js
@oyiptong @jaredkerim r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/907)
> feat(addon): Add Recommendation Provider

- content-src/components/Spotlight/Spotlight.scss
- content-src/static/img/glyph-check-16.svg
- content-src/static/img/glyph-pocket-16.svg
- content-src/styles/icons.scss
- content-src/styles/variables.scss
@k88hudson r? just the css part of recommendations to help split up the patch 🐱
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/913)
> feat(content): CSS for recommendations

- lib/ActivityStreams.js
- lib/PreviewProvider.js
- lib/main.js
- test/test-ActivityStreams-async-preview-cache-rebuild.js
- test/test-ActivityStreams-awesomebar-empty.js
- test/test-ActivityStreams-home-page.js
- test/test-ActivityStreams-message-passing.js
- test/test-ActivityStreams-places-caching.js
- test/test-ActivityStreams-private-browsing.js
- test/test-ActivityStreams-workers.js
- test/test-ExperimentProvider.js
- test/test-PerfMeter.js
- test/test-TabTracker.js
- test/test-TelemetrySender.js
@ncloudioj @jaredkerim @k88hudson r?
this is step 1 of replacing simple storage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/914)
> feat(addon): Start/close the Metadata DB

- test/lib/utils.js
- test/test-ActivityStreams-async-preview-cache-rebuild.js
- test/test-ActivityStreams-awesomebar-empty.js
- test/test-ActivityStreams-home-page.js
- test/test-ActivityStreams-message-passing.js
- test/test-ActivityStreams-places-caching.js
- test/test-ActivityStreams-private-browsing.js
- test/test-ActivityStreams-workers.js
- test/test-ExperimentProvider.js
- test/test-PerfMeter.js
- test/test-TabTracker.js
- test/test-TelemetrySender.js
🎉  @jaredkerim r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/919)
> fix(test): #918 Mock the ActivityStream instance

- package.json
This adds image compression and a number of new icons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/923)
> fix(content): #828 Bumped tippy-top sites to 0.2

- content-src/selectors/selectors.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/922)
> fix(content): #748 Add deduping to timeline highlights

- common/action-manager.js
- common/event-constants.js
- content-src/components/LinkMenu/LinkMenu.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Spotlight/Spotlight.js
- content-src/selectors/selectors.js
- content-test/components/LinkMenu.test.js
- content-test/components/NewTabPage.test.js
- content-test/components/Spotlight.test.js
- content-test/test-utils.js
Some content side stuff for the recommendations:
1. Styling for spotlight + tooltip
2. Styling settings 
3. Styling for link context menu
4. Tests
@k88hudson r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/915)
> feat(content): Add react components to recommendations

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/selectors/selectors.js
- content-test/components/ActivityFeed.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/921)
> fix(content): #852 Only show one preview on new tab

- lib/MetadataStore.js
- lib/main.js
- test/lib/utils.js
- test/test-MetadataStore.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/917)
> fix(metadata-store): #916 Ensure drop transaction gets committed

- common/action-manager.js
- lib/ActivityStreams.js
- package.json
@oyiptong r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/925)
> feat(addon): Invoke the Recommendation Provider on addon-side

- package.json
@sarracini r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/937)
> Use production recommendation endpoint #936

- common/event-constants.js
- content-src/components/LinkMenu/LinkMenu.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Spotlight/Spotlight.js
- content-test/components/LinkMenu.test.js
- content-test/components/Spotlight.test.js
- lib/ActivityStreams.js
- lib/RecommendationProvider.js
- test/test-RecommendationProvider.js
@emtwo r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/933)
> feat(metrics): Collect metrics on Pocket Recommendations

- lib/RecommendationProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/940)
> Change recommendations timeout to 1 hour #939

- bin/generate-html.js
Closes #829 
r? @rlr: I think you were the one to implement the CSP originally
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/942)
> fix(content): #829 fix deprecation warning for frame-src CSP directive

- content-src/components/LinkMenu/LinkMenu.js
- content-test/components/LinkMenu.test.js
- experiments.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/932)
> chore(experiment): #931 Disable experiment for context menu

- data_dictionary.md
- data_events.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/949)
> fix(metrics): Add recommendation fields to data_events.md

- lib/MetadataStore.js
- test/test-MetadataStore.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/943)
> feat(metadata-store): #929 Add metadata query to search cache keys

- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-test/components/Spotlight.test.js
- lib/RecommendationProvider.js
- test/test-RecommendationProvider.js
@jaredkerim r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/963)
> fix(content): #957 Remove publish timestamp from recommendations

- lib/MetadataStore.js
- test/test-MetadataStore.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/967)
> chore(metadata-store): #966 Return RGB color for favicon and images

- content-src/components/HighlightContext/types.js
- content-test/components/HighlightContext.test.js
@jaredkerim r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/982)
> Remove timestamps for recommendations

- metadata_schema.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/987)
> Document metadata database schema #985

- content-src/components/SiteIcon/SiteIcon.js
- content-test/components/SiteIcon.test.js
fix #944 r?@k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/993)
> fix(content): #944 Detect small favicons to show fallback instead.

- content-src/components/SiteIcon/SiteIcon.js
- content-test/components/SiteIcon.test.js
fix #488 r?@k88hudson 
This should land after #993.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/994)
> fix(content): #488 Handle errored favicons (0x0) like small icons.

- lib/main.js
fix #992 @jaredkerim r? 🐱
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/995)
> fix(addon): #992 Always close metadataStore

- lib/ActivityStreams.js
fix #989 @jaredkerim r? 😸
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/996)
> fix(addon): #989 Initialize perfMeter before calling setupPageMod

- lib/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1009)
>  Do not close metadatastore connection twice #1008

- test/test-MetadataStore.js
This fixes #1012
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1021)
> fix(metadata-store): #1012 Fix the intermittent timeout failure

- lib/MetadataStore.js
- lib/main.js
This fixes #1029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1032)
> chore(metadata-store): #1029 Move metadata.sqlite to the root profile directory

- content-src/components/LinkMenu/LinkMenu.js
- content-src/components/Spotlight/Spotlight.js
- content-test/components/Spotlight.test.js
- lib/RecommendationProvider.js
This fixes #1034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1036)
> fix (addon): #1034 Fix event ping to include experiment data only if necessary

- package.json
- yamscripts.yml
Fixes #1024 
@SoftVision-VladBacia are you able to try this out? Fixes it for me, but my error message was slightly different than yours on OS-X.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1030)
> fix (addon): #1024 fix package script

- .eslintrc
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/Search/Search.js
- lib/ColorAnalyzerProvider.js
- lib/MetadataStore.js
- lib/PlacesProvider.js
- lib/PreviewProvider.js
- test/test-ExperimentProvider.js
- test/test-MetadataStore.js
- test/test-PlacesProvider.js
- test/test-PreviewProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1040)
> chore(lint): Enable various eslint rules that only need a few fixes

- lib/ActivityStreams.js
fixes #1053
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1065)
> fix(startup-race): #1053 fix content request and provider race condition

- .eslintignore
- lib/Memoizer.js
- lib/MetadataCache.js
- lib/PreviewProvider.js
- lib/SimpleStorage.js
- lib/main.js
- lib/vendor-src.js
- package.json
- test/test-MetadataCache.js
- test/test-SimpleStorage.js
Fixes #981 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1064)
> Add caching for metadata store queries

- package.json
This was missing – it's needed for the tdd task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1077)
> chore(karma): Add dependency for tdd task

- README.md
- config.default.yml
- config.production.yml
Fixes #1059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1061)
> fix(config): Change config values to use production embedly-proxy URI

- content-src/components/Search/Search.scss
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1096)
> Fix typo in img path

- lib/ShareProvider.js
- lib/TabTracker.js
- test/test-ShareProvider.js
@mixedpuppy can you r? these fixes please? 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1112)
> fix (addon): #1099 fix the providers-changed listener

- lib/ShareProvider.js
Fixes #1113 
r? @ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1119)
> fix (addon): #1113 re-enable button after customization

- test/test-ActivityStreams-private-browsing.js
r? @ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1121)
> fix (tests): #1045 fix for private browsing test

- common/recommender/Baseline.js
- common/recommender/Recommender.js
- content-test/recommender/Baseline.test.js
- content-test/recommender/Recommender.test.js
- lib/ActivityStreams.js
- package.json
As described in #1101 
@sarracini || @k88hudson please review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1106)
> Weights prefs

- common/event-constants.js
- data_events.md
- lib/ShareProvider.js
To keep under 16 chars.
r? @ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1128)
> fix (addon): s/SHARE_FROM_TOOLBAR/SHARE_TOOLBAR/

- test/test-PerfMeter.js
There are two failures found in this unit test for Firefox 49+:
* `tabData.tab` is undefined
* the timeout failure when executing the line `yield promiseLoadURI(tab, "about:about")` in `test_PerfMeter_tab_restore`
The first one is due to the race condition where the `onShow` didn't get executed as the promise got resolved in the "onNotify".
The cause of the second failure is a little bit obscure, looks like `gBrowser.addTab(appUrl)` sometimes might take some time to do its job, calling `tab.linkBrowser.loadURI(uri)` before it's done will hit the timeout in this case.
I think the similar issues exist in `test-TabTracker.js` as well, will fix it shortly.
@oyiptong @emtwo @k88hudson can anyone r? it, please?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> fix(test): #1046 Intermittent failures in PerfMeter

- test/test-TabTracker.js
Fix #1043, #1044, #1080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1133)
> fix(test) #1043 fix test failures in TabTracker

- content-src/lib/first-run-data.js
r? literally anybody
Fixes #951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1151)
> fix(topsites): Fix YouTube background color in Top Sites

- addon/MetadataStore.js
- addon/MetadataStoreMigration.js
- test/lib/MetastoreFixture.js
- test/test-MetadataStoreMigration.js
This fixes #1159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1163)
> feat(metadata): #1159 add migration support for metadata store

- addon/MetadataStore.js
- addon/MetadataStoreMigration.js
- metadata_schema.md
- test/lib/MetastoreFixture.js
- test/test-MetadataStore.js
- test/test-MetadataStoreMigration.js
@ncloudioj r?
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1164)
> feat(metadata): Closes #1156 Add metadata_source field to MetadataStore

- addon/ShareProvider.js
- test/test-ShareProvider.js
r? @ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1176)
> fix (addon): #1173 fix SocialService import

- addon/MetadataStore.js
@ncloudioj r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1193)
> Add 'Embedly' as default metadata_source

- addon/PreviewProvider.js
@jaredkerim r? 🐱
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1194)
> fix(metrics): Fixes #983 Fix cacheMiss performance metric

- addon/PreviewProvider.js
- data_dictionary.md
- data_events.md
- package.json
- test/test-PreviewProvider.js
Dynamically set prefs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1158)
> feat(metadata): Closes #1143 Dynamically set metadata source

- .jpmignore
@ncloudioj r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1204)
> Add .storybook files to jpm ignore

- package.json
Ref: https://github.com/mozilla/activity-stream/pull/1158#discussion-diff-77243490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1205)
> chore(addon): Convert metadata server URI to prod stack

- experiments.json
super quick r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1234)
> fix(experiments): Closes #1230 Disable 'Trending' Highlights experiment

- addon/PreviewProvider.js
- addon/TippyTopProvider.js
- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/LinkMenu/LinkMenu.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/TopSites/TopSites.js
- content-test/components/ActivityFeed.test.js
- content-test/components/LinkMenu.test.js
- content-test/components/NewTabPage.test.js
- content-test/components/Spotlight.test.js
- content-test/faker.js
- data_dictionary.md
- data_events.md
- test/test-PreviewProvider-MetadataStore.js
- test/test-PreviewProvider.js
- test/test-TabTracker.js
- test/test-TippyTopProvider.js
@jaredkerim r?
Fixes #1175 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1224)
> feat(metrics): Closes #1175 Add metadata_source to pings

- test/lib/Benchmark.js
- test/test-Benchmark.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1209)
> feat(addon): add benchmarking support

- addon/ActivityStreams.js
- addon/PreviewProvider.js
- test/test-PreviewProvider.js
super quick r? @jaredkerim
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1262)
> chore(addon): Closes #1245 Remove unused 'previewsOnly' flag

- common/getBestImage.js
- common/recommender/Baseline.js
- content-test/common/Baseline.test.js
- content-test/lib/getBestImage.test.js
@jaredkerim r?
cc @piatra for sanity check 
Fixes #1149
> fix(content): Closes #1149 Remove best image logic

- content-src/selectors/selectors.js
- content-test/faker.js
- content-test/faker.test.js
- content-test/selectors/selectors.test.js
Fixes #1252
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1266)
> #1252 - Fix timeline highlights

- addon/ActivityStreams.js
- addon/ShareProvider.js
- common/action-manager.js
- common/reducers/ShareProviders.js
- common/reducers/reducers.js
- content-src/components/Base/Base.js
- content-src/components/ContextMenu/ContextMenu.js
- content-src/components/ContextMenu/ContextMenu.scss
- content-src/components/LinkMenu/LinkMenu.js
- content-src/lib/fake-data.js
- content-src/selectors/selectors.js
- content-src/styles/icons.scss
- content-test/components/LinkMenu.test.js
- data_events.md
@k88hudson r?
Fixes #414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1186)
> feature (addon): #414 context menu share

- addon/PreviewProvider.js
- test/test-PreviewProvider.js
- Ensures we _always_ add tippytop data if we have it 
- As a result the youtube icon is nice
- Update the tests
@jaredkerim r?
> fix(metadata): Closes #1278 Fix YouTube Top Sites icon

- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
> Refactor selectors to fix dedupe bug

- content-src/components/ContextMenu/ContextMenu.js
tiny r? @k88hudson 
Fixes #1298
> fix (content): #1298 stop propagation on "Share" click event

- addon/ActivityStreams.js
- addon/AppURLHider.js
- content-src/components/Routes/Routes.js
- test/test-ActivityStreams-awesomebar-empty.js
> fix (addon): #1228 simplify url hiding

- addon/ActivityStreams.js
This PR fixes a bug introduced by the new page worker strategy, in which infinite scroll no longer works on the Timeline pages.
Fixes #1323
> fix(timeline): #1323 Fix infinite scroll events for timeline

- test/test-MetadataStore.js
This fixes #1317 
Turns out the `waitUntil` function in addon sdk doesn't take a generator as the predicate function, we had to refactor the failed test case accordingly.
> Fix(test): fix the test failure in metadata store

- addon/ActivityStreams.js
- addon/ExperimentProvider.js
This reverts commit 5f666023d878672bfb3b04504c6be163e56e23a3.
> Revert "Initialize experiment provider in constructor fixes #1343"

- common/recommender/Baseline.js
- content-test/common/Baseline.test.js
> 1274 score consecutive images

- contributing.md
> docs(activity-stream): add contributing.md

- experiments.json
> Create weighted highlights experiment

- test/lib/Benchmark.js
Came across this function `Cu.forceGC()` while working on writing some benchmark baselines. I think it's helpful to get a more comparable benchmark results with it.
> chore(benchmark): force GC for each run in the benchmark

- .mention-bot
Avoid skynet for a little bit longer. r?@piatra 
https://github.com/facebook/mention-bot#configuration
> Add users/bots to .mention-bot blacklist

- content-src/selectors/selectors.js
- content-test/selectors/selectors.test.js
Possibly fix #1393. Updated the before step, added another test to check for correct number of elements. Will run on travis a few times and see what happens.
> Rewrite failing test

- addon/PreviewProvider.js
- test/test-PreviewProvider.js
> fix(addon): Closes #1418 Split adding to metadataDB

- data/page-scraper-content-script.js
* Create the framescript which will collect a DOM when the content is loaded on the current page and send it as a msg to our page scraper
> feat(metadata): Closes #1417 Add a framescript for local metadata parsing

- .gitignore
- .jpmignore
- .storybook/config.js
- .storybook/head.html
- .storybook/webpack.config.js
- content-test/components/Spotlight.story.js
- content-test/faker.js
- package.json
- yamscripts.yml
Once this lands, we'll be able to get automatically built storybooks.  Click on the last "View Deployment" button in https://github.com/dmose/activity-stream/pull/6 to see an example.
r? @Mardak
> chore(storybook): support building of storybooks for PRs by storybook.io

- test/test-ActivityStreams-places-caching.js
> fix(test): #1407 - Fix a race condition in places caching unit test

- addon/ActivityStreams.js
- addon/PageScraper.js
- test/test-PageScraper.js
> metrics(metadata): Closes #1432 Add metrics to local metadata parsing

- test/lib/utils.js
- test/resources/dummy-frameScript.html
- test/test-PageScraper-FrameScript.js
* Integration test for the local metadata parser's framescript
> tests(metadata): Closes #1467 Integration test for framescript

- addon/ActivityStreams.js
- experiments.json
* Set up the page scraper as an experiment!!!
> feat(experiments): Closes #1431 Set up local metadata parser as experiment

- addon/ShareProvider.js
> fix (addon): #1373 fix sharing from new private windows

- addon/ActivityStreams.js
- addon/PageWorker.js
- content-test/addon/PageWorker.test.js
Forgot to add this in the last patch, or maybe it got deleted somehow.
> bug(addon): Destroy pageworker

- addon/ActivityStreams.js
- test/test-TabTracker.js
> fix (addon) Remove timeline toolbar button

- addon/ActivityStreams.js
- addon/main.js
- test/lib/utils.js
Fix #1480.
* Creates an initialization function for Activity Stream
* Removes all side effects of the constructor
> fix(addon): Closes #1480 Create an init function for ActivityStreams

- common/reducers/SetRowsOrError.js
> fix(bookmarks): Fixes #1551 Bookmarks is busted

- addon/PageScraper.js
* Add required field ```source``` for performance pings coming from PageScraper
> fix(metrics): Add a source for performance pings

- addon/ActivityStreams.js
Fix #1382 and maybe fix #1493. On init when app states are initially cached, the recommender might not be loaded yet, so refresh things when it does get loaded. r?@piatra or r?@sarracini
> fix(highlights): Wait for async initializers before loading app data

- dev-prefs.json
- experiments.json
- package.json
* Turn on the metadataService experiment
* Force it to be on in dev-prefs
* Update endpoint
> experiments(metadata): Closes #1361 Turn metadataService experiment on

- addon/main.js
* Don't assume ```this``` exists - exclusively declare the variable
> fix(crash): Fixes #1567 AS crashes on force shutdown

- data_dictionary.md
- data_events.md
Let's clean up the data dictionary as it's getting more complicated.
> chore(doc): Clarify each field in data_dictionary.md

- addon/MetadataStore.js
- addon/MetadataStoreMigration.js
- metadata_schema.md
- test/lib/MetastoreFixture.js
- test/test-MetadataStoreMigration.js
* Add provider_name to metadataStore
> migration(metadata): Add a provider_name field in metadataStore

- fabfile.py
> chore(addon): Bump up the version for dev build

- addon/ActivityStreams.js
- common/action-manager.js
- common/event-constants.js
* Remove ```UNBLOCK_ALL``` functionality
> remove(unblock): Closes #941 Depreciate unblock_all functionality

- content-src/components/TopSites/TopSites.scss
> fix (content): #1547 fix top sites context menu button css

- addon/TabTracker.js
Give some default values to places queries for tabtracker - so we can use it in the broader scope for SHIELD
> shield(tabtracker): Closes #1540 Give tabTracker init default values

- addon/MetadataParser.js
- addon/MetadataStore.js
- content-test/addon/MetadataParser.test.js
- package.json
* Update ```page-metadata-scraper``` to ```0.5.1```
* Add ```provider_name``` to metadataStore 
* Update tests
> feat(metadata): Closes #1588 add provider_name to metadata

- .travis.yml
- artifacts/latest/latest.html
- bin/continuous-integration.sh
- fabfile.py
> chore(addon): #1587: add a channel for pre-release

- addon/ActivityStreams.js
- addon/TabTracker.js
- addon/main.js
- test/lib/utils.js
- test/test-TabTracker.js
* Add to common properties
* Revert original addition to just user events
* Update tests
* Update mock
> shield(metrics): Closes #1516 Add 'shield_variant' to common properties of pings

- addon/ActivityStreams.js
- test/test-ExperimentProvider.js
> chore(addon): Fixes #1521 - Disable ExperimentProvider for SHIELD study users

- data_dictionary.md
- data_events.md
> shield(doc): Closes #1440 Update doc for shield pings

- content-src/components/ActivityFeed/ActivityFeed.js
- content-src/components/SiteIcon/SiteIcon.js
- content-test/faker.js
Fixes #1591
* Only use ```provider_name``` - remove other kinds of provider fields
> fix(metadata): Fixes #1591 Consolidate the use of provider fields

- dev-prefs.json
Fix #1621. I forgot about this, let's turn this on, on dev
> chore(dev): #1621 update dev-prefs with weighted highlights pref

- addon/TabTracker.js
> Revert default values to tabTracker

- .eslintignore
- .gitignore
- SHIELD.md
- addon/index.js
- addon/shield.js
- package.json
- yamscripts.yml
SHIELD stuff 
Sets up the SHIELD and adds @Mardak's about:newtab ping injection patch from PR #1561 
See [doc](https://github.com/sarracini/activity-stream/blob/43adbabf34862b15872e65b318d6bb76584bdbed/SHIELD.md) about how to run this PR and how the study works
> shield(addon): Closes #1515 Try addon as shield study

- addon/PageScraper.js
> fix(metrics): Fixes #1630 Add value to metadataReceivedRawHTML ping

- common/recommender/Baseline.js
- content-test/common/Baseline.test.js
* Sets score of highlights without images to 0
* Filters out the highlights with 0 score
* Update tests
Could possibly fix #1577
> fix(highlights): Fixes #1635 Filter out highlights with no images

- deploy.md
This adds more details about the release process we've discussed during the workweek.
> chore(doc): augment deploy.md with the detailed release process

- addon/MetadataParser.js
- addon/PageScraper.js
- content-test/addon/MetadataParser.test.js
- test/test-PageScraper-FrameScript.js
- test/test-PageScraper.js
Fix #1571. Possible way to compute image sizes locally
Not sure if it's worth it? 
@Mardak can you give some feedback?
> feat(metadata): Closes #1571 Compute image size locally

- content-src/components/Hint/Hint.scss
@k88hudson R? This seems to work for me. But the comment you had makes me think there might be an issue with it.
> fix (content): #1605 fix hint z-index issue

- package.json
Will squash/merge the updates together.
> chore(package): update various dependencies to latest version

- addon/MetadataStore.js
> fix (metadatastore): parameterize the images SELECT query

- data_dictionary.md
- data_events.md
Revert docs for shield_variant ping - will be aded in shield branch
> Revert "shield(doc): Closes #1440 Update doc for shield pings"

- content-src/components/ContextMenu/ContextMenu.js
- content-src/components/LinkMenuButton/LinkMenuButton.js
* Fixes the busted top sites context menu after a dismiss
> fix(contextmenu): Fix #1722 TopSites context menu not clickable

- .eslintignore
- .eslintrc
- addon/MetadataStore.js
- content-test/lib/getRelativeTime.test.js
Ref: https://github.com/mozilla/activity-stream/issues/1768#issuecomment-259546442
> chore(addon): Fix invalid template strings in addon/MetadataStore.js

- addon/MetadataStore.js
* Truncate the SQL parameters to the defined limit
@ncloudioj r?
Needs to be uplifted to 1.1.7
> fix(sqlite): Fixes #1768 Limit MetadataStore SQLite parameters

- addon/SearchProvider.js
- test/test-SearchProvider.js
Fix #1795. This patch triggers an event when the `browser.search.hiddenOneOffs` changes, which `SearchFeed` already listens to.
> fix(search): #1795 Listen to browser.search.hiddenOneOffs

- addon/TabTracker.js
> fix(addon): #1756 - fix a race condition in TabTracker

- content-src/components/ContextMenu/ContextMenu.js
- content-src/components/LinkMenuButton/LinkMenuButton.js
- content-src/components/TopSites/TopSites.js
Breaking out `TopSitesItem` into a separate component like we do for Spotlights fixed the issue.
r? @sarracini 
Fixes #1763
> fix (content): #1763 fix context menu button clicking

- addon/ActivityStreams.js
- experiments.json
- package.json
> metadata(experiment): Closes #1813 Graduate local metadata experiment

- addon/ActivityStreams.js
- addon/ExperimentProvider.js
- common/action-manager.js
- content-test/addon/ExperimentProvider.test.js
- shims/_utils/globals.js
To test this patch, open the debug page (look at the Experiments section) and edit an experiment pref in `about:config`.
On master, no change should show up immediately.
In this branch, you should immediately see the correct value.
> Fix #1680 Trigger action for experiment changes

- addon/main.js
Enable the data expiry job
Fixes #1822
> fix(metadata): Fixes #1822 Enable data expiry job

- content-src/components/TopSites/TopSites.js
Fix those sneaky TOP_SITES pings
> fix(reporting): fix #1831 Missing TOP_SITES pings

- content-src/components/TopSites/TopSites.js
- content-test/components/TopSites.test.js
Add a test for ensuring the top sites clicks are dispatching actions
> tests(topsites): Add action tests for TOP_SITES click

- addon/ShareProvider.js
- content-src/static/img/glyph-share-linux-16.svg
- content-src/static/img/glyph-share-mac-16.svg
- content-src/static/img/glyph-share-windows-16.svg
r? @ncloudioj can you test on linux?
Fixes #1711
> fix (addon): #1711 use OS specific share icon in toolbar

- content-src/components/DebugPage/DebugPage.js
- content-test/components/DebugPage.test.js
- The first commit adds a failing test (it will fail if the debug page is critically broken, which it is on master)
- The second commit fixes all warnings and the actual bug, as well as the test. To check this, just run the add-on and open the debug page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1903)
Fix #1902
> Fix Debug page

- common/create-store.js
- common/selectors/selectorUtils.js
- common/selectors/selectors.js
- content-test/common/selectors/selectorUtils.test.js
Simple refactor gets rid of duplicated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1911)
> chore(selectors): closes #1798; unifies and tests areSelectorsReady

- package.json
- Add open graph provider name parsing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1913)
>  Update to Page Metadata Parser 0.5.2 fixes #1912

- fabfile.py
This closes #1930 
r? @rlr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1933)
> chore(addon): #1930: Change version scheme

- common/selectors/selectAndDedupe.js
- content-test/common/selectors/selectAndDedupe.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1938)
> fix(content) #1916 Dedupe against defaults in selectAndDedupe

- content-src/components/HighlightContext/HighlightContext.js
- content-src/components/Snippet/Snippet.js
- content-test/components/HighlightContext.test.js
- content-test/components/Snippet.test.js
- content-test/components/Spotlight.test.js
- content-test/test-utils.js
- karma.conf.js
- package.json
This change adds Enzyme so it's straightforward to test stateless, functional components.  
It also rewrites a few test sets to use Enzyme, and changes those components to be functional ones.
Using Enzyme in new tests also means that its possible to rewrite existing components into functional ones without (necessarily) having to change the tests.  As an added bonus, it can also make tests more readable, and making it easy to use shallow rendering is great because it can enforce that tests are actually unit-tests rather than inadvertent integration tests.
See https://medium.com/@housecor/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc for info on why functional components are worthwhile...
---
This change is [<img …
> chore(testing): #1929 Add Enzyme and add functional components

- addon/TabTracker.js
- common/event-constants.js
- data_events.md
- test/test-TabTracker.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1950)
> feat (metrics): #1782 ping event when slow addon detected

- experiments.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1966)
> chore(exp): Re-balance the experiment groups

- addon/PlacesProvider.js
Fix the experiment for top sites
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2046)
> fix(experiment): Fix top sites experiment favicons

- content-src/main.scss
r? @bryanbell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2047)
> fix (content): add system fonts for Windows and Ubuntu

- content-src/styles/variables.scss
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2048)
> fix (content): Implement new gutter size

- addon/PlacesProvider.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2053)
> fix(addon): Filter blocked urls from NewTab links

- addon/MetadataStore.js
- addon/PageScraper.js
- addon/PreviewProvider.js
- addon/TippyTopProvider.js
- addon/lib/utils.js
- test/test-PageScraper.js
- test/test-PreviewProvider-MetadataStore.js
- test/test-PreviewProvider.js
- test/test-TippyTopProvider.js
- test/test-utils.js
* Adds ```favicon_height``` ```favicon_width``` for each link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2054)
> feat(metadata): Closes #2044 compute and store favicon sizes

- addon/PlacesProvider.js
r? @Mardak
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2056)
> refactor (addon): reduce some code duplication in PlacesProvider

- addon/ActivityStreams.js
- addon/MetadataStore.js
- addon/PreviewProvider.js
- common/action-manager.js
- config.default.yml
- config.production.yml
- data_dictionary.md
- data_events.md
- dev-prefs.json
- package.json
- test/test-PreviewProvider-MetadataStore.js
- test/test-PreviewProvider.js
Get rid of Embedly!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1962)
> feat(metadata): Closes #1940 Deprecate Embedly

- content-test/addon/PreviewProvider.test.js
- experiments.json
Turn the experiment off
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2068)
> fix(experiments): Turn MetadataService experiment off

- addon/Feeds/TopSitesFeed.js
- addon/lib/getScreenshots.js
- addon/lib/utils.js
- common/selectors/colorSelectors.js
- common/selectors/selectors.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/components/TopSites.test.js
- experiments.json
r?
This is purely style changes but I had to pass the experiment into the components so there are changes for that (which can be removed after we graduate the experiment).
Fixes #1988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2066)
> feat (content): #1988 new style for top sites (behind screenshots experiment)

- content-src/components/TopSites/TopSites.scss
tiny r? @sarracini 
Fixes #2084
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2087)
> fix (content): #2084 center screenshot on top sites

- addon/Feeds/TopSitesFeed.js
small r? @sarracini 
Fixes #2081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2088)
> fix (addon): #2081 use asyncGetTopNewTabSites in screenshots experiment

- addon/Feeds/TopSitesFeed.js
- content-src/components/TopSites/TopSites.js
- content-src/lib/first-run-data.js
- content-test/addon/Feeds/TopSitesFeed.test.js
@k88hudson r?
Fixes #2083 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2089)
> fix (content): #2083 make large favicons fill the tile

- content-src/components/TopSites/TopSites.scss
lolcss
Fixes #2095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2099)
> fix (style): #2095 css fixes for narrow windows

- experiments.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2104)
> fix (experiments): disable screenshots experiment in release branch

- package.json
Latest page metadata parser includes logic to distinguish multiple favicons based on their size and pick the largest one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2112)
> Update to Metadata Parser 0.6.0 fixes #2082

- addon/PageScraper.js
Fixes #1996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2133)
> fix (addon): #1996 fix for PageScraper dead object exception

- content-src/components/Base/Base.js
* Add locale data for our current locale. 
* Dynamically set the ```lang``` of the document to reflect the current locale
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2137)
> feat(l10n): Fixes #2128 Add support files for locales

- addon/PreviewProvider.js
- test/test-PreviewProvider-MetadataStore.js
Fixes #2102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2132)
> fix (addon): #2102 handle exceptions/rejects from _computeImageSize()

- docs/localization.md
* Add some tips for writing CSS that is RTL happy
> docs(l10n): Add tips for RTL-ing CSS

- addon/Feeds/LocalizationFeed.js
- common/reducers/Intl.js
- content-src/components/Base/Base.js
- content-test/addon/Feeds/LocalizationFeed.test.js
- content-test/common/reducers/Intl.test.js
* Determine which language is an RTL language and set the html's dir based on that
> feat(l10n): Closes #2136 Determine dir of html

- dev-prefs.json
https://github.com/mozilla/activity-stream/issues/2155
> Force 1 content process in dev prefs fixes #2155

- README.md
- docs/redux_actions.md
Someone mentioned that we don't have a link to the test pilot project etc. from our docs, so I added it
> docs(README): Updated README to include links to test pilot, etc.

- common/selectors/colorSelectors.js
- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
> fix (style): #2168 no icon borders for screenshots experiment

- content-src/styles/icons.scss
Remove unused css rule (was causing a mochitest failure)
> fix(css): Fixes #2189 Missing glyph-showmore-16.svg

- addon/ActivityStreams.js
- common/action-manager.js
- common/selectors/selectors.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/NewTabPage/NewTabPage.scss
- content-src/components/PreferencesPane/PreferencesPane.js
- content-src/components/PreferencesPane/PreferencesPane.scss
- content-src/components/Search/Search.scss
- content-src/lib/fake-data.js
- content-src/main.scss
- content-src/styles/variables.scss
- content-test/components/PreferencesPane.test.js
- locales/en-US/strings.properties
- package.json
- test/test-ActivityStream-pref-changes-from-ui.js
> feat (content): #1984 implement preferences pane

- content-src/components/Search/Search.js
- locales/en-US/strings.properties
> fix (l10n): localize screenreader text for Search button

- content-src/components/TopSites/TopSites.js
- content-src/lib/first-run-data.js
- package.json
* bigger icons
* always show border around them
Fixes #2168
> fix (content): #2168 update tippy tops.

- addon/PlacesProvider.js
> remove(sdk): Remove sdk/base64 and replace with btoa

- addon/TabTracker.js
- docs/data_dictionary.md
- docs/data_events.md
- test/test-TabTracker.js
> fix(addon): #2210 - Add telemetry for screenshots expriment

- addon/ActivityStreams.js
- addon/TabTracker.js
- common/action-manager.js
- test/test-ActivityStreams-awesomebar-empty.js
- test/test-TabTracker.js
> chore (addon): remove legacy route change handling

- addon/Feeds/HighlightsFeed.js
- addon/Feeds/TopSitesFeed.js
- addon/PlacesProvider.js
- common/constants.js
- common/selectors/selectors.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/PreferencesPane/PreferencesPane.js
- content-src/components/PreferencesPane/PreferencesPane.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/main.scss
- content-src/styles/variables.scss
- content-test/addon/Feeds/HighlightsFeed.test.js
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/common/selectors/selectors.test.js
- content-test/components/EditTopSites.test.js
- locales/en-US/strings.properties
- package.json
- test/test-PlacesProvider.js
> feat (top sites): #2218 implement Show More/Show Less feature

- addon/TabTracker.js
- common/constants.js
- docs/data_dictionary.md
- docs/data_events.md
- test/test-TabTracker.js
> fix(addon): #2245 - Add user prefs to the session/event/performance pings

- content-src/components/NewTabPage/NewTabPage.js
I just noticed I wasn't getting any screenshots and it's because we missed this one.
r? @jaredkerim
> fix (screenshots): s/screenshots/screenshotsAsync/ miss

- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/TopSites/TopSites.js
This one needs to be uplifted to the release branch.
r? @ncloudioj
> fix (experiments) #2282 hide Edit Top Sites behind newTabPrefs experiment

- addon/Feeds/HighlightsFeed.js
- common/recommender/Baseline.js
- content-src/components/Spotlight/Spotlight.js
- content-src/components/Spotlight/Spotlight.scss
- content-test/addon/Feeds/HighlightsFeed.test.js
- content-test/common/Baseline.test.js
- experiments.json
> feat (experiment): #2065 screenshots in highlights experiment

- content-src/components/PreferencesPane/PreferencesPane.scss
- content-src/components/Search/Search.scss
- content-src/styles/variables.scss
Some style tweaks requested by @bryanbell 
r? @ncloudioj
> body background color and sidebar positioning tweaks

- karma.mc.config.js
- package.json
- system-addon/common/Actions.jsm
- system-addon/content-src/activity-stream.js
- system-addon/content-src/components/Base/Base.js
- system-addon/lib/MessageManager.jsm
- system-addon/lib/NewTabInit.jsm
- system-addon/lib/Store.jsm
- system-addon/test/unit/common/Actions.test.js
- system-addon/test/unit/lib/MessageManager.test.js
- system-addon/test/unit/lib/Store.test.js
- yamscripts.yml
This patch adds a `MessageManager` for the system-addon and related actions. It's currently blocked on #2249 landing.
It also relies on a couple of patches I recently landed in MC, so please do a pull before testing this.
> Add Message Manager

- bin/download-firefox-artifact
- bin/prepare-mochitests-dev
- bin/test-merges.js
Running a bunch of pushes to pine in preparation for setting this up in cron, and needing to debug various things, it became clear that various things weren't aborting on errors like they should have. There are several small bugs in play here; this PR fixes them, and renames some variables for clarity.
> Test merges fixups

- addon/ActivityStreams.js
- addon/TabTracker.js
- common/action-manager.js
- content-src/components/NewTabPage/NewTabPage.js
- content-test/components/NewTabPage.test.js
> fix(telemetry): #2301 - compute the newtab stats in content

- addon/PreviewProvider.js
> chore(metadata): #2295 - increase metadata lifespan

- bin/test-merges.js
Was going through treeherder/perfherder and it was quite obtuse tracking down which revisions were what, so adding the original git commit message to hg too.
r?@dmose
> feat(testing): Include original git commit message in hg test-merges version

- docs/deploy.md
> Minor documentation typos

- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/styles/variables.scss
- content-test/components/TopSites.test.js
- locales/en-US/strings.properties
> feat (customization): #2273 implement dismiss UI in Edit Top Sites

- addon/PlacesProvider.js
- test/test-PlacesProvider.js
Gets the favicons from the favicons service API. fix #2376
> feat(places): Closes #2376 Ditch the left join on moz_favicons

- system-addon/jar.mn
> fix(mc): #2389 Fix unused files error for jar.mn

- addon/Feeds/TopSitesFeed.js
- addon/PreviewProvider.js
- common/constants.js
- content-test/addon/Feeds/TopSitesFeed.test.js
Add a bool to track if a link has a high res icon
>  Add hasHighResIcon to link object fixes #2392

- addon/Feeds/MetadataFeed.js
- addon/Feeds/TopSitesFeed.js
- common/action-manager.js
- common/event-constants.js
- common/reducers/SetRowsOrError.js
- common/selectors/selectAndDedupe.js
- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/addon/Feeds/MetadataFeed.test.js
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/components/TopSites.test.js
- docs/data_events.md
- locales/en-US/strings.properties
> feat (topsites): #2274 Pinning

- addon/Feeds/TopSitesFeed.js
> fix (pinning): do not pass empty slots to getCachedMetadata

- system-addon/lib/ActivityStream.jsm
- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
- system-addon/test/unit/unit-entry.js
> feat(mc): Closes #2401 Port top sites feed to system addon

- content-src/components/NewTabPage/NewTabPage.js
- experiments.json
> feat (content): #2410 "graduate" preferences sidebar

- content-src/components/TopSites/TopSites.js
- content-test/components/TopSites.test.js
> fix (content): #2415 unpin site when dismissing (if pinned)

- addon/Feeds/MetadataFeed.js
> fix (feeds): skip empty slots in MetadataFeed

- addon/Feeds/TopSitesFeed.js
- addon/PreviewProvider.js
- content-src/components/NewTabPage/NewTabPage.js
- content-test/addon/Feeds/TopSitesFeed.test.js
- experiments.json
- test/test-PlacesProvider-synced-tabs.js
- test/test-PreviewProvider-MetadataStore.js
- test/test-PreviewProvider.js
> chore(exp): #2410 - Graduate screenshots experiment

- addon/Feeds/HighlightsFeed.js
- common/recommender/Baseline.js
- content-test/addon/Feeds/HighlightsFeed.test.js
- content-test/common/Baseline.test.js
- experiments.json
> chore (experiments): #2410 graduate screenshots in highlights

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/functional/mochitest/browser_as_load_location.js
- system-addon/test/functional/mochitest/browser_dummy_test.js
Fix #2422. r?@sarracini `grep`ped for `Task` and `yield`
> fix(mc): Switch Task/yield usage to async/await

- content-src/components/NewTabPage/NewTabPage.js
- content-src/components/SiteIcon/SiteIcon.js
- content-src/components/SiteIcon/SiteIcon.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/components/SiteIcon.test.js
> chore (styles): css cleanup after screenshots graduation

- system-addon/lib/MessageManager.jsm
- system-addon/test/unit/lib/MessageManager.test.js
Send the entire msg up instead of just data
> feat(system-addon): Closes #2437 Send entire message to parent

- content-src/components/Base/Base.scss
- content-src/components/HighlightContext/HighlightContext.scss
- content-src/components/Search/Search.scss
- content-src/components/Spotlight/Spotlight.scss
- content-src/components/TopSites/TopSites.scss
- content-src/static/img/glyph-forward-16-white.svg
- content-src/static/img/glyph-forward-16.svg
- content-src/styles/variables.scss
@bryanbell and I have been "beta-testing" some style tweaks for a few weeks and decided it's time to unleash them out into the wild. The changes are defined in https://cl.ly/2z0G2c3F1H24 and I've applied that to our styles.
Before:
After:
> fix (styles): style updates from @bryanbell

- system-addon/content-src/activity-stream.scss
- system-addon/content-src/components/Base/Base.jsx
- system-addon/content-src/components/Base/Base.scss
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/content-src/components/TopSites/TopSites.scss
- system-addon/content-src/styles/variables.scss
These are just a few css tweaks / code ported from the prototype based on Bryan's feedback
> style(mc): Style touch-ups from bbell

- addon/ActivityStreams.js
Probably should be uplifted?
Fixes #2461
> fix (addon): #2461 fix typo in _handleExperimentChange

- system-addon/bootstrap.js
Start the system-addon once the browser is ready
cc @Mardak
> feat(system-addon): Closes #2455 start AS on browser-ui-startup-complete

- system-addon/bootstrap.js
> fix(system-addon): Always watch for the enabled pref

- content-src/components/PreferencesPane/PreferencesPane.scss
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/styles/variables.scss
- content-test/components/TopSites.test.js
3 for 1. r? @ncloudioj 
Fixes #2441 
Fixes #2443 
Fixes #2444
> #2441, #2443, #2444 zindex and other tiny css fixes.

- addon/Feeds/PocketStoriesFeed.js
- locales/en-US/strings.properties
https://github.com/mozilla/activity-stream/issues/2467 Dismissing a Pocket story doesn't add a new one
https://github.com/mozilla/activity-stream/issues/2463 Fix string or add comment for "Trending Stories by [pocket]"
> Minor fixes to Pocket experiment issues (see below)

- content-src/components/PreferencesPane/PreferencesPane.scss
- content-src/components/TopSites/TopSites.scss
I got lazy for some of the customization UI stuff and didn't use the RTL friendly properties. This fixes.
Fixes #2388
> fix (styles): #2388 RTL fixes for prefs sidebar and edit top sites

- content-src/components/PocketStories/PocketStories.js
- locales/en-US/strings.properties
Fix #2463. See https://github.com/mozilla/activity-stream-l10n/pull/1 and https://github.com/mozilla/activity-stream/issues/2463#issuecomment-297171710 for details.
> fix(content): Improve localization values and notes for Pocket (read more)

- content-src/components/PreferencesPane/PreferencesPane.scss
@ncloudioj tiiiiiny one. R? fix #2499
> fix (styles): #2499 remove prefs checkbox transition

- system-addon/lib/ActivityStreamMessageChannel.jsm
@ncloudioj another tiiiiiny one ;) Missed a change from #2448.
> chore(mc): Backport class definition from Bug 1350411

- content-src/components/PreferencesPane/PreferencesPane.js
- content-src/components/PreferencesPane/PreferencesPane.scss
- content-test/components/PreferencesPane.test.js
some sidebar tweaks from @aaronrbenson 
r? @ncloudioj
> feat (styles): add animation for sidebar and change button to X while open

- content-src/components/Search/Search.scss
- content-src/styles/variables.scss
> fix (styles): #2497 remove box-shadow transitions in search box

- system-addon/lib/TopSitesFeed.jsm
- system-addon/test/unit/lib/TopSitesFeed.test.js
Backports changes to use our query in Bug 1345122 
Don't merge this until the bug has landed in nightly
> chore(mc): Closes #2308 Backport changes from Bug 1345122

- content-src/components/NewTabPage/NewTabPage.js
- experiments.json
> chore (experiment): disable/graduate editTopSites experiment

- addon/ExperimentProvider.js
- content-test/addon/ExperimentProvider.test.js
- experiments.json
r? @jaredkerim is this how you envisioned this being done?
Fixes #2300
> feat (experiment): #2300 add experiment for two rows of top sites by default

- addon/ExperimentProvider.js
- content-test/addon/ExperimentProvider.test.js
- experiments.json
This closes the old pocket experiment and defines a new one.
> Add new pocket hot fix experiment fixes #2534

- system-addon/content-src/components/Search/Search.scss
Removes the transition effect from ticket #2497, copied from PR #2509
> chore(css): Backport search style changes from test pilot

- system-addon/content-src/components/Search/Search.scss
> fix(css): Fix width and remove transition

- system-addon/content-src/activity-stream.scss
- system-addon/content-src/components/ContextMenu/ContextMenu.jsx
- system-addon/content-src/components/ContextMenu/ContextMenu.scss
- system-addon/content-src/components/LinkMenu/LinkMenu.jsx
- system-addon/content-src/components/TopSites/TopSites.jsx
- system-addon/content-src/components/TopSites/TopSites.scss
- system-addon/content-src/styles/icons.scss
- system-addon/content-src/styles/normalize.scss
- system-addon/content-src/styles/variables.scss
- system-addon/data/content/assets/glyph-bookmark-16.svg
- system-addon/data/content/assets/glyph-delete-16.svg
- system-addon/data/content/assets/glyph-dismiss-16.svg
- system-addon/data/content/assets/glyph-more-16.svg
- system-addon/data/content/assets/glyph-newWindow-16.svg
- system-addon/data/content/assets/glyph-newWindow-private-16.svg
- system-addon/test/unit/content-src/components/TopSites.test.js
Waiting for #2532 to land
Part 1 of #2533
> contextmenu(system-addon): Closes #2544 Port context menu UI

- system-addon/content-src/components/ContextMenu/ContextMenu.jsx
- system-addon/content-src/components/LinkMenu/LinkMenu.jsx
- system-addon/test/unit/content-src/components/ContextMenu.test.js
- system-addon/test/unit/content-src/components/LinkMenu.test.js
- system-addon/test/unit/content-src/components/TopSites.test.js
Adds tests for LinkMenu and ContextMenu UI. Part 2 of #2533
> tests(contextmenu): Closes #2445 Test the context menu UI

- system-addon/lib/PlacesFeed.jsm
- system-addon/test/unit/lib/PlacesFeed.test.js
r?@k88hudson Observer with two "r"s!
> fix(mc): Fix typo in PlacesFeed

- system-addon/content-src/components/LinkMenu/LinkMenu.jsx
- system-addon/test/unit/content-src/components/LinkMenu.test.js
Followup to #2313 and #2544 by using the just added localization. r?@sarracini
> feat(mc): Additionally localize LinkMenu

- package.json
- yamscripts.yml
> tests(mc): Exclude content-src src and test from buildmc

- addon/Feeds/PocketStoriesFeed.js
- content-test/addon/Feeds/PocketStoriesFeed.test.js
The urls were already persisted (using the same functionality as Highlights), but there was no check in place to filter out these urls so they won't reappear.
> fix(content): #2561 Persist Pocket dismissals

- addon/Feeds/TopSitesFeed.js
- common/action-manager.js
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-src/main.scss
- content-src/styles/variables.scss
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/components/EditTopSites.test.js
- locales/en-US/strings.properties
New form to add a "custom" top site accessed by clicking "Add" in the Edit Top Sites modal. I'm proud I got to use recursion for the first time I can remember in years.
Fixes #2524
> feat (topsites): #2524 Add top sites form.

- addon/Feeds/TopSitesFeed.js
- common/action-manager.js
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/components/EditTopSites.test.js
- locales/en-US/strings.properties
I still need to add the user event pings for both add and edit. I'll do it as a followup because this is big enough as it is.
r? @ncloudioj  
Fixes #2525
> feat (topsites): #2525 implement edit top site feature

- docs/v2-system-addon/1.GETTING_STARTED.md
- system-addon/README.md
add some reference link for system-addon related docs
> link reference docs for system-addon related docs

- addon/Feeds/TopSitesFeed.js
- common/action-manager.js
- common/reducers/SetRowsOrError.js
- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/addon/Feeds/TopSitesFeed.test.js
- content-test/components/TopSites.test.js
> feat (customization): #2275 top sites drag and drop

- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
* fixes the quirky hover in and out issues where it sometimes got stuck on hover
* fixes dropping on itself so it doesnt click the link
r? @ncloudioj
> fix (content): create dedicated "drop zone" div

- content-src/components/TopSites/TopSites.js
- content-src/components/TopSites/TopSites.scss
- content-test/components/TopSites.test.js
> fix (drag n drop): #2634 only allow dropping of other topsites for now

- bin/test-merges.js
Fix #2630. This just uses a different version of exec to avoid shell quoting issues entirely.  r=@Mardak?
> fix(test): #2630 fix shell quoting issue in test-merges

- addon/PlacesProvider.js
- test/test-PlacesProvider.js
> fix (addon): #2670 fix LinkChecker to match m-c

- addon/ExperimentProvider.js
- content-test/addon/ExperimentProvider.test.js
- experiments.json
- package.json
> feat (experiment): #2647 graduate pocket experiment

- addon/ActivityStreams.js
- addon/Feeds/MetadataFeed.js
- addon/PreviewProvider.js
- content-test/addon/Feeds/MetadataFeed.test.js
- dev-prefs.json
- experiments.json
- package.json
- test/test-PreviewProvider-MetadataStore.js
- test/test-PreviewProvider.js
lots of red here 🎆 
Fixes #2666 
Fixes #2667
> #2666, #2667 graduate metadataNoService and retire metadataLocalRefresh experiments
