lib/ActivityStreams.js, lib/main.js
I'm not sure why, but for some reason the `main` function never gets run when you replace `exports` completely; 
Also fixes defaulting of individual options for `ActivtiyStreams`
=> fix(add-on): Fix ActivityStreams option defaulting, main.js exports

.eslintignore, .eslintrc, content-src/lib/ActionManager.js, lib/ActivityStreams.js, webpack.config.js
Current output is:
```sh
➜  activity-streams git:(eslint-tweaks) npm run test:lint
> activity-streams@0.0.1 test:lint /Users/pdehaan/dev/github/activity-streams
> eslint . && jscs .
/Users/pdehaan/dev/github/activity-streams/lib/ActivityStreams.js
24:3   warning  Unexpected console statement  no-console
114:13  warning  Unexpected console statement  no-console
119:13  warning  Unexpected console statement  no-console
126:9   warning  Unexpected console statement  no-console
135:5   warning  Unexpected console statement  no-console
/Users/pdehaan/dev/github/activity-streams/test/lib/utils.js
24:7  warning  Unexpected console statement  no-console
✖ 6 problems (0 errors, 6 warnings)
➜  activity-streams git:(eslint-tweaks) echo $?
0
```
Only 6 warnings (so task still passes), but makes the …
=> chore(lint): Extend the ESLint recommended rules

content-src/actions/action-manager.js, lib/ActivityStreams.js, lib/PlacesProvider.js, test/lib/PlacesTestUtils.js, test/lib/utils.js, test/test-PlacesProvider.js
This contains the bookmarks API for requests and updates
=> Bookmarks API

content-src/components/Spotlight/Spotlight.js, content-test/components/Spotlight.test.js
This should fix an existing bug where Spotlights don't show up at all if the `images` prop is missing
Fixes #121
=> fix(content): Only show sites in Spotlight if it has atleast one image

content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/Spotlight/Spotlight.scss, content-src/lib/utils.js, content-test/components/ActivityFeed.test.js, content-test/lib/utils.test.js
Removes leading "http://" and "https://" (and "www.", if it exists) from the displayed URLs in the ActivityFeed, if they exist. This only removes them from the displayed URL, not the link, so this is purely cosmetic.
Fixes #134
=> refactor(ActivityFeed): Remove leading http(s)://(www.) from displayed URLs

content-src/components/Header/Header.js, content-src/components/SiteIcon/SiteIcon.js, content-src/lib/embedly-middleware.js, content-src/lib/utils.js, content-test/components/ActivityFeed.test.js, content-test/components/Header.test.js, content-test/components/SiteIcon.test.js, content-test/components/TopSites.test.js, content-test/lib/utils.test.js, package.json, yamscripts.yml
The reasoning behind this is that sometimes we get weirdly formatted history items, which ideally we will filter out, but at least we don't want to crash the whole parent component.
=> fix(content): Make sure components do not throw if some data is missing

content-src/lib/embedly-middleware.js, content-src/lib/filters.js, content-test/lib/filters.test.js, lib/PlacesProvider.js, package.json
Fixes #177 by filtering out error responses. I also added some URL filtering for long URLs (>100 characters), localhost, and non-http[s] protocols
=> fix(content): #177 Handle filtering of URLs and embedly data more gracefully

content-src/actions/action-manager.js, content-src/components/TopSites/TopSites.js, content-src/lib/dedupe.js, content-src/lib/embedly-middleware.js, content-src/lib/filters.js, content-src/lib/logger.js, content-src/lib/parse-url-middleware.js, content-src/lib/utils.js, content-src/store.js, content-test/lib/dedupe.test.js, content-test/lib/filters.test.js, content-test/lib/utils.test.js
This uses `url-parse` to dedupe sites (i.e. remove sites that are basically equivalent). We also need to do some work to dedupe *across* components, but this is a good start
Fixes #180 
Fixes #182 
Fixes #194
=> Add hostname for top site, dev logger, deduping

content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-test/components/Spotlight.test.js
=> fix(content) #202: Use real labels for spotlight bookmarks v.s. visits

.gitignore, .jpmignore, fabfile.py, package.json, requirements.txt
This change includes a Fabric deployment script that uploads to the following URLs:
* https://moz-activity-streams.s3.amazonaws.com/dist/activity_streams_experiment-[VERSION_NUMBER]-fx.xpi
* https://moz-activity-streams.s3.amazonaws.com/dist/activity-streams-latest.xpi
* https://moz-activity-streams.s3.amazonaws.com/dist/update.rdf
The update URL is checked by the addon manager. This file points to `activity-streams-latest.xpi`.
=> chore(deploy): #219 s3 deployment scripts for addon

content-src/actions/action-manager.js, lib/PlacesProvider.js, test/lib/utils.js, test/test-PlacesProvider.js
Simply add beforeDate in milliseconds to  RequestRecentLinks() as in
For example to get recent links 3 days or older, do call below
```
RequestRecentLinks({beforeDate: Date.now - 3*24*60*60*1000})
```
@rlr @k88hudson  let me know if this is something that you expected
Fixes #198
=> Closes #198 - Add some sort of pagination to Recent Links API query

content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/Base/Base.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js, content-src/components/TimelinePage/TimelineBookmarks.js, content-src/components/TimelinePage/TimelineHistory.js, content-src/lib/dedupe.js, content-src/lib/embedly-middleware.js, content-src/lib/getBestImage.js, content-src/lib/parse-url-middleware.js, content-src/selectors/selectors.js, content-test/components/ActivityFeed.test.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.test.js, content-test/components/TimelinePage.test.js, content-test/index.js, content-test/lib/dedupe.test.js, content-test/lib/getBestImage.test.js, content-test/selectors/selectors.test.js, content-test/test-utils.js, package.json, webpack.config.js, yamscripts.yml
This patch adds "selectors" as a means of calculating derived data used by components (in this case, de-duping each data type, and deriving `Spotlight` and `TopActivity` from `History`).
Selectors are just functions passed to `connect`, when connecting components to redux:
```js
// Instead of:
//   const selector  = (state => state);
const selector = require("selectors/selectors").dedupedItems;
connect(selector)(NewTabPage)
```
Selectors use [reselect](https://github.com/reactjs/reselect) to memoize derived data, which is nice.
For the deduping I wrote a small library called [fancy-dedupe](https://github.com/k88hudson/fancy-dedupe), which basically dedupes stuff on custom keys, with a custom compare function, and across multiple arrays.
Fixes #220
=> feat(content): #220 Dedupe sites via redux selectors

data_dictionary.md
This is the ping / log data that is sent from Firefox to Mozilla servers on Activity Stream activity.  It is used to optimize the user experience.
fixes #282 
r? @nchapman @ncloudioj
=> chore(documentation)-#282-Document-data-collection-in-repo

content-src/components/ActivityFeed/ActivityFeed.scss, lib/PerfMeter.js, test/test-PerfMeter.js
Noticed this while doing some local builds.
We still have 1 ESLint warning, but wasn't sure if we should ignore that warning using `// eslint-disable-line no-console`, or use something better than `console.info()` in PerfMeter.
```
> eslint . && jscs . && sass-lint -v -q
/Users/pdehaan/dev/github/activity-streams/lib/PerfMeter.js
142:7  warning  Unexpected console statement  no-console
✖ 1 problem (0 errors, 1 warning)
```
=> chore(lint): Fix a few ESLint and Sass-lint warnings

lib/ActivityStreams.js, lib/PlacesProvider.js, lib/TabTracker.js, test/lib/PlacesTestUtils.js, test/test-PlacesProvider.js, test/test-TabTracker.js
* added PlacesProvider API to get history and bookmarks sizes
* added corresponding queries to memoizer cache
* added notification data containing history and bookmarks sizes to "activity-streams-places-cache-complete" event
* added "activity-streams-places-cache-complete" observer to TabTracker which updates appropriate keys inside tabData
* a bunch of test changes 
Fixes #309
=> Closes #309 - Add total_bookmarks and total_history_size to telemetry ping

.eslintrc, lib/TabTracker.js
Promotes ESLint `eqeqeq` warning to an unforgiving build breaking error.
=> chore(lint): Fix eqeqeq warning, and promote it to an ESLint error

content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/ActivityFeed/ActivityFeed.scss, content-src/styles/variables.scss, content-test/components/ActivityFeed.test.js
This PR adds an additional grouping to the `ActivityFeed` component, which separates sites into sessions, where a session is defined as history items that are viewed within 10 minutes of each other
Code is ready, but I want to verify 10 minutes is a good amount. Seems a bit long to me
Fixes #345
=> session ui

content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js
Renamed Spotlight to Featured and Top Activity to Recent Activity. Both appear to be showing up correctly on new tab and the timeline.
Fixes #352.
@pdehaan @k88hudson r?
=> fix(content): #352 Renamed Spotlight and Top Activity

content-src/components/Spotlight/Spotlight.js
I managed to get this wrong the last time. Apologies. Spotlight -> Featured -> Highlights :tada: 
Fixes #388.
@pdehaan r?
=> fix(content): #388 Rename Featured to Highlights

package.json
Now that we've published to the registry, might as well use it
=> chore(build): use npm for tippy-top-sites

common/action-manager.js, content-src/components/Spotlight/Spotlight.js, content-src/components/TopSites/TopSites.js, content-src/lib/fake-data.js, content-src/reducers/reducers.js, content-src/selectors/selectors.js, content-test/components/Spotlight.test.js, content-test/components/TopSites.test.js, content-test/selectors/selectors.test.js
This changes delete for spotlight, top sites to a "block" strategy and warns that it's not yet complete.
Requires a follow-up for filling in empty boxes after deleting, https://github.com/mozilla/activity-streams/issues/393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/476)
=> Block instead of delete for spotlight, top sites

lib/PreviewProvider.js, test/test-PreviewProvider.js
This fixes `getCachedLinks` so that new values in links will be prioritized over cached ones if they are available.
Fixes #468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/487)
=> fix(addon): #468 Prioritize new data in getCachedLinks

content-src/components/NewTabPage/NewTabPage.js, content-src/components/NewTabPage/NewTabPage.scss
Fixes #458 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/512)
=> fix(content): #458 always show link to timeline on newtab

common/action-manager.js, content-src/components/Base/Base.js, content-src/components/DebugPage/DebugPage.js, content-src/lib/fake-data.js, content-src/lib/shim.js, content-src/reducers/reducers.js, content-src/selectors/selectors.js, lib/ActivityStreams.js, lib/PlacesProvider.js, test/test-ActivityStreams-places-caching.js, test/test-PlacesProvider.js
As requested in #389, this implements a new highlight query.
Given that we're likely to iterate rapidly on the query, there isn't thorough testing for the results of the query, just a sanity check.
I started implementing the UI integration, however, I found that the deduping logic yields potentially undesirable effects, resulting in empty spotlight spots. We'll have to file a follow-up bug to play around with the query and its integration overall.
r? @k88hudson, @mzhilyaev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/531)
=> New highlight query

lib/ActivityStreams.js, lib/PreviewProvider.js, test/test-PreviewProvider.js
This PR:
* increases the TTL for previews to 30 days
* makes cleanups run lazily (allowing for long browser inactivity)
* adds a feature where links are updated periodically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/541)
=> Fix some preview caching issues

lib/ActivityStreams.js, lib/PreviewProvider.js, test/test-PreviewProvider.js
This PR contains commits that:
* ensure that links are always returned for history type queries, even if there are no previews available
* makes the cache cleanup job more tolerant to errors (better for tests)
r? @rlr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/542)
=> Always return links

common/action-manager.js, common/event-constants.js, content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/ActivityFeed/ActivityFeed.scss, content-src/components/ContextMenu/ContextMenu.js, content-src/components/ContextMenu/ContextMenu.scss, content-src/components/DeleteMenu/DeleteMenu.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/components/TimelinePage/TimelineBookmarks.js, content-src/components/TimelinePage/TimelineHistory.js, content-src/components/TopSites/TopSites.js, content-src/components/TopSites/TopSites.scss, content-src/main.scss, content-src/selectors/selectors.js, content-src/styles/variables.scss, content-test/components/ActivityFeed.test.js, content-test/components/ContextMenu.test.js, content-test/components/DeleteMenu.test.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.test.js, content-test/components/TopSites.test.js, content-test/index.js
This patch:
* adds a `ContextMenu` component (a little drop down with options)
* centralizes delete logic in `DeleteMenu` component that includes two options: 
* Remove from History (this is actually deleting the item for history)
* Never show this site (this is adding to the block list)
The delete menu has clearer language around what delete actually does, plus a confirmation alert for deleting from history. It also extends the  block list to Activity feed items as well.
Note that the block list is still in memory only, with an alert that says "we're still working on this feature"
See #483 for reference mocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/543)
=> Gh483 - Delete

lib/PreviewProvider.js, test/test-PreviewProvider.js
This resolves an issue where youtube links were using old cached data, since query strings weren't being included in the cache key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/563)
=> fix(addon): #555 Add search to cache key

README.md, content-src/reducers/SetRowsOrError.js, content-src/reducers/reducers.js, content-test/reducers/SetRowsOrError.test.js, package.json, yamscripts.yml
Right now, if an append-type response with an error is received (e.g. a timeout), we actually clear the whole rows value, which isn't what we want.
This PR changes the behaviour to leave `rows` unchanged for append-type errors.
We also might want to adjust the timeout maybe?
Fixes #558 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/576)
=> fix(content): #558 Dont clear rows for error append actions

content-src/components/Routes/Routes.js, lib/ActivityStreams.js, lib/TabTracker.js, test/test-TabTracker.js
This patch: 
* ends a session with a new `unload_reason` of `route_change`
* changes a session end caused by a window closing to use `close`, not `unfocus`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/596)
=> feat(reporting): #477 End session on route change

bin/generate-html.js, package.json, yamscripts.yml
r? @oyiptong 
This is a little bit more permissive but a lot better than nothing. Some of the directives are only for local dev and/or testing, so we could possibly look into having separate rules or just disable it altogether for dev/test. Thoughts?
Fixes #310 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/588)
=> chore (content): #310 Add meta tag for CSP

content-src/selectors/selectors.js, content-test/selectors/selectors.test.js
This will prevent there being missing top sites if any deduping happens internally within Top Sites
Fixes #572 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/614)
=> fix(content): #572 pre-dedupe TopSites

data_events.md, lib/TabTracker.js, test/test-TabTracker.js
Fixes #625 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/636)
=> fix(addon): #625 Renaming ping attributes for bookmarks and history counts

lib/ActivityStreams.js
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/660)
=> fix(concurrency): guard against handlers called when ActivityStream object is gone

.travis.yml, package.json
It seems like for some reason after `47.0b3`, travis hangs on creating a profile – I'm not sure why. I also noticed we removed `json-loader` by accident (it's needed for webpack to load json).
Anyway, creating a profile seems to be fine on `46.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/664)
=> chore(travis): Lock to 46.0

content-src/components/NewTabPage/NewTabPage.js, content-src/components/NewTabPage/NewTabPage.scss
- Add space to See More Activity button container
- Make settings button icon only until hover
Fixes #627 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/661)
=> style(content): #627 Fix buttons on New Tab Page

content-src/components/Loader/Loader.js, content-src/components/Loader/Loader.scss, content-src/components/NewTabPage/NewTabPage.js, content-src/components/NewTabPage/NewTabPage.scss, content-src/lib/ReduxChannel.js, content-src/reducers/SetRowsOrError.js, content-test/components/Loader.test.js, content-test/reducers/SetRowsOrError.test.js, lib/ActivityStreams.js
This patch:
* removes the `previewsOnly` constraint for Highlights/TopSites
* increases the timeout content-side from `5s` to `20s`
* shows a loading spinner that says `Hang on tight! We are analyzing your history to personalize your experience` if loading is taking longer than 20 seconds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-streams/662)
=> Loading improvements

content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/TimelinePage/TimelineBookmarks.js, content-src/components/TimelinePage/TimelineHistory.js, content-test/components/ActivityFeed.test.js
r? @k88hudson 
What do you think of this? The New Tab page will keep the "Recent Activity" but the Timeline pages will show "Today"/"Yesterday"/etc instead of "Just now".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/710)
=> fix (content): #604 remove custom titles from GroupedActivityFeed

content-src/components/ActivityFeed/ActivityFeed.js, lib/PreviewProvider.js, test/test-PreviewProvider.js
- leaves all history items and their URLs intact
- only dedupes items when they are sent to embedly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/711)
=> fix(addon): #638 Dedupe history for embedly only

lib/TabTracker.js, test/test-TabTracker.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/717)
=> fix(addon): #716 Don't send session pings for tabs that finish loading in the background.

lib/TabTracker.js, test/test-TabTracker.js
This fixes #698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/726)
=> fix(addon): #698 Don't send session pings for inactive tabs when closing the broswer window

content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/DeleteMenu/DeleteMenu.js, content-src/components/Spotlight/Spotlight.js, content-src/components/TopSites/TopSites.js, content-src/reducers/SetRowsOrError.js, content-test/components/DeleteMenu.test.js, content-test/reducers/SetRowsOrError.test.js, lib/ActivityStreams.js
Fixes #659 
This still don't work on the Top Sites, since we don't get the bookmarkGuid for the top frecent sites. Should I file a follow up issue to fix this?
Note that I replaced a "NOTIFY_HISTORY_DELETE" event listener at the ActivityStream.js since it was duplicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/715)
=> feat(content): add Remove Bookmark UI

common/constants.js, content-src/reducers/SetRowsOrError.js, content-src/reducers/reducers.js, content-test/reducers/SetRowsOrError.test.js, lib/PlacesProvider.js
This fixes an issue where we still see the load more box if < 20 items are returned from the query.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/739)
=> fix(addon): #454 Hide Load More if < 20 items on history

lib/PreviewProvider.js
This PR ensures that we include tippy-top data for all links whenever we can, even if they don't have data from embedly yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/740)
=> fix(addon): #687 move tippytop to getEnhancedLinks

.eslintignore, .jscsrc, common/action-manager.js, content-src/components/Base/Base.js, content-src/components/DebugPage/DebugPage.js, content-src/components/DeleteMenu/DeleteMenu.js, content-src/lib/fake-data.js, content-src/reducers/reducers.js, content-test/components/DeleteMenu.test.js, lib/ActivityStreams.js, lib/SeedRandom.js
Fixes #732 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/777)
=> feat(addon): #732 Create experiment for DeleteMenu

lib/PreviewProvider.js, test/test-PreviewProvider.js
This patch removes the `_runPeriodicUpdate` function and replaces it with a strategy where when links from a query are sent to `asyncSaveLinks`, they are re-requested if they have expired.
This will eliminate unnecessary update requests for items in the cache that won't ever be needed again/requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/787)
=> Refactor cache updating strategy

dev-prefs.json, package.json, test-prefs.json, yamscripts.yml
This will hide a whole bunch of javascript warnings and show the pass/fail state of each test (way more interesting info).
We could optionally not have `-v` if it's too much info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/789)
=> test(addon): Reduce useless jpm test output

lib/ActivityStreams.js
Fixes #731 
I'm not sure we need tests for this. What do you think?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/792)
=> feat(addon): set browser pref to store bigger favicons

content-src/components/TimelinePage/TimelineFeed.js, content-test/components/TimelinePage.test.js
This fixes a couple more of cases:
* switching between routes
* when more than two pages fit on the screen - it was only loading up to two pages
Also I renamed the scroll handlers since they aren't only called during scrolling now. Open to better suggestions.
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/804)
=> fix (content): #774 more fixes related to more data on zoom/scroll/resizing

lib/ActivityStreams.js
Fixes an issue where deleting history items stopped working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/807)
=> fix(addon): #796 Fix delete observer notification

common/action-manager.js, common/event-constants.js, content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/ActivityFeed/ActivityFeed.scss, content-src/components/ContextMenu/ContextMenu.js, content-src/components/ContextMenu/ContextMenu.scss, content-src/components/LinkMenu/LinkMenu.js, content-src/components/LinkMenuButton/LinkMenuButton.js, content-src/components/LinkMenuButton/LinkMenuButton.scss, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/components/TopSites/TopSites.js, content-src/components/TopSites/TopSites.scss, content-src/main.scss, content-src/reducers/SetRowsOrError.js, content-src/styles/variables.scss, content-test/components/ActivityFeed.test.js, content-test/components/ContextMenu.test.js, content-test/components/LinkMenu.test.js, content-test/components/LinkMenuButton.test.js, content-test/components/Spotlight.test.js, content-test/components/TopSites.test.js, content-test/reducers/SetRowsOrError.test.js, lib/ActivityStreams.js, lib/PlacesProvider.js, test/test-PlacesProvider.js
This patch adds a new context menu which includes
- adding/removing bookmarks
- opening a link in a new window
- deleting/blocking
- tests, tests, tests
The add bookmark and open window APIs are in separate commits for easier reviewing.
TODO (in a follow-up patch):
- more sophisticated blocking 
- add icons
Fixes #701
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/801)
=> Add new context menu

content-src/components/ActivityFeed/ActivityFeed.scss
Fixes #815
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/826)
=> bug(content): remove css that breaks timestamp alignment

content-src/selectors/selectors.js, lib/ActivityStreams.js, lib/ColorAnalyzerProvider.js, lib/PreviewProvider.js, test/resources/colors.js, test/test-ColorAnalyzerProvider.js
This is a WIP, I want to add caching for color analysis and change the logic about where it gets done as well before merging this, but it seems to be working pretty well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/793)
=> feat(addon): Local color analysis for favicons

lib/ActivityStreams.js
We shouldn't cache places queries if `afterDate` or `beforeDate` are provided because we have no way to replace/invalidate them on history changes. Those queries only happen when scrolling down through the feed and are much less likely to be repeated anyway.
r? @oyiptong 
Fixes #769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/851)
=> fix (addon): #769 stop caching when afterDate or beforeDate provided

lib/ActivityStreams.js, test/test-ActivityStreams-home-page.js
r? @sarracini or @oyiptong 
Basically, we don't reset the home page back on unload unless the user is disabling (uninstalling).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/878)
=> fix (addon): #849 only reset back home page on disable

content-src/reducers/setSearchContent.js
This bit me a couple times so looked into it... @sarracini what do you think of this fix? We already update `searchString` when handling the `NOTIFY_UPDATE_SEARCH_STRING` action so we shouldn't need to update it again when suggestions come back from the addon side. It seems to fix the issue for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/879)
=> fix (content): #848 fix fast typing issue with search box

lib/ActivityStreams.js
@oyiptong turns out unload is called with `reason="uninstall"` when uninstalling. mdn and bugzilla are wrong or outdated.
r?
Fixes #882
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/884)
=> fix (addon): #882 handle unload(reason="uninstall")

content-src/components/LinkMenu/LinkMenu.js, content-test/components/LinkMenu.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/883)
=> fix(content): #859 'Delete from History' should not be available for bookmarks

content-src/components/Search/Search.js, content-test/components/Search.test.js
the onMouseMove stuff is to prevent the double selection stuff that was going on
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/890)
=> fix(content): #838 Search keyword is removed after navigating with the arrow keys through the search suggestion dropdown

package.json, yamscripts.yml
Since lint is taking quite a long time with all the extra files, let's run our hook on `push` not `commit`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/893)
=> chore(build): Only run git hook on push not commit

content-src/main.js, data/content-bridge.js
There are some cases where we end up dispatching actions before the content bridge is set up, so the addon side never receives the initial messages to get data. Then the actions time out and the user is stuck hanging tight...
It only seems to happen in some cases when firing up Firefox with the Activity Stream page open. Happens more with e10s disabled. See issue for more details. I was able to reliably reproduce by having Firefox open my home page on startup. I would install the addon, make sure it was working, close Firefox, reopen Firefox, it still worked, close Firefox, reopen Firefox and then it was busted. Obviously it was a painful troubleshooting/debugging session.
r? @k88hudson 
Fixes #891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" …
=> fix (content): #891 wait for content bridge to be setup before render

lib/ActivityStreams.js, lib/MetadataStore.js, test/lib/MetastoreFixture.js, test/test-MetadataStore.js
This is the first cut of metadata persistence implementation #863. It now supports:
* insertion of metadata, images(favicon and preview), and relations of those two
* table dropping
* data expiry (for metadata only, not for images yet)
* executeQuery (raw SQL statements)
To be added shortly:
* more specific query APIs (once we know how we want to query against those tables)
* data expiry for images
Also, table schema is open to change anytime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/899)
=> Metadata store

content-src/components/TopSites/TopSites.js, content-src/components/TopSites/TopSites.scss
This patch fixes a weird issue where if you open a `ContextMenu` in Highlights and then open one in `TopSites`, the original one doesn't close. `stopPropagation` was messing with the window listener.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/924)
=> fix(content): #657 Restructure TopSite to remove stopPropagation

common/action-manager.js, content-src/components/Base/Base.js, content-src/reducers/SetRowsOrError.js, content-test/reducers/SetRowsOrError.test.js, lib/ActivityStreams.js, lib/RecommendationProvider.js
This change:
1. adds the redux part to actually show recommendations. 
2. fixes a typo I had in RecommendationProvider which went unnoticed because it was never being invoked until now
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/938)
=> feat(content): Add redux flow to recommendations

common/action-manager.js, common/event-constants.js, content-src/components/Base/Base.js, content-src/components/LinkMenu/LinkMenu.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js, content-src/reducers/Experiments.js, content-src/reducers/SetRowsOrError.js, content-src/selectors/selectors.js, content-src/static/img/glyph-pocket-16.svg, content-src/styles/icons.scss, content-test/components/LinkMenu.test.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.test.js, content-test/reducers/SetRowsOrError.test.js, content-test/selectors/selectors.test.js, content-test/test-utils.js, experiments.json, lib/ActivityStreams.js, lib/RecommendationProvider.js, package.json, test/test-RecommendationProvider.js
This sets up recommendations as an experiment and flips the pref on
Last patch for #870 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/906)
=> feat(content): #870 Turn recommendations on as experiment

content-src/components/Spotlight/Spotlight.js, content-test/components/Spotlight.test.js
fix #935. This adds the highlight source to the click pings.
The related change for the data pipeline will be made in Splice and Infernyx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1003)
=> feat(addon): #935 Track highlight source in click pings

content-src/components/TopSites/TopSites.js, content-test/components/TopSites.test.js
fix #978 r?@k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/997)
=> fix(content): #978 Put the active class on the tile-outer container instead of on the tile link.

lib/MetadataStore.js, lib/main.js, test/test-MetadataStore.js
This fixes #1002
Note that those two commits are closely related. The first one adds the database reconnecting feature, and the other one reinforces the exception handling in the case that the connection is either unopened or closed in the MetadataStore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1019)
=> Handle exceptions if the addon couldn't connect to Metadatastore

lib/TabTracker.js
Should Fix #1013 and #1022
r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1031)
=> fix (addon): #1013 only send tab data if there is an active tab

.eslintignore
As we're using fab to do the addon deploy, eslint will check the json assets in the Python virtual environment by mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1047)
=> chore (addon): Add python virtual env to eslintignore

lib/TabTracker.js, lib/TelemetrySender.js, package.json, test/lib/cachePromises.js, test/test-ActivityStreams-places-caching.js, test/test-PerfMeter.js, test/test-TabTracker.js
This seems to get us enough to turn on the multiprocess compatibility flag and to avoid the use of the shims (which may impact performance in e10s mode).
Most of the work here is to correct the uses of `Services.obs.addObserver` this is meant to take [three arguments](https://dxr.mozilla.org/mozilla-central/rev/0ba72e8027cfcbcbf3426770ac264a7ade2af090/xpcom/ds/nsIObserverService.idl#25), but for some reason with the shims / non-e10s we were getting away with two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1042)
=> fix(addon): #1033 Turn on the Multiprocess compatibility flag, correct the uses of addObserver, and avoid the use of shims.

content-src/styles/icons.scss
Fixes #1057
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1058)
=> fix(icon): Fix bad path to glyph-showmore-16.svg in icons.scss

lib/RecommendationProvider.js, test/test-RecommendationProvider.js
uses ```recommended``` as type, to be consistent with the type naming in ```content-src/HighlightContext/types.js``` @ncloudioj  r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1063)
=> chore(addon): Closes #1007 Add type for recommendations

.eslintignore, .storybook/config.js, .storybook/head.html, .storybook/webpack.config.js, content-src/components/ActivityFeed/ActivityFeed.scss, content-src/components/LinkMenuButton/LinkMenuButton.scss, content-src/components/LoadMore/LoadMore.scss, content-src/components/Loader/Loader.scss, content-src/components/MediaPreview/MediaPreview.scss, content-src/components/Search/Search.scss, content-src/main.js, content-src/styles/icons.scss, content-src/styles/variables.scss, content-test/components/ContextMenu.story.js, content-test/components/Spotlight.story.js, package.json, webpack.common.js, webpack.config.js, yamscripts.yml
I've removed the storybooks.io integration for the moment, in the interest of getting something landed, and because the current version of React storybook seems to have an odd install issue with it.
Presumably I'll need to squash this before landing, I've left the commits for reviewing, though, as they _might_ be useful in understanding the motivation for given changes.
r? @k88hudson
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1039)
=> React storybook

artifacts/latest/latest.html
Now passes https://validator.w3.org/nu/#textarea
For some reason this page was unscrapeable by https://github.com/mozilla/page-metadata-service/issues/49, but not sure if the invalid markup was the reason.
r? @oyiptong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1076)
=> fix(artifacts): Fix invalid markup in artifacts latest.html

lib/ShareProvider.js
This fixes makes each provider have it's own window so you can have multiple share windows open at once. And it makes sure to focus the window on share if it was already open in the background.
r? @ncloudioj 
Fixes #1107 
Fixes #1109 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1117)
=> fix (addon): #1109, #1107 use separate window per provider and focus it on share

addon/PlacesProvider.js, test/test-PlacesProvider-synced-tabs.js
The content side is blocked on the new "rules engine" for highlights. I figured I'd try to get the addon side merged before it rots. It will probably need some tweaks depending on how the rules get implemented but it's a good start.
r? @oyiptong and/or @sarracini and/or anybody else
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/988)
=> feat(addon): #411 get synced/remote tabs (addon side only)

addon/MetadataStore.js
@sarracini r?
Turns out it wasn't `sqlite.jsm` fault, it's mine. I should take the "credit" ;)
All the tests in your branch should pass now with this patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1166)
=> fix(metadata-store): #1165 - Drop the migrations table in reset

addon/ColorAnalyzerProvider.js
This closes #1139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1198)
=> fix(addon): #1139 Add error handling for colorAnalyzer

common/action-manager.js, content-src/components/ActivityFeed/ActivityFeed.js, content-src/components/Header/Header.js, content-src/components/Header/Header.scss, content-src/components/Search/Search.scss, content-src/components/TimelinePage/TimelineBookmarks.js, content-src/components/TimelinePage/TimelineFeed.js, content-src/components/TimelinePage/TimelineHistory.js, content-src/lib/fake-data.js, content-src/reducers/Filter.js, content-src/reducers/reducers.js, content-src/selectors/selectors.js, content-src/styles/variables.scss, content-test/components/ActivityFeed.test.js, content-test/components/Header.test.js, content-test/components/TimelinePage.test.js
Fix #416. This approach does the filtering in content after passing the query string to a new notify action that gets selected by the timeline page views. Tests are updated to handle the now-connected Header in addition to new tests covering dispatching notify action, passing filter query from `TimelinePage`, and filtering in `GroupedActivityFeed` component. Styles are mostly reusing the input from the `Search` component, so refactored accordingly.
Todo: file followup performance bugs, ui tweaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1199)
=> feat(content): Add basic token matching for Timeline all/bookmark views with search in header.

content-src/selectors/selectors.js, content-test/selectors/selectors.test.js
Fixed #1244 moves dedupe and lib/utils to /common
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1246)
=> Dedupe URLs before sending them to content side

common/recommender/Baseline.js, content-src/selectors/selectors.js, content-test/common/Baseline.test.js, content-test/components/NewTabPage.test.js, content-test/selectors/selectors.test.js
Default history size to 1 if it doesn't exist.
Default idf value to 1.
Keep first time use cards around until we have at least 6 highlights. This helps https://github.com/mozilla/activity-stream/pull/1153.
Add tests for the changes described above.
Fixes #1241 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1242)
=> Fixes #1241 - First time use with weighted highlights

content-src/components/NewTabPage/NewTabPage.js
This PR sends our key performance ping *after* a render occurs, not before. It will result in the load times recorded appearing to be slower in our metrics, since they will include render time.
Test this by adding `"extensions.@activity-streams.performance.log": true` to your dev prefs.
@emtwo do you think this is worth doing? if so, is there anywhere we can add a note for this?
Fixes #1271
=> fix(metrics): #1271 Send ping on didUpdate, not receiveProps

content-src/components/Header/Header.js, content-src/components/Header/Header.scss, content-src/styles/variables.scss, content-test/components/Header.test.js
Fix #1260. Adds just the dismiss button as the other items from the mock are outdated. Uses the existing dismiss icon. Adds tests for the new state and shared updating logic. r?@sarracini
=> feat(content): Add dismiss button for timeline filtering

addon/PlacesProvider.js
Added a left join to the bookmarks table so that the bookmark info is returned in getTopFrecentSites. When opening a new tab and expanding the context menu of a top site, it will now correctly show "Bookmark" or "Remove Bookmark" depending on the bookmark status.
=> fixes #847 top site bookmark info works in context menu

content-src/components/Header/Header.scss
Fix #1305. Visually hide the search input box without affecting tests. r?@k88hudson
=> fix(content): Disable search for current release

common/recommender/Baseline.js, content-src/selectors/selectors.js, content-test/common/Baseline.test.js
Fix for #1264, new metadata service does not return image size. Feature value ends up being `undefined` and therefore the final score is NaN. Using `width x height` to replace image size.
Small updates to the test as well to ensure all feature extraction methods provide defaults and that all function calls are made, because one test was actually making assertions on a stubbed method.
=> Bug 1264 missing image size

package.json
we stopped using `history` in d6c0aed3abcb83305564ccd0b5c73ba2fefb1815
=> chore (package): Remove history package

addon/ActivityStreams.js, common/action-manager.js
This PR fixes an issue where search strings are getting stored in the master store.
=> fix(page-worker): #1322 Don't sync search strings and suggestions

addon/PerfMeter.js, addon/PreviewProvider.js, addon/RecommendationProvider.js, addon/TabTracker.js, common/AbsPerf.js, content-test/common/AbsPerf.test.js
This PR switches the various timing uses of Date.now (except for httpd.js, which seems to be an external module, and I'd be surprised if we care about the timing there).
One can test some data collection by adding this to dev-prefs.json
```json
"extensions.@activity-streams.performance.log": true
```
On my relative new Macbook Pro, opening and closing 8 new tabs on master without this patch yielded this for NEWTAB_RENDER:
```
SIZE=8 MEAN=519.63 STD=31.69 MEDIAN=514.5
```
with the commits in this PR, it yielded
```
SIZE=8 MEAN=526.43 STD=30.83 MEDIAN=511.6549072265625
```
Which I would guess is not statistically significant.  That said, I'd also expect that it'll come in handing for we're timing smaller things, plus it avoids the occasional "NTP clock shift" issues.
Note that this change …
=> switch timing uses of Date.now to performance.now wrapper for better accuracy 

addon/ActivityStreams.js, addon/PreviewProvider.js, experiments.json, test/test-PreviewProvider-MetadataStore.js, test/test-PreviewProvider.js
- Sets up metadataService as an experiment
- Updates tests to mock the experiments bit
@jaredkerim r?
=> feat(experiments): Closes 1084 Run MetadataService vs Embedly

addon/ActivityStreams.js, content-src/components/DebugPage/DebugPage.js, content-src/selectors/selectors.js, content-test/faker.js, content-test/selectors/selectors.test.js, dev-prefs.json, package.json, test-prefs.json
This pull requests creates a weighted highlights experiment and turns it on for everyone.
Some questions:
cc @k88hudson
=> Create higlights experiment

content-test/index.js, content-test/meta/globals.test.js, content-test/test-utils.js, package.json, shims/_utils/globals.js
This PR adds overrides for globals in test utils, as well as a shim for `Task`. see `globals.test.js` for examples of usage.
=> Add generic override globals function and Task shim

addon/PlacesProvider.js, content-src/selectors/siteMetadataSelectors.js, content-test/selectors/colorSelectors.test.js, content-test/selectors/siteMetadataSelectors.test.js, test/test-PlacesProvider.js
Fix #1376 by using Services.eTLD to get the effective top level domain of a top frecent site url. Use that eTLD to remove it from the displayed hostname label.
r?@piatra
=> feat(topsites): Show shorter top sites label without top level domain

bin/generate-html.js
According to [devmo](https://developer.mozilla.org/docs/Web/Security/CSP/CSP_policy_directives) and the [implementation bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1045891), `child-src` was introduced in Firefox 45.
Currently the CSP lists both `child-src` and `frame-src`, however, as activity stream's minimum version is FF 45, all that needs to be listed is `child-src`.
This will also avoid the obsolete warning that is seen on the console when a new tab is opened.
=> fix(addon): Remove the frame-src definition as it is now obsolete.

content-src/components/ActivityFeed/ActivityFeed.js, content-test/components/ActivityFeed.test.js
Fix #1349 with a smarter `filterSites` to not just find a substring match anywhere but locate word boundaries and check case sensitivity. Added various tests checking the matching logic.
r?@sarracini
=> feat(timeline): Improve filtering with word boundary and smart-case-sensitive matches

addon/PlacesProvider.js, common/action-manager.js, common/reducers/Filter.js, common/reducers/SetRowsOrError.js, content-src/components/Header/Header.scss, content-src/components/TimelinePage/TimelineFeed.js, content-src/selectors/selectors.js, content-test/selectors/selectors.test.js, test/test-PlacesProvider.js
Fix #1302 by passing the filter to `PlacesProvider` allowing it to do the multi-token matching on title/url. These SQL-filtered results are tagged with the filter they were matched with, so that the selector only shows the results that are relevant to the current filter. This is faster because the 20 results the timeline gets are already most likely going to match the filter instead of going through many "pages" of non-matches.
This also fixes #1261 at the same time as it doesn't try showing many pages of results when clearing search. By including the tagged filter, more specific searches can be quickly ignored when deleting in addition to there being fewer fetched rows in the first place.
r?@sarracini
=> fix(timeline): Filter links with SQL and only show filter-compatible results

addon/MetadataParser.js, common/vendor-src.js, content-test/addon/MetadataParser.test.js, content-test/meta/shims/chrome.test.js, package.json, shims/chrome.js
* Creates a MetadataParser module (not actually used anywhere yet)
* Receieves a DOM, parses it
* Gets metdata for that DOM (from remote service)
* Formats it correctly for the metadataStore to insert it correctly 
* Module calls into remote page-metadata-parser service
* Import the page-metadata-parser package
* Tests for MetadataParser
* Adds relevant shims for MetadataParser
=> feat(metadata) Closes #1410 Create a metadata parser

addon/PlacesProvider.js, test/test-PlacesProvider.js
Fix #1300. Update the internal grouping by rev_host to a dynamic value based on whether the domain includes `www.` or not.
r?@k88hudson
=> fix(topsites): Dedupe www. sites with non-www. sites

addon/MetadataStore.js, addon/PageScraper.js, addon/PreviewProvider.js, test/test-MetadataStore.js, test/test-PageScraper.js, test/test-PreviewProvider.js
* Create a PageSraper module (not instantiated anywhere yet)
* Makes use of the MetadataParser to get metadata for links locally within page 
* Injects a frame script (not yet created) to get metadata for the page you're browsing
* Has a blacklist for links NOT to get metadata for (can be added to)
* Inserts metadata into the MetadataStore DB (and respectively to it's cache)
* Tests for PageScraper
* A function in PreviewProvider to check if the single page you're visiting already has metadata for it - in that case don't re-parse and re-compute metadata
* Tests for the addition of PreviewProvider's function
Fixes #1409
=> feat(metadata): Closes #1409 Create a page scraper

addon/ActivityStreams.js, package.json, test/lib/utils.js
* Creates an instance of PageScraper (pref'ed off)
* Creates a pref listener so that you can manually create an instance of PageScraper if you switch on ```extensions.@activity-streams.pageScraper``` to true.
* Adds the pref in ```package.json```
* Mocks out an instance of PageScraper for the tests
=> feat(metadata): Closes #1430 Init PageScraper and pref it off

addon/PageWorker.js, common/reducers/Filter.js, common/vendor-src.js, content-test/addon/PageWorker.test.js, content-test/common/reducers/equality.test.js, content-test/common/reducers/reducers.test.js, package.json
This PR changes the page worker behaviour so that it only saves a new copy of the redux state if anything has changed.
=> chore(performance): Only set state if differences were found

addon/ActivityStreams.js, addon/SearchProvider.js, addon/main.js, test/lib/utils.js, test/test-ActivityStreams-home-page.js, test/test-SearchProvider.js, test/test-TabTracker.js
* Mock the SearchProvider for tests that create an instance of ActivitySream
* Add a ```isUnloaded``` flag to ActivityStream to fix race condition of attempting to uninit when app is already destroyed (in ```test-TabTracker``` and ```test-ActivityStreams-home-page```)
* Make ```get currentState``` sync - it didn't need to be async
* Use the conventional way of creating an instance of searchProvider (create a ```this._searchProvider```)
* Pull it out of the scope of the addon, and into the scope of ActivityStream
* Clean up the SearchProvider
* Fix the SearchProvider tests 
* Add a before/after
* Fix deprecation warning about falling back to synchronous initialization of ```Services.search```
* Create a proper handler for the observe test
Ran the tests a bunch of times with these changes …
=> fix(tests) Closes #1196 Intermittent SearchProvider failure

.gitignore
When we run `npm run package` it's kind of annoying that these get added and not ignored. Can we just gitignore it? I'm doing this a lot for remote testing on windows.
=> chore(gitignore): Ignore .update.rdf

addon/PlacesProvider.js, test/test-PlacesProvider.js
Fixes #1275. Supersedes #1362.
Does the existing query (recent links) first then if there aren't enough results, do a subsequent query fetching enough links to reach the limit.
r?@ncloudioj
=> feat(highlights): Fetch a minimum number of results if not enough recent links

addon/ActivityStreams.js, addon/RecommendationProvider.js, test/lib/utils.js, test/test-RecommendationProvider.js
Problem: since we were calling the function ```_asyncUpdateRecommendations``` which makes a network request in the constructor, every time we were creating an instance of RecommendationProvider we were risking making a network call if that function executed without a network connection. 
Fix: Make an init function and only call that function if we have a timeout (which we set to null in the tests) & mock it out for when we create an instance of Activity Streams
** Also had to move the initialization of recommendationProvider into a separate function because the linter was complaining that ActivityStream's constructor is too big lol **
=> fix(tests): Fixes #1197 Intermittent RecommendationProvider failure

addon/ActivityStreams.js, test/lib/utils.js
~~I haven't been able to trigger the race condition manually or via our tests after removing the workaround. So I just removed the workaround. We'll see if travis is happy.~~
UPDATE: I figured it out. The issue was with the mock provider used for testing.
r? @k88hudson
=> fix (addon): #1314 remove ShareProvider race condition workaround

content-src/components/ContextMenu/ContextMenu.js, content-src/components/LinkMenuButton/LinkMenuButton.js
The issue was that `hideContext` was getting called and hiding the just shown context menu. This happens after sharing and also if you try to open a context menu while already having one open for another site. It's because `window.removeEventListener("click", this.hideContext);` wasn't called yet. There might be other ways to fix this?
@k88hudson r?
Fixes #1372
=> fix (content): #1372 stopPropagation of LinkMenuButton click

data/page-scraper-content-script.js
Don't listen for load event - send metadata as soon as we get DOMContentLoaded
=> fix(framescript): Don't wait for load before sending metadata

addon/PageWorker.js, common/vendor-src.js, content-test/addon/PageWorker.test.js, webpack.addon.config.js
This will prevent the cached state object from updating more than once a second – it's hard to actually see the effect of this unless you log inside of onDispatch, but tests are included. Fix #1512
=> Debounce pageWorker updates

content-src/selectors/selectors.js, content-test/selectors/selectors.test.js
Fix #1500. Removes unused History and bookmarks selectors.
Guess what? This also removes the test that was failing intermittently!!!!!!
=> Remove Timeline selectors and NO MORE INTERMITTENT TEST YAY

addon/ActivityStreams.js, addon/TabTracker.js, addon/main.js, test/lib/utils.js
* Pull TabTracker out of ActivityStream scope
* Put it in the scope of ```main.js```
* Update tests to reflect this change
=> shield(addon): Closes #1482 Pull tabTracker out of ActivitySteam scope

addon/ActivityStreams.js, addon/main.js, test/lib/utils.js
* Pulls ```TelemetrySender``` out of scope of Activity Stream so the shield study can use it too to send pings
* Update tests accordingly
=> shield(addon): Closes #1541 Pull TelemetrySender out of ActivityStream scope

.sass-lint.yml
I don't think this is a common issue we need to check for, and it's annoying seeing the warning every time.
=> chore(lint): Remove no-vendor-prefix rule for sasslint

addon/ActivityStreams.js, test/test-TabTracker.js
* Add a ```shield_variant``` field to pings in order to track which variant we are in
* Give it a default value for non-shield users
=> shield(metrics): Closes #1516 Add 'shield_variant' to pings

.storybook/config.js, common/action-manager.js, common/reducers/Hints.js, common/reducers/SetRowsOrError.js, common/reducers/reducers.js, content-src/components/DebugPage/DebugPage.js, content-src/components/DebugPage/DebugPage.scss, content-src/components/Hint/Hint.js, content-src/components/Hint/Hint.scss, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js, content-src/components/TopSites/TopSites.js, content-src/lib/fake-data.js, content-src/main.scss, content-src/styles/variables.scss, content-test/common/reducers/Hints.test.js, content-test/components/Hint.story.js, content-test/components/Hint.test.js
This patch adds:
- a `Hint` component (see comps here: https://mozilla.invisionapp.com/share/8F8V2GX3S#/screens)
- `Hint`s for Top Sites and Highlights
- a `Hints` reducer, to store (and persist) disabled hints 
- a button on the Debug page that can enable all of the hints again
To test it, please try:
- clicking on the "What's this?" text next to the Top Sites and Highlights titles on New Tab
- click on the blue button inside the hint (it should make the "What's this" text disappear)
- open another new tab, make sure "What's this" is still gone
- go to the debug page, and click the `Show all Tooltip Hints` button, and see if all the "What's this" reappear
=> Tooltip hints for Highlights, TopSites

content-src/components/HighlightContext/HighlightContext.scss, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/styles/variables.scss, content-test/components/Spotlight.story.js
fix(Highlights): fix vertical text cropping & layout in individual items (closes #1526)
The easiest way to test is to do:
npm run bundle
npm run storybook
(browse to localhost:9001)
and look over the various Highlight Item stories
=> fix vertical text cropping in items (#1526)

.eslintrc, common/constants.js, content-src/components/DebugPage/DebugPage.js, content-src/components/NewTabPage/NewTabPage.js, content-src/selectors/colorSelectors.js, content-src/selectors/getHighlightContextFromSite.js, content-src/selectors/oldSpotlightSelectors.js, content-src/selectors/selectAndDedupe.js, content-src/selectors/selectors.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.test.js, content-test/faker.js, content-test/index.js, content-test/selectors/oldSpotlightSelectors.test.js, content-test/selectors/selectAndDedupe.test.js, content-test/selectors/selectors.test.js
This patch simplifies the selectors used for Highlights by:
- Renaming "Spotlight" to "Highlights"
- putting some of the old stuff related to pre-weighted highlights into isolated, separate selectors (in `oldSpotlightSelectors.js`)
- simplifying deduping code (with a refactor of `selectAndDedupe`)
- adding detailed comments for most selectors
=> Refactor New Tab / Highlight selectors

addon/PlacesProvider.js
Fix #1555 by getting the same number of results for bookmarks and history then letting the weighting algorithm decide which to show. We don't need to arbitrarily limit bookmarks to 1 as we now show more than 3 results.
r?@k88hudson
=> fix(highlights): Use the same limit for bookmarks as history and let weighter decide

package.json
This fixes #1509. This appears to be the easiest solution by far after exploring other workarounds. See more details at #1509.
Note that we are only moving the `release` to the Test Pilot channel, everything else remains the same (i.e. being hosted in A-S S3 bucket) for the `dev` and `prerelease`.
=> chore(addon): #1509 - Host the add-on release channel via Test Pilot

addon/PreviewProvider.js, test/test-PreviewProvider-MetadataStore.js, test/test-PreviewProvider.js
Fix #1609 
* Explicitly unpacks the metadata fields that we care about onto a site object
* Update tests
@jaredkerim r?
=> chore(metadata): Closes #1609 Unpack metadata fields onto site object

common/recommender/Baseline.js, content-test/common/Baseline.test.js
- Dedupes the sites based on a key (in this case, domain)
- Update tests
=> fix(highlights): Fixes #1553 Limit highlights to one item per domain

content-src/components/NewTabPage/NewTabPage.js
Fix #1593. If the state for new tab page isn't ready yet, poll `localStorage` for stabilized changes to reload the page.
r?@sarracini
=> fix(content): Detect stabilization of state to reload from "Hang on tight"

addon/ActivityStreams.js, test/lib/utils.js
* Mocks out the PageWorker in ActivityStream tests
* Fixes warning ```this._pageWorker = null``` during tests
=> fix(tests): Fixes #1557 mock PageWorker to remove null warning

addon/MetadataStore.js, addon/PreviewProvider.js, test/test-MetadataStore.js
This fixes #1577 as well as following issues that we've encountered before:
* failure of fetching metadata if there are special characters in the `cache_key`
* `unique constraint violation` due to the similar bug in the "asyncCacheKeyExists"
More importantly, it prevents metadata store from the potential SQL injection hazard.
=> fix(metadatastore): #1577: Add parameterized query

.eslintrc, addon/ActivityStreams.js, addon/Memoizer.js, addon/PageScraper.js, addon/PlacesProvider.js, addon/PreviewProvider.js, addon/SearchProvider.js, addon/ShareProvider.js, addon/TabTracker.js, package.json, test/test-ActivityStreams-workers.js, test/test-MetadataStore.js
Adding some catch enforcement
So this patch only enforces the catching of promises - we should file another PR for logging it to a central place, once we decide what that is, so that we can essentially mimic what sentry does.
@k88hudson r?
=> fix(exceptions): Fixes #1667 add .catch to promises

.eslintrc
=> chore(lint): Switch to new import-globals rule to fix warnings

.storybook/config.js, addon/ActivityStreams.js, content-src/selectors/oldSpotlightSelectors.js, content-src/selectors/selectors.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.story.js, content-test/selectors/selectors.test.js, experiments.json
This PR forces on the weightedHighlights for all activity-stream users.  This is the lowest-risk way to get it turned on for the Shield study.  After this lands, #1611 can be moved out of La Mauricie and into Mount Revelstoke, where another PR will tear out the non-weighted code entirely so that that issue can be closed.
The main things to test here is that 
npm run test
the XPI generated by 'npm run package'
npm run firefox
all default to the weighted highlights in a new profile.
r? @sarracini
=> feature(Highlights): force on weightedHighlights for everyone

.eslintrc, package.json
Pretty much the same thing as #1684 with #1688 merged into the `eslint-plugin-mozilla` commit. Trying to track down why this is going red on master when it was green in #1684...
=> chore(package): update various dependencies to latest version

addon/TabTracker.js
Revert adding shield variant field to pings on MASTER - instead it will be added to the shield_study branch
=> shield(metrics): Revert #1598 Add 'shield_variant' to pings

addon/PreviewProvider.js
* Fix ```embedlyProxyRequestReceivedCount``` performance ping to have the correct value
=> metrics(metadata): Fixes #1713 Send correct value for perf ping

package.json
This upgrade adds a bunch of new sites and updated images.
Fixes #1706
=> content(metadata): #1706 Upgrade tippy-top-sites to 0.3.0

content-src/components/DebugPage/DebugPage.js, content-src/components/DebugPage/DebugPage.scss, content-src/styles/variables.scss
Fix #1721 . This patch adds a display for experiments in the debug page; no editing for now, but it does include a description of how to find the relevant prefs.
=> feat(experiments): #1721 Add display for experiments to debug

content-src/components/DebugPage/DebugPage.js
Fix #1738. Adds the "Highlights" choice back to the UI tester, and sets the default data source to `TopSites`
=> fix(debug): #1738 Restore Highlights to UI tester

karma.conf.js
Fix #1786. This patch adds the addon and common directory to coverage reporting, as well as excluding existing addon files with addon tests.
=> chore(coverage): #1786 Add common, addon to coverage reporting

common/constants.js, common/recommender/Baseline.js
Fix #1670 by not filtering out recently bookmarked/visited pages that relied on a pixel threshold. There isn't as much of a need to filter recent items now that we show 9 highlights.
r?@sarracini
=> fix(recommender): Remove recent filtering logic relying on faulty SCROLL_THRESHOLD usage

addon/ActivityStreams.js, addon/TabTracker.js, data_dictionary.md, data_events.md, test/test-ActivityStreams-home-page.js, test/test-TabTracker.js
Fix #1606 by setting the home page to a special #/HOME hash that gets reported as the page in payloads.
r?@rlr
=> fix(addon): Differentiate homepage-loaded activity stream for pings

content-src/components/DebugPage/DebugPage.js, fabfile.py
This closes #1799 and closes #1203 
For the dev and pre-release channel, it'll attach the commit hash to the version string. Also, it'll show the version in the DebugPage.
=> Add commit hash in the version string

addon/ActivityStreams.js, addon/TabTracker.js
=> Fix(addon): #1620 - Update experimentId for TabTracker upon changes

addon/MetadataStore.js, addon/PreviewProvider.js, addon/lib/utils.js, common/constants.js, common/selectors/colorSelectors.js, common/selectors/siteMetadataSelectors.js, content-src/components/SiteIcon/SiteIcon.js, content-src/lib/first-run-data.js, content-src/lib/utils.js, content-test/addon/PreviewProvider.test.js, content-test/common/selectors/colorSelectors.test.js, content-test/common/selectors/selectors.test.js, content-test/components/SiteIcon.test.js, content-test/components/Spotlight.story.js, content-test/faker.js, content-test/faker.test.js, content-test/lib/utils.test.js, test/test-MetadataStore.js, test/test-PreviewProvider-MetadataStore.js, test/test-PreviewProvider.js, test/test-utils.js
Consolidates favicon, favicons, and favicon_url into favicon_url
Consolidates background_color, favicons.color, favicon_colors, favicon_color into background_color
Does that on addon side so we only store the ones we need - and removes it from selectors side
Updates Tests
Don't review - needs addon tests for consolidation
=> fix(metadata): Fixes 1658 Consolidate favicon fields

addon/ActivityStreams.js, addon/PageModProvider.js, addon/PerfMeter.js, common/constants.js, content-test/addon/PageModProvider.test.js, content-test/addon/PerfMeter.test.js, shims/_utils/globals.js, shims/sdk/page-mod.js, shims/sdk/private-browsing.js, shims/sdk/util/uuid.js, test/test-ActivityStreams-workers.js
This patch refactors the worker management to use a `Map` with unique identifiers, so actions from each worker are tagged with a `workerId`. 
Actually using send/broadcast in feeds will be implemented in https://github.com/mozilla/activity-stream/issues/1829
=> feat(feeds): #1750 PageModProvider, add broadcasting/send to feeds

addon/ActivityStreams.js, addon/Feeds/SearchFeed.js, addon/lib/getCurrentBrowser.js, content-test/addon/Feeds/SearchFeed.test.js
This patch removes the rest of the search-related items from `ActivityStreams.js` and adds them to `SearchFeed.js`, and adds unit tests for each thing.
=> chore(feeds): #1829 Refactor respondToSearchRequests into SearchFeed

common/recommender/Baseline.js, content-test/common/Baseline.test.js
Fix #1794. Turns out enhanced links don't get bookmarkId passed but bookmarkDateCreated does. Also, the boost for bookmarks doesn't work for image-less ones because that score drops to 0, so multiplying doesn't do anything.
r?@ncloudioj
=> feat(highlights): Always show recent bookmarks even without images

content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-test/components/Spotlight.test.js
This patch changes the `Spotlight` component to show the hostname (e.g. `foo.com`) instead of the provider name.
=> fix(content) #1816 Use label instead of provider_name for spotlight

addon/MetadataParser.js, common/vendor-src.js, content-src/lib/getRelativeTime.js, content-src/main.js, content-test/lib/getRelativeTime.test.js, webpack.addon.config.js, webpack.common.js, webpack.config.js
This PR contains two bits of optimization:
1. 4b5595b changes the webpack config to exclude addon-only dependencies from `common/vendor`, as well as excluding un-needed node shims.
2. 1571bfe replaces `moment.js` in the build with a custom function. Note that moment.js is still used as a test utility.
In total, this results in a 46% reduction for the production build.
With patch (total 304k):
```
140K	./data/content/bundle.js
164K	./data/content/vendor.bundle.js
```
```
react: 617.99 KB (73.8%)
fbjs: 31.21 KB (3.73%)
redux: 22.36 KB (2.67%)
react-redux: 19.37 KB (2.31%)
url-parse: 11.23 KB (1.34%)
lodash: 5.77 KB (0.689%)
process: 5.17 KB (0.618%)
reselect: 3.74 KB (0.446%)
object-assign: 1.95 KB (0.233%)
invariant: 1.48 KB (0.177%)
object-sizeof: 1.47 KB (0.176%)
hoist-non-react-statics: …
```
=> Optimze webpack

addon/PlacesProvider.js, test/test-PlacesProvider.js
Fix #1874. r?@sarracini Some pages were picking the lower scored page instead of the higher scored page. We can use both scores by combining them.
=> fix(topsites): Combine frecency of deduped pages

addon/PreviewProvider.js
Just resolving doesn't stop the code execution - so it went through to getColor with a null favicon and then ColorAnalyzer exploded. We have to bail out completely if we don't have a favicon
=> fix(coloranalyzer): Fix #1842 Color Analyzer throwing

webpack.config.js
Tweaked webpack config to include polyfill for Buffer because it is
required by object-sizeof.
This was broken in 1917fda4ed555cf28567bbcd85defe1f99168b1c
r? @jaredkerim
Fixes #1875
=> fix (debug): #1875 Fix debug page

addon/ActivityStreams.js, addon/TabTracker.js, addon/TelemetrySender.js, common/action-manager.js, common/event-constants.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Spotlight/Spotlight.js, content-test/components/NewTabPage.test.js, content-test/components/Spotlight.test.js, data_dictionary.md, data_events.md, test/test-TabTracker.js
This needs to wait for @ncloudioj to be back to r? the new pings and create the new table. Not sure if @sarracini or @k88hudson is around to r? the addon and frontend code changes?
Fixes #1595
=> feat (metrics): #1595 implement undesired event pings for loader and missing image

common/constants.js, common/recommender/Baseline.js, content-test/common/Baseline.test.js
Fix #1887. Instead of a fixed number, base the boost on the age of the bookmark. r?@ncloudioj
=> fix(highlights): Heavily boost recent bookmarks and not much from 3 days or older

addon/PlacesProvider.js, common/constants.js, test/test-PlacesProvider.js
Fix #1855 and update tests to use the constant instead of hardcoded number.
=> fix(highlights): Use a single recent query with a limit of 500

addon/MetadataParser.js, addon/PageScraper.js, content-test/addon/MetadataParser.test.js, data/page-scraper-content-script.js, test/test-PageScraper.js
Makes ```parseHTMLText``` synchronous LIKE IT SHOULD BE
Properly catches errors in ```PageScraper```
Checks that the document actually exists before attempting to get it's outerHTML
Update tests
=> fix(pagescraper): Fix #1859 PageScraper unhandled exception

content-src/components/SiteIcon/SiteIcon.js, content-src/components/SiteIcon/SiteIcon.scss, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/components/TopSites/TopSites.scss, content-test/components/Spotlight.test.js
Fix #1892. r?@dmose There was a reference to "spotlight-icon" from `PlaceholderSiteIcon` that was being used for `PlaceholderSpotlightItem`, so I switched it to "site-icon" and updated both places.
After/before pictures here: https://github.com/mozilla/activity-stream/issues/1892#issuecomment-268619007
=> fix(newtab): Show a border between top site icon/title and highlight picture/details

addon/ColorAnalyzerProvider.js, addon/PreviewProvider.js
Shuts ColorAnalyzer up because it's crying all the time for no reason
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1922)
=> fix(coloranalyzer): Fixes #1920 Resolve on null color for ColorAnalyzer

addon/ActivityStreams.js
We were clearing the prefs before unhooking the pref change listeners. Clearing the prefs at the end of unload fixes the issue.
You can repro/verify fix by disabling and enabling from about:addons looking at your browser console.
r? @jaredkerim
Fixes #1867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1925)
=> fix (addon): #1867 fix ExperimentProvider exception on unload

addon/TabTracker.js, test/test-TabTracker.js
This closes #1877. 
The related change for the data pipeline is already deployed. We only track the total number of highlights as the first step instead of the breakdown as specified in #1877. The more detailed information could be implemented in the follow-up PRs or possibly by a new ping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1927)
=> fix(addon): #1877 Attach number of highlights in session ping

addon/PlacesProvider.js, experiments.json, test/test-PlacesProvider.js
Fix #1896. Support both original plain frecency and combined frecency as control and experiment variant. r?@sarracini 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1928)
=> experiments(topsites): Compare uncombined/combined frecency scores of deduped top sites

addon/ActivityStreams.js, addon/Feeds/PlacesStatsFeed.js, addon/MetadataStore.js, addon/PlacesProvider.js, content-test/addon/Feeds/PlacesStatsFeed.test.js, test/lib/utils.js, test/test-MetadataStore.js, test/test-PlacesProvider.js
* PlacesStats Feed now collects metadata coverage and sends a ping
* MetadataStore has 2 new functions - one which gets the oldest entry in the database and the other which counts the rows in the database
* PlacesProvider has a new function to get all the places entries since the earliest timestamp from MetadataStore
* Write some more tests
@jaredkerim r? cc @ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1926)
=> metrics(metadata): Closes #1897 Track metadata coverage for sites

.storybook/config.js, content-src/components/DebugPage/DebugPage.js, content-src/components/HighlightContext/HighlightContext.js, content-src/components/Snippet/Snippet.js, content-src/components/Snippet/Snippet.scss, content-src/main.scss, content-test/components/Snippet.story.js, content-test/components/Snippet.test.js, package.json
This patch adds a `Snippet` component, as well as an example in the `Debug` page, a storybook, and tests. Refer to the trello card for more information: https://trello.com/c/LmsamLox/39-as-mozilla-we-want-to-inform-our-users-about-interesting-things-marketing-initiatives-friendly-tips-other
To try it:
- Open the debug page, you should see it in the bottom
- Run `npm run storybooks`
Notes:
- I had to use `dangerouslySetInnerHTML` for the snippet description, since it sometimes contains links/other HTML. However, because this text is controlled internally, this should be OK. We should keep this in mind whenever we decide how to store/ship snippet content.
- There is no implementation of the snippet yet on the New Tab page, I will do that once we confirm the variants for the experiment in …
=> feat(content): #1906 Add Snippet component

addon/SearchProvider.js
remoteTimeout was throwing the error - it seems as though it's been deprecated from ContentSearch.jsm - which is where this code originally comes from. As seen here:
https://dxr.mozilla.org/mozilla-central/source/browser/modules/ContentSearch.jsm#270-271
If they don't need it then neither do we. And we're not using it anywhere in the repo either
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1936)
=> fix(search): Fixes #1900 Search suggestions not being displayed

addon/PlacesProvider.js, test/test-PlacesProvider.js
Fix #1918. Use 2x the visible limit for now. r?@sarracini
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1941)
=> fix(topsites): Limit queried sites closer to visible count

addon/Feeds/HighlightsFeed.js, content-test/addon/Feeds/HighlightsFeed.test.js
Cap the number of times we retry to get metadata after a re-install to > 5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1935)
=> fix(highlights): Fixes #1932 Cap the retry logic for HIGHLIGHTS_AWAITING_METADATA

addon/PlacesProvider.js, test/test-PlacesProvider.js
Fix #1898. Make sure we combine just the top page instead of all pages with a test. r?@ncloudioj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1946)
=> fix(topsites): Combine frecency of the top pages of with/without www instead of all pages

addon/PlacesProvider.js
Fix #1919. Just ignore the exception as it's expected for certain cases and is just control flow. r?@jaredkerim 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1943)
=> fix(places): Ignore expected control flow exception for bad URIs

addon/PageScraper.js, test/test-PageScraper.js
Handle the case that the image fails to load
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1948)
=> fix(pageScraper): Fixes #1947 Handle image load failures

addon/ActivityStreams.js, addon/Feeds/MetadataFeed.js, addon/PageScraper.js, content-test/addon/Feeds/MetadataFeed.test.js, experiments.json, test/lib/utils.js, test/test-PageScraper.js
* Creates an experiment to fetch page content locally
* If the experiment is on - call a new function in PageScraper
* Split some logic in PageScraper for less code duplication with new function
* Create a separate function for framescript listener (having it in the init is yucky)
* Update existing tests
* Write new tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1894)
=> feat(metadata): Closes #1685 Fetch page content locally

addon/PageWorker.js, content-test/addon/PageWorker.test.js
Lower the debounce time so we can sync up the store when someone opens a new tab immediately after doing a user action
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1958)
=> fix(store): Fixes #1766 Sync user actions to store update

addon/PreviewProvider.js, test/test-PreviewProvider.js
Add the ```bookmarkGuid``` to the link's properties so it can be checked against later when updating the context menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1959)
=> fix(bookmarks): Fixes #1957 Remove bookmark option unavailable

addon/ActivityStreams.js, test/test-TabTracker.js
Captures the event for when a user clears their history
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1963)
=> feat(metrics): Closes #1961 Capture telemetry for clearing history

addon/PreviewProvider.js, test/test-PreviewProvider.js
Fix #980. This got regressed with PreviewProvider change not extending the base link. r?@sarracini
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1983)
=> fix(topsites): Restore eTLD truncating

addon/Feeds/TopSitesFeed.js, addon/PlacesProvider.js, content-test/addon/Feeds/TopSitesFeed.test.js, experiments.json
Use the newtab sites that are returned by ```NewtabUtils.jsm``` which are the same links that about:newtab shows on it's tiles
cc @emtwo 
dxr links: 
https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#920
https://dxr.mozilla.org/mozilla-central/source/browser/base/content/newtab/grid.js#139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1954)
=> feat(experiments): Closes #1952 Use orig tiles algorithm for top sites

common/selectors/siteMetadataSelectors.js, content-test/common/selectors/siteMetadataSelectors.test.js
Followup from #1983. r?@rlr 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/1992)
=> fix(topsites): Guess that .com is a TLD if none is provided

addon/PlacesProvider.js, content-test/components/Spotlight.test.js, test/test-PlacesProvider.js
@Mardak I see you did the original eTLD stuff. Now we (@bryanbell) want it for everywhere else (highlights). r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2055)
=> fix (addon): add eTLD property after all places queries

.storybook/webpack.config.js
I broke this when I landed the enzyme changes.  Fixed, in about the same way this is already fixed for Karma.
To test:
```
npm run start
npm run storybook   # in a separate shell
```
then navigate to localhost:9001.  It should work rather than spewing a bunch of errors.
r=@rlr?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2067)
=> Workaround some enzyme/webpack weirdness for storybook

addon/TippyTopProvider.js, content-src/lib/first-run-data.js, package.json, test/test-TippyTopProvider.js
This patch bumps `tippy-top-sites` to 1.1.1, which includes
- larger icons
- a constant for `IMAGE_SIZE`
I filed https://github.com/mozilla/activity-stream/issues/2069 as a follow-up to change the first-run sites to be generated from tippy-top sites instead of being hardcoded, since this requires somewhat of a larger change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2070)
=> fix(content): Bumped tippy-top-sites for better icons

content-src/components/TopSites/TopSites.scss
r? @sarracini 
To repro: 
* start with a new profile
* enable the screenshots
* visit http://moz-activity-streams-prerelease.s3.amazonaws.com/
* open new tab page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2072)
=> fix (content): #2071 fix site title overflow in top sites experiment

content-src/components/Search/Search.scss
Make the search suggestions the biggest z-index (the top sites icon is at 1000)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2074)
=> fix(topsites): Fixes #2073 TopSites icon displayed over search suggestions

content-src/styles/variables.scss
Fixes an issue where letters are cut off in certain fonts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2086)
=> fix(content): #2079 Remove vertical padding on search input

content-src/components/TopSites/TopSites.scss
I couldn't reproduce this, but this will fix it; 
Note that `offset-inline-start` is an RTL-compatible version of `left`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2090)
=> fix(style): #2076 force alignment of top sites titles

content-src/components/SiteIcon/SiteIcon.scss, content-src/components/TopSites/TopSites.scss
Keeps the focus on top sites when you hover over link menu button. Works on both original tiles UI and new tiles UI
Uplift to 1.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2096)
=> fix(topsites): Fixes #1154 TopSites tile loses highlight on hover

content-src/components/HighlightContext/HighlightContext.js, content-src/lib/getRelativeTime.js, content-test/components/HighlightContext.test.js, content-test/lib/getRelativeTime.test.js, locales/en-US/strings.properties
Fix #2019. Localize the timestamps in the highlight context
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2119)
=> feat(l10n): Closes #2019 Localize number display

content-src/components/HighlightContext/types.js, content-src/components/LinkMenu/LinkMenu.js, content-src/components/Loader/Loader.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/Search/Search.js, content-src/components/Spotlight/Spotlight.js, content-src/components/TopSites/TopSites.js, content-src/lib/getRelativeTime.js, content-test/components/HighlightContext.test.js, content-test/lib/getRelativeTime.test.js, locales/en-US/strings.properties
Addresses the first few i18n comments mentioned here: https://github.com/mozilla/activity-stream/issues/2027#issuecomment-277087062
* Adds comments describing the strings for translators
* Uses unicode … rather than ```...```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2124)
=> feat(l10n): Closes #2122 Add comments to strings.properties

content-src/components/Spotlight/Spotlight.scss, content-src/components/TopSites/TopSites.scss
The selector for hiding site icons in Highlights was a little too greedy. I also fixed the height of the placeholder icon when the experiment is on to make it square.
Fixes #2091
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2105)
=> fix (styles): #2091 fix placeholder CSS when screenshot experiment enabled

locales/en-US/strings.properties
Firefox desktop uses the strings `Open Link in a New Window` and `Open Link in a New Private Window`. Change to make string consistent with desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2135)
=> String change to be consistent with desktop

content-src/components/TopSites/TopSites.scss
Quickest way to verify:
- start with a new profile (`npm run once` or whatever)
- visit https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html
- verify top sites with `screenshots` experiment on and off
Fixes #2125 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2138)
=> fix (styles): #2125 fix site icon fallback style in screenshots experiment

addon/Feeds/LocalizationFeed.js, content-test/addon/Feeds/LocalizationFeed.test.js
This patch allows `en-US`strings to be fallbacks for the selected locale.
This is kind of hard to manually test right now – check out the unit tests for an example for how it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2139)
=> fix(l10n): #2129 Fall back to en-US strings if some are missing

docs/localization.md
This patch adds documentation for how to localize new strings, as well as how to build a version of the add-on with different locales.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/activity-stream/2130)
=> docs(l10n): #2123 Add docs for localization

addon/Feeds/LocalizationFeed.js, bin/strings-import.js, common/constants.js, common/getLocalizedStrings.js, common/reducers/Intl.js, content-test/addon/Feeds/LocalizationFeed.test.js, content-test/common/getLocalizedStrings.test.js, content-test/common/reducers/Intl.test.js, content-test/test-utils.js
This patch fixes an issue where strings are not available during loading.
I also moved `DEFAULT_LOCALE` to our constants file.
=> More getLocalizedStrings to reducers

content-src/components/LinkMenuButton/LinkMenuButton.scss, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/components/TopSites/TopSites.js, content-src/components/TopSites/TopSites.scss, content-src/styles/variables.scss, content-test/components/TopSites.test.js
This diff is really hard to read but basically what I did was:
1. Move ```.tile``` so that it's nested in ```.tile-outer```. This allowed for some of the focus stuff to work properly
2. Add a new mixin for these "inner" elements, ```.tile``` and ```.spotlight-inner``` which keeps the border and shows the link menu button when you tab through it
The best way to test this is to just run this and start tabbing through the top sites and highlights. What happens is when you tab through it, it'll show focus in 3 ways: 1. the border shows up 2. background colour of ```.site-icon-title``` turns white and 3. the menu link button shows up. Another tab brings the menu link button into focus and if you press enter it'll open the context menu. This works for both top sites and highlights.
Note: In the …
=> feat(a11y): Closes #1993 Bring '...' button to foreground

content-src/components/Base/Base.js
Here is the fix – we were trying to look for locale data AFTER the strings were already being rendered, this adds locale data before. We missed this because we were testing languages that were variants of `en`. Oops!
We will add a test for non-`en` locales as a follow-up, but putting this up on its own since it's fairly urgent.
=> fix(l10n): #2158 use componentWillMount to load locale data

addon/Feeds/MetadataFeed.js, content-test/addon/Feeds/MetadataFeed.test.js, experiments.json
Close the old experiment, create a new experiment, switch all references to the new experiment.
=> Increase localFetch experiment population to 20% fixes #2144

addon/ExperimentProvider.js, content-test/addon/ExperimentProvider.test.js, mozilla-central/prefs_general.diff, package.json
* Creates a pref which, if set to false, will not initialize the experiment provider.
* Turns that pref to false in ```prefs_general.diff``` so we can turn them off during mochitests
* Adds a test
=> feat(prefs): Closes #2170 Global pref to turn experiments off

docs/mochitests.md, test/functional/mochitest/.eslintrc, test/functional/mochitest/browser.ini, test/functional/mochitest/browser_as_about_home.js
Fix #2151. Creates a mochitest to ensure activity stream takes over about:home
=> feat(tests): Closes #2151 Migrate about:home test to mochitest

content-src/components/TopSites/TopSites.js, content-src/components/TopSites/TopSites.scss
=> fix (style): #2217 round corners for full size icons

addon/ActivityStreams.js
This fixes an issue where if bookmark-related event is fired with no data (from a test, for example) it will not propagate through our system.
It was causing `data.action is undefined` errors
=> fix(events): #2113 do not fire bookmark events if no data in event

package.json, system-addon/bootstrap.js, system-addon/lib/ActivityStream.jsm, yamscripts.yml
This patch adds a task which simply copies changes from `mozilla-central` back to this repository.
It's needed because there were a couple of (small) review changes as per https://bugzilla.mozilla.org/show_bug.cgi?id=1344319
What do you think? Not exactly a sophisticated approach, but works for now maybe?
=> Add importmc task

package.json
just a tiny update for the Ycombinator icon.
before:
after:
=> chore (tippy-top): update tippy-top-sites to v1.2.1

package.json
this fixes the icon for talking points memo.
before:
after:
=> chore (tippy-top): update tippy-top-sites to v1.2.2

content-src/components/NewTabPage/NewTabPage.js, experiments.json
This one needs to be uplifted to release with an additional commit to deactivate it for now.
r? @ncloudioj 
Fixes #2246
=> fix (experiments): #2246 hide New Tab Prefs behind an experiment

addon/TabTracker.js
This issue was also found in performance/masga pings.
The fix is a workaround that checks the `session_id` field before each assignment statement (i.e. `session_id` as a left value).
=> fix(metrics): #2244 - fix the missing session_id in the event pings

content-src/components/TopSites/TopSites.scss
this fixes a little issue @bryanbell noticed where there is some extra space between the bottom of the screenshot and the hover border (the container was a little too tall).
before:
after:
=> fix (style): tweak for top sites hover state

karma.mc.config.js, package.json, system-addon/common/Actions.jsm, system-addon/common/Reducers.jsm, system-addon/jar.mn, system-addon/lib/ActivityStream.jsm, system-addon/lib/NewTabInit.jsm, system-addon/lib/Store.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/Store.test.js, system-addon/test/unit/unit-entry.js, system-addon/test/unit/utils.js, system-addon/vendor/Redux.jsm
This patch adds a store, actions, reducers, and Redux to the system addon. 
An instance of`lib/Store.jsm` when `lib/ActivityStream.jsm` starts up. It inititializes a redux store, as well as a list of `Feed`s.
I've included a really simple one for now called `NewTabInit`, that just logs the initial state. When the `MessageManager` lands, it can properly be hooked up to send the initial state to the content page.
I had to add a few things to help with tests, including:
- `rewire`, a babel plugin that allows us to rewrite `import` statements;
- `GlobalOverrider`, a utility to set and restore global variables (e.g. `Components.utils`). unfortunately `rewire` doesn't support globals.
As usual, run `testmc` to run the tests.
Try running the code in Firefox and checking your console output. You …
=> feat(mc): #2249 Add Store, Actions, Reducers, and Redux

content-src/components/NewTabPage/NewTabPage.scss, content-src/components/PreferencesPane/PreferencesPane.js, content-src/components/PreferencesPane/PreferencesPane.scss, content-src/main.scss, content-src/styles/variables.scss, content-test/components/PreferencesPane.test.js, locales/en-US/strings.properties
This changes the prefs modal to a sidebar among other tweaks listed out in the issue.
before:
after:
Fixes #2227
=> #2227 - New Tab Preferences Design Updates

bin/prepare-mochitests-dev, mozilla-central-patches/disable-search-tests.diff
This just adds a patch disabling some tests that are a bit too tightly coupled to help green up pine.  To test:
```
./bin/prepare-mochitest-dev
cd ../mozilla-central
./mach mochitest -f browser browser/components/search/test
```
Should no longer have 15 errors.
=> fix(tests) disable tightly coupled search tests on pine; closes #2339

bin/prepare-mochitests-dev, mozilla-central-patches/disable-tiles-tests.diff
This is part of the greening up of the mochitests.  It simply disables the tiles tests for now, since the tiles code itself is turned off on pine.  I'll file another issue to make sure that we reconsider what to do about this once we get close to turning on in m-c. Fix #2342
=> fix(tests): temporarily disable tiles tests on pine, closes #2342

mozilla-central-patches/disable-undo-notification-tests.diff
This disables a couple of tests which expect about:home and about:newtab to handle various migration undo related messages.  These will need to be implemented before we can pref on A-S in mozilla-central.
=> fix(tests): #2362 disable m-c undo notification tests

addon/Feeds/TopSitesFeed.js, addon/PreviewProvider.js, content-src/components/NewTabPage/NewTabPage.js, content-test/addon/Feeds/TopSitesFeed.test.js, experiments.json, test/test-PreviewProvider-MetadataStore.js, test/test-PreviewProvider.js
Create a new topsites screenshots experiment that includes a long metadata timeout so that high res icons don't disappear after 3 days.
=> Create Screenshots Long Metadata Cache Experiment #2263

addon/PreviewProvider.js, experiments.json
Create an experiment that increases the metadata cache timeout to a long time to see how it affects engagement
=> Create Local Metadata Long Cache Experiment fixes #2356

system-addon/jar.mn
I'm not sure if there's a better way to do this, but this should fix it
=> fix(mc): #2369 Only include .js and .jsm files from vendor dir

mozilla-central-patches/disable-search-tests.diff
This just completely disables a test that was already disabled on artifact builds.  Once this is pushed to pine, the browser_google_codes.js failure should go away. fix #2366
r=Mardak?
=> fix(tests): Fixes #2366 browser_google_codes.js failure on pine

karma.mc.config.js, system-addon/content-src/activity-stream.jsx, system-addon/content-src/activity-stream.scss, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/Base/Base.scss, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/components/TopSites/TopSites.scss, system-addon/content-src/lib/init-store.js, system-addon/data/content/activity-stream.html, system-addon/jar.mn, system-addon/test/unit/lib/init-store.test.js, system-addon/vendor/redux.js, webpack.system-addon.config.js
This patch ports code from `create-store` in the sdk add-on, but replaces the local storage rehydration with message-based rehydration provided by the system-addon. 
It also adds the `react-redux` bindings necessary for the React side of things, and a small placeholder `TopSites` component.
I figured externalizing `redux` was probably the right way to go in the end.
=> Add react-redux to content and Top Sites shell

bin/test-merges.js
All this does is fix test-merges.js to exit with an actual error code, so that chronic/cron notice the error and handle message sending correctly.
=> Fix(tests): fixes #2394 to make test-merges send mail on errors

package.json
Here is the changelog. The primary motivator is that stubs now have .resolve and .reject methods for more readable tests: sinonjs/sinon#1211. There are some breaking changes in 2.x compared to 1.x; I've verified that we're not using any of the APIs that have changed.
As far as testing, if this passes Travis, we're good.  :-) fix #2402
=> Chore(testing) Fixes #2402, upgrades Sinon to 2.1.0

addon/TabTracker.js, content-src/components/NewTabPage/NewTabPage.js, content-src/lib/fake-data.js, content-src/lib/first-run-data.js, content-test/components/NewTabPage.test.js, test/test-TabTracker.js
This closes #2355.
Note that we only collect the # of low-res favicons as the high-res one could be easily inferred by using `highres = total - lowres - screenshots`
=> chore(telemetry): #2355 - track low-res favicons in topsites

.eslintrc.js
fix #2407. For performance reasons, [Firefox is switching away from Task.jsm to async/await](https://bugzilla.mozilla.org/show_bug.cgi?id=1353542).  Our infrastructure is almost set to do this, except that right now, we've got eslint using the default ES5 parser, rather than the ES8/ES2017 parser.  
I'm not so sure that we want to accept all the ES2017 features in our code base, but I don't see a way to turn async/await on selectively.  Additionally, the [Firefox codebase is already set to use ES8](https://dxr.mozilla.org/mozilla-central/source/.eslintrc.js#26).
An additional big bonus is that it makes it possible to [write more readable tests of Promise-based stuff, and ones that more robust against becoming "evergreen"](https://wietse.loves.engineering/testing-promises-with-mocha-90df8b7 …
=> Switch eslint from expecting ES5 to expecting ES8

addon/TabTracker.js, common/event-constants.js, docs/data_events.md, test/test-TabTracker.js
Fix #2360 basically reverting #1782 2988d545 except the added `switch`/`case` structure. r?@rlr
=> fix(metrics): Remove no-longer-existant AddonWatcher usage

package.json, system-addon/lib/ActivityStream.jsm
Changes for `babel-plugin-jsm-to-commonjs` here: https://github.com/k88hudson/babel-plugin-jsm-to-commonjs/commit/1f14d9e7872873a399a3785af04e3dc61898f266
=> fix(mc): #2430 Upgrade jsm parser, lazily import feeds

addon/Feeds/MetadataFeed.js, content-test/addon/Feeds/MetadataFeed.test.js
The TopSitesFeed seems to have everything required already: https://github.com/mozilla/activity-stream/blob/04789d1c3c1b28afea575378a0f0d84d858e938d/addon/Feeds/TopSitesFeed.js#L75-L87
Fixes #2432
=> fix (metadata): #2432 fetch metadata for pinned sites first

system-addon/lib/TelemetrySender.jsm, system-addon/test/unit/lib/TelemetrySender.test.js, system-addon/test/unit/unit-entry.js, system-addon/test/unit/utils.js
Port of TelemetrySender file, with fresh unit tests.  It's not actually hooked up to anything yet, so the only thing to do to test is it to run the unit tests.
r=@sarracini?
=> feature(telemetry): fixes #2284, port TelemetrySender to system addon

system-addon/lib/ActivityStream.jsm, system-addon/lib/Store.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/Store.test.js
This patch adds a pref-based lazy-loading of method of turning feeds off and on.
Prefs can be stand-alone or experiment prefs depending on what is needed.
I still need to add the pref flipping for tests.
=> feat(mc) #2423 Add pref-based initialization for feeds

system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/lib/NewTabInit.jsm, system-addon/lib/Store.jsm, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js, system-addon/test/unit/lib/Store.test.js
These are review fixes as requested in Bugzilla Bug 1350411 (r=mconley), as well as some necessary test changes to reflect those fixes.
=> chore(mc): Backport changes from Bug 1350411

addon/Feeds/LocalizationFeed.js
Fix #2452. r?@sarracini There's a bug in `findClosestLocale` where the preferred locale is kept as "zh-TW" but the array of locales is checked as lower case, so it doesn't detect an "exact match" and falls back to partial matching of "zh-CN".
https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/l10n/locale.js#45-48
Fixing this so localizers can test their strings even though we won't be using the SDK for system-addon.
=> fix(l10n): Work around SDK locale selection bug by lower-casing

system-addon/common/Actions.jsm, system-addon/common/Reducers.jsm, system-addon/content-src/activity-stream.scss, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/Search/Search.jsx, system-addon/content-src/components/Search/Search.scss, system-addon/content-src/styles/variables.scss, system-addon/data/content/assets/glyph-forward-16-white.svg, system-addon/data/content/assets/glyph-forward-16.svg, system-addon/data/content/assets/glyph-search-16.svg, system-addon/data/content/assets/glyph-search-history.svg, system-addon/lib/ActivityStream.jsm, system-addon/lib/SearchFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/SearchFeed.test.js, system-addon/test/unit/unit-entry.js
Closes #2312 Adds some base functionality for the Search component:
- Search react component (just the search bar + button)
- CSS for the Search component 
- Functionality to perform a search
- Functionality to get the default engine so the search properly works
- Brand new assets for the new search spec: https://mozilla.invisionapp.com/share/GMBA4GJRA#/screens
- Tests for the reducer, and the feed
Notes: the actual search component isn't tested - though it's simple
To try it out: ```npm run buildmc``` in activity stream -> ```./mach build faster && ./mach run``` in mozilla-central. and voila! we are able to do some searches! (without suggestions for now)
=> feat(system-addon): Closes #2312 Create search feed + base search UI

addon/Feeds/PocketFeed.js, content-test/addon/Feeds/PocketFeed.test.js
Triggering a feed refresh on pref. change so that when experiment is turned on, firefox doesn't have to be restarted to see data.
=> feat(content): Refresh pocket feed on pref change

mozilla-central-patches/disable-as-top-sites-feed-tests.diff
This patch turns off top sites for tests.
=> fix(mc): #2423 Patch mozilla central to turn off top sites in tests

addon/Feeds/HighlightsFeed.js, content-test/addon/Feeds/HighlightsFeed.test.js
r? @sarracini and/or @jaredkerim 
The issue was that METADATA_UPDATED action was coming in before APP_INIT.
Fixes #2469
=> fix (feeds): #2469 ignore actions before APP_INIT in Highlights Feed

system-addon/common/Reducers.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
This patch moves default top sites from the reducer to the `TopSitesFeed`, so that defaults can take advantage of metadata extraction (so they can get screenshots, for example).
=> feat(mc): #2472 Integrate default top sites

addon/ExperimentProvider.js, content-test/addon/ExperimentProvider.test.js
Let's fire an event at experiment enrollment time to make it easy to detect when a user is first assigned to an experiment.
=>  Fire event for experiment enrollment fixes #2477

mozilla-central-patches/eslintignore.diff
Fix #2488. Don't merge this until https://bugzilla.mozilla.org/show_bug.cgi?id=1359481 gets to mozilla-central.
=> chore(mc): Remove unneeded eslint patch that has landed

addon/ExperimentProvider.js, addon/Feeds/PocketStoriesFeed.js, addon/Feeds/PocketTopicsFeed.js, addon/TabTracker.js, common/constants.js, content-src/components/HighlightContext/types.js, content-src/components/LinkMenu/LinkMenu.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/PocketStories/PocketStories.js, content-src/components/PreferencesPane/PreferencesPane.js, content-src/components/Spotlight/Spotlight.js, content-src/lib/fake-data.js, content-test/addon/ExperimentProvider.test.js, content-test/addon/Feeds/PocketStoriesFeed.test.js, content-test/addon/Feeds/PocketTopicsFeed.test.js, content-test/components/LinkMenu.test.js, content-test/components/PreferencesPane.test.js, docs/data_dictionary.md, package.json
This makes sure pocket is available to all users, but prefed off for the control group. The preference pane allows to opt-in to the experiment.
Had to put the condition to set the simplePrefs.prefs.showPocket into enroll() directly, as discussed, as the "experimentEnrolled" event is firing too late in this case.
=> feat(content): #2466 Enable pocket pref for all users

addon/Feeds/PocketStoriesFeed.js, content-src/components/LinkMenu/LinkMenu.js, content-src/components/PocketStories/PocketStories.js, content-test/components/LinkMenu.test.js, content-test/components/PocketStories.test.js
This PR adds the new impression tracking for Pocket plus test coverage for it.
We're tracking: views (list of tiles being displayed), clicks, save to pocket, and dismiss.
=> feat(content): #2486 Track impressions for Pocket

package.json, yamscripts.yml
Sorry, I missed this in review! The `startmc` task is currently broken on master
=> fix(build): Add in prebuildmc task

addon/Feeds/MetadataFeed.js, addon/PageScraper.js, content-test/addon/Feeds/MetadataFeed.test.js, experiments.json
This experiment will test the configuration of having long metadata cache timeout, no remote service calls, and a background periodic metadata refresh task which queries the PlacesDB for all URLs which do not have metadata and fetches them in the background.
This configuration consists of:
Long metadata cache timeout
Local Metadata Parser
No Metadata Service
Periodic background refresh task
=> Metadata Local Refresh Experiment fixes #2358

bin/test-merges.js
A simple fix that changes an error message for a github issue to clearly identify the problem and suggest a workaround.  r=@k88hudson?
=> fix(mc): closes #2519, fix err message/suggest workaround for test-merges

karma.mc.config.js, system-addon/content-src/components/Search/Search.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/lib/short-url.js, system-addon/test/unit/content-src/components/Search.test.js, system-addon/test/unit/content-src/components/TopSites.test.js, system-addon/test/unit/content-src/lib/short-url.test.js
This patch ports the code for generating short urls (e.g. `https://foo.com` => `foo`) from the test pilot add-on, which is possible now that we are using our own query that returns `eTLD`. 
I also ported relevant tests for the Search/TopSites components and added support for React/Enzyme in our karma config while I was there.
=> Port short url code and add tests for react components in system add-on

addon/TabTracker.js, common/constants.js, content-src/components/NewTabPage/NewTabPage.js, content-src/components/NewTabPage/NewTabPage.scss, content-src/components/Spotlight/Spotlight.js, content-src/components/Spotlight/Spotlight.scss, content-src/static/img/glyph-arrowhead-down-12.svg, content-src/static/img/glyph-arrowhead-up-12.svg, content-src/styles/icons.scss, content-test/components/Spotlight.test.js, package.json
A new customization feature to collapse Highlights by clicking on the section header.
Fixes #2385
=> feat (content): #2385 collapse highlights on section title click

package.json, yamscripts.yml
I thought this might be a helpful shortcut for people debugging coverage reports.
Test by running `npm run debugcoverage` after running tests, and you should see the report show up in a browser. 
/cc @Mardak @dmose @sarracini
=> chore(npm): Add debugcoverage task that opens coverage html report

system-addon/content-src/components/Search/Search.jsx, system-addon/lib/SearchFeed.jsm, system-addon/test/unit/lib/SearchFeed.test.js, system-addon/test/unit/unit-entry.js
Fix #2548. @sarracini @k88hudson There must be a better way to do this…?
note: there's two commits with different approaches. The former eagerly inits `ContentSearch` on activity stream init and the latter only inits when the search is rendered/mounted.
=> fix(mc): Closes #2548 Send a dummy content message to trigger ContentSearch initialization

docs/v2-system-addon/1.GETTING_STARTED.md
There are some people who need to work with our code base outside of our team, so I started on some general documentation for the system add-on:
=> docs(mc): Add getting started documentation

docs/v2-system-addon/unit_testing_guide.md, karma.mc.config.js, system-addon/test/unit/unit-entry.js
This patch adds some testing documentation, fixes source maps for Chrome (they don't work for Firefox), and includes`.jsx` files (whoops!)
The docs could definitely use a Best Practices section or something like that, but I thought it would be good to start with the basics
=> docs(mc): Add testing documentation

docs/v2-system-addon/data_events.md, system-addon/content-src/components/LinkMenu/LinkMenu.jsx, system-addon/content-src/components/Search/Search.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/.eslintrc.js, system-addon/test/schemas/pings.js, system-addon/test/unit/content-src/components/LinkMenu.test.jsx, system-addon/test/unit/content-src/components/Search.test.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx, system-addon/test/unit/lib/TelemetryFeed.test.js, system-addon/test/unit/unit-entry.js
This patch adds telemetry for Top Sites and their context menu options, and search.
I also added an assertion for testing user event actions which can be used like so:
```
assert.isUserEventAction(someAction);
```
=> chore(mc): #2572 Add Telemetry for search, Top Sites clicks

addon/PageScraper.js
We can't use Date.now() for this because the ETL job in Onyx will fail to load it into Redshift.
=> Replace performance ping values with a valid 32 bit integer fixes #2601

content-src/components/PocketStories/PocketStories.js, content-src/lib/fake-data.js, content-test/components/PocketStories.test.js
After discussion, we decided the simplest way is to use default events as "impression stats" won't add much value (trending topic don't seem to change much.)
=> feat(content): #2600 Add telemetry on the 'Read More' links for Pocket

docs/v2-system-addon/preferences.md, system-addon/bootstrap.js, system-addon/lib/ActivityStream.jsm, system-addon/lib/ActivityStreamPrefs.jsm, system-addon/lib/Store.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/ActivityStreamPrefs.test.js, system-addon/test/unit/lib/Store.test.js, system-addon/test/unit/unit-entry.js
This patch adds default pref setting to Activity Stream, including for feeds. The pref configuration is stored in `ActivityStream.jsm` although theoretically this could be moved to a separate file.
The schema for prefs is pretty much the same as in `package.json`, although it does allow for different values to be set in different contexts:
```
{
{
name: "telemetry",
title: "Enable system error and usage data collection",
value: false
},
{
name: "pocket",
title: "Some other pref about pocket",
values: {
nightly: true, // In nightly, the default value will be true
default: false // In other builds, the default will be false
}
},
}
```
=> feat(mc): #2507 Add ActivityStreamPrefs.jsm to manage default prefs

content-src/components/PocketStories/PocketStories.scss
=> fix(content): #2637 Pocket info modal needs a faster fade-in-out

addon/PlacesProvider.js
When you add labels to bookmarks it saves 1 bookmark per label (in the places.db) When displaying spotlight items the key prop used in React is places.guid (which is the same for all items) so it only gets rendered once. But the .slice(0, 3) call on `sites` already happened so you end up actually showing `3 - (number of duplicates)` items.
=> Group duplicate bookmarks as 1 item

mozilla-central-patches/disable-tiles-tests.diff
Fix #2344. Now that https://bugzilla.mozilla.org/show_bug.cgi?id=1369875 has landed, we should be able to reenable tiles tests
=> tests(mc): #2344 Reenable tiles tests

mozilla-central-patches/disable-search-tests.diff, system-addon/content-src/components/Search/Search.jsx
Fix #2340. Don't land this until https://bugzilla.mozilla.org/show_bug.cgi?id=1371479 lands.
First change removes the disabling of search tests except for the one removed by #2366 because we're using artifact builds on `pine`.
Second change is to correctly use "newtab" as the `searchPurpose` and "activity" as `healthReportKey`. See: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/contentSearchUI.js#32-35
r?@sarracini
=> fix(mc): Re-enable tightly-coupled search tests and correctly use newtab as the searchPurpose

addon/PlacesProvider.js
Replace GROUP BY with the correct filtering of bookmarks. Discussion here https://github.com/mozilla/activity-stream/pull/2687
=> Filter out bookmark labels, reverts the changes from #2687

docs/v2-system-addon/data_events.md, system-addon/common/Actions.jsm, system-addon/common/Reducers.jsm, system-addon/content-src/activity-stream.scss, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss, system-addon/content-src/styles/_icons.scss, system-addon/content-src/styles/_variables.scss, system-addon/data/content/assets/glyph-settings-16.svg, system-addon/lib/ActivityStream.jsm, system-addon/lib/PrefsFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/content-src/components/PreferencesPane.test.jsx, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/PrefsFeed.test.js
This patch adds the Prefs panel to the system add-on, as well as a feed that watches changes for all activity-stream-related prefs and writes them to a`Prefs` reducer.
To manually test this, click on the gear in the top right hand corner and try flipping the prefs.
=> feat(mc): #2684 Add Prefs feed, panel UI, and reducer

mozilla-central-patches/disable-usage-telemetry-tests.diff, system-addon/content-src/components/Search/Search.jsx
Change the source to be "newtab" so it can be recognized in BrowserUsageTelemetry.jsm and we get the search events properly. Also change the id on the input to "newtab-search-text" (which is what the test looks for). As a consequence this fixes the browser_UsageTelemetry_content.js test, so we can re-enable it on pine 
cc @Mardak there's no reason this *needs* to be "activity", right?
=> system-addon(tests): Closes #2348 Re-enable browser_UsageTelemetry_content.js

content-src/components/CollapsibleSection/CollapsibleSection.scss
=> fix (style): #2708 fix top site icon truncation during collapse animation

content-src/components/Spotlight/Spotlight.scss
Today's fix of #2708 causes Highlights and Top Stories to break into a new line after the second tile.
This commit fixes that.
=> fix(content): Enhance #2708 fix to avoid line wrapping of Highlights

content-src/components/PocketStories/PocketStories.js
```
FAILED TESTS:
PocketStories
valid stories
should render a SpotlightItem for each item
Firefox 54.0.0 (Linux 0.0.0)
expected 3 to equal 2
```
The intermittent failure occurs if the test data generated by faker.js causes a key collision for tiles. For Pocket, we use the URL as key. The URL data is generated by a random selection of tippy-top-sites, which makes collisions much more likely compared to Highlights, which use the GUID as key.
Now that we have a reliable GUID for Pocket stories we can use it as key.
=> fix(tests): Intermittent test failures of PocketStories on Travis

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, package.json, system-addon/common/PerfService.jsm, system-addon/content-src/lib/detect-user-session-start.js, system-addon/lib/TelemetryFeed.jsm, system-addon/lib/TelemetrySender.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/common/PerfService.test.js, system-addon/test/unit/content-src/lib/detect-user-session-start.test.js, system-addon/test/unit/lib/TelemetryFeed.test.js, system-addon/test/unit/lib/TelemetrySender.test.js, system-addon/test/unit/unit-entry.js, system-addon/test/unit/utils.js
This adds basic performance telemetry infrastructure and the first bits of telemetry that use it for the new tab.  I suspect it'll mostly be easier to review the individual commits.
How to test if it's working
1. Edit [system-addon/lib/Activity-Stream.jsm](system-addon/lib/Activity-Stream.jsm) and 
set the `telemetry.log` preference value to `true`.
2. `npm run startmc`
3. `cd ../mozilla-central && ./mach build && ./mach run`
4. Open the Browser Console
5. Create a new tab
6. Close it
7. Make sure the logged session ping has an appropriate .perf object
=> feat(performance): #2539 Add perf telemetry + infrastructure

docs/v2-system-addon/telemetry.md
"As a developer, I have a simple checklist that I can go through when I want to add some telemetry so that I can avoid missing things or having to redo them."
This is a straw-man checklist for how to add telemetry items to the system add-on.  I'm not convinced it's necessarily right at this point, and I'd love some feedback from @emtwo, @ncloudioj, @k88hudson, @tspurway, and anyone else who cares to give it.
Fixes #2700
=> Add a telemetry doc

addon/ActivityStreams.js, addon/Feeds/BookmarksFeed.js, addon/PageScraper.js, addon/PlacesProvider.js, common/action-manager.js, content-src/components/LinkMenu/LinkMenu.js, content-test/components/LinkMenu.test.js, content-test/components/PocketStories.test.js, test/test-PageScraper.js
Explanation:
Previous version of the `getBookmarks` query filtered by `last_visit_date` IS NOT NULL. 
This excluded default bookmarks but also Pocket Stories that you would bookmark.
With this fix we try to fetch metadata information when a bookmark is added. If the page is visited it will just hit the Metadata store cache, otherwise (as for Pocket Stories) it will make a network request.
And filtering for the section happens based on metadata & images being present.
If you happen to actually visit a default bookmark page and metadata is present then yes the link will show up in the Bookmarks section.
Alternative solution included `PlacesUtils` module and added a "fake" visit in `moz_places` with current timestamp when you added a bookmark.
Fixes #2718
=> Add bookmarks from pocket to recent bookmarks

system-addon/bootstrap.js
Fix #2741. r?@sarracini
Matches the notifications from `nsBrowserGlue` https://dxr.mozilla.org/mozilla-central/source/browser/components/nsBrowserGlue.js#324-328
=> fix(mc): Wait until delayed startup instead of startup complete

docs/v2-system-addon/1.GETTING_STARTED.md, system-addon/README.md
This patch cleans up our getting started page a little and adds a table of contents.
=> Add table of contents, clarification for docs

system-addon/content-src/components/LinkMenu/LinkMenu.jsx, system-addon/test/unit/content-src/components/LinkMenu.test.jsx
This patch refactors `LinkMenu` for more flexibility in terms of what user events can be dispatched.
It also makes `userEvent` optional.
For example, a `BOOKMARK_ADD` action that must be sent to the chrome process:
```js
const AddBookmark = site => ({
id: "menu_action_bookmark",
icon: "bookmark",
action: ac.SendToMain({
type: at.BOOKMARK_URL,
data: site.url
}),
userEvent: "BOOKMARK_ADD"
});
```
or an `OPEN_DIALOG`, that should only be dispatched locally:
```js
const DeleteUrl = site => ({
id: "menu_action_delete",
icon: "delete",
action: {
type: at.OPEN_DIALOG,
data: {...}
}
});
```
=> chore(mc): #2752 Refactor LinkMenu for clarity, flexibility

system-addon/bootstrap.js, system-addon/common/Actions.jsm, system-addon/lib/ActivityStream.jsm, system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/lib/ActivityStreamPrefs.jsm, system-addon/lib/LocalizationFeed.jsm, system-addon/lib/NewTabInit.jsm, system-addon/lib/PlacesFeed.jsm, system-addon/lib/PrefsFeed.jsm, system-addon/lib/Store.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/lib/TelemetrySender.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/ActivityStreamPrefs.test.js, system-addon/test/unit/lib/PlacesFeed.test.js, system-addon/test/unit/lib/PrefsFeed.test.js, system-addon/test/unit/lib/Store.test.js, system-addon/test/unit/lib/TelemetryFeed.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js, system-addon/test/unit/unit-entry.js, system-addon/test/unit/utils.js
Fix #2750 and fix #2759. r?@k88hudson I've pushed various separate commits that optimize in various ways. Try runs seem to confirm fixing the `sessionrestore` Talos regression.
https://treeherder.mozilla.org/perf.html#/compare?originalProject=try&originalRevision=99adfb3d3f9edb5de25fb9325a25c9a149a1548c&newProject=try&newRevision=368b0dd9c3e2b68fbd6048f551a24cf53129088e&framework=1
Local profiles show it reducing the running time of `bootstrap.js`'s `observe` from 40ms to 20ms.
Here's a description of commits:
Defer loading until after sessionrestore: Looks like we can wait until later without affecting the ability to restore about:newtab or open Firefox directly to about:newtab
Convert looping to for-of: Various microbenchmarks seem to have .forEach being faster after it gets optimized …
=> fix(mc): Optimize startup init by avoiding overhead and lazy loading

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
This patch reuses existing screenshots from the old state when refreshing top sites – it results in a lot less screenshots being computed.
=> fix(mc): #2770 Reuse existing screenshots if they exist

mozilla-central-patches/enable-mc-as.diff
Fix #2785. r?@dmose
This will turn things on for `pine`. And when we actually turn on in mozilla-central, we can get rid of this patch (as it will be the patch being reviewed by mconley to pref on for Nightly.
=> fix(mc): Turn off processPrelaunch when preffing on activity stream

system-addon/lib/TelemetrySender.jsm, system-addon/test/unit/lib/TelemetrySender.test.js
Because `[Object object]` is not a particularly useful ping
=> fix(mc): (nobug) Stringify telemetry sender payload

system-addon/lib/ActivityStreamPrefs.jsm, system-addon/lib/Store.jsm, system-addon/test/unit/lib/ActivityStreamPrefs.test.js
r?@k88hudson Didn't actually remove the observer on uninit. Also has `ignoreBranch` be the first thing on `uninit` just in case something triggered pref changes during `uninit`.
=> fix(mc): Stop observing the same branch observed

mozilla-central-patches/disable-undo-notification-tests.diff
=> fix(mc): Allow notification tests to run now that AutoMigrate is off

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, system-addon/lib/TelemetryFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/lib/TelemetryFeed.test.js
Fix #2728. r?@dmose See https://github.com/mozilla/activity-stream/issues/2728#issuecomment-312049022 for reasoning behind actually sending ping instead of aborting.
=> fix(mc): Allow for pings from sessions that did not "start"

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #2821. Just adds a listener in the feed for the history cleared action and refreshes
=> feat(systemaddon): Closes #2821 Implement clear history

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Reverts mozilla/activity-stream#2822
This is breaking any test that clears history:
https://treeherder.mozilla.org/#/jobs?repo=pine&revision=9b6d236e412509e7972c064458dfca6a30917f25&selectedJob=112428374&filter-resultStatus=testfailed&filter-resultStatus=busted&filter-resultStatus=exception&filter-classifiedState=unclassified
This didn't actually work because refresh tries to `SendToContent` but history clearing is triggered independent of a page, so we probably want `BroadcastToContent` instead from `refresh`
=> Revert "feat(systemaddon): Closes #2821 Implement clear history"

system-addon/content-src/lib/short-url.js, system-addon/test/unit/content-src/lib/short-url.test.js
The issue is that localhost has eTLD set to localhost. This results in `shortURL` to slice it completely returning an empty string. This change returns hostname which always exists given a valid URL. Should guard against similar scenarios with custom/special DNS entries.
=> fix(system-addon): Return a topsite label for localhost. Closes #2814

system-addon/test/unit/content-src/components/LinkMenu.test.jsx
The first bullet point (correct options for default sites and bookmarks, pinning) was covered by tests added in 8647c9c. This should cover making sure actions are dispatched with the correct data and making sure `intl` gets called.
=>  tests(systemaddon): Fixes #2754 Improve LinkMenu test coverage

system-addon/lib/Screenshots.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/functional/mochitest/blue_page.html, system-addon/test/functional/mochitest/browser.ini, system-addon/test/functional/mochitest/browser_getScreenshots.js, system-addon/test/unit/lib/Screenshots.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #2820. removes dependency on preview provider so that we don't have to deal with failures from: https://bugzilla.mozilla.org/show_bug.cgi?id=1343150
=> feat(systemaddon): Closes #2820 Remove dependency on Preview Provider

locales/en-GB/strings.properties, locales/en-US/strings.properties
Fixed in en-GB and en-US. Also capitalised `Show More` for consistency.
=> fix(testpilot): Fixes #2613 Typo in Top Sites Editor

system-addon/lib/TopSitesFeed.jsm
Fix #2849. r?@sarracini Just adds a lazyModuleGetter that we don't end up triggering.
=> fix(mc): Temporarily restore reference to PreviewProvider

system-addon/bootstrap.js, system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/unit-entry.js
Fix #2856. r?@sarracini Delay `addObserver` which loads bookmark service which loads annotation service. Use `dispatchToMain` instead of loading `Timer.jsm`
=> fix(mc): Use dispatch avoiding Timer.jsm to delay some startup

system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/lib/short-url.js, system-addon/test/unit/content-src/components/TopSites.test.jsx
@aaronrbenson do you think this is acceptable? Showing title when we can't get a URL. This happens when you open a file from your computer instead of accessing a website, there might be other scenarios but edge cases basically.
Fixes #2857
=> fix(systemaddon): Fallback to link title for topsite title.

system-addon/content-src/components/Sections/_Sections.scss
Unprefixed user-select causes Mozilla Central test failures.
=> fix(systemaddon): Delete unprefixed user-select in css

addon/ActivityStreams.js, addon/ExperimentProvider.js, addon/TabTracker.js, content-test/addon/ExperimentProvider.test.js, package.json, test-prefs.json, test/test-TabTracker.js
Experiment Provider now has two modes, one where it is fully synchronous during unit tests and receives its experiment definitions from an external caller, and the other where it asynchronously fetches experiment definitions periodically from a remote source and reinitializes itself.
=> Query experiment definitions from experimenter fixes #2100

system-addon/common/Reducers.jsm, system-addon/content-src/lib/init-store.js, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/init-store.test.js
Fix #2829 with the narrow fix to handle `null` action data when reducing. More broadly catches exception on dispatch to prevent them from mysteriously leaking from RemotePageManager. r?@k88hudson 
Unfortunately, this doesn't fix the current `onboarding` leak.
=> fix(mc): Catch content dispatch errors to prevent RemotePage reporting them (and leaking)

system-addon/content-src/styles/_icons.scss, system-addon/data/content/assets/glyph-check-16.svg
Re-use the existing check.svg so that pine can be happy again
=> fix(systemaddon): Closes #2918 Reuse check.svg from firefox

system-addon/content-src/components/Search/Search.jsx, system-addon/test/unit/content-src/components/Search.test.jsx
Reverts mozilla/activity-stream#2921
Backed out for causing
```
FAIL | browser/components/search/test/browser_amazon_behavior.js | Test timed out [log…] 
FAIL | browser/modules/test/browser/browser_UsageTelemetry_content.js | Test timed out [log…] 
```
https://treeherder.mozilla.org/logviewer.html#?job_id=116099787&repo=pine&lineNumber=3970
https://treeherder.mozilla.org/logviewer.html#?job_id=116099802&repo=pine&lineNumber=4637
=> Revert "fix(mc): #2917 Only initialize search on focus"

system-addon/content-src/components/Sections/_Sections.scss
Minor fix to add some space below the empty state placeholder:
=> fix(systemaddon): Add margin below empty state placeholder

.eslintrc.js, content-src/.eslintrc.js, content-test/.eslintrc.js, system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/ContextMenu/ContextMenu.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/.eslintrc.js, system-addon/test/unit/content-src/components/ContextMenu.test.jsx
As now there's more people touching system-addon code, `jsx-no-bind` should be an easy way to make sure we don't accidentally cause performance/memory regressions by having React unnecessarily re-`render`.
I ended up needing to create a `ContextMenuItem` to hold a reference to `option` so that it can be accessed from callbacks.
=> chore(lint): Turn on jsx-no-bind for system-addon and clean up existing code

system-addon/common/Reducers.jsm, system-addon/test/unit/common/Reducers.test.js
Adds an action in the reducer for sections for adding and removing bookmarks
=> fix(systemaddon): Closes #2930 Bookmarking from context menu does nothing

system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
The "offending" hash value is caused by blocking undefined. So, at some point the call to ```blockURL``` was implemented incorrectly, passing a string instead of ```{url: value}```. This caused the hash value in the ```browser.newtabpage.blocked``` list. This is no longer a problem in Activity Stream.
Now, I have made a similar mistake when calling ```isBlocked``` passing the url instead of ```{url: value}```. If now undefined was previously blocked, all URLs will appear blocked.
=> fix(systemaddon): All links blocked by NewTabUtils. Closes #2941

locales/en-US/strings.properties, system-addon/common/Actions.jsm, system-addon/content-src/activity-stream.scss, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/ManualMigration/ManualMigration.jsx, system-addon/content-src/components/ManualMigration/ManualMigration.scss, system-addon/content-src/components/Search/_Search.scss, system-addon/content-src/styles/_icons.scss, system-addon/content-src/styles/_variables.scss, system-addon/data/content/assets/glyph-info-16.svg, system-addon/lib/ActivityStream.jsm, system-addon/lib/ManualMigration.jsm, system-addon/test/unit/content-src/components/ManualMigration.test.jsx, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/ManualMigration.test.js
Still waiting on spec for the messages, button text. 
Fixes #2787
=> Add Manual Migration component.

system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/styles/_icons.scss, system-addon/data/content/assets/glyph-topsites-16.svg
Fix #2942. Adds the top sites icon to match the headers for sections
=> fix(systemaddon): Closes #2942 Update top sites header with icon

system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx
Fix #2923. r?@rlr 
As an example with auto and not:
=> fix(content): Use dir=auto for various context-provided text

locales/en-US/strings.properties, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
Fix #2934. r?@sarracini Replaced the hardcoded "Pocket" with `{provider}` and added notes.
=> fix(l10n): Add better localization notes for section strings

system-addon/lib/ActivityStream.jsm
Fix #2943. Turns on top stories by default for locales en-US and en-CA
=> feat(systemaddon): Closes #2943 Pocket on by default for en-{US,CA}

system-addon/content-src/components/Base/_Base.scss
The icon was vertically aligned to the middle and the text was aligned to the top. This makes them both aligned to the middle.
r? @sarracini 
Fixes #2958
=> fix (systemaddon): #2958 vertically align section title

docs/v2-system-addon/snippets.md, system-addon/content-src/activity-stream.jsx, system-addon/content-src/lib/snippets.js, system-addon/lib/SnippetsFeed.jsm, system-addon/test/unit/content-src/lib/snippets.test.js, system-addon/test/unit/lib/SnippetsFeed.test.js, system-addon/test/unit/unit-entry.js
This PR adds information about profile age and telemetry to `gSnippetsMap` for use by snippet payloads.
=> feat(mc): Add profile age, telemetryEnabled to snippets

system-addon/content-src/activity-stream.scss, system-addon/content-src/components/ContextMenu/_ContextMenu.scss, system-addon/content-src/styles/_variables.scss
Fix #2978. r?@dmose Further photon matching to be done #2979
=> fix(styles): Use Photon grey-90 for dark-grey and action buttons

system-addon/content-src/lib/snippets.js
The snippets payload is responsible to select a snippet to display. It's very
possible that no snippet qualifies. In this case #snippets-container should stay
hidden, otherwise the snippets payload will unhide it.
See also [mozmeao/snippets-service@2a2e16](https://github.com/mozmeao/snippets-service/commit/2a2e16aeaa474cfd523ded02e6f72d68eba875af#diff-050fa7fbdf0fa60913c8fc36985fa302R26)
/cc @k88hudson
=> Let snippets payload unhide #snippets-container.

system-addon/content-src/components/ManualMigration/ManualMigration.scss
=> fix(systemaddon): Prevent migration button text from wrapping.

docs/v2-system-addon/snippets.md, system-addon/content-src/lib/snippets.js, system-addon/test/unit/content-src/lib/snippets.test.js
This adds blocking functionality for snippets that can be used by the payload JS
=> feat(mc): #2017 Add blocking to snippets.js

system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/lib/ActivityStream.jsm
Suggestion for a simple fix of #2973.
Reason I used "hidden" (negated showByDefault) is so nobody has to reset their prefs to keep seeing top stories.
=> feat(topstories): Hide preference section for unsupported locales

system-addon/lib/ManualMigration.jsm, system-addon/test/unit/lib/ManualMigration.test.js
=> Migration for old profiles

system-addon/content-src/components/ManualMigration/ManualMigration.scss
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385235
issue #2787 introduced a migration request message for new profiles. Unfortunately, this looks worse on RTL builds than on LTR. 
The change I am suggesting included using margin-inline-end correctly, so the same rules will apply correctly to both LTR and RTL builds.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1385235
=> Change margin on Manual Migration message for better RTL support

system-addon/lib/TopSitesFeed.jsm
This shouldn't land until https://bugzilla.mozilla.org/show_bug.cgi?id=1384977 makes its way from autoland to mozilla-central so that pine doesn't break.
r?ursula Fix #2984.
=> chore(testing): #2984 remove reference to PreviewProvider.jsm

system-addon/content-src/components/ManualMigration/ManualMigration.scss
Follow up from: https://github.com/mozilla/activity-stream/pull/3008#pullrequestreview-52925047
=> fix(systemaddon): Use margin-inline-end/start for migration component

docs/v2-system-addon/preferences.md, system-addon/lib/ActivityStream.jsm, system-addon/lib/ActivityStreamPrefs.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/unit-entry.js
Fix #3004. r?@k88hudson This cleans up `AS.jsm` a little bit to not have a separate `SECTIONS` and just inlines it to the rest of `FEEDS_DATA`. Also sorts things alphabetically.
The main core change is that prefs can have a `valueFunc` that will compute a value based on geo/locale. If geo isn't available, it'll observe the pref and update the pref config as well as updating the default.
This should also greatly simplify things for #2776.
=> feat(pocket): Use geo and locale to determine when to enable Pocket

system-addon/data/content/activity-stream.html
CSP tag on Report-Only mode which reports to a prod endpoint as per the comment in ticket fix #2645 
@dmose @Mardak @k88hudson @ncloudioj  what do we think?
=> feat(systemaddon): Closes #2645 Add <meta> CSP to activity-stream.html

system-addon/lib/ActivityStream.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
Follow up to https://github.com/mozilla/activity-stream/pull/3021, fixes #3000, by making sure the feed re-initializes when its options have changed.
This also includes the refactoring to no longer read the locale from within the TopStoriesFeed.
=> feat(topstories): Get new recommendations on locale|options change

system-addon/content-src/components/Base/_Base.scss, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/content-src/components/Topics/_Topics.scss, system-addon/content-src/styles/_variables.scss
I also added a couple of commits to fix some responsive styling for the topics part of the Top Stories section, and fixed the vertical spacing being uneven
=> Add extra space for snippets, fix various CSS stuff

system-addon/content-src/components/Card/Card.jsx, system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/lib/PlacesFeed.test.js
=> fix(topstories): Ctrl-click/middle mouse button does not open new tab

system-addon/lib/LocalizationFeed.jsm, system-addon/test/unit/lib/LocalizationFeed.test.js, system-addon/test/unit/unit-entry.js
Fix #3003. How to test:
1. download a de-DE nightly build
2. in about:config, set the various appropriate *xpinstall* prefs to false
3. `npm run packagemc`
4. from about:addons, use the gear dropdown menu to install the .xpi
5. open a new tab, verify that the words are in german rather than English
=> Fix(l10n): closes #3003, makes locale fallback work

system-addon/bootstrap.js, system-addon/test/functional/mochitest/.eslintrc.js, system-addon/test/functional/mochitest/browser.ini, system-addon/test/functional/mochitest/browser_as_load_location.js, system-addon/test/functional/mochitest/browser_as_render.js, system-addon/test/functional/mochitest/head.js
Fix #2880. r?@dmose Beefs up `as_load_location` to work preloaded or not and activity-stream.enabled or not. Adds a `head.js` that turns on activity-stream with a set of basic actual react rendering tests covering some of those itemized in #2127. Also cleans up eslint to use the fancy "plugin:mozilla/browser-test" that auto-globalizes-head.js helpers (and other test globals).
Try looks good when a-s.enabled: https://treeherder.mozilla.org/#/jobs?repo=try&revision=2b1081f19bfc7b5adbd761e347a26fd264b55783
And disabled: https://treeherder.mozilla.org/#/jobs?repo=try&revision=34f4c5cf8fbe1c0e2933c429e270e03817b55b2c
=> fix(tests): Add mochitests that run successfully whether enabled or not

system-addon/lib/ActivityStream.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Fixes #2776. r?@k88hudson 
Uses the `getValue` of #3021 and updates `TopSitesFeed` to watch pref changes instead of just grabbing once on init.
=> feat(topsites): Use different default sites depending on geo

system-addon/content-src/components/Topics/_Topics.scss
These CSS adjustments for Topics are the only way I found to get relatively consistent rendering of the "View More Stories" anchor on Windows/Mac/Ubuntu, using the provided svg.
Other alternative is to adjust the svg or get rid of it (it's not localizable anyway to RTL)
Before (bad alignment of ">" on Win):
After adjustments (Win/Mac/Ubuntu):
=> style(mc): Fix view more stories alignment on windows

system-addon/lib/ActivityStream.jsm, system-addon/lib/SnippetsFeed.jsm, system-addon/lib/TelemetrySender.jsm, system-addon/test/unit/lib/SnippetsFeed.test.js, system-addon/test/unit/lib/TelemetrySender.test.js, system-addon/test/unit/unit-entry.js
Fix #3056 and fix #3007.
I've updated the PR to also fix TelemetrySender and related tests, as well as updating the value on every new tab init.'
I also snuck a `.hasFxAccount` property into snippets data
=> use Services.telemetry.canRecordBase, enable snippets by default

system-addon/common/Dedupe.jsm, system-addon/common/ShortURL.jsm, system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/lib/link-menu-options.js, system-addon/lib/TopSitesFeed.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/common/Dedupe.test.js, system-addon/test/unit/common/ShortUrl.test.js, system-addon/test/unit/content-src/components/LinkMenu.test.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx, system-addon/test/unit/lib/TopSitesFeed.test.js, system-addon/test/unit/lib/TopStoriesFeed.test.js
Fixes #2933 
Dedupe happens in the Feeds. I've added the hostname key to the site objects because it is displayed in the cards. Previously the value returned by `shortURL` was named title (especially in the tests) it but made it confusing since websites already have a title.
=> fix(systemaddon): Dedupe Topsites

package.json
Fix #3051. This version of tippy-top-sites only has the 16 sites that are included in our default top sites list. See https://github.com/mozilla/tippy-top-sites/blob/v1.3.1/top_sites.json
r? @Mardak
=> fix (systemaddon): #3051 update to tippy top v1.3.1 (default sites only)

system-addon/common/Reducers.jsm, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/lib/ActivityStream.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/ActivityStream.test.js
Fix #3054 with https://bugzilla.mozilla.org/show_bug.cgi?id=1386445 but this can land separately. When the bug lands, it will allow activity stream to load earlier, and some things don't quite work right when running earlier. Those are fixed here mostly small fixes checking if things actually exist before using them.
One meaningful change is `ac.BroadcastToContent({` of `INIT` that causes the page/content's `Reducer` to actually set `initialized` on the `App` state, which also needed a fix to pull in `INITIAL_STATE.App` as `prevState`
=> fix(init): Let content know things are initialized and fix "early" issues

mozilla-central-patches/patch-referenced.diff
r?@dmose If we want to fix pine and test `npm install` stuff.
=> tests(mc): Patch for pine to fix browser_all_files_referenced test failure

system-addon/bootstrap.js
Fix #3065. r?@dmose Just applied the patch directly then fixed 2 eslint issues: no-use-before-define (can't fix as `observe` calls both `onBrowserReady` and `onPrefChanged`). and `==` vs `===`
=> chore(bootstrap): Backport Preferences -> Services.prefs change from bug 1357517

system-addon/content-src/components/Sections/Sections.jsx, system-addon/content-src/components/Sections/_Sections.scss, system-addon/test/unit/content-src/components/Sections.test.jsx
This gets most of the suggestions in fix #2997.  We'll have to spin off a bug to do the aria-describedby work, as well as getting better focus stuff for 57 for the expanded info option.
=> Fix(a11y): closes #2997, add basic a11y support to section-info-option

system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js
=> mcbackport bug 1385090; Closes #3060; Closes #2819

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Should fix https://github.com/mozilla/activity-stream/issues/3071
What I think is happening:
- When we call [`insertPinned`](https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/TopSitesFeed.jsm#L74) we call it with `pinned` which do not have the hostname property. If it happens that the pinTitle is missing then we end up with `title = undefined`.
=> Add hostname to pinned links.

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
=> fix (systemaddon): #3058 refresh TopSitesFeed when TippyTopProvider init is complete

system-addon/common/Reducers.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js
Closes #2945.
Cause of bug seems more of an edge case: if you switch from AS to Tiles you could get different sites presented to you and pin > 12 sites. I managed to get 14 pinned sites on my profile. These show up on `PINNED_SITES_UPDATED` actions because the reducer does not `slice` the results.
I moved the slice in the actual component this way we could catch the issue if it happens from other sources as well.
It should not be a problem for people coming over from Tiles because they only had at most 12 tiles.
=> fix(systemaddon): Limit the number of topsites being rendered.

system-addon/common/Reducers.jsm, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/content-src/components/TopSites.test.jsx, system-addon/test/unit/lib/TopSitesFeed.test.js
Closes #3080.
When switching your pinned sites from tiles we would store `pinTitle = site.title` which is not what we want. Currently pinTitle is not being used we just ported from Test Pilot side so I went ahead and removed it completely.
=> fix(systemaddon): Remove pinTitle from sites, currently not being used.

system-addon/content-src/lib/link-menu-options.js, system-addon/test/unit/content-src/components/LinkMenu.test.jsx
This is a followup to pull #3091
Since we aren't using the `pinTitle` right now, we don't need to save it. We will probably need it back when we implement customization, but we should call it `label` or something less confusing at that point.
r? @piatra
=> fix(systemaddon): remove title from pinned site pref value

system-addon/lib/SnippetsFeed.jsm, system-addon/lib/TelemetrySender.jsm, system-addon/test/unit/lib/SnippetsFeed.test.js, system-addon/test/unit/lib/TelemetrySender.test.js, system-addon/test/unit/unit-entry.js
This reverts commit aeee212d3f0c4ede4647e065af8a328ca6f5bc11.
After some discussion with gfritzsche, it looks like we need to use the datareporting.healthreport.uploadEnabled pref (which refers to the uploading of data) not .canRecordBase, which refers to the recording of data.
=> Revert #3007 use Services.telemetry.canRecordBase for snippets telemetry

bin/prepare-mochitests-dev
The pine script blew up this morning because we don't currently have any patches in the mozilla-central-patches directory.  Here's a fix.
=> fix(testing): make prepare-mochitest-build work even if no patches

system-addon/lib/Screenshots.jsm, system-addon/test/unit/lib/Screenshots.test.js
Fix #3099. r?@sarracini Add a helper function that can consistently process large number of bytes. Adds tests for it too!
=> fix(screenshots): Split bytes into smaller chunks to run through fromCharCode

system-addon/test/functional/mochitest/browser.ini
Fix #3100. r=@sarracini already reviewed as part of https://hg.mozilla.org/integration/autoland/rev/02f357c8e980 but can't land until that makes it to mozilla-central.
=> chore(tests): Re-enable getScreenshots test with bug 1387682 fixed

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, system-addon/common/Actions.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/common/Actions.test.js, system-addon/test/unit/lib/TelemetryFeed.test.js
This closes #2898. r? @k88hudson 
@fmarier Could you take a look at the new pings defined in `data_events.md`?
@csadilek This is lite literally a direct port from the Test Pilot Pocket telemetry. Wanna take a quick look at it, please?
=> feat(mc): Add telemetry for Pocket

system-addon/common/Reducers.jsm, system-addon/content-src/components/Base/Base.jsx
Fix #3092 and address some of #3090.
Here's how startup renders 10x slowed down:
https://ed.agadak.net/as/activity-stream.startup.strings.10x.webm
=> fix(init): Wait until we have strings to render/update

system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx
This does two things: 
* avoids extra marks that corrupt topsites_first_painted_ts fix #3105 
* switches to using RFA + Promise instead of double RFA to make painting times more precise.
The part that is easily testable is the extra marks: 
1. start up the browser
2. start the profiler
3. open a new tab
4. capture the profile
5. In the profile, switch to the Markers view
6. Enter "User Timing" in the filter textbox
7. Go through the main and all content processes
8. There should be one, or at most two, topsites_first_painted_ts
There should be exactly two topsites_first_painted_ts.
r? Mardak
=> Topsites telemetry fixes (#3105)

system-addon/lib/TelemetryFeed.jsm, system-addon/test/unit/lib/TelemetryFeed.test.js
Fix #3118. r?Mardak  This should be the exact fix we already discussed.
=> fix(telemetry): #3118 workaround 500s apparent topsites_first_paint_ts

system-addon/content-src/components/TopSites/_TopSites.scss
Fix #2975. r?@sarracini This makes the font bigger on Linux matching a <tab>'s label. The change doesn't affect the look on Mac.
Double checking with @bryanbell that this screenshot looks okay:
=> fix(styles): Use message-box for font (including sizing) for Top Sites title

system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js
Fix #3094. r?@k88hudson This is just backporting https://hg.mozilla.org/mozilla-central/rev/b48486fff521 and adding tests.
=> fix(channel): Check if message port had already loaded to simulate a load

system-addon/lib/ActivityStream.jsm, system-addon/lib/SectionsManager.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/SectionsManager.test.js, system-addon/test/unit/unit-entry.js, system-addon/test/unit/utils.js
=> feat(system-addon): Implement SectionsManager for custom sections

system-addon/data/content/activity-stream.html
=> chore(favicon): Closes #3123 Show the Firefox (or Nightly) logo

system-addon/content-src/components/Sections/_Sections.scss, system-addon/content-src/components/Topics/_Topics.scss
Just minor tweaks after recent changes. Not sure why the ">" need another realignment but fixing it by removing code is always welcome :). Tested on Windows, too.
Before:
After:
=> fix(style): Minor adjustments after #3076 fix

system-addon/content-src/lib/link-menu-options.js, system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/content-src/components/LinkMenu.test.jsx, system-addon/test/unit/lib/PlacesFeed.test.js
Fix #3126. Backport of: https://bugzilla.mozilla.org/show_bug.cgi?id=1388863 . Do not merge until that's landed
=> [DO NOT MERGE] chore(mc): Backport bug 1388863 add bookmarking UI

system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/test/unit/content-src/components/TopSites.test.jsx
This adds some hover buttons for the Top Sites edit modal:
Default (first run) sites only get a Pin button since we don't allow dismissing them:
Fixes #3133
=> feat (systemaddon): #3133 edit hover menu: pin and dismiss buttons

system-addon/content-src/components/LinkMenu/LinkMenu.jsx, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/content-src/components/LinkMenu.test.jsx, system-addon/test/unit/lib/TopSitesFeed.test.js
allows you to dismiss, but not delete, default top sites
=> fix(contextmenu): Closes #3188 Default Top Sites should be dismissable

system-addon/content-src/components/Card/_Card.scss
I think the font size is already 14px, so the only outstanding issue left is the vertical alignment of the icon with the label. Removing this fixes that
=> fix(css): Closes #3076 Context string is vertically aligned

system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
just uses transform. tested in rtl 👍 Fix #3192
=> fix(sidebar): Closes #3192 Minimize sidebar repaints during animation

system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js
Fix #3163. r?@k88hudson Just call `onNewTabInit` similar to calling `onNewTabLoad` when inheriting pages.
=> fix(channel): Always simulate an init for existing ports

system-addon/lib/LocalizationFeed.jsm, system-addon/test/unit/lib/LocalizationFeed.test.js
Fix #3052. r?@dmose Needed to update the test to have `negotiateLanguages` correctly return the default as part of the array. Also a slight behavior change of using the best negotiated language as the locale instead of what would have been returned by `getRequestedLocale`, e.g., "xyz" in the test.
Here's a screenshot of pretending bn-IN had a top sites string of "Llocs principals" then falling back to bn-BD (see search) then en-US (see migration):
=> feat(l10n): Use strings from multiple locales in order of negotiated languages

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Closes #3220.
Call refresh when a topsite is blocked.
=> fix(systemaddon): Refresh TopsitesFeed when blocking to keep 12 Topsites

system-addon/content-src/components/Base/_Base.scss, system-addon/content-src/components/ManualMigration/_ManualMigration.scss, system-addon/content-src/components/Search/_Search.scss, system-addon/content-src/components/Sections/_Sections.scss, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/content-src/styles/_variables.scss
Fix #2738. This change is on top of #3225 to fix the .scss file naming. This changes the float of stories to just absolutely position the (?) like how top sites edit button.
@aaronrbenson Here's some screenshots of before/after at 1344 x 768px window with first run (onboarding and migration) and ongoing. Potentially we can tighten the space between top sites and pocket as there's whitespace around the site label that is in addition to the 40px spacing.
before screenshot of first run user:
after screenshot of first run user:
before screenshot of ongoing user:
after screenshot of ongoing user:
=> fix(styles): Adjust spacing to be 40px around each section

system-addon/lib/ActivityStream.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
Upgrades the Pocket endpoint to version 2 which uses a more generic payload and includes fields which will be used to experiment with recs personalization, at a later point.
=> feat(topstories): Upgrade Pocket API to version 2

system-addon/lib/ActivityStream.jsm
CDN for Pocket just became available, so switching endpoints to use the CDN instead.
=> feat(topstories): Use CDN for pocket endpoints

system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss, system-addon/content-src/components/Sections/_Sections.scss, system-addon/content-src/components/Topics/Topics.jsx, system-addon/content-src/components/Topics/_Topics.scss
Fix #3238. r?@csadilek Topics and/or r?@AdamHillier Info Section or for both. Also removed the width on topics section (not sure why it was there and not the right width to begin with…?) and moved the logo to `::after` as `inline-block` so it can be `transform`ed.
RTL:
and RTL info dropdown:
=> fix(styles): Fix Topics and others with inline-start/end instead of left/right

system-addon/moz.build
Fix #3243. r?@dmose Mostly from https://hg.mozilla.org/mozilla-central/rev/f3455c101b7a#l5.1
=> chore(build): Backport and fix bug 1355088 to use correct bug component

system-addon/common/Reducers.jsm, system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/lib/ActivityStream.jsm, system-addon/test/unit/content-src/components/PreferencesPane.test.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx
This adds a "Show More" button to the Edit Top Sites modal:
Clicking it expands Top Sites to two rows and the button changes to "Show Fewer" which does the opposite:
Fixes #3132
=> feat (systemaddon): #3132 implement 1 vs 2 rows for Top Sites

system-addon/content-src/activity-stream.scss, system-addon/content-src/components/Search/_Search.scss, system-addon/content-src/components/Sections/_Sections.scss
Followup to Amy's comment in https://github.com/mozilla/activity-stream/issues/2979#issuecomment-325012363
The inherits don't seem totally necessary as it appears that the colors are the same.. But if you set `body {color: red}` to test, you can tell they're not using the right colors.
For info-option-icon, adjusted color to be darker on hover and tweaked the position of the appearing doorhanger as requested.
=> chore(styles): Fix various followup style tweaks from design

system-addon/content-src/components/ManualMigration/_ManualMigration.scss, system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
Fix #3244. r?@piatra Refactor Manual Migration spacing styles to use a variable and remove the fixed `height`s. Also makes the pref label/header a block so multi-line wraps to the same position.
=> fix(styles): Avoid fixed heights to wrap long strings properly

system-addon/lib/ShortURL.jsm, system-addon/test/unit/lib/ShortUrl.test.js
`eTLD` information required to trim the hostname comes in puny code form. The fix is to just handle the i18n at the end when we have the final hostname.
fixes #3221
=> Bug #3221 topsite etld

bin/update-version.js
Versions slightly changed with #3286. r?@dmose
=> chore(build): Restore version zero pad of minutes to 4 instead of 5

system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/unit/content-src/components/TopSites.test.jsx
@Mardak thoughts on this approach?
One difference is that `new URL("http://whatever")` is valid. That's weird, but I guess it is technically correct?
=> fix (systemaddon): use `new URL()` instead of regex for validation

system-addon/content-src/components/Card/Card.jsx, system-addon/test/unit/content-src/components/Card.test.jsx
Setting the menu items at a section level is through `contextMenuOptions`. At a card level it's through `context_menu_options`. They should be the same, and camel case is also consistent with other card properties.
=> fix(sections): Rename context_menu_options to contextMenuOptions for consistency

system-addon/content-src/components/Sections/Sections.jsx, system-addon/lib/ActivityStream.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/lib/UserDomainAffinityProvider.jsm, system-addon/test/unit/content-src/components/Sections.test.jsx, system-addon/test/unit/lib/TopStoriesFeed.test.js, system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
closes #3259 .
This PR adds support for personalized recs based on domain affinities. 
*This functionality is turned **off** by default.* We want to bring this in so we can run experiments in 57.
The algorithm works as follows:
- Pocket's endpoint (v2) returns a settings object containing *timeSegments* [1] and *parameterSets* [2]
- For every time segment we calculate the corresponding domain visit counts, yielding result objects of the following structure: ```{"mozilla.org": 12, "mozilla.com": 34}```
- These visit counts are transformed to domain affinity scores for all provided parameter sets: ```{"mozilla.org": {"paramSet1": 0.8, "paramSet2": 0.9}, "mozilla.org": {"paramSet1": 1, "paramSet2": 0.9}}```
- The parameter sets provide factors for weighting which allows for flexible …
=> feat(topstories): Personalized recs based on user domain affinities

system-addon/common/Reducers.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #3296. Instead of the Reducer listening for a ```BLOCK_URL``` and also a ```TOP_SITES_UPDATED``` event that comes from TopSitesFeed.jsm when you block -> refresh, we should just send a ```TOP_SITES_UPDATED``` event when we received the OK from PlacesFeed that the link has been blocked/deleted/history cleared. That way we save ourselves a bounce of a message.
=> fix(topsites): Closes #3296 Deleting from history should update the top sites

system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/lib/PlacesFeed.test.js
Fix #3201. This fixes the warnings and makes everything happy again.
=> fix(systemaddon): Fix #3201 Add missing history/bookmark observer methods to avoid warnings from xpconnect.

system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/lib/PlacesFeed.test.js
Fix #3203 and closes #3317 by superseding.
=> fix(places): Avoid impacting performance when listening to onItemChanged for bookmarks - avoid the fetch by disabling the unused code for now

system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
=> fix(styles): Have pref options stretch in height but anchor icon to top line

system-addon/common/Dedupe.jsm, system-addon/lib/ShortURL.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/common/Dedupe.test.js, system-addon/test/unit/lib/ShortUrl.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js, system-addon/test/unit/unit-entry.js
r?@piatra This has a few behavior changes. `Dedupe.group` now takes each array as individual parameters instead of an array of arrays. `shortURL` no longer takes a `link` with `eTLD` nor `hostname` as those are unnecessarily provided (or worse -- could be wrong) when `url` includes them. `TopSitesFeed` no longer unnecessarily calls `shortURL`.
Either of the latter 2 changes would fix #3310. Either by not incorrectly slicing hostname or not incorrectly passing a pinned link with a `hostname` to `shortURL`. This fixes both as doing things unnecessarily has led to this issue.
Screenshot of fix where pinned amazon.com and visited bbc.com dedupe GB's default amazon.co.uk and bbc.co.uk:
Also, might be useful to note that `TopSitesFeed.test.js` did **not** catch this because there's a fake …
=> fix(topsites): Compute hostname once for defaults and only require url for shortURL

system-addon/content-src/components/TopSites/TopSite.jsx, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/content-src/components/TopSites/TopSitesEdit.jsx, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/test/unit/content-src/components/TopSites.test.jsx
This adds placeholders for TopSites. Part of the prerendering work.
This is alternative approach that requires fewer changes, which one do you think is better?
https://github.com/mozilla/activity-stream/compare/master...k88hudson:gh3262b?expand=1
=> feat(mc): #3262 Add placeholders for TopSites

system-addon/content-src/components/Search/Search.jsx, system-addon/content-src/lib/constants.js, system-addon/test/unit/content-src/components/Search.test.jsx
Fix #3321.
1. Exposes  gContentSearchcontroller to window so that various tests in browser_aboutHome.js can find it (and removes it on unmount)
2. Adds a healthReportKey and a source depending on the document uri. see -> http://searchfox.org/mozilla-central/source/browser/base/content/abouthome/aboutHome.js#235-236
=> chore(search): Closes #3321 Change contentSearchUIController to better match existing tests

locales/en-US/strings.properties, system-addon/content-src/components/ManualMigration/ManualMigration.jsx, system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/lib/ActivityStream.jsm, system-addon/test/unit/content-src/components/ManualMigration.test.jsx
Fix #3267 by adding strings for #3146, #3147 and #3155. Also fix #3271. r?@sarracini 
---
old stuff
@flodolo this isn't the final set of strings yet as we have some "Design feedback needed" issues (`settings_pane_snippets_header=Snippets` -> "Tips from Mozilla" ? and #3265), but we're trying to be string frozen by end of this week, so I'll update this PR by then. A couple questions for you:
1. We previously removed Highlights in #2740 and split it to a Recently Visited section and a Bookmarks section, but it was decided to combine them for the initial 57 release and potentially split again later. `header_highlights=Highlights` is actually exactly the same from before but `settings_pane_highlights_body` is a previously used and currently removed identifier with a new string. Is it okay to …
=> chore(l10n): Add remaining strings for Firefox 57 (highlights, Pocket, prefs)

system-addon/common/Reducers.jsm, system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/Card/_Card.scss, system-addon/content-src/components/Sections/Sections.jsx, system-addon/lib/SectionsManager.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/content-src/components/Card.test.jsx, system-addon/test/unit/content-src/components/Sections.test.jsx, system-addon/test/unit/lib/SectionsManager.test.js, system-addon/test/unit/lib/TopStoriesFeed.test.js
This also changes the behaviour of sections relative to `initialized` somewhat.
- When sections are first registered, `initialized` is  `false` unless the register action contains non-empty `rows` (in that case, `initialized` will be `true`). 
- When a section is *updated* with an action that includes the `rows` property, `initialized` is set to `true` whether or not rows are empty.
The result of this is that when the section first starts, it will show placeholders; it will only show the empty state if it receives an empty response and there is no data to show.
=> Placeholders for sections

system-addon/common/Reducers.jsm, system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/PlacesFeed.test.js
Fix #3204. I switched to dateAdded as discussed, and hence we can now avoid the extra fetch.
=> fix(places): Avoid impacting performance when listening to onItemAdded - switch to dateAdded to avoid an extra fetch (#3204)

system-addon/lib/TippyTopProvider.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
=> fix: Stop TopSites refreshing before TippyTop init. Closes #3352.

system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
Fix #3357. r?@rlr Looks like the negative right offset was causing the scrollbar.
=> fix(styles): Avoid horizontal scrollbar on pref page by staying within the size

system-addon/content-src/components/Search/_Search.scss
Fix #3374. r?@sarracini 
"muuuuuuch better, thank you!"
=> fix(styles): Remove sharp corner of search when suggestions are shown to not need extended border

system-addon/lib/HighlightsFeed.jsm, system-addon/test/unit/lib/HighlightsFeed.test.js
Fix #3382. r?@rlr I see it's the same pattern from `TopSitesFeed` but turns out by waiting for `TippyTopProvider`, it delays accessing `NewTabUtils.activityStreamLinks` long enough to avoid startup load checks. I also removed some unnecessary imports.
=> fix(highlights): Avoid fetching Highlights on INIT and just wait for NEW_TAB_LOAD

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
This is one (simple) way to fix #3377 the problem.
The downside is that TippyTop provider can be initialized twice in some cases, but that does no harm other than wasting a few cycles.
Another option is to not call `refresh()` on `INIT` and wait until `NEW_TAB_LOAD`. Downside of that is the first tab load might take more time.
There are more complex solutions. Like we could have some sort of list of targets that need to be refreshed when the current refresh is complete. 
@AdamHillier @Mardak thoughts?
=> fix (systemaddon): #3377 dont skip refresh if already refreshing

system-addon/lib/HighlightsFeed.jsm, system-addon/test/unit/lib/HighlightsFeed.test.js
Fix #3390. r?@rlr Did some refactoring / clean up too.
Before (team):
After (only aaron):
=> feat(highlights): Show more diverse highlights by limiting to one per domain

bin/render-activity-stream-html.js, system-addon/common/Reducers.jsm, system-addon/content-src/activity-stream-prerender.jsx, system-addon/content-src/components/Base/Base.jsx, system-addon/test/unit/activity-stream-prerender.test.jsx, system-addon/test/unit/common/Reducers.test.js
Fix #3371. r?@k88hudson Adds support but doesn't actually generate the prerendered rtl file. (Currently working on doing it for each "mozilla-central locale".)
=> feat(prerender): Compute rtl in Reducer for use in Base and prerendered

system-addon/content-src/components/Card/Card.jsx
Fix #3391. r?@csadilek Design says to just use "Trending" until we're out of string freeze to use "Popular" #3402
=> chore(topstories): Pretend "Now" is "Trending" until we have strings

system-addon/content-src/components/TopSites/TopSite.jsx, system-addon/content-src/components/TopSites/TopSitesConstants.js, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/content-src/components/TopSites.test.jsx, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #3327. Generalize the icons so that it's just a rich icon instead of a screenshot
=> feat(topsites): Set Top Site card image source to high-res icon when available

system-addon/content-src/components/Card/_Card.scss, system-addon/content-src/styles/_icons.scss
Fix #3399. r?@sarracini This keeps #3195 by adjusting the Trending icon positioning. The only change necessary was `line-height`. The other removals were because they weren't necessary -> confusing.
After:
Before:
=> fix(styles): Shift context label down to be centered with icon

system-addon/content-src/activity-stream-prerender.jsx, system-addon/test/unit/activity-stream-prerender.test.jsx
=> fix(prerender): #3414 Render English string for prerender search

system-addon/content-src/components/TopSites/TopSite.jsx, system-addon/content-src/components/TopSites/TopSitesConstants.js, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/test/unit/content-src/components/TopSites.test.jsx
=> feat(topsites): Fixes #3150 Show low-res icon in corner of screenshot

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
This generalizes the ```_getPinnedWithData``` function so that we can augment with the data that comes from either some links that we give, or from the store if we don't give links. It wasn't enough to just change the Object.assign to smoosh onto the pinnedLink, because when we restart firefox and it gets it from the store, the favicons don't exist yet - we have to get them out of places. So to fix that we need to also augment the pinnedLinks on the refresh with the links that come out of places.
=> fix(topsites): Fixes #3428 When pinning a site the corner icon disappears

system-addon/common/PrerenderData.jsm, system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/Base/_Base.scss, system-addon/lib/PrefsFeed.jsm, system-addon/test/unit/common/PrerenderData.test.js, system-addon/test/unit/lib/PrefsFeed.test.js
This patch also:
* Refactors PrerenderData to compute whether prefs are valid, allowing
it to be used in content.
* Adds highlights to the prerendered initial sections
* Adds some styles that reduce the extent to which elements move around
on the page: a new fixed-to-top class that gets added to outer-wrapper
=> fix(prerender): Use prerendered if either pocket or highlights are on

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js, system-addon/test/unit/lib/TelemetryFeed.test.js
Fix #2510. This shouldn't be landed/tested until [bug 1398955](https://bugzilla.mozilla.org/show_bug.cgi?id=1398955) is merged to mozilla-central.
Once that happens, it's only easy to see that it's working with the first PingCentre commit in this PR (which should be removed before this patch is merged to master).
r? @ncloudioj and r? @emtwo, since this makes session.page optional in some cases.
=> feature(telemetry): make session.page optional & support about:home (closes #2510)

system-addon/lib/HighlightsFeed.jsm, system-addon/test/unit/lib/HighlightsFeed.test.js
=> fix(highlights): Ensure that Highlights are refreshed on init.

system-addon/content-src/components/Card/Card.jsx, system-addon/lib/ActivityStream.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/content-src/components/Card.test.jsx, system-addon/test/unit/lib/TopStoriesFeed.test.js
This brings in the functionality we need for the spoc experiment. In this experiment, we swap out the third story/card at a frequency defined in the API response (```spocsPerNewTab```). So, every Nth new tab would render the top scored spoc. Scoring is based on our personalization algorithm.
The only other change in this PR is for the Card UI to allow setting a custom context and icon and some refactorings.
This is preffed off by default. To turn it on, the following changes to ```feeds.section.topstories.options``` are required [1]:
```
show_spocs: true,
personalized: true,
stories_endpoint: `https://getpocket.cdn.mozilla.net/v3/firefox/global-recs?version=2&consumer_key=$apiKey&locale_lang=${args.locale}&feed_variant=spocs`,
```
[1] This will currently only display test spocs
=> feat(topstories): Add functionality for spoc experiment

docs/v2-system-addon/data_events.md, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
Measuring the time it takes to calculate domain affinities (once a day, when preffed on) and sending a ping.
=> feat(topstories): Add perf telemetry for domain affinity calculation

system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/Card/_Card.scss
Fix #1971. r?@sarracini Adds a "no-description" like the other class names although I suppose it might be a little confusing with the `:not(.no`
Before:
After:
=> fix(styles): Truncate card titles to 3 lines if it has a description

system-addon/content-src/components/Base/_Base.scss, system-addon/content-src/components/TopSites/_TopSites.scss
Fix #2963. r?@k88hudson Tested as if on maximized reference machine (753px `innerHeight`). Onboarding is actually 100px, but in the screenshots below, I pretended they were 120px of snippets. This also fixes the increase in spacing below top sites to be decreased to 40px to the next section.
Before with scrollbar:
After without scrollbar:
=> chore(styles): Reduce bottom spacing of content and site titles to avoid scrollbars

system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js
Previous solution didn't take into account that:
- after re-fetching the feed, a top item that was previously
rotated could be top scored again and therefore needs to be
rotated again to not appear on top.
- a single rotation might not be good enough as the subsequent
item could have also been on top for too long.
=> fix(topstories): Fix story rotation in personalization experiment

system-addon/content-src/lib/link-menu-options.js, system-addon/lib/PlacesFeed.jsm, system-addon/test/unit/content-src/components/LinkMenu.test.jsx, system-addon/test/unit/lib/PlacesFeed.test.js
Fix #3254. Adds an additional field to data to force a block action for sites that need to no longer be shown once deleted. This was to fix the bug where you can't delete a site that's been bookmarked - so now we force it to block a site that has a bookmark guid
=> fix(bookmarks): Fixes #3254 Block bookmarked items that were deleted from history

system-addon/content-src/components/TopSites/_TopSites.scss
Fix #3492. r?@k88hudson 
Before:
After:
=> fix(styles): Move favicon from top left to bottom right

system-addon/lib/ActivityStream.jsm
Closes #3476 .
@Mardak Pocket endpoint has been updated as well so that the topic links returned use src=fx_new_tab (instead of ff_new_tab). Also links go through the CDN now e.g. https://getpocket.cdn.mozilla.net/explore/must-reads?src=fx_new_tab
=> fix(pocket): Change 'ff' prefix to 'fx'

system-addon/vendor/Redux.jsm
=> chore(vendor): Backport Bug 1399997 - Remove usage of eval and new Function() in JSM scopes. r=Mossop

system-addon/bootstrap.js, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #2592. r?@rlr Unofficially support a larger `topSitesCount` so the pref pane still juts shows "[x] Show two rows" Also I suppose because it's not super official, some things might be broken. But at least it shows this with 20 pinned sites, 1 history visit after migrating from a `browser.newtabpage.rows` of 4:
Makes use of the `{numItems}` I snuck into https://hg.mozilla.org/mozilla-central/rev/73c7371abb7f#l1.140 >:)
=> feat(topsites): Migrate browser.newtabpage.rows and fetch more topSitesCount

system-addon/lib/ActivityStream.jsm
Fix #3544. r?@rlr I suppose the dream of a clean revert are long gone. ;)
=> fix(prefs): Default about:home search autoFocus to false

system-addon/content-src/components/TopSites/_TopSites.scss
Fix #3549. r?@rlr 
Before top, after bottom:
title I put as "youtube..."
=> fix(styles): Use right aligned ltr for url input

system-addon/content-src/components/Base/Base.jsx, system-addon/content-src/components/Base/_Base.scss
This hides top sites and sections until we've initialized, but leaves the search box visible from the start. Let's see if this looks better?
=> feat(style): Hide top sites and sections before we've initialized

docs/v2-system-addon/data_events.md, system-addon/lib/ActivityStream.jsm, system-addon/lib/Store.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/test/unit/lib/ActivityStream.test.js, system-addon/test/unit/lib/Store.test.js
This closes #3522 
Patch notes:
* The init failure ping was sent from `ActivityStream.init` other than`bootstrap.js` for better test-ability.
* Not sure if we can re-arrange the `ActivityStream.init` function so that it could init the TelemetryFeed as early as possible to be able to report other potential init errors. @k88hudson What do you think about this?
=> fix(telemetry): Send an undesired event ping if addon fails to init

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, system-addon/common/PerfService.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/lib/TelemetryFeed.test.js
How to test:
1. buildmc & `mach run`
2. ensure that your telemetry and logging prefs are on
3. restart and open the browser console
4. open a new tab
5. close the original tab from the startup
6. in the console, you should see a TELEMETRY PING log with page=about:home, load_trigger_type=first_window_opened,load_trigger_ts=(some number)
7. open a new window and close
8. in the console, you should see a TELEMETRY PING log with page=about:home, load_trigger_type=unexpected
@fmarier fmarier has given this data-review+
=> feat(telemetry): add about:home first-window-opened load_trigger_type (#2658)

system-addon/content-src/components/Base/_Base.scss, system-addon/content-src/components/Sections/_Sections.scss, system-addon/content-src/components/TopSites/TopSites.jsx
Fix #3562. r?@sarracini 
Before left, after right:
=> fix(styles): Use the same 12px margin between section title and content

system-addon/content-src/components/Base/_Base.scss
Fix #3568. r?@k88hudson aaron says fix the performance issue now and adjust later
https://bugzilla.mozilla.org/show_bug.cgi?id=1401682#c4
=> fix(styles): Adjust fade in timing to avoid tart regression

system-addon/content-src/components/Search/_Search.scss, system-addon/content-src/styles/_variables.scss
Fix #3583. r?@sarracini Removed the confusing / duplicate `search-input` mixin. Also removed unnecessary `z-index`
=> fix(styles): Update search focus to Blue-50 shades of Grey-90

system-addon/content-src/components/TopSites/_TopSites.scss
Fix #3598. r?@rlr Were the `205px` picked for a specific reason?
=> fix(styles): Size edit input boxes based on available width

system-addon/content-src/components/TopSites/_TopSites.scss
Fix #3602. r?@rlr Guess what?! Taking away italics makes it not italics. ;)
=> fix(styles): Remove italics from edit placeholder

system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/Card/_Card.scss, system-addon/content-src/styles/_variables.scss, system-addon/test/unit/content-src/components/Card.test.jsx, system-addon/test/unit/unit-entry.js
Fix #3605. r?@sarracini Adds an image loader that sets the "loaded" class only after loading instead of when the image is set.
See video with existing on left and with PR on right:
https://ed.agadak.net/as/activity-stream.fade-pocket.webm
This video includes the changes from #3610.
=> fix(card): Fade from gradient to loaded image only after loading

system-addon/content-src/components/Search/_Search.scss
=> chore(styles): Backport Bug 1399642 - Use photon search icon in awesomebar. r=dao

system-addon/common/PrerenderData.jsm, system-addon/content-src/components/Sections/Sections.jsx, system-addon/content-src/components/Topics/Topics.jsx, system-addon/test/unit/content-src/components/Sections.test.jsx
Fix #3604. r?@k88hudson Make topics initial data be like the actual initial data of undefined and render the empty section until actual topics come in.
=> fix(topics): Allow showing uninitialized topics to avoid height changes on receiving topics

system-addon/content-src/components/Base/_Base.scss, system-addon/content-src/components/Search/_Search.scss, system-addon/content-src/components/Sections/_Sections.scss, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/content-src/styles/_variables.scss
r?@rlr I split this into 3 commits:
1) fix #3634 spacing
2) switch to aliased grey-90 opacities
3) fix #3631 arrow stuff
Screenshots:
Linux:
Invisible sizing:
RTL:
=> feat(styles): Convert the info panel into an door hanger with arrow

system-addon/content-src/components/Sections/_Sections.scss
=> fix(styles): Avoid reshowing info option when moving pointer away and back quickly

system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss, system-addon/lib/SectionsManager.jsm, system-addon/test/unit/content-src/components/PreferencesPane.test.jsx
Enhancement to support nested prefs in Sections.
This will be needed when
- refactoring TopSites to a Section as it has a nested pref ("Show two rows")
- enhancing the spoc experiment to support opt-out functionality via a nested pref
To declare nested prefs in SectionManager:
```javascript
const BUILT_IN_SECTIONS = {
"feeds.section.topstories": options => ({
id: "topstories",
pref: {
titleString: {id: "header_recommended_by", values: {provider: options.provider_name}},
descString: {id: options.provider_description || "pocket_feedback_body"},
nestedPrefs: [{
name: "foo",
titleString: {id: "Some nested pref", values: {}},
icon: "icon-info"
}, {
name: "bar",
titleString: {id: "Some other nested pref", values: {}},
icon: "icon-info"
}]
...
```
UI:
=> feat(sections): Add support for nested prefs

system-addon/lib/HighlightsFeed.jsm, system-addon/lib/LinksCache.jsm, system-addon/lib/Screenshots.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/HighlightsFeed.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #3564. r?@k88hudson The main change is adding a `__sharedCache` that copies of a given link will share via shallow copying. I also stashed the `updateLink` helper on that object so only one thing needs to be `delete`d before dispatch. I also made it so that `Screenshots` doesn't modify the link as generally it'll be too late anyway and would need a `dispatch`, so this fixes #3561.
Added concurrency tests where the first one (backing data called once) was already passing, but the two additional ones are specifically testing for #3564's issues. Other tests were updated for the various naming changes.
=> fix(cache): Allow concurrent cache callers to get links with shared state

system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/TopSitesFeed.test.js
Fix #3609. r?@sarracini In the first commit, I just cleaned up a top level `action` variable to avoid shadowing it and test the `target` behavior. The second commit adds an integration test for pinning then unpinning.
=> fix(topsites): Refresh pinned links when one is blocked

system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
@Mardak this fixes it.
Fixes #3681
=> fix (styles): #3681 dont clip dropshadows during section collapse/expand animation

system-addon/common/Reducers.jsm, system-addon/lib/HighlightsFeed.jsm, system-addon/lib/SectionsManager.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/common/Reducers.test.js, system-addon/test/unit/lib/HighlightsFeed.test.js, system-addon/test/unit/lib/SectionsManager.test.js, system-addon/test/unit/lib/TopStoriesFeed.test.js
fix #3573 and fix #3629 and fix #3587. Re submitting https://github.com/mozilla/activity-stream/pull/3623 without highlights date filtering that was based on `ProfileAge` module.
I did a bigger try push https://treeherder.mozilla.org/#/jobs?repo=try&revision=ceb8c64e3ee8035a463a778bb3561ebfa5cb101a 
Some recurrent failures:
* devtools/shared/webconsole/test/test_console_serviceworker.html -- consistently failing but also on latest master so disregarding.
* Unused file whitelist item. file: chrome://global/skin/arrow/panelarrow-vertical@2x.png -- referenced files?
* `SpecialPowers.getDOMWindowUtils(...).addToStyloBlocklist is not a function` -- but I don't see how we could cause this
=> Dedupe sections in the reducer

system-addon/common/Dedupe.jsm, system-addon/lib/HighlightsFeed.jsm, system-addon/test/unit/common/Dedupe.test.js, system-addon/test/unit/lib/HighlightsFeed.test.js
Fix #3608. r?@piatra Removes `compare` of `Dedupe`. Make bookmark type highlights un-dedupable
=> feat(highlights): Always show bookmarks even if duplicate of top sites

system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss
Fix #3699. r?@rlr Couldn't reproduce on mac, so below are screenshots from linux.
Before:
After:
=> fix(styles): Use css to calculate rtl offset instead of hardcoded of expected width

system-addon/lib/PersistentCache.jsm, system-addon/lib/TopStoriesFeed.jsm, system-addon/test/unit/lib/PersistentCache.test.js, system-addon/test/unit/lib/TopStoriesFeed.test.js, system-addon/test/unit/unit-entry.js
This a file on disk as a persistent cache.
Fixes #3606
=> fix (performance): #3606 Add cache for pocket stories and topics

system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
Fix #3706. r?@rlr Like #3480 but also making it a `class`.
=> chore(react): Switch ConfirmDialog to extend PureComponent

system-addon/lib/TopStoriesFeed.jsm, system-addon/lib/UserDomainAffinityProvider.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js, system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
This PR brings in frequency caps for the sponsored content experiment:
Frequency caps are based on campaigns (not individual spocs). We currently support two types of frequency caps:
- lifetime: Indicates how many times spocs from a campaign can be shown in total
- period: Indicates how many times spocs from a campaign can be shown within a period
So, for example, the feed configuration below defines that for campaign 1 no more than 5 spocs can be show in total, and no more than 2 per hour.
```
"campaign_id": 1,
"caps": {
"lifetime": 5,
"campaign": {
"count": 2,
"period": 3600
}
}
```
This is implemented storing a mapping of campaign IDs to timestamps (impressions) in a pref. The pref is cleaned up every time the feed is fetched. Only campaigns part of the last response are considered …
=> Frequency caps support for spoc experiment

system-addon/common/PrerenderData.jsm, system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx, system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Fix #3682. Don't prerender if we have sections collapsed - also lets us get rid of the animation-enabled class
=> fix(collapsing): Fixes #3682 Sections are no longer animated when collapsed if the sections were disabled and re-enabled from customization menu

system-addon/content-src/components/ConfirmDialog/ConfirmDialog.jsx
This was in the console when prerendering:
`Warning: getDefaultProps was defined on ConfirmDialog, a plain JavaScript class. This is only supported for classes created using React.createClass. Use a static property to define defaultProps instead.`
Followup from #3713. r?@rlr We get the props through `connect` state.
https://github.com/mozilla/activity-stream/blob/d6b67193c571c697105d1ee04f595f4f7f4477b3/system-addon/common/Reducers.jsm#L47-L49
=> chore(react): Remove unused and unnecessary defaultProps from ConfirmDialog

system-addon/lib/TopStoriesFeed.jsm, system-addon/lib/UserDomainAffinityProvider.jsm, system-addon/test/unit/lib/TopStoriesFeed.test.js, system-addon/test/unit/lib/UserDomainAffinityProvider.test.js
This is a refactoring to no longer trigger domain affinity calculation on the first fetch, but on idle-daily, and cache the result so it's available on next startup.
This is a performance trade-off. So, in case idle-daily hasn't run yet, there will be no sorting, and the result is the same as the un-personalized, global feed.
=> chore(performance): Cache affinity scores and calculate on idle-daily

system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx, system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss, system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
The issue was that animations/transitions in background tabs are aggressively throttled or paused. So once the tab is brought into view, the rest of the animation happens. To fix, I just disabled the transitions for non visible tabs.
Fixes #3707
=> fix (animations): #3707 only animate when page is visible

system-addon/lib/HighlightsFeed.jsm, system-addon/lib/TopSitesFeed.jsm, system-addon/test/unit/lib/HighlightsFeed.test.js, system-addon/test/unit/lib/TopSitesFeed.test.js
Closes #3646. 
Needs a follow up bug in m-c to remove the current TopSites expiration https://github.com/mozilla/activity-stream/issues/3646#issuecomment-337616103. Should be fine to land this independently right?
=> Register thumbnail expiration filters for topsites and highlights

system-addon/lib/SnippetsFeed.jsm, system-addon/test/unit/lib/SnippetsFeed.test.js
This supports [Bugzilla #1395460](https://bugzilla.mozilla.org/show_bug.cgi?id=1395460).
TLDR: we are going to get rid of about:accounts, and clients should link to the FxA URLs directly.
Note: Do not merge until the Firefox changes are merged onto mozilla-central.
=> fix(snippets): do not redirect to about:accounts

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, system-addon/content-src/components/TopSites/TopSites.jsx, system-addon/test/schemas/pings.js, system-addon/test/unit/content-src/components/TopSites.test.jsx, system-addon/test/unit/lib/TelemetryFeed.test.js
Closes #3449.
I've moved the decision logic for topsite image and favicon from `TopSiteLink.render` to TopSites into it's own fn `selectTopSiteIcon`. This way on render `<TopSites>` knows the image quality of all its children. I also think it makes it easier to test.
The information about the 3 types of TopSite images: `tippytop`, `screenshot + favicon`, `screenshot + fallback letter` are added to the user session and updated every time TopSites updates. They are only sent once when the session ends.
@emtwo we currently handle tippytop and rich icons as one (because visually it's the same thing when we render). Are we interested in splitting the telemetry information?
=> Log TopSites icons stats in session object.

system-addon/lib/ShortURL.jsm, system-addon/test/unit/lib/ShortUrl.test.js
Fix #3716 and fix #3460. Fall back to hostname and clean up the code a little. (Remove duplicate `newURI`/`URL`, lowercase, and only use url-related fallbacks for `shortURL`.)
before/after:
=> fix(highlights): Use appropriate short url fallbacks

system-addon/lib/ActivityStreamMessageChannel.jsm, system-addon/lib/NewTabInit.jsm, system-addon/test/unit/lib/ActivityStreamMessageChannel.test.js, system-addon/test/unit/lib/NewTabInit.test.js
Fix #3747. r?@k88hudson Special case early tabs by marking them as `simulated` and only `reply`ing once.
=> fix(init): Remember when rehydrating early tabs to only do it once

system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx, system-addon/content-src/lib/snippets.js, system-addon/lib/ActivityStream.jsm, system-addon/test/unit/content-src/components/PreferencesPane.test.jsx, system-addon/test/unit/content-src/lib/snippets.test.js
Backports Bug 1409058
https://hg.mozilla.org/mozilla-central/rev/eb5138e5bd55
=> chore(snippets): Add disableSnippets pref

docs/v2-system-addon/data_dictionary.md, docs/v2-system-addon/data_events.md, locales/en-US/strings.properties, system-addon/content-src/components/Card/Card.jsx, system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx, system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss, system-addon/content-src/components/Sections/Sections.jsx, system-addon/content-src/lib/link-menu-options.js, system-addon/lib/ActivityStream.jsm, system-addon/lib/SectionsManager.jsm, system-addon/lib/TelemetryFeed.jsm, system-addon/test/schemas/pings.js, system-addon/test/unit/content-src/components/Card.test.jsx, system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx, system-addon/test/unit/content-src/components/Sections.test.jsx, system-addon/test/unit/lib/TelemetryFeed.test.js
Closes #3770 
- Adds new `impression_id` which gets used instead of `client_id` for impression pings
- Adds new `user_event` for acknowledging disclaimers: `SECTION_DISCLAIMER_ACKNOWLEDGED`
- Removes client-side deduping of impressions
- Shows a disclaimer until acknowledged. Includes UI tweaks to make sure disclaimer/section resizes properly.
=> feat(telemetry): #3770 Generate unique ID for impression pings

system-addon/content-src/components/Search/_Search.scss
This patch makes the border a consistent color when hovering over the submit button, and adds a slightly darker border color when hovering over the input.
=> style(search): #3679 Fix search hover border styles

.gitignore, bin/render-activity-stream-html.js, package.json, system-addon/content-src/styles/_activity-stream.scss, system-addon/content-src/styles/_variables.scss, system-addon/content-src/styles/activity-stream-linux.scss, system-addon/content-src/styles/activity-stream-mac.scss, system-addon/content-src/styles/activity-stream-windows.scss, system-addon/jar.mn, yamscripts.yml
Includes a windows-specific search focus border style
=> style(content): #3745 Add per-platform css files

system-addon/content-src/components/ManualMigration/_ManualMigration.scss, system-addon/content-src/components/PreferencesPane/_PreferencesPane.scss, system-addon/content-src/styles/_activity-stream.scss
Closes #3630 
Quickest fix. Could use some margins but this seems to obscure to write media queries for. And we've closed quite a few issues recently where we decided this width doesn't make too much sense to support. https://github.com/mozilla/activity-stream/issues/3749#issuecomment-339401334
=> Use flex-wrap to force a new line for small width.

system-addon/lib/LinksCache.jsm, system-addon/lib/Screenshots.jsm, system-addon/test/unit/lib/Screenshots.test.js
Closes #3763.
@Mardak would this be a good enough fix? Would prevent per browser session repeated requests while still allow to make the request on restart for websites that might have legitimate issues.
I've looked into the Screenshots/BackgroundPageThumbs code but it doesn't give more information in case of error to make this more precise. `page-thumbnail:error` is a generic fail.
> fails (eg, times out, remote process crashes.)
=> Skip failed Screenshot requests.

system-addon/content-src/components/Search/Search.jsx
Regressed by #3755 incorrectly removing the `App`/`locale` state. r? @k88hudson I'll land a test separately after we export.
=> fix(search): Restore connect for Search so it can dispatch

system-addon/lib/SectionsManager.jsm
Closes #3796 
This is adding a fallback in case the disclaimer link is not configured and the defaults can't be overridden i.e. due to an active shield study.
=> fix(topstories): #3796 Pocket disclaimer not clickable for some users

locales/de/strings.properties, system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss
Closes #3801 
- Includes refactoring to remove no longer needed styles
- Adds the missing comma in the temporary German translations
=> fix(topstories): #3801 Pocket notice text and button overlap on Windows

system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx, system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
How to test: need to actually write a webextension that does tries to do this to see if this is the consequence of the test warning that was fixed.  That said, it looks pretty straightforward...
r? @rlr
=> fix(addons): #3803 CollapsibleSection icons from add-ons appear to fail

system-addon/content-src/components/CollapsibleSection/CollapsibleSection.jsx, system-addon/content-src/components/CollapsibleSection/_CollapsibleSection.scss, system-addon/content-src/components/Sections/_Sections.scss, system-addon/test/unit/content-src/components/CollapsibleSection.test.jsx
Fix #3677, fix #3806, fix #3807, fix #3809. r?@rlr See https://ed.agadak.net/as/activity-stream.collapsible.maxHeight.webm
There's some magic forced flushing to get things to work…
I'll add some tests to at least make sure the style is set at the appropriate times.
=> fix(collapsing): Set max-height via javascript to transition for any size section

system-addon/content-src/components/TopSites/TopSite.jsx, system-addon/content-src/components/TopSites/_TopSites.scss, system-addon/test/unit/content-src/components/TopSites.test.jsx
Fix #3765. r?@sarracini 
Before:
After:
=> fix(topsites): Use ::before to show letter fallback to avoid extra link text

system-addon/test/unit/content-src/components/ConfirmDialog.test.jsx
This is in preparation for making all React warnings fail in order to have more confidence in the React 16 upgrade.  
How to test: both without and with the patch, do this:
`npm run testmc | grep FormattedMessage`
with the patch, there should be no matches.
=> fix(tests): closes #3814, ConfirmDialog propType errors

system-addon/content-src/styles/_activity-stream.scss
Fix #3818. r?@sarracini 
Before:
After:
=> fix(styles): Specify background-color to avoid setting other background-{size,*} values

system-addon/content-src/components/Sections/_Sections.scss
Closes #3772.
I got the 👍 to remove the property [in the issue](https://github.com/mozilla/activity-stream/issues/3772#issuecomment-343250007).
Windows 7
With `font-weight: 300` (as it is now)
Without the `font-weight` property
OSX without font-weight property
=> Fix font issue caused by font-weight prop.

system-addon/lib/FaviconFeed.jsm, system-addon/test/unit/lib/FaviconFeed.test.js
r? @Mardak 
With this patch I'm able to set the endpoint to localhost and run tests
```
...
Browser Chrome Test Summary
Passed: 30
Failed: 0
Todo: 0
Mode: e10s
*** End BrowserChrome Test Results ***
```
=> fix (tippytop): handle fetch fail in FaviconFeed

mozilla-central-patches/disable-testing-tippy.diff
Followup to #3827. r?@rlr Sets the pref to ""
=> fix(tippytop): Disable service endpoint for testing

mozilla-central-patches/disable-testing-tippy.diff
More followup to #3829 and #3827. r?@rlr Also disable reftests.
=> fix(tippytop): Also disable tippy top service for reftests

system-addon/test/unit/unit-entry.js
The warnings are now all gone; this patch will keep them from returning.
How to test: after applying this patch, edit a test somewhere to be missing a required prop while `npm run tddmc` is going and save the file.  The tests should break.
=> React error on key warnings during tests

system-addon/content-src/components/Card/_Card.scss
Spoke with Bryan IRL and he said ellipses are good
Before: 
After:
=> fix(cards): Fixes #3805 Very long domain names overflow in cards

system-addon/lib/FaviconFeed.jsm, system-addon/test/unit/lib/FaviconFeed.test.js
Fix #3842. r?@rlr Not entirely sure if this is desired… but it would fix the go.twitch.tv vs twitch.tv situation. However, as in the unit test, it would set bugzilla.mozilla.org's icon to mozilla.org. Or similarly mail.google.com would get google.com.
=> fix(favicons): Fall back to higher domain's icon if no subdomain match
